### PR TITLE
fix: query with workspace descendents

### LINKED ISSUE #703: [BUG] query command returns incomplete dependency list for workspaces
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Assuming the following project set-up:
```
$ cat package.json 
{
  "name": "root",
  "version": "1.0.0",
  "workspaces": ["./a", "./b"]
}

$ npm ls -all
root@1.0.0 /private/tmp/root
├─┬ a@1.0.0 -> ./a
│ └── b@1.0.0 deduped -> ./b
└─┬ b@1.0.0 -> ./b
  └── lodash@4.17.21
```

Run the query:
```
$  npm query '#a *' | jq '.[].name'
```

The only returned result is:
```
"b"
```

### Expected Behavior

Run the query:
```
$  npm query '#a *' | jq '.[].name'
```

The returned result should be:
```
"b"
"lodash"
```

Similar to the result returned from `npm-ls` with the `--workspace` flag:
```
$ npm ls --workspace a
root@1.0.0 /private/tmp/root
└─┬ a@1.0.0 -> ./a
  └─┬ b@1.0.0 -> ./b
    └── lodash@4.17.21
```

### Steps To Reproduce

Set-up the following directory structure:

```
root
├── a
│   └── package.json
├── b
│   └── package.json
└── package.json
```

In the _root_ directory, create the following _package.json_ file:
```json
{
  "name": "root",
  "version": "1.0.0",
  "workspaces": ["./a", "./b"]
}
```

In the _a_ directory, create the following _package.json_ file:
```json
{
  "name": "a",
  "version": "1.0.0",
  "dependencies": {
    "b": "1.0.0"
  }
}
```

In the _b_ directory, create the following _package.json_ file:
```json
{
  "name": "b",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "^4.17.21"
  }
}
```

Execute the following:
```
$ npm query '#a *' | jq '.[].name'
"b"
```

Note that `b` is returned but NOT `lodash`

### Environment

- npm: 10.0.0
- Node: v18.12.1
- OS: macOS
- platform: arm64

### PR DESCRIPTION
**Pull request by bdehamer**
Fixes https://github.com/npm/statusboard/issues/703

In scenarios where one workspace has a dependency on another workspace, `querySelectorAll` may omit some child dependencies. This stems from the fact that the algorithm to find dependencies, starts at the leaf and tries to find a path (following `edgesIn`) which leads back to the selected node. When workspaces are involved you can't reliably walk back up the dependency tree in this direction (`ArboristNode`s representing a workspace have no `edgesIn`).

The proposed fix updates the `hasAscendant` function to also follow the `linksIn` collection when trying to find a path to the selected node.

### CODE REVIEW

File: workspaces/arborist/test/query-selector-all.js [hunk 1]
```diff
@@ -24,6 +24,7 @@ t.test('query-selector-all', async t => {
     │   └── lorem@1.0.0 (production dep of baz)
     ├── abbrev@1.1.1 (production dep of query-selector-all-tests)
     ├─┬ b@1.0.0 -> ./b (workspace)
+    │ ├── a@2.0.0 (dev dep of b, deduped)
```
Comment (bdehamer) [inline workspaces/arborist/test/query-selector-all.js:27]: It wasn't previously represented in this diagram, but the test fixture does have the `a` workspace as a (dev) dependency of `b`. Correcting the comment to reflect the actual project set-up.

https://github.com/npm/cli/blob/39e2b87f283a80af8c79eb76096c017127b2d63f/workspaces/arborist/test/query-selector-all.js#L266-L276

File: workspaces/arborist/test/query-selector-all.js [hunk 2]
```diff
@@ -513,7 +514,7 @@ t.test('query-selector-all', async t => {
     ['*:has(* > #bar:semver(1.4.0))', ['foo@2.2.2']],
     ['*:has(> #bar:semver(1.4.0))', ['foo@2.2.2']],
     ['.workspace:has(> * > #lorem)', ['a@1.0.0']],
-    ['.workspace:has(* #lorem, ~ #b)', ['a@1.0.0']],
+    ['.workspace:has(* #lorem, ~ #b)', ['a@1.0.0', 'b@1.0.0']],
```
Comment (bdehamer) [inline workspaces/arborist/test/query-selector-all.js:517]: This test case covers the same bug discussed in https://github.com/npm/statusboard/issues/703 . . . unfortunately, the expected result for this test case was incorrect so it didn't surface the bug.

Given that `a` is a dependency of `b`, `b` is ALSO a workspace with a dependency on `lorem` (via `a`).

The `~ #b` bit is sorta confusing here, but since `,` behaves like an OR I think it's still correct to include `b` in the result set (it's the `* #lorem` bit that should be selecting `b`, NOT the `~ #b` bit)

**Comment by lukekarrys** [comment]
@npm-cli-bot benchmark this

**Comment by lukekarrys** [comment]
(ignore me, just using this PR to test out new benchmarking changes)

File: workspaces/arborist/lib/query-selector-all.js [hunk 3]
```diff
@@ -719,7 +719,10 @@ const hasAscendant = (node, compareNodes, seen = new Set()) => {
   }
 
   if (node.isTop && node.resolveParent) {
-    return hasAscendant(node.resolveParent, compareNodes)
+    if(hasAscendant(node.resolveParent, compareNodes)) {
+      /* istanbul ignore next */
+      return true
+    }
   }
```
Comment (bdehamer) [inline workspaces/arborist/lib/query-selector-all.js:726]: I suspect that this entire check can be removed (I couldn't craft a test case that would return true here) but, at the very least, we need to continue processing if `hasAscendant` returns false.

File: workspaces/arborist/lib/query-selector-all.js [hunk 4]
```diff
@@ -719,7 +719,10 @@ const hasAscendant = (node, compareNodes, seen = new Set()) => {
...
 
   if (node.isTop && node.resolveParent) {
-    return hasAscendant(node.resolveParent, compareNodes)
+    if (hasAscendant(node.resolveParent, compareNodes)) {
+      /* istanbul ignore next */
+      return true
+    }
   }
```
Comment (bdehamer) [inline workspaces/arborist/lib/query-selector-all.js:726]: I suspect that this entire check can be removed (I couldn't craft a test case that would return true here) but, at the very least, we need to continue processing if `hasAscendant` returns false.

File: workspaces/arborist/lib/query-selector-all.js [hunk 5]
```diff
@@ -719,7 +719,10 @@ const hasAscendant = (node, compareNodes, seen = new Set()) => {
...
 
   if (node.isTop && node.resolveParent) {
-    return hasAscendant(node.resolveParent, compareNodes)
+    /* istanbul ignore if */
+    if (hasAscendant(node.resolveParent, compareNodes)) {
+      return true
+    }
   }
```
Comment (bdehamer) [inline workspaces/arborist/lib/query-selector-all.js]: I suspect that this entire check can be removed (I couldn't craft a test case that would return true here) but, at the very least, we need to continue processing if `hasAscendant` returns false.

Comment (wraithgar) [reply workspaces/arborist/lib/query-selector-all.js]: It's entirely likely this is obviated by the new linksIn check.  Skipping coverage is the most prudent choice since we don't really have time to dig fully into it.  Can you add a comment about why it's ignored for future us to be able to approach it properly?

Comment (bdehamer) [reply workspaces/arborist/lib/query-selector-all.js]: updated

**Review by wraithgar — APPROVED** [review]
