### PR TITLE
fix(utils/tar): index access while match is null (#7555)

### LINKED ISSUE #7555: [BUG] Failed index access on utils/tar.js while trying to publish a package with node_modules
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
npm verbose cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@10.8.0
npm info using node@v22.2.0
npm verbose title npm publish npm-example-v1.tgz
npm verbose argv "publish" "--loglevel" "verbose" "npm-example-v1.tgz"
npm verbose logfile logs-max:10 dir:/Users/normanperrin/.npm/_logs/2024-05-23T06_39_11_271Z-
npm verbose logfile /Users/normanperrin/.npm/_logs/2024-05-23T06_39_11_271Z-debug-0.log
npm verbose publish [ 'npm-example-v1.tgz' ]
npm verbose stack TypeError: Cannot read properties of null (reading '1')
npm verbose stack     at onentry (/usr/local/lib/node_modules/npm/lib/utils/tar.js:63:77)
npm verbose stack     at Parser.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/list.js:57:5)
npm verbose stack     at Parser.emit (node:events:520:28)
npm verbose stack     at [processEntry] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:248:12)
npm verbose stack     at [nextEntry] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:259:36)
npm verbose stack     at [consumeHeader] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:223:32)
npm verbose stack     at [consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:513:30)
npm verbose stack     at [consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:485:30)
npm verbose stack     at Unzip.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:410:59)
npm verbose stack     at Unzip.emit (node:events:520:28)
npm error Cannot read properties of null (reading '1')
npm verbose cwd /Users/normanperrin/.local/work/npm-example
npm verbose os Darwin 23.4.0
npm verbose node v22.2.0
npm verbose npm  v10.8.0
npm verbose exit 1
npm verbose code 1
```

### Expected Behavior

For the package to be published

### Steps To Reproduce

1. `mkdir package`
1. `echo '{ "name": "@npm/example", "version": "0.0.1", "engines": { "node": "20.0.0" } }' > package/package.json`
1. `cp -r node_modules package/node_modules`
1. `tar -zcvf npm-example-v1.tgz package`
1. `npm publish --verbose npm-example-v1.tgz`

### Environment

- npm: 10.8.0
- Node.js: 22.2.0
- OS Name: macOS
- System Model Name: Macbook Pro
- npm config: I have none

### PR DESCRIPTION
**Pull request by NormanPerrin**
Details explained in issue #7555

Closes #7555

### CODE REVIEW

**Comment by wraithgar** [comment]
I'm not sure that issue fully explains how to get into this situation.  It mentions

```
cp -r node_modules package/node_modules
```

But there's no indication of what's in that directory that's causing this.  Once that is known, it will inform what the test will look like for this PR.

File: lib/utils/tar.js [hunk 1]
```diff
@@ -60,7 +60,12 @@ const getContents = async (manifest, tarball) => {
       totalEntrySize += entry.size
       const p = entry.path
       if (p.startsWith('package/node_modules/')) {
```
Comment (wraithgar) [inline lib/utils/tar.js]:
```suggestion
      if (p.startsWith('package/node_modules/') && p !== 'package/node_modules/') {
```

Comment (wraithgar) [reply lib/utils/tar.js]: The regex falls over if there are NO characters after `package/node_modules/`

File: lib/utils/tar.js [hunk 2]
```diff
@@ -60,7 +60,12 @@ const getContents = async (manifest, tarball) => {
...
-        const name = p.match(/^package\/node_modules\/((?:@[^/]+\/)?[^/]+)/)[1]
+        const match = p.match(/^package\/node_modules\/((?:@[^/]+\/)?[^/]+)/)
+        if (!match) {
+          return
+        }
+
+        const name = match[1]
```
Comment (wraithgar) [inline lib/utils/tar.js]: This can be reverted w/ the above suggestion

File: lib/utils/tar.js (hunk 1 above)
Comment (NormanPerrin) [reply lib/utils/tar.js]: Suggestion applied 👍🏽

**Comment by wraithgar** [comment]
Great! Now it'll just need a test to cover that new code path.

**Comment by NormanPerrin** [comment]
@wraithgar 
> Great! Now it'll just need a test to cover that new code path.

Added 👌🏽

**Review by wraithgar — APPROVED** [review]
