### PR TITLE
fix(publish): skip workspace packages marked private on publish

### LINKED ISSUE #7199: [BUG] publish with workspaces doesn't respect access controls
### Is there an existing issue for this?

It looks like this is the same issue as #3268, although the error I'm getting is different, and it appears that the fix in 4a4fbe33c51413adcd558b4af6f1e204b1b87e41 is specific to the error.

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am trying to use workspaces where a number of the packages should not be published (they have `"private": true` in their `package.json`).  I would like to run a single command that publishes all of the non-private packages.  I was hoping this would work:
```shell
npm publish --workspaces
```

When I try this, I get this error:
```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

I found #3268 and was hoping that #3285 might have addressed the issue, but it that fix was specific to the `EPRIVATE` error code.  In this case I am seeing `ENEEDAUTH`.

### Expected Behavior

I was hoping that `npm publish --workspaces` could be used to publish all workspace packages except those that have `"private": true` in their `package.json`.

### Steps To Reproduce

1. create a package with two workspaces, one named `do-not-publish` and one named `@example/package`
2. in the `package.json` for the `do-not-publish` package, add `"private": true`
3. run `npm logout && npm login --registry=https://npm.pkg.github.com --scope=@example`
4. run `npm publish --workspaces`
5. See `npm ERR! code ENEEDAUTH`

It looks like the `ENEEDAUTH` error is thrown for the `do-not-publish` package even though it includes `"private": true`.  I assume this only happens when the user is not already authenticated with the default registry.  In my case, it is occurring in a CI job where an auth-token is only provided for a non-default registry (where the scoped packages are published).

### Environment

- npm: 10.2.4
- Node.js: 21.5.0

### PR DESCRIPTION
**Pull request by milaninfy**
`npm publish --workspaces` will skip workspace packages marked as private in package.json. 
Currently it's skipping those packages only when you have configured auth for those packages, it would error out with `ENEEDAUTH` if it doesn't find the valid auth information. 

this fix checks for the private property before checking for auth for the packages that will essentially not going to get published. 

Fixes https://github.com/npm/cli/issues/7199

### CODE REVIEW

File: lib/commands/publish.js [hunk 1]
```diff
@@ -127,6 +127,15 @@ class Publish extends BaseCommand {
     const noCreds = !(creds.token || creds.username || creds.certfile && creds.keyfile)
     const outputRegistry = replaceInfo(registry)
 
+    // if a workspace package is marked private then we skip it
+    if (workspace && manifest.private) {
```
Comment (milaninfy) [inline lib/commands/publish.js:131]: Is there a better way to check if the package is workspace package ?

Comment (wraithgar) [reply lib/commands/publish.js:131]: No this is fine.

**Review by wraithgar — APPROVED** [review]

**Review by Dropkick13 — COMMENTED** [review]
[]()
