### PR TITLE
fix(sbom): deduplicate sbom dependencies

### LINKED ISSUE #6967: [BUG] SBOM generation for CycloneDX generates duplicate dependencies
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The generated CycloneDX SBOM may not be able to be parsed by tools, as it generates duplicate dependencies.

### Expected Behavior

A CycloneDX v1.5 SBOM generated from a repository can be parsed correctly.

### Steps To Reproduce

1. Clone https://gitlab.com/tanna.dev/renovate-graph
2. Run `npm  sbom --sbom-format cyclonedx > cyclonedx.json`
3. Run through an Cyclone validator i.e. `go run github.com/CycloneDX/sbom-utility@latest validate --input-file cyclonedx.json`

[renovate-graph.cyclonedx.json](https://github.com/npm/cli/files/13260555/renovate-graph.cyclonedx.json)

### Environment

- npm: 10.2.3
- Node.js: v18.17.1
- OS Name: Linux
- System Model Name:
- npm config:
```ini
; "user" config from /home/jamie/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /usr/bin/node
; node version = v18.17.1
; npm local prefix = /home/jamie/workspaces/renovate-graph
; npm version = 10.2.3
; cwd = /home/jamie/workspaces/renovate-graph
; HOME = /home/jamie
; Run `npm config ls -l` to show all defaults.

```

### PR DESCRIPTION
**Pull request by bdehamer**
Certain project dependency trees may result in an SBOM with duplicate entries. This fix ensures that each unique dependency (identified by the combination of package name and version) only appears in the SBOM once. Applies to both SPDX and CycloneDX SBOM formats.

Specific to the CycloneDX format, this change also removes the `cdx:npm:package:path` property from the `component` entries in the generated SBOM. Since the same package may be present at multiple paths within the project and we're now de-duplicating those packages, it no longer makes sense to include this in the SBOM. This does not impact the SPDX format as there is no equivalent property.

Fixes: #6967

### CODE REVIEW

File: lib/utils/sbom-cyclonedx.js [hunk 1]
```diff
@@ -31,19 +30,18 @@ const cyclonedxOutput = ({ npm, nodes, packageType, packageLockOnly }) => {
   const childNodes = nodes.filter(node => !node.isRoot && !node.isLink)
   const uuid = crypto.randomUUID()
 
-  const deps = []
-  const seen = new Set()
-  for (let node of nodes) {
-    if (node.isLink) {
-      node = node.target
```
Comment (wraithgar) [inline lib/utils/sbom-cyclonedx.js:38]: What was this doing before that we aren't needing now?  It's unclear to my how this change removes the need to set the target here.

Comment (bdehamer) [reply lib/utils/sbom-cyclonedx.js:38]: Previously, this logic was used to de-dupe link nodes from their corresponding target nodes. When there is a linked dependency you'd end-up with something like the following in the list of nodes:

```json
[
  {
    "name": "chai",
    "version": "1.0.0",
    "location": "node_modules/chai",
    "path": "/private/tmp/sbom/node_modules/chai",
    "realpath": "/private/tmp/chai",
    "resolved": "file:../../chai",
    "edgesIn": {},
    "target": {
      "name": "chai",
      "version": "1.0.0",
      "location": "../chai",
      "path": "/private/tmp/chai",
      "edgesOut": {},
      "children": {}
    },
  },
  {
    "name": "chai",
    "version": "1.0.0",
    "location": "../chai",
    "path": "/private/tmp/chai",
    "edgesOut": {},
    "children": {}
  }
]
```

Now, since we're deduplicating ALL of the nodes based on their name/version this is no longer needed -- the link and target or handled as part of the overall deduplication of the list.

**Review by wraithgar — APPROVED** [review]
