### PR TITLE
fix: skip creation of log directory if `logs-max` is set to 0

### LINKED ISSUE #7032: [BUG] Why is `npm` run writing into the `.npm/_logs` directory or creating it?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm run` is creating if it does not exist and writing if it exists into the `.npm/_logs` directory.

### Expected Behavior

Even if logs are turned off completely with the `--logs-max=0` option, the directory is still created. This calls for workarounds if the current directory is not writable (a relatively common scenario if you're working inside a container) or workarounds, but there is apparently no way to turn it off completely.

### Steps To Reproduce

This Dockerfile:

```Dockerfile
FROM node:21-alpine

RUN mkdir -p /app/test && chown -R node:node /app && npm install -g npm@latest

USER node

WORKDIR /app

COPY package.json ./

WORKDIR /app/test

ENTRYPOINT ["npm", "--logs-max=0", "run", "test"]
```

With this `package.json` 

```json
{
  "name": "dotnpm-created",
  "version": "1.0.0",
  "description": "Test file",
  "main": "index.js",
  "scripts": {
    "test": "echo \"test\""
  },
  "author": "",
  "license": "ISC"
}
```

When run with:

```shell
podman run --rm -it -v `pwd`:/app/test -u 1001 jjmerelo/dotnpm-test
```

It creates a `.npm` file with:

```text
.npm:
total 12
drwxr-xr-x 3  101000 jmerelo 4096 nov 28 14:38 .
drwxrwxr-x 3 jmerelo jmerelo 4096 nov 28 14:38 ..
drwxr-xr-x 2  101000 jmerelo 4096 nov 28 14:38 _logs

.npm/_logs:
total 8
drwxr-xr-x 2 101000 jmerelo 4096 nov 28 14:38 .
drwxr-xr-x 3 101000 jmerelo 4096 nov 28 14:38 ..
```

So it still has an empty log directory.

### Environment

-  `npm@10.2.4`
-  `node@v21.2.0`
-  Alpine OS
- npm config: 

```
; node bin location = /usr/local/bin/node
; node version = v21.2.0
; npm local prefix = /app
; npm version = 10.2.4
; cwd = /app/test
; HOME = /home/node
```

### PR DESCRIPTION
**Pull request by JJ**
If no logs are needed, don't call the task that creates the directory anyway. This goes mainly to fix #7032. Also, typo.

### CODE REVIEW

File: lib/npm.js [hunk 1]
```diff
@@ -216,11 +216,13 @@ class Npm {
       fs.mkdir(this.cache, { recursive: true })
         .catch((e) => log.verbose('cache', `could not create cache: ${e}`)))
 
-    // its ok if this fails. user might have specified an invalid dir
+    // it's ok if this fails. user might have specified an invalid dir
     // which we will tell them about at the end
-    await this.time('npm:load:mkdirplogs', () =>
-      fs.mkdir(this.logsDir, { recursive: true })
-        .catch((e) => log.verbose('logfile', `could not create logs-dir: ${e}`)))
+    if ( this.logsDir !== '' ) {
```
Comment (wraithgar) [inline lib/npm.js]:
```javascript
  get logsDir () {
    return this.config.get('logs-dir') || join(this.cache, '_logs')
  }
```

I'm not sure how this can be an empty string.

Comment (JJ) [reply lib/npm.js]: Didn't get that far. You want me to work around this?
Also, it might still create the cache dir, `.npm` so it might not be fixing #7032 after all.

Comment (JJ) [reply lib/npm.js]: Temptatively solved in 30b1fbc9b4f700288de161a2e3b87ecf0b3ed8da

Comment (wraithgar) [reply lib/npm.js]: That commit joins the config with the cacheDir, which wasn't happening before. That only happens in the fallback if the user did not configure a logs-dir.

I'm not sure this is a very safe path to go down.  It seems like a poor idea to use "set logs dir to an empty string" as the signal for npm to NOT use logs at all.

I think a more correct course of action would be for `lib/npm.js` (and `lib/utils/exit-handler.js`) to be aware of `logs-max` and to not create a log dir if it's not going to be used.

`silent` should NOT affect log file writing, as that is only a directive for what npm prints to stdout.

Comment (wraithgar) [reply lib/npm.js]: Looks like the exit handler is already aware of `logs-max` so the mkdir is the only new thing that needs to be aware of it.

Comment (JJ) [reply lib/npm.js]: > That commit joins the config with the cacheDir, which wasn't happening before. That only happens in the fallback if the user did not configure a logs-dir.
> 
> I'm not sure this is a very safe path to go down. It seems like a poor idea to use "set logs dir to an empty string" as the signal for npm to NOT use logs at all.
> 
> I think a more correct course of action would be for `lib/npm.js` (and `lib/utils/exit-handler.js`) to be aware of `logs-max` and to not create a log dir if it's not going to be used.

OK, I'll try that. Thanks for the review!

**Comment by wraithgar** [comment]
`npm run lintfix` should get you all green now.

File: test/lib/utils/exit-handler.js [hunk 2]
```diff
@@ -344,12 +344,12 @@ t.test('no logs dir', async (t) => {
   const { exitHandler, logs } = await mockExitHandler(t, {
     config: { 'logs-max': 0 },
   })
-
   await exitHandler(new Error())
 
   t.match(logs.error.filter(([t]) => t === ''), [
     ['', 'Log files were not written due to the config logs-max=0'],
   ])
+  t.match(logs.filter(([_,task]) => task === 'npm.load.mkdirplogs'), [])
```
Comment (wraithgar) [inline test/lib/utils/exit-handler.js]:
```suggestion
  t.match(logs.filter(([_, task]) => task === 'npm.load.mkdirplogs'), [])
```
