### PR TITLE
fix: don't die if manNumberRegex doesn't match the glob (#4610)

### LINKED ISSUE #4610: [BUG] `npm help config` fails with "Cannot read property '1' of null"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Here's the relevant error:

29 verbose stack TypeError: Cannot read property '1' of null
29 verbose stack     at /nobackup/usr/share/nodejs/npm/lib/commands/help.js:65:49
29 verbose stack     at Array.sort (<anonymous>)
29 verbose stack     at Help.exec (/nobackup/usr/share/nodejs/npm/lib/commands/help.js:63:17)
29 verbose stack     at async module.exports (/nobackup/usr/share/nodejs/npm/lib/cli.js:66:5)

The full log, slightly scrubbed for privacy:

0 verbose cli [ '/nobackup/usr/bin/node', '/usr/bin/npm', 'help', 'config' ]
1 info using npm@8.5.5
2 info using node@v12.22.10
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/nobackup/usr/share/nodejs/npm/npmrc Completed in 5ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/davedude/public_html/ConjunctionJunction/.npmrc Completed in 1ms
10 timing config:load:project Completed in 5ms
11 timing config:load:file:/home/davedude/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 15ms
19 timing npm:load:configload Completed in 16ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:display Completed in 4ms
23 verbose logfile /home/XXX/.npm/_logs/YYY-debug-0.log
24 timing npm:load:logFile Completed in 5ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 25ms
28 timing command:help Completed in 17ms
29 verbose stack TypeError: Cannot read property '1' of null
29 verbose stack     at /nobackup/usr/share/nodejs/npm/lib/commands/help.js:65:49
29 verbose stack     at Array.sort (<anonymous>)
29 verbose stack     at Help.exec (/nobackup/usr/share/nodejs/npm/lib/commands/help.js:63:17)
29 verbose stack     at async module.exports (/nobackup/usr/share/nodejs/npm/lib/cli.js:66:5)
30 verbose cwd /home/XXX/YYY
31 verbose Linux 5.9.0-5-amd64
32 verbose argv "/nobackup/usr/bin/node" "/usr/bin/npm" "help" "config"
33 verbose node v12.22.10
34 verbose npm  v8.5.5
35 error Cannot read property '1' of null
36 verbose exit 1
37 timing npm Completed in 161ms
38 verbose code 1
39 error A complete log of this run can be found in:
39 error     /home/XXX/.npm/_logs/YYY-debug-0.log

### Expected Behavior

I get help for the config sub-command.

### Steps To Reproduce

1. In Debian (possibly Ubuntu or others), install `npm` using `dpkg`. The important thing here is that it's installed via the system package manager, and thus using the system `man` directories.
2. Install `openssl`. This package owns the manpage "man5/config.5ssl.gz".
3. Run `npm help config`
4. Receive error

### Environment

- npm: 8.5.5
- Node.js: v12.22.10
- OS Name: Debian testing
- System Model Name: Linux 5.9.0-5-amd64 x86_64
- npm config: (lightly scrubbed for privacy)
```ini
; "builtin" config from /nobackup/usr/share/nodejs/npm/npmrc

globalignorefile = "/etc/npmignore"
prefix = "/usr/local"

; node bin location = /nobackup/usr/bin/node
; cwd = /home/XXX/YYY
; HOME = /home/XXX
```

### PR DESCRIPTION
**Pull request by d0sboots**
In certain edge cases, the glob could find files that manNumberRegex wouldn't match.

A possible solution would be to try to bring the two closer, but since globs and regexes are different syntaxes, the two will never be exactly the same.
It's always asking for bugs; better to just handle the issue directly.

In addition, when npm is installed globally in a system directory, the
glob can find other manpages with similar names.
For instance "install.1", "init.1", etc. Preferring low-numbered
sections isn't enough in these cases; it's also necessary to prefer
the pages prefixed with "npm-".

Fixes #4610

### CODE REVIEW

File: lib/commands/help.js [hunk 1]
```diff
@@ -61,9 +61,10 @@ class Help extends BaseCommand {
     const f = `${manroot}/${manSearch}/?(npm-)${section}.[0-9]*`
     let mans = await glob(f)
     mans = mans.sort((a, b) => {
-      // Because of the glob we know the manNumberRegex will pass
-      const aManNumber = a.match(manNumberRegex)[1]
-      const bManNumber = b.match(manNumberRegex)[1]
+      // Because the glob is (subtly) different from manNumberRegex,
+      // we can't rely on it passing.
+      const aManNumber = (a.match(manNumberRegex) || Infinity)[1]
```
Comment (ljharb) [inline lib/commands/help.js]: I don’t think you want index 1 of Infinity
```suggestion
      const aManNumber = a.match(manNumberRegex)?.[1] || Infinity
```
(assuming optional chaining is available in all of npm’s supported nodes)

Comment (wraithgar) [reply lib/commands/help.js]: It is not

**Comment by wraithgar** [comment]
This would need tests as well.

File: lib/commands/help.js (hunk 1 above)
Comment (ljharb) [reply lib/commands/help.js]: Then the match object probably needs to be saved in its own variable, and the [1] done separately.

Comment (d0sboots) [reply lib/commands/help.js]: Fixed. I'm not sure how that worked in my manual testing...

**Comment by d0sboots** [comment]
I've added tests and significantly redid the PR. I also addressed an issue that I see as linked, but I can separate it out if you want - that frequently, `npm help` gets the wrong page, showing me system manpages instead of help for npm. This happens for me for `npm help init`, `npm help install`, and others.

**Comment by d0sboots** [comment]
Amusingly, there's actually no check that `npm help` is getting help about `npm` **at all**. So `npm help sudo` works for me as an alternative to `man sudo`, for instance. But fixing that is out of scope for this...

File: lib/commands/help.js [hunk 2]
```diff
@@ -61,13 +63,27 @@ class Help extends BaseCommand {
     const f = `${manroot}/${manSearch}/?(npm-)${section}.[0-9]*`
     let mans = await glob(f)
     mans = mans.sort((a, b) => {
-      // Because of the glob we know the manNumberRegex will pass
-      const aManNumber = a.match(manNumberRegex)[1]
-      const bManNumber = b.match(manNumberRegex)[1]
+      // Prefer the page with an npm prefix, if there's only one.
+      const aHasPrefix = a.match(manNpmPrefixRegex)
+      const bHasPrefix = b.match(manNpmPrefixRegex)
+      if (!aHasPrefix !== !bHasPrefix) {
```
Comment (ljharb) [inline lib/commands/help.js:69]: this seems like a really weird way to do this; if you’re not using the match object, do regex.test(str) instead?

Comment (ljharb) [inline lib/commands/help.js]:
```suggestion
      if (!!aHasPrefix !== !!bHasPrefix) {
```
the single ! makes it look more like a bug than intentional imo

but also this should use manNpmPrefixRegex.test(a) instead, since it’s not using the match object

Comment (d0sboots) [reply lib/commands/help.js]: Done. I'm a decent developer in general, but I won't claim to be good at JS...

File: lib/commands/help.js (hunk 1 above)
Comment (wraithgar) [reply lib/commands/help.js]: you tested in a version of node that supported it. npm has to run in older versions that don't have that feature.

**Comment by d0sboots** [comment]
Is there anything remaining here that I need to do?

**Review by lukekarrys — APPROVED** [review]
