### PR TITLE
fix(libnpmexec): fix bug not install latest pkg

### LINKED ISSUE #4619: [BUG] npx add confirmation to proceed everytime
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
➜  docusaurus git:(main) node -v
v16.14.2
➜  docusaurus git:(main) npm -v
8.5.0

➜  docusaurus git:(main) npx yarn-deduplicate
Need to install the following packages:
  yarn-deduplicate
Ok to proceed? (y) y

➜  docusaurus git:(main) npx yarn-deduplicate
Need to install the following packages:
  yarn-deduplicate
Ok to proceed? (y) y
```

### Expected Behavior

The second execution of `npx yarn-deduplicate` shouldn't ask for a confirmation

### Steps To Reproduce

see above

### Environment

- npm: 8.5.0
- Node.js: 16.14.2
- OS Name: MacOS 12.1 Monterey
- System Model Name: ?
- npm config:
```ini
; "user" config from /Users/sebastienlorber/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /Users/sebastienlorber/.volta/tools/image/node/16.14.2/bin/node
; cwd = /Users/sebastienlorber/Desktop/projects/docusaurus
; HOME = /Users/sebastienlorber
; Run `npm config ls -l` to show all defaults.
```

### LINKED ISSUE #4871: [BUG] npx command not install latest package
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I runned  `npx create-react-app` to create react project three months ago. The create-react-app package version is v4.0.3.
Now, I want to run run  `npx create-react-app` to create react project, but npx command not install create-react-app package latest version.
飞书20220509-203144
I never install create-react-app  use -g params.

### Expected Behavior

npx command install create-react-app  package latest version

### Steps To Reproduce

1. create a test package and npm publish it
2. run npx <package>
3. bump package version and publish it
4. run npx <package>
5. <package> version not update

### Environment

- npm: 8.9.0
- Node.js: 16.15.0
- OS Name: macOS
- System Model Name:10.15.7
- npm config:
```ini
; "user" config from /Users/admin/.npmrc

//registry.npmjs.org/:_authToken = (protected)
access = "public"

; "project" config from /Users/admin/.nvm/.npmrc

package-lock = false

; node bin location = /Users/admin/.nvm/versions/node/v14.19.0/bin/node
; node version = v14.19.0
; npm local prefix = /Users/admin/.nvm
; npm version = 8.9.0
; cwd = /Users/admin/.nvm/versions/node/v16.15.0
; HOME = /Users/admin
; Run `npm config ls -l` to show all defaults.
; copy and paste output from `npm config ls` here
```

### PR DESCRIPTION
**Pull request by jihunleekr**
After the major version of the package is changed (e.g. 0.9 > 1.0 > 2.0)
npx just asks if you want to install it every time 
It doesn't actually install.

## References
Fixes #4871
Fixes #4619

### CODE REVIEW

File: workspaces/libnpmexec/lib/index.js [hunk 1]
```diff
@@ -166,7 +166,7 @@ const exec = async (opts) => {
     const add = manis
       .filter(mani => !mani[_localManifest])
       .filter(filterMissingPackagesFromInstallDir)
-      .map(mani => mani._from)
+      .map(mani => mani._id ? mani._id : mani._from)
```
Comment (ljharb) [inline workspaces/libnpmexec/lib/index.js]:
```suggestion
      .map(mani => mani._id || mani._from)
```

**Review by ruyadorno — APPROVED** [review]
Let's go ahead with this change, I'm pretty sure this will be a more reasonable behavior in terms of UX 👍 thanks @jihunleekr
