### PR TITLE
fix(exec): look in workspace and root for bin entries

### LINKED ISSUE #7379: [BUG] npm exec -w [workspace] doesn't local deps installed in parent-repository node_modules
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When a workspace has a (bin) @scope/dependency thats installed in the root-workspace's node_modules; and you execute it with `npm exec -w child-workspace @scope/name`, the node_modules from root-workspace is ignored and global version is used instead.

Added problem: Since the global node_modules is used, a different version of the package may be used.

### Expected Behavior

`npm exec -w child-workspace @scope/name` uses `root_workspace/node_modules/@scope/name`

### Steps To Reproduce

```
npm init -y
npm init -w child-workspace -y
npm i -w child-workspace @pega/dx-component-builder-sdk@23.1.11
npm exec -w child-workspace @pega/dx-component-builder-sdk
```

Result:
```
Need to install the following packages:
@pega/dx-component-builder-sdk@23.1.14
Ok to proceed? (y)
```

### Environment

- npm: 10.5.0
- Node.js: 20.12.2
- OS Name: MacOS Sonoma 14.3.1
- System Model Name: Apple M1 Pro
- npm config: 
```ini
% npm config ls
; node bin location = /Users/wimbarelds/.nvm/versions/node/v20.12.2/bin/node
; node version = v20.12.2
; npm local prefix = /Users/wimbarelds/projects/npm-test
; npm version = 10.5.0
; cwd = /Users/wimbarelds/projects/npm-test
; HOME = /Users/wimbarelds
; Run `npm config ls -l` to show all defaults.
```

### Notes:

- I am not completely sure if the scope is relevant
  - I do _not_ have this issue with `eslint`
  - I _do_ have this issue with `@pega/dx-component-builder-sdk`.
- I can confirm this issue does not occur with npm 9.8.1

### PR DESCRIPTION
**Pull request by wraithgar**
Closes: https://github.com/npm/cli/issues/7379

### CODE REVIEW

**Review by reggi — APPROVED** [review]
LTGM

File: lib/commands/exec.js [hunk 1]
```diff
@@ -54,7 +51,7 @@ class Exec extends BaseCommand {
       localBin = resolve(this.npm.localDir, name, 'node_modules', '.bin')
       // We also need to look for `bin` entries in the workspace package.json
       // libnpmexec will NOT look in the project root for the bin entry
-      path = runPath
+      pkgPath = runPath
```
Comment (Thorsmercy) [inline lib/commands/exec.js:54]: Run

File: workspaces/libnpmexec/lib/index.js [hunk 2]
```diff
@@ -14,7 +14,7 @@ const getBinFromManifest = require('./get-bin-from-manifest.js')
 const noTTY = require('./no-tty.js')
 const runScript = require('./run-script.js')
 const isWindows = require('./is-windows.js')
-const { dirname, resolve } = require('path')
+const { dirname, resolve } = require('node:path')
```
Comment (nehtech9) [inline workspaces/libnpmexec/lib/index.js:17]: []()Node.js[]()@npm-cli-bot
