### PR TITLE
fix!: refuse to pack when overrides apply to bundled packages

### LINKED ISSUE #1102: Refuse to publish package with bundled dependencies AND overrides
This is a follow up to https://github.com/npm/cli/pull/9235.  If a package has bundled dependencies AND overrides, the tree that is bundled will be invalid and should not be published.

### PR DESCRIPTION
**Pull request by owlstronaut**
Follow up to #9235.

When a package defines `overrides` that apply to one or more of its `bundledDependencies` (or `bundleDependencies`), the resulting bundled tree is invalid from the perspective of any consumer: consumers do not apply the publishing package's overrides when validating the bundled tree, so `npm ls` will always show invalid edges for the affected bundled packages.

This PR refuses to pack (and therefore publish) such packages with a clear `EBUNDLEOVERRIDE` error that lists the offending bundled package names. Defining both `overrides` and `bundledDependencies` is still allowed — the error only fires when an override actually targets a package inside the bundled subtree. Cases that are now correctly accepted include:

- overrides that target dev dependencies (which are not bundled),
- overrides that target packages outside the bundled subtree, and
- packages that bundle some deps but override only unrelated ones.

The check uses Arborist's own `inBundle` / `inDepBundle` / `overridden` semantics on the actual on-disk tree (the same tree pacote uses to build the tarball), so it stays consistent with what `npm-packlist` actually publishes.

The check lives in `libnpmpack`, so it covers `npm pack`, `npm publish`, and any direct consumers of the library.

Closes https://github.com/npm/statusboard/issues/1102.

BREAKING CHANGE: npm pack and npm publish now error when a package's overrides apply to one or more of its bundled packages (`bundledDependencies` / `bundleDependencies`). Defining both fields is still allowed as long as no override actually targets a bundled package. To resolve the error, remove the affected entries from either `overrides` or the bundle.

### CODE REVIEW

**Comment by wraithgar** [comment]
What if we have overridden dev dependencies?
What if we only bundle some of our dependencies and none of them are overridden?

**Comment by owlstronaut** [comment]
> What if we have overridden dev dependencies? What if we only bundle some of our dependencies and none of them are overridden?

those are good points. I'll need to make this a little more flexible

File: workspaces/libnpmpack/lib/index.js [hunk 1]
```diff
@@ -14,6 +14,41 @@ async function pack (spec = 'file:.', opts = {}) {
 
   const manifest = await pacote.manifest(spec, { ...opts, Arborist, _isRoot: true })
 
+  if (spec.type === 'directory') {
+    const bundled = manifest.bundledDependencies || manifest.bundleDependencies
```
Comment (wraithgar) [inline workspaces/libnpmpack/lib/index.js]: Pacote already [normalizes the manifest](https://github.com/npm/pacote/blob/6c2555a38a2dc0ab2fb98c4f934d714be5f3ba49/lib/registry.js#L134) and part of that normalization is to deal with [bundleDependencies etc](https://github.com/npm/package-json/blob/1affdf1c3ce78b78775ef29faa2f45fa08abb1e9/lib/index.js#L43-L44).

File: workspaces/libnpmpack/lib/index.js [hunk 2]
```diff
@@ -14,6 +14,41 @@ async function pack (spec = 'file:.', opts = {}) {
...
+    const hasBundled = Array.isArray(bundled) ? bundled.length > 0 : Boolean(bundled)
```
Comment (wraithgar) [inline workspaces/libnpmpack/lib/index.js]: This should[ always be an array](https://github.com/npm/package-json/blob/1affdf1c3ce78b78775ef29faa2f45fa08abb1e9/lib/normalize.js#L221-L238) if it exists

File: workspaces/libnpmpack/lib/index.js [hunk 3]
```diff
@@ -14,6 +14,41 @@ async function pack (spec = 'file:.', opts = {}) {
...
+    const hasOverrides = manifest.overrides
+      && typeof manifest.overrides === 'object'
```
Comment (wraithgar) [inline workspaces/libnpmpack/lib/index.js:20]: This is a hole in package-json's normalization.  We can update there to make sure of the data shape and not be required to do these kinds of things every time we want to read a manifest.

File: workspaces/libnpmpack/lib/index.js [hunk 4]
```diff
@@ -14,6 +14,41 @@ async function pack (spec = 'file:.', opts = {}) {
...
+      && Object.keys(manifest.overrides).length > 0
+    if (hasBundled && hasOverrides) {
+      // Only refuse when an override rule actually applies to a package that is bundled by the root. Overrides targeting dev dependencies or any package outside the bundled tree are harmless to consumers, because consumers do not apply the publishing package's overrides. We rely on Arborist's own semantics (inBundle/inDepBundle/overridden) rather than reimplementing what npm-packlist/arborist already know.
```
Comment (wraithgar) [inline workspaces/libnpmpack/lib/index.js]:
```suggestion
      // Only refuse when an override rule actually applies to a package that is bundled by the root.
      // Overrides targeting dev dependencies or any package outside the bundled tree are harmless to consumers, because consumers do not apply the publishing package's overrides.
      // We rely on Arborist's own semantics (inBundle/inDepBundle/overridden) rather than reimplementing what npm-packlist/arborist already knows.
```

File: workspaces/libnpmpack/lib/index.js [hunk 5]
```diff
@@ -14,6 +14,41 @@ async function pack (spec = 'file:.', opts = {}) {
...
+      const arb = new Arborist({ ...opts, path: spec.fetchSpec })
```
Comment (wraithgar) [inline workspaces/libnpmpack/lib/index.js]: When pacote makes the tarball the only thing it [passes to arborist](https://github.com/npm/package-json/blob/1affdf1c3ce78b78775ef29faa2f45fa08abb1e9/lib/normalize.js#L221-L238) is the path:

```js
  const arb = new this.Arborist({ path: this.resolved })
  this.tree = await arb.loadActual()
```

Comment (wraithgar) [reply workspaces/libnpmpack/lib/index.js]: This makes me wonder: should this live in pacote.tarball?  We are already loading the actual tree there so it'd be the right time to make this check.

Comment (owlstronaut) [reply workspaces/libnpmpack/lib/index.js]: I think it still lives here, it shouldn't be a fetcher's concern.

File: workspaces/libnpmpack/lib/index.js (hunk 3 above)
Comment (owlstronaut) [reply workspaces/libnpmpack/lib/index.js:20]: Agreed, I'll keep the defensive check here for now but follow up in package-json with a fix for that

File: workspaces/libnpmpack/lib/index.js [hunk 6]
```diff
@@ -14,6 +14,43 @@ async function pack (spec = 'file:.', opts = {}) {
 
   const manifest = await pacote.manifest(spec, { ...opts, Arborist, _isRoot: true })
 
+  if (spec.type === 'directory') {
+    const hasBundled = Array.isArray(manifest.bundleDependencies)
+      && manifest.bundleDependencies.length > 0
```
Comment (wraithgar) [inline workspaces/libnpmpack/lib/index.js]:
```suggestion
    const hasBundled = manifest.bundleDependencies?.length > 0
```

normalize already turns this into an array or nothing: https://github.com/npm/package-json/blob/1affdf1c3ce78b78775ef29faa2f45fa08abb1e9/lib/normalize.js#L220-L238

Comment (owlstronaut) [reply workspaces/libnpmpack/lib/index.js]: haha, you responded to this while I was in the middle of changing it 😛

**Review by wraithgar — APPROVED** [review]
