### PR TITLE
fix: installLinks works with transitive external file dependencies

### LINKED ISSUE #8342: [BUG] `--install-links` fails when local package has nested local dependencies
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

When installing a local package with `--install-links`, if that package has its own local dependencies, the installation fails. Is this behavior by design?

In this example, package `b` depends on package `a`, both located in sibling directories:

```
$ tree . -I node_modules
.
├── a
│   ├── package-lock.json
│   └── package.json
├── b
│   ├── package-lock.json
│   └── package.json
└── mainpkg
    ├── package-lock.json
    └── package.json

4 directories, 6 files

$ cat b/package.json 
{"name":"b","dependencies":{"a":"file:../a"}}
```

The npm CLI attempts to resolve `../a` from within `node_modules/b` or `node_modules/a`, which does not exist. This results in an `ENOENT` error:

```
$ cd mainpkg && npm install --install-links ../b
npm error code ENOENT
npm error syscall open
npm error path /home/mukai/Documents/mainpkg/node_modules/a/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/mukai/Documents/mainpkg/node_modules/a/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /home/mukai/.npm/_logs/2025-06-03T11_28_04_990Z-debug-0.log
```

### Expected Behavior

The dependency `a`, as listed in `b`'s `package.json`, should be resolved relative to `b` itself (i.e., `../a` from `b`). As a result, the structure of `mainpkg/node_modules` should look like this:

~~~
$ tree mainpkg/node_modules
mainpkg/node_modules
├── a -> ../../a
└── b -> ../../b

3 directories, 0 files
~~~

### Steps To Reproduce

~~~
$ mkdir a b mainpkg
$ echo '{"name":"a"}' > a/package.json
$ echo '{"name":"b"}' > b/package.json
$ cd b && npm install ../a && cd ../
$ cd mainpkg && npm init --yes
$ npm install --install-links ../b
~~~

### Environment

- npm: 11.4.1
- Node.js: v22.14.0
- OS Name: Ubuntu 24.04
- System Model Name: ThinkPad-X1-Carbon-7th
- npm config:
```ini
; "user" config from /home/mukai/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = /home/mukai/.nvm/versions/node/v22.14.0/bin/node
; node version = v22.14.0
; npm local prefix = /home/mukai/Documents/mainpkg
; npm version = 11.4.1
; cwd = /home/mukai/Documents/mainpkg
; HOME = /home/mukai
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by owlstronaut**
fixes https://github.com/npm/cli/issues/8342

What
This PR fixes an issue where npm fails to properly handle transitive file dependencies when using the --install-links flag. Previously, when a file dependency had its own file dependencies, npm would fail to resolve them correctly, resulting in `ERR_MODULE_NOT_FOUND` errors.

Why
When using `npm install --install-links` to install a local package that has its own file dependencies, npm would attempt to resolve the transitive dependencies relative to the installed location in `node_modules` rather than the original source location. This caused the installation to fail because the transitive dependencies couldn't be found at the incorrect path.

For example, given this structure:

Running `npm install --install-links ../b` from `mainpkg` would fail because npm tried to find a relative to `b` instead of relative to the original `b` source location.

How
The fix introduces logic to detect transitive file dependencies when `--install-links` is used and ensures they are resolved relative to their parent's original source location:

Detect transitive file dependencies: When a parent package was installed (not linked) due to `--install-links` and has file dependencies of its own, those are identified as transitive file dependencies.

Preserve original paths: The parent's resolved` field (e.g., file:../b) is used to determine the original source location.

Correct path resolution: Transitive file dependencies are resolved relative to the parent's original location rather than its installed location in `node_modules`

### CODE REVIEW

File: workspaces/arborist/lib/arborist/build-ideal-tree.js [hunk 1]
```diff
@@ -1238,22 +1238,36 @@ This is a one-time fix-up, please be patient...
...
     }
 
+    // For file: dependencies that we're installing (not linking), ensure proper resolution
+    if (isTransitiveFileDep && edge) {
+      // For transitive file deps, resolve relative to the parent's original source location
+      const parentOriginalPath = parent.resolved.slice(5) // Remove 'file:' prefix
+      const relativePath = edge.rawSpec.slice(5) // Remove 'file:' prefix
+      const absolutePath = resolve(parentOriginalPath, relativePath)
+      spec = npa(`file:${absolutePath}`)
+      spec.name = name
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/build-ideal-tree.js]:
```suggestion
      spec = npa.resolve(name, `file:${absolutePath}`)
```

**Review by wraithgar — APPROVED** [review]
