### PR TITLE
fix: shrinkwrap setting incorrect lockfileVersion

### LINKED ISSUE #3962: [BUG] --lockfile-version is not respected when using shrinkwrap and hidden lockfile
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`$ npm shrinkwrap --lockfile-version=2` produces a v3 lockfile.

`v8.1.1` used to print a warning, but https://github.com/npm/cli/pull/3949 changed that.

`v8.1.2` just produces a v3 lockfile without any warnings.

### Expected Behavior

`lockfile-version` param/config should be respected.

### Steps To Reproduce

0. `$ rm -rf npm-shrinkwrap.json` (if the shrinkwrap exists - it seems to work OK)
1. `$ npm shrinkwrap --lockfile-version=2`
2. `$ cat npm-shrinkwrap.json | jq .lockfileVersion`

Actual: 3
Expected: 2

### Environment

- OS: macOS 11.6
- Node: 14.18.1
- npm: 8.1.2

### PR DESCRIPTION
**Pull request by lukekarrys**
Fix: #3962

When created from a hidden lockfile, shrinkwrap was always setting the
lockfileVersion to 3. The shrinkwrap command also needed to be updated
to log the correct message based on the lockfileVersion config instead
of the static lockfileVersion.

With these fixes, it was possible to log a better message whenever we
are changing the lockfileVersion, either from a config or any existing
lockfile.

Lastly, the tests for shrinkwrap were completely refactored to use the
real npm and test all conceivable scenarios, as well as removing usage
of `util.promisify` in favor of `fs.promises` now that we've dropped
support for Node 10.

### CODE REVIEW

**Comment by lukekarrys** [comment]
@wraithgar I realize this conflicts with #3959, so I'm happy to hold off and fix my conflicts after that is merged.

**Comment by lukekarrys** [comment]
Converting to a draft until #3959 is merged.

File: test/lib/commands/shrinkwrap.js [hunk 1]
```diff
@@ -1,330 +1,212 @@
...
+  config = {},
+  mocks = {}
+) => {
+  const { Npm, logs } = mockNpm(t, mocks)
+  const npm = new Npm()
+  await npm.load()
+
+  npm.localPrefix = t.testdir(testdir)
+  if (config.lockfileVersion)
+    npm.flatOptions.lockfileVersion = config.lockfileVersion
```
Comment (wraithgar) [inline test/lib/commands/shrinkwrap.js]: `npm.config.set('lockfile-version')`

**Review by wraithgar — APPROVED** [review]
