### PR TITLE
fix(arborist): workspaces respect overrides on subsequent installs

### LINKED ISSUE #7660: [BUG] subsequent installs breaks override dependencies in workspaces
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Npm overrides are not respected in subsequent installs.

Output log on installs:
First install. It adds the root node_module.
 ```sh
PS C:\Users\IvanVaccari\Desktop\test-ws> npm i
npm warn deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm warn deprecated connect@2.30.2: connect 2.x series is deprecated

added 135 packages, and audited 137 packages in 4s

23 vulnerabilities (2 moderate, 18 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
 ```
Immediately re-run install. This changes the dependencies by adding node_module in the workspace module.
Was not expecting this.

 ```sh
PS C:\Users\IvanVaccari\Desktop\test-ws> npm i

added 65 packages, and audited 67 packages in 3s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\IvanVaccari\Desktop\test-ws> npm i
npm warn deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm warn deprecated connect@2.30.2: connect 2.x series is deprecated

added 117 packages, removed 47 packages, and audited 137 packages in 7s

23 vulnerabilities (2 moderate, 18 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

### Expected Behavior

Running again npm install on a fresh-installed workspace should not change the dependency tree.

### Steps To Reproduce

The target package is Express.
The workspace module **onepackage** requires express ^3.0.0
The **root** package.json declares **overrides**" express with version ^4.0.0

1. clone the test repo at https://github.com/ivanvaccari/npm-workspace-issue-demo
2. run `npm install` at root directory
3. Check the root node_module directory. It includes express ^4.0.0.  No node_modules directory is present in **onepackage**
4. Run again `npm install` at root directory
5. A node_modules directory is created in **onepackage**. It includes express ^3.0.0. 
6. This configuration does not respect the definition of **overrides** because now **onepackage** use the outdated version of express

### Environment

- npm: 10.8.2
- Node.js: 18.20.4
- OS Name: Wikn 10
- npm config: default?
```ini
; "user" config from C:\Users\IvanVaccari\.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = C:\Program Files\nodejs\node.exe   
; node version = v18.20.4
; npm local prefix = C:\Users\IvanVaccari\Desktop\test-ws
; npm version = 10.8.2
; cwd = C:\Users\IvanVaccari\Desktop\test-ws
; HOME = C:\Users\IvanVaccari
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by owlstronaut**
Fixes: https://github.com/npm/cli/issues/7660 https://github.com/npm/cli/issues/5443

Currently overrides are applied correctly to workspaces when a user does their initial `npm install`. However, when a user runs `npm install` again, the overrides are not being respected, and versions that the user has specifically overridden because of vulnerabilities or other reasons, are being installed in the node_modules of those workspaces. This ensures that when a package-lock.json is loaded, the overrides are calculated and applied to the workspaces.

### CODE REVIEW

File: workspaces/arborist/lib/arborist/build-ideal-tree.js [hunk 1]
```diff
@@ -279,14 +280,23 @@ module.exports = cls => class IdealTreeBuilder extends cls {
...
+            path: this.path,
+            lockfileVersion: this.options.lockfileVersion,
+            resolveOptions: this.options,
+          }).then(meta => Object.assign(root, { meta }))
+        } else {
+          return this.loadVirtual({ root })
+            .then(tree => {
+              this.#applyRootOverridesToWorkspaces(tree)
+              return tree
+            })
```
Comment (owlstronaut) [inline workspaces/arborist/lib/arborist/build-ideal-tree.js:297]: this is the only new functionality in this block, I just hate chained ternary operators, so did a minimal refactor.

File: workspaces/arborist/lib/arborist/build-ideal-tree.js [hunk 2]
```diff
@@ -1475,6 +1485,32 @@ This is a one-time fix-up, please be patient...
...
+        // safely skip if either edge or rootNode doesn't exist yet
+        if (!edge || !rootNode) {
+          continue
+        }
+
+        const resolvedRootVersion = rootNode.package.version
+        if (!semver.satisfies(resolvedRootVersion, edge.spec)) {
+          edge.detach()
+          node.children.delete(depName)
+        }
```
Comment (fritzy) [inline workspaces/arborist/lib/arborist/build-ideal-tree.js:1509]: If we remove the edge/children from the tree if it's not satisfied by an override, then we're assuming that the package is elsewhere in the tree already. I can imagine a case where that isn't true.

```
- package.json
  - override package-x@^1.0.0
  - dependences { doesn't include package-x }
- workspace/
  - package.json
    - dependencies {does include package-x@^2.0.0 }
```
In this case, the tree would not include the required dependency once this function removes it from the tree.

Is that possible?

Comment (owlstronaut) [reply workspaces/arborist/lib/arborist/build-ideal-tree.js:1509]: @fritzy Yep, that is a possible setup, but the guard against rootNode will skip removing in that case (undefined rootNode).

```javascript
const rootNode = tree.root.children.get(depName)

// safely skip if either edge or rootNode doesn't exist yet
if (!edge || !rootNode) {
      continue
}
```

The issue is on subsequent installs where the root overrides aren't being reapplied like they are on the initial install - so if it wasn't a root dependency, the virtual tree that is loaded will be correct already. The issue is overrides weren't being reapplied when loading the virtual tree, so the workspaces were then installing their dependencies when those edges needed to be removed.

**Review by fritzy — APPROVED** [review]
