### PR TITLE
fix(arborist): resolve sibling override sets via common ancestor

### LINKED ISSUE #9109: [BUG] Overrides with shared transitive deps cause silent exit 1
Found while testing overrides in [WordPress/gutenberg](https://github.com/WordPress/gutenberg/pull/75814). We're switching to `strict-peer-deps` after adopting linked strategy and wanted to test react/react-dom overrides ahead of time. `npm install` just exits with code 1 and no error message.

## Is there an existing issue for this?

- [x] I have searched the existing issues

## This issue exists in the latest npm version

- [x] I am using the latest npm

## Current Behavior

Adding two or more packages to `overrides` that share a transitive dep (e.g. `react` + `react-dom` both pull in `loose-envify`) causes `npm install` to silently exit 1 in large monorepos. No error, no ERESOLVE, nothing — just exit code 1 and a log file pointer.

## Expected Behavior

Install should succeed, or show a clear error message.

## Steps To Reproduce

```bash
mkdir -p repro/packages/{app,editor}
cd repro

cat > package.json << 'EOF'
{
  "name": "override-repro",
  "private": true,
  "workspaces": ["packages/*"],
  "devDependencies": {
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "overrides": {
    "react": "$react",
    "react-dom": "$react-dom"
  }
}
EOF

for pkg in app editor; do
cat > "packages/$pkg/package.json" << PKGEOF
{
  "name": "@repro/$pkg",
  "private": true,
  "dependencies": { "react": "18.3.1", "react-dom": "18.3.1" }
}
PKGEOF
done

echo 'install-strategy=linked' > .npmrc

npm install --loglevel=silly 2>&1 | grep -i conflicting
# silly Conflicting override sets <OverrideSet react> <OverrideSet react-dom>
# silly Conflicting override sets loose-envify
```

In this minimal repro the install finishes (exit 0) because the tree is small. In Gutenberg (hundreds of workspaces), the broken state cascades into an ERESOLVE during `buildDeps`, and then the error formatting crashes — so you get a silent exit 1.

## Root Cause

Two bugs combine:

### 1. Sibling override sets treated as conflicting

`findSpecificOverrideSet` in `override-set.js` walks parent chains to see if one override set contains the other. Sibling sets (e.g. the `react` and `react-dom` children of the root override set) are never ancestors of each other, so it returns `undefined`. This leaves shared deps like `loose-envify` with an inconsistent override state. The existing `haveConflictingRules` check (which handles this correctly) is not used in this path.

### 2. ERESOLVE report crashes with `depth=Infinity`

`explain-eresolve.js` generates the full report file with `depth=Infinity`. In large monorepos (especially linked strategy), this recurses through the entire dep graph and eventually hits `RangeError: Invalid string length`. That error is thrown inside the error formatter, which swallows the original ERESOLVE — so you get exit 1 with no message at all.

## Workaround

`legacy-peer-deps = true` in `.npmrc`.

## Environment

- npm: 11.11.1
- Node.js: 22.20.0
- OS Name: macOS
- npm config: `install-strategy=linked`, `strict-peer-deps=true`

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Two bugs combine to cause `npm install` to silently exit 1 in large monorepos when multiple packages are listed in `overrides` and share a transitive dependency.

**Bug 1 — Sibling override sets treated as conflicting:** `findSpecificOverrideSet` walks parent chains to determine if one override set contains the other. Sibling sets (e.g. the `react` and `react-dom` children of the root override set) are never ancestors of each other, so it returned `undefined`. This left shared transitive deps like `loose-envify` with an inconsistent override state, eventually causing an ERESOLVE during `buildDeps`. Fixed by checking `haveConflictingRules` (which already existed but was not used in this path) and falling back to the nearest common ancestor when the rules are compatible.

**Bug 2 — ERESOLVE report crashes with infinite depth:** `explain-eresolve.js` generates the full report file with `depth=Infinity`. In large trees (especially linked strategy), cycles in the dependency graph (e.g. store nodes referencing each other) cause `explainFrom` to recurse infinitely, hitting `RangeError: Invalid string length`. That error is thrown inside the error formatter, which swallows the original ERESOLVE — so you get exit 1 with no message. Fixed by adding cycle detection in `explain-dep.js` using stack-based `seen` tracking (add on enter, delete on leave) so diamond dependencies still work but cycles are broken. ~~Also capped report depth to 16.~~ (reverted — `depth=Infinity` is intentional for the full report file)

Found while testing overrides in [WordPress/gutenberg#75814](https://github.com/WordPress/gutenberg/pull/75814).

## References

Fixes #9109

### CODE REVIEW

File: lib/utils/explain-eresolve.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ const report = (expl, chalk, noColorChalk) => {
 
   return {
     explanation: `${explain(expl, chalk, 4)}\n\n${fix}`,
-    file: `# npm resolution error report\n\n${explain(expl, noColorChalk, Infinity)}\n\n${fix}`,
```
Comment (wraithgar) [inline lib/utils/explain-eresolve.js:57]: This is done on purpose so that the eresolve-report.txt has the full json output.  See the comment on line 6.

Comment (manzoorwanijk) [reply lib/utils/explain-eresolve.js:57]: You're right, reverted that change. The `depth=Infinity` is preserved.

The underlying issue was that in large linked-strategy trees, cycles in the dependency graph (e.g. store nodes referencing each other) caused `explainFrom` to recurse infinitely, eventually hitting `RangeError: Invalid string length`.

The fix is now in `explain-dep.js` instead - added stack-based cycle detection in `explainFrom` so it breaks out of recursive cycles while still fully expanding diamond dependencies (same node reached via different paths). This way, the full report is still generated as intended, just without infinite recursion.

**Review by wraithgar — APPROVED** [review]
