### PR TITLE
fix: ensure progress bars display consistently across all environments

### LINKED ISSUE #996: [BUG] progress config defaults based on CI but flatOptions based on tty
This is inconsistent and might mean weird output in TTY environments that are not CI (i.e. as codespaces)

### PR DESCRIPTION
**Pull request by owlstronaut**
The progress configuration's default value and runtime behavior now use
identical logic, preventing cases where progress bars were unexpectedly
disabled in cloud IDEs and other environments.

Fixes npm/statusboard#996

### CODE REVIEW

File: workspaces/config/lib/definitions/definitions.js [hunk 1]
```diff
@@ -1571,9 +1571,9 @@ const definitions = {
     },
   }),
   progress: new Definition('progress', {
-    default: !ciInfo.isCI,
+    default: !!process.stderr.isTTY && !!process.stdout.isTTY && process.env.TERM !== 'dumb',
```
Comment (wraithgar) [inline workspaces/config/lib/definitions/definitions.js]: This seems like a pretty significant change in logic.

I think detecting CI is still important, decoupled from the tty check.  If we're in CI we should default to false even if a tty is detected.

Comment (owlstronaut) [reply workspaces/config/lib/definitions/definitions.js]: Restored that bit and added some compatibility tests

Comment (alexsch01) [reply workspaces/config/lib/definitions/definitions.js]: @owlstronaut I don't see the updated code

Comment (owlstronaut) [reply workspaces/config/lib/definitions/definitions.js]: @alexsch01 we do a lot of rebase-and-force around here. `!ciInfo.isCI &&` should make sure it's not in CI to further evaluation. Let me know if I have a pre-coffee haze about the logic as it is

Comment (alexsch01) [reply workspaces/config/lib/definitions/definitions.js]: @owlstronaut i see this

image

Comment (wraithgar) [reply workspaces/config/lib/definitions/definitions.js]: We may need to move this into a code block.  If we are in CI, display should be false and we should move on.  That initial `&&` is wrong.

**Comment by wraithgar** [comment]
Ok after a deep dive with boolean tables and everything the logic should be: `!(ci || !tty || dumb)`

This will properly short circuit if we are in CI, or if we're not a TTY, and set display appropriately for all 3 conditions.

**Comment by owlstronaut** [comment]
> Ok after a deep dive with boolean tables and everything the logic should be: `!(ci || !tty || dumb)`
> 
> This will properly short circuit if we are in CI, or if we're not a TTY, and set display appropriately for all 3 conditions.

Just pushed for that. So same thing but with shortcut advantage 😄 I'm still not completely convinced it is actually different, lol

**Review by wraithgar — APPROVED** [review]
