### PR TITLE
fix(libnpmexec): workspaces support

### LINKED ISSUE #3520: [BUG] npx/npm exec don't work in child workspace when using --no/--no-install and --package
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using NPM workspaces. I am running a command of the format:

```
npm exec --no --workspace=my-workspace --package @graphql-codegen/cli -- graphql-codegen --config codegen.js
```

It fails with a rather terse `npm ERR! canceled`.

This is related to a previous issue #2826. The bug was partially resolved by @ruyadorno in https://github.com/npm/libnpmexec/pull/2. However, looking at the commit, it seems that the fix was only applied inside the `if (needPackageCommandSwap)` block. This only executes if no `--package` option has been specified.

If `--package` is specified, then the code falls through to https://github.com/npm/libnpmexec/blob/a9423e441b914571ec18ad8a4496a3ecf2f500e2/lib/index.js#L153. It will then try to install the package (even though it's already available locally). However, if `--no[-install]` is specified, it will simply throw an exception instead.

### Expected Behavior

The `npm exec` and `npx` commands should work when used in a workspace with the `--package` and `--no[-install]` options.

### Steps To Reproduce

_No response_

### Environment

- OS: Windows
- Node: 16.4.0
- npm: 7.19.1

### PR DESCRIPTION
**Pull request by ruyadorno**
Fixes the proper path location to use when targetting specific workspaces.

## References
Fixes: https://github.com/npm/cli/issues/3520
Relates to: https://github.com/npm/statusboard/issues/403

### CODE REVIEW

File: workspaces/libnpmexec/lib/index.js [hunk 1]
```diff
@@ -86,20 +85,47 @@ const exec = async (opts) => {
...
+  const localTree = await localArb.loadActual()
+
+  const getLocalManifest = ({ tree, name }) => {
+    // look up the package name in the current tree inventory,
+    // if it's found then return that normalized pkg data
+    let node
+    const nodes = tree.inventory.query('packageName', name)
+    for (const n of nodes) {
+      node = n
+      break
```
Comment (nlf) [inline workspaces/libnpmexec/lib/index.js]: this is because the above `tree.inventory.query()` returns a `Set` and we want the first item? if so, might be worth a comment because otherwise this pattern feels weird at a glance.

i've done `nodes.values().next().value` in the past, but i don't think that's really any more readable lol

File: workspaces/libnpmexec/lib/index.js [hunk 2]
```diff
@@ -86,20 +85,47 @@ const exec = async (opts) => {
...
+    }
+
+    if (node) {
```
Comment (nlf) [inline workspaces/libnpmexec/lib/index.js]: instead of checking this after the fact, maybe a check on `nodes.size` before you even read a node from it is more clear?

File: workspaces/libnpmexec/lib/index.js [hunk 3]
```diff
@@ -86,20 +85,47 @@ const exec = async (opts) => {
...
-      try {
-        const pj = resolve(path, 'node_modules', spec.name, 'package.json')
-        return await readPackageJson(pj)
-      } catch (er) {}
+      const localManifest = getLocalManifest({
+        tree: localTree,
+        name: spec.name,
+      })
+      if (localManifest) {
+        return localManifest
```
Comment (nlf) [inline workspaces/libnpmexec/lib/index.js]: `getLocalManifest()` will return `undefined` if no manifest is found, right? so why not skip the condition and always return `localManifest` here since it's the same effect either way?

File: workspaces/libnpmexec/lib/index.js [hunk 4]
```diff
@@ -114,16 +140,9 @@ const exec = async (opts) => {
...
-    ...flatOptions,
-    path,
-  })
-  const localTree = await localArb.loadActual()
-
-  // do we have all the packages in manifest list?
+  // are all packages from the manifest list installed?
   const needInstall =
-    manis.some(manifest => manifestMissing({ tree: localTree, manifest }))
+    manis.some(manifest => !manifest[_localManifest])
```
Comment (nlf) [inline workspaces/libnpmexec/lib/index.js]: isn't `manifest` potentially `undefined` here? won't that cause the prop check to explode?

File: workspaces/libnpmexec/lib/index.js [hunk 5]
```diff
@@ -135,16 +154,23 @@ const exec = async (opts) => {
...
     // by npm exec in the cache install directory
-    const add = manis.filter(mani => manifestMissing({
-      tree,
-      manifest: {
-        ...mani,
-        _from: `${mani.name}@${mani.version}`,
-      },
-    }))
+    const add = manis
+      .filter(mani => !mani[_localManifest])
```
Comment (nlf) [inline workspaces/libnpmexec/lib/index.js]: same `undefined` concern here

File: workspaces/libnpmexec/lib/index.js (hunk 1 above)
Comment (nlf) [reply workspaces/libnpmexec/lib/index.js]: if you do the `nodes.size` check first, then you can do `const [node] = nodes` and _that_ feels better

Comment (nlf) [reply workspaces/libnpmexec/lib/index.js]: actually.. you can skip the size check entirely now that i think about it.

```
const [node] = tree.inventory.query()
return node
```

is plenty

Comment (ruyadorno) [reply workspaces/libnpmexec/lib/index.js]: omg that's awesome 😍 thanks @nlf

File: workspaces/libnpmexec/lib/index.js (hunk 2 above)
Comment (ruyadorno) [reply workspaces/libnpmexec/lib/index.js]: I'll stick with the deconstruction proposed in the previous comment and keep this check here 😊

File: workspaces/libnpmexec/lib/index.js (hunk 3 above)
Comment (ruyadorno) [reply workspaces/libnpmexec/lib/index.js]: ~oops, I believe this is just a leftover from previous of moving the logic to `getLocalManifest` 😬 good catch!~

no wait, actually I remember what was going on here, the check is there so that we can also fallback to `pacote.manifest` and retrieve that manifest from the registry in case it was not found in the local install... it actually works as expected but maybe there's a better syntax to describe that

**Comment by ruyadorno** [comment]
@nlf after jumping back at the code here I realized that I could get the original bugfix without explicit requiring that arborist-read-data-refactor 😊 I'm going to split these into two separate PRs so that they're more atomic, simpler to review and revert if needed be.

So here now is only the change required in `lib/commands/exec.js` in order to properly use `localPrefix` as the place to load **arborist** when running in the context of workspaces.

**Review by nlf — APPROVED** [review]

**Review by nlf — APPROVED** [review]
fix looks good, and these tests are great!
