### PR TITLE
fix: `npm ls` now respects `--include-workspace-root`

### LINKED ISSUE #3945: [BUG] npm ls does not include root
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running the `npm ls` command within the [`--include-workspace-root`](https://docs.npmjs.com/cli/v7/commands/npm-ls#include-workspace-root) does not change the output.

The outputs:

 Correct
```
npm ls

npm-ls@1.0.0 /Users/mspigolon/workspace/_experiments/npm-workspaces/npm-ls
├── avvio@8.0.0
└─┬ pkg-a@1.0.0 -> ./pkg-a
  └── fastify@3.22.1
```

Correct
```
npm ls -w pkg-a

npm-ls@1.0.0 /Users/mspigolon/workspace/_experiments/npm-workspaces/npm-ls
└─┬ pkg-a@1.0.0 -> ./pkg-a
  └── fastify@3.22.1
```

Incorrect
```
npm ls -w pkg-a --include-workspace-root

npm-ls@1.0.0 /Users/mspigolon/workspace/_experiments/npm-workspaces/npm-ls
└─┬ pkg-a@1.0.0 -> ./pkg-a
  └── fastify@3.22.1
```

### Expected Behavior

`npm ls -w pkg-a --include-workspace-root` should list the root package.json dependancies

### Steps To Reproduce

```
mkdir npm-ls
cd npm-ls
npm init --yes
npm init -w pkg-a --yes
npm install avvio
npm install fastify -w pkg-a
```

### Environment

- OS: mac 11.6
- Node: node 16.11.1
- npm: 8.1.1

### PR DESCRIPTION
**Pull request by fritzy**
`npm ls` with a workspace specified used to ignore `--include-workspace-root`, but now includes the root when set.

Closes #3945

### CODE REVIEW

File: lib/commands/ls.js [hunk 1]
```diff
@@ -96,9 +96,11 @@ class LS extends ArboristWorkspaceCmd {
       }
 
       if (edge.from.isProjectRoot) {
-        return edge.to &&
-          edge.to.isWorkspace &&
-          wsNodes.includes(edge.to.target)
+        return (edge.to
```
Comment (wraithgar) [inline lib/commands/ls.js:104]: This is getting a little unweildy, maybe a comment is in order, or two if statements?

Comment (fritzy) [reply lib/commands/ls.js:104]: done

**Review by wraithgar — APPROVED** [review]

File: lib/commands/ls.js (hunk 1 above)
Comment (khaled200286) [reply lib/commands/ls.js:104]: Yes
