### PR TITLE
fix(arborist): do not hoist undeclared workspaces in linked strategy

### LINKED ISSUE #9072: [BUG] Linked install strategy hoists all workspace packages to root `node_modules`
## Is there an existing issue for this?

- [x] I have searched the existing issues
- [x] I am using the latest npm

## Current Behavior

With `install-strategy=linked`, all workspace packages are unconditionally symlinked into the root `node_modules/`, regardless of whether the root or any other workspace declares them as a dependency. This makes every workspace resolvable from anywhere in the monorepo, defeating the strict isolation that the linked strategy is supposed to provide.

Related: #6537 (same problem with `--install-strategy=nested` — workspace symlinks are hoisted to root instead of being placed in dependent packages' `node_modules`). This issue reports the same behavior with `--install-strategy=linked`.

## Expected Behavior

Workspace packages should only appear in the `node_modules/` of packages that declare them as dependencies. If `@scope/a` depends on `@scope/b`, the symlink should be at:

```
packages/a/node_modules/@scope/b -> packages/b
```

Not at:

```
node_modules/@scope/b -> packages/b
```

## Steps To Reproduce

1. Create a workspace monorepo:

   ```bash
   mkdir repro && cd repro
   mkdir -p packages/a packages/b
   ```

2. With this config:

   `package.json`:

   ```json
   {
     "name": "repro",
     "workspaces": ["packages/*"]
   }
   ```

   `packages/a/package.json`:

   ```json
   {
     "name": "@scope/a",
     "version": "1.0.0",
     "dependencies": {
       "@scope/b": "*"
     }
   }
   ```

   `packages/b/package.json`:

   ```json
   {
     "name": "@scope/b",
     "version": "1.0.0"
   }
   ```

   `.npmrc`:

   ```ini
   install-strategy=linked
   ```

3. Run `npm install`
4. See that both `@scope/a` and `@scope/b` are symlinked at root:

   ```
   node_modules/@scope/a -> ../../packages/a
   node_modules/@scope/b -> ../../packages/b
   ```

   Neither package should appear at root since the root `package.json` does not depend on them.

## Environment

- npm: v10.9.5 and v11 (latest) -- both affected
- Node.js: v22.20.0
- OS Name: macOS (Darwin)
- npm config:
  ```ini
  install-strategy=linked
  ```

### PR DESCRIPTION
**Pull request by manzoorwanijk**
In continuation of our exploration of using `install-strategy=linked` in the [Gutenberg monorepo](https://github.com/WordPress/gutenberg/pull/75814), which powers the WordPress Block Editor.

## Summary

With `install-strategy=linked`, all workspace packages are unconditionally symlinked into the root `node_modules/`, regardless of whether the root declares them as dependencies. This defeats the strict isolation that the linked strategy is supposed to provide — any workspace can import any other workspace without declaring it as a dependency.

The root cause is two-fold:

1. `assignCommonProperties()` includes all workspaces in root's `localDependencies` because npm auto-creates `type: 'workspace'` edges from root to every workspace
2. `createIsolatedTree()` unconditionally creates a workspace Link entry in `root.children` at `node_modules/<wsName>` for every workspace

The fix:

1. Filters undeclared workspace deps in `#assignCommonProperties()` so they don't enter root's `localDependencies`
2. Only creates root-level workspace symlinks (`node_modules/<wsName>`) for declared dependencies

### Before (broken)

```
node_modules/@scope/a -> packages/a    # root doesn't depend on @scope/a
node_modules/@scope/b -> packages/b    # root doesn't depend on @scope/b
```

### After (fixed)

```
packages/a/node_modules/@scope/b -> packages/b   # @scope/a depends on @scope/b
```

No symlinks at root `node_modules/` since root doesn't depend on either workspace.

## References

Fixes #9072
Related to #6537 (same problem with `--install-strategy=nested`)

### CODE REVIEW

File: workspaces/arborist/lib/arborist/isolated-reifier.js [hunk 1]
```diff
@@ -189,7 +189,18 @@ module.exports = cls => class IsolatedReifier extends cls {
       edge.to?.target &&
       !(node.package.bundledDependencies || node.package.bundleDependencies)?.includes(edge.to.name)
     )
-    const nonOptionalDeps = edges.filter(edge => !edge.optional).map(edge => edge.to.target)
+    let nonOptionalDeps = edges.filter(edge => !edge.optional).map(edge => edge.to.target)
+
+    // npm auto-creates 'workspace' edges from root to all workspaces.
+    // For isolated/linked mode, only include workspaces that root explicitly declares as dependencies.
+    if (node.isProjectRoot) {
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/isolated-reifier.js:206]: Is this the real node?  Why do this all over again when we already calculated this for idealGraph.package?  We can attach rootDeclaredDeps to this.idealGraph and use it agan here perhaps?

Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js:206]: Good call.

Let us move the computation to `makeIdealGraph` and store it as a private field (`#rootDeclaredDeps`) so it's calculated once and reused in both `#assignCommonProperties` and `createIsolatedTree`.

Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js:206]: Done in https://github.com/npm/cli/pull/9076/commits/c44c44dbfec96f137e8a0b52b9bf998aac1e37e2

Comment (wraithgar) [reply workspaces/arborist/lib/arborist/isolated-reifier.js:206]: private field works too!  That looks much cleaner now.

File: workspaces/arborist/lib/arborist/isolated-reifier.js [hunk 2]
```diff
@@ -73,6 +74,15 @@ module.exports = cls => class IsolatedReifier extends cls {
...
     const omit = new Set(this.options.omit)
 
+    // npm auto-creates 'workspace' edges from root to all workspaces.
+    // For isolated/linked mode, only include workspaces that root explicitly declares as dependencies.
+    const rootPkg = idealTree.package
+    this.#rootDeclaredDeps = new Set([
+      ...Object.keys(rootPkg.dependencies || {}),
+      ...Object.keys(rootPkg.devDependencies || {}),
+      ...Object.keys(rootPkg.optionalDependencies || {}),
+    ])
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/isolated-reifier.js:84]:
```suggestion
     this.#rootDeclaredDeps.add(...Object.keys(rootPkg.dependencies || {}))
    this.#rootDeclaredDeps.add(...Object.keys(rootPkg.devDependencies) || {})
    this.#rootDeclaredDeps.add(...Object.keys(rootPkg.optionalDeependencies) || {})
    }
```

Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js:84]: That suggestion apparently has a syntax error. I will apply it manually. Thanks

File: workspaces/arborist/lib/arborist/isolated-reifier.js [hunk 3]
```diff
@@ -289,22 +305,41 @@ module.exports = cls => class IsolatedReifier extends cls {
...
       root.fsChildren.add(workspace)
       root.inventory.set(workspace.location, workspace)
+      root.workspaces.set(wsName, workspace.path)
 
-      // Create workspace Link entry in children for _diffTrees lookup
+      // Create a workspace Link entry for the reifier's diff machinery (createSparseTree, script execution) and for workspace-filtered installs which look up idealTree.children.get(wsName) (reify.js:430).
+      // This link points to the workspace's own location, NOT root node_modules/, so undeclared workspaces are not hoisted.
       const wsLink = new IsolatedLink({
-        location: join('node_modules', wsName),
+        location: join(c.localLocation, 'node_modules', wsName),
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/isolated-reifier.js]: Do we need to create two isolated links to workspaces?  Would it be enough to omit the localLocation if it is a root declared dep?

File: workspaces/arborist/lib/arborist/isolated-reifier.js (hunk 2 above)
Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js:84]: Also, [`Set.add` accepts only one value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/add). So, we will need a loop here. So, I think the current implementation is cleaner.

Comment (wraithgar) [reply workspaces/arborist/lib/arborist/isolated-reifier.js:84]: You're right. I thought Set.add could accept a spread operator.

Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js:84]: If the intent is just to not reassign `this.#rootDeclaredDeps`, we can keep the initial new Set() declaration and populate it here inside loops using `.add()`

File: workspaces/arborist/lib/arborist/isolated-reifier.js (hunk 3 above)
Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js]: Good point.

Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js]: Simplified to create a single link per workspace, root-level (`node_modules/<ws>`) for declared deps, self-link (`packages/<ws>/node_modules/<ws>`) for undeclared. No need for both.

See https://github.com/npm/cli/pull/9076/commits/7218ba31405a80ad43f221c1cf499af31170265b

**Review by wraithgar — APPROVED** [review]
