### PR TITLE
fix: properly handle newlines with input when using the spinner

### LINKED ISSUE #7425: [BUG] npm 10.6.0 doesn't log anything while npm install
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The latest npm 10.6.0 doesn't log anything while installing the packages with `npm install`. It only prints the final results. So npm is working for almost 50 seconds without notifying the user whether it is doing anything at all. The behavior is similar to `npm install --loglevel silent` of the previous version 10.5.2.

### Expected Behavior

The logging should be displayed, showing the user that the installation is proceeding. It shouldn't be silenced completely.

### Steps To Reproduce

1. Environment: Command Prompt, npm 10.6.0, node 18.20.2
2. `npm install` with an existing package.json in the root directory
3. no loggin observed while installing the packages to node_modules

### Environment

- npm: 10.6.0
- Node.js: 18.20.2
- OS Name: Windows
- System Model Name: Desktop PC
```ini
; copy and paste output from `npm config ls` here
```

### LINKED ISSUE #7583: [BUG] npm shows spinner while waiting for password
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Since version 10.7, when the "spinner" was introduced (I dislike it for various reasons, ugly flickering a.s.o., but wont discuss it here further since it's not related), the password prompt of `npm login` is misleading.
Instead of waiting behind "Password:" it shows the spinner, indicating some "progress" that does not happen. Instead it's actually waiting for the password which has to be typed or inserted while according to the spinner npm seems busy.
It appears as if the password prompt is skipped.

### Expected Behavior

Clearly indicate that npm is waiting for the password to be entered.

### Steps To Reproduce

Simply execute `npm login`, type some username. Enjoy :-/

### Environment

- npm: 10.8.1
- Node.js: 20.14.0

### PR DESCRIPTION
**Pull request by mbtools**
TL;DR

I fixed the spinner, yay! If you like it, [buy me a ☕ or 🍕 ](https://github.com/sponsors/mbtools). 

### Background

In 10.7.0, a [spinner](https://github.com/npm/cli/pull/7432) was introduced to the npm cli, a small progress indicator showing that npm is still busy and not dead.

I'm *not* a JavaScript developer, but I love a good challenge: Debugging and finding a fix for annoying bugs that no one had time to or wanted to fix is as good as sx (well, almost). 

### Problem

With the spinner came a regression that disrupted the user experience when npm asked for input during login or adding a user: The spinner would show up after the second prompt and drive users nuts.

For example, the username prompt for `npm adduser` would be ok but subsequent prompts for password and email showed the spinner although users were asked to enter something. Very confusing.

Cursor_2354

### Root Cause

The was a race condition between turning off the spinner and showing a new prompt.

I tried setting timers, waiting for the next tick, and a flag indicating if there's an active prompt. None worked.

### Solution

This PR improves the cli prompt experience by ensuring the progress spinner does not appear between consecutive user prompts (such as username and password).

- Fixes race condition in input handler
- Avoids spinner interfering with input prompts
- Properly adds newlines with silent prompts or when input is cancelled by user

### Demo

Here's a demo of what it looks after this PR 😃 (uses [Verdaccio](https://verdaccio.org/) in case you wonder)

Cursor_2345

### References

Ref https://github.com/npm/cli/pull/7432
Closes https://github.com/npm/cli/issues/7425
Closes https://github.com/npm/cli/issues/7583

Enjoy, [Marc](https://github.com/sponsors/mbtools)

### CODE REVIEW

File: lib/utils/display.js [hunk 1]
```diff
@@ -357,10 +362,7 @@ class Display {
         const [res, rej, p] = args
         return input.start(() => p()
           .then(res)
-          .catch(rej)
-          // Any call to procLog.input.read will render a prompt to the user, so we always
-          // add a single newline of output to stdout to move the cursor to the next line
-          .finally(() => output.standard('')))
```
Comment (wraithgar) [inline lib/utils/display.js:346]: We still need this for all other input prompts, including the initial password prompt.

Comment (mbtools) [reply lib/utils/display.js:346]: do we? for example, with `npm init`, when I hit `enter`, it jumps to a newline (win, powershell).

File: lib/utils/read-user-info.js [hunk 2]
```diff
@@ -24,6 +24,9 @@ function readOTP (msg = otpPrompt, otp, isRetry) {
 
 function readPassword (msg = passwordPrompt, password, isRetry) {
   if (isRetry && password) {
+    // because the prompt is silent and we need to move the cursor
+    // to the next line so the next output is on a new line.
+    process.stdout.write('\n')
```
Comment (wraithgar) [inline lib/utils/read-user-info.js]: We never write to stdout directly in npm.  All input and output goes through their respective functions in `proc-log` which are event-driven and intercepted by npm in its display layer.

There already was an effective newline in `lib/utils/display.js` that was covering this use case whenever we intercepted an "input" event from proc-log.  This is needed because the newline that a user enters is not acted on in and of itself, it's consumed by readline as part of the end of input.  If that isn't working I don't understand how this will.  You can also see in snapshots where that newline is now missing from all other input prompts.


```
const read = (...args) => input.read(() => _read(...args))
```

`input.read` is what emits `input.KEYS.read` and is then intercepted by npm, writing that newline via `output.standard('')`.


I think you may have been on the right track with the counter for active inputs.  I don't understand right now how we could have two active inputs, it may be a race condition.  However ALL of the functionality in there (not just the progress spinner) would need to be in the consideration for pausing until all input prompts are finished.

Comment (mbtools) [reply lib/utils/read-user-info.js]: for me (win), only the silent password prompt consumes the newline at end of input (which is common for making sure the password won't be visible). the other prompts, work well without any of this. i understand that process.stdout isn't proper but didn't know how to do it otherwise (just for the pwd prompt). maybe there's some platform difference here?

i didn't see how two prompts could be active but the counter says otherwise ;-).

File: lib/utils/auth.js [hunk 3]
```diff
@@ -51,7 +51,7 @@ const adduser = async (npm, { creds, ...opts }) => {
   if (!res) {
     const username = await read.username('Username:', creds.username)
     const password = await read.password('Password:', creds.password)
-    const email = await read.email('Email: (this IS public) ', creds.email)
+    const email = await read.email('Email (this will be public):', creds.email)
```
Comment (wraithgar) [inline lib/utils/auth.js]: this is an unrelated `docs:` change that we don't want to hide in this PR under the `fix:`

File: lib/utils/read-user-info.js (hunk 2 above)
Comment (mbtools) [reply lib/utils/read-user-info.js]: i tested with cmd, pwsh, and bash and it works well as is. each input is on it's own line. I don't get the point of the additional newline.

Comment (wraithgar) [reply lib/utils/read-user-info.js]: This is a place where we are definitely going to have to lean on the "Chesterton's Fence" principle here and not remove something unless we can explain why it's there.  This would require testing in linux, osx and windows in multiple versions of each, and likely a deeper dive into the history of this code to see if it's not a legacy from a previous input method.

Please keep that output line in the display layer.


Going back to the process.stdout itself, that is going to have to be an emitted newline.  It should also be something we can see if we can work into the display layer itself.  This is not the only place where we will potentially be inputting silently, and if we did that in the future we would almost certainly forget to add this new line.  Perhaps we can add a flag on the input meta to let the display layer know it was a silent input?

Comment (mbtools) [reply lib/utils/read-user-info.js]: The `finally` was added as part of https://github.com/npm/cli/pull/7432 which introduced the spinner. I think there's a good chance that it was put into the `inputHandler` because of the side-effect that the spinner shows up on the second and subsequent prompts. Now that this PR makes sure that the spinner no longer gets in the way, the `finally` is not necessary in general but only for silent prompts. maybe @lukekarrys remembers?

I will work on moving the newline for silent prompts to the display layer.

Comment (wraithgar) [reply lib/utils/read-user-info.js]: Thanks for doing that history search.

Comment (lukekarrys) [reply lib/utils/read-user-info.js]: iirc, the newline was written to move the cursor so no output would be overwritten if the user does a `ctrl+c` during one of the prompts.

Here's an example from `npm@11.4.1` and this PR where I `ctrl+c` during the `Username` prompt:

```
╰❯ npm adduser --auth-type=legacy
npm notice Log in on https://registry.npmjs.org/
Username:
npm error canceled
npm error A complete log of this run can be found in: /Users/lukekarrys/.cache/npm/_logs/2025-05-27T22_52_17_565Z-debug-0.log
```

```
╰❯ node . adduser --auth-type=legacy
npm notice Log in on https://registry.npmjs.org/
npm error canceled
npm error A complete log of this run can be found in: /Users/lukekarrys/.cache/npm/_logs/2025-05-27T22_52_23_380Z-debug-0.log
```

You can see in the second example from this PR that the `Username:` line get overwritten by the first line of the error. I believe this might be the only reason for the `.finally()` block. A small thing in comparison to the usability of multi-prompt commands I think, but maybe this context is helpful in deciding if it should stay or go.

Comment (wraithgar) [reply lib/utils/read-user-info.js]: THANK YOU. We need to add the ctrl-c consideration to the comments so we know why it's there.  I think it needs to stay.

The newline on password prompts can be a separate concern still and `mbtools` is working on move that into the display layer.

**Comment by mbtools** [comment]
My AI friends and I spend a long time to figure this out, but we found a solution that is straight forward.

### Details

Here are the input events as they are processed currently, for example with `npm adduser`:

```
input.KEYS.read
input.KEYS.start
Username: me
input.KEYS.read.finally
input.KEYS.read
input.KEYS.start
Password: input.KEYS.end
input.KEYS.read 
input.KEYS.start
Email (this will be public): input.KEYS.read.finally
input.KEYS.end
me@me.com
input.KEYS.read.finally
input.KEYS.end
```

When `input.KEYS.read` is processed, it calls `input.start()` which immediately emits `input.KEYS.start`. However, the corresponding `input.KEYS.end` is only emitted when the promise returned by `input.start()` settles (due to the `.finally()` mechanism in `proc-log`  `input.start` function).

This creates a race condition where:

- The next prompt's `input.KEYS.read` and `input.KEYS.start` are emitted synchronously
- The previous prompt's `input.KEYS.end` is emitted asynchronously when the promise chain completes

This explains why we see the events out of order:

- `input.KEYS.read` (username)
- `input.KEYS.start` (username)
- `input.KEYS.read.finally` (username)
- `input.KEYS.read` (password) - next prompt starts
- `input.KEYS.start` (password) - next prompt starts
- `input.KEYS.end` (username) - previous prompt finally ends

The issue is that the `input.KEYS.end` event is tied to the promise resolution timing rather than being emitted immediately when the prompt completes, causing the overlapping event sequence.

### Solution

We switched to sequential input management because:

- *Minimal changes*: Only requires modifying the display handler
- *Clear event ordering*: Ensures start/end events are properly sequenced
- *Backward compatible*: Doesn't change the external API
- *Simple to understand*: The flow is straightforward and predictable

The key insight is to emit the `input.KEYS.end` event immediately when the input promise resolves, rather than relying on proc-log's finally callback mechanism. This ensures that each input operation completes fully before the next one begins. Therefore, the prompt counter is not required anymore.

Cancelled user prompts are now handled directly in `catch` making `finally` obsolete.

As suggested, we're now passing the `silent` prompt parameter to the `inputHandler`. This way we can output a newline for password prompts, so they are not overwritten by subsequent output. 

### Summary

- Fixes race condition in input handler
- Avoids spinner interfering with input prompts
- Properly adds newlines with silent prompts or when input is cancelled by user
- Added tests to cover various prompt cases

😃

File: lib/utils/display.js [hunk 4]
```diff
@@ -355,12 +361,29 @@ class Display {
...
-        return input.start(() => p()
-          .then(res)
-          .catch(rej)
-          // Any call to procLog.input.read will render a prompt to the user, so we always
-          // add a single newline of output to stdout to move the cursor to the next line
-          .finally(() => output.standard('')))
+
+        // Silent inputs like password prompts require special handling
+        // to preserve output when users hit enter (see input.KEYS.end).
+        this.#silentPrompt = meta[META]?.silentPrompt || false
```
Comment (wraithgar) [inline lib/utils/display.js]: This makes me nervous.  The display class is global, and state should be for the entire npm process, not for a single event.  It will likely mean we need to pass this along as we are calling the input events.


It seems here we have a more subtle issue in that `proc-log` itself isn't aware of `META` in the input start/end lifecycle.    It's an oversight and one we likely need to fix there instead.  Then our input handler in the display layer can rely on having the `META` passed into it as originally requested.

TLDR: the real problem here is that we need to ensure that `META` is maintained and passed along through the entire input lifecycle so that `input.KEYS.end` has access to it as originally requested.

Comment (mbtools) [reply lib/utils/display.js]: I removed the META logic. The input options are now passed from read to end event.

**Comment by mbtools** [comment]
It's now straightforward and behave well in manual testing. Please give it a try

**Comment by wraithgar** [comment]
Howdy @mbtools just wanna say this is NOT being ignored.  We're focusing on the OIDC PR (and some other housekeeping items) before looking at this one and some other community PRs.

Thanks for your patience here.

**Comment by wraithgar** [comment]
> TLDR: the real problem here is that we need to ensure that META is maintained and passed along through the entire input lifecycle so that input.KEYS.end has access to it as originally requested.

I think this is still a root problem.  You have 100% "solved" the problem here which is always the hardest part.  This is going to require a PR to `proc-log` first, which we can then utilize here.  I'll start work on that now.

**Comment by Aeolun** [comment]
@wraithgar If you are not going to have time to solve this problem any time soon, maybe it would make sense to just merge this PR until you can get around to the proper solution? It's gotten to the point where my LLM tells me NPM displaying a spinner during the login password prompt is 'expected behavior'.

**Comment by edraft-123** [comment]
@wraithgar Since it's still a bug, will it ever be merged?

**Comment by wraithgar** [comment]
https://github.com/npm/cli/pull/8779 updates proc-log in npm to have the code this PR needs to move forward

**Comment by mbtools** [comment]
All events now go via `proc-log` 🎉. I improved the email prompt a bit, too (see #8780).

File: lib/utils/display.js [hunk 5]
```diff
@@ -330,20 +330,38 @@ class Display {
         this.#progress.off()
         break
 
-      case input.KEYS.end:
+      case input.KEYS.end: {
         log.resume()
+        // For silent prompts (like password), add newline to preserve output
+        const [options] = args
```
Comment (wraithgar) [inline lib/utils/display.js]: the `withMeta` code has parsed the args at this point and looked for the meta symbol to pull out meta args and put them into `meta`.  You can see how we use it in the write path.  

At this point in the code it means is you can just optimistically ask for things like `meta.silent`.

Comment (wraithgar) [reply lib/utils/display.js]: This will also mean adding META to the input events in read-user-info.js.

Examples of its use here in the cli can be found in `lib/utils/open-url.js`, `lib/commands/view.js` and `lib/commands/token.js`

Comment (mbtools) [reply lib/utils/display.js]: Now I see how META works 😃  Thanks!

Comment (wraithgar) [reply lib/utils/display.js]: It is NOT an intuitive thing, for sure.  Really glad this is getting near to completion!

**Comment by wraithgar** [comment]
This is looking really good now.  As a reminder we are approaching a very long weekend here in the U.S. so an actual review (and, one may hope, a merge) won't likely happen till next week.

**Comment by mbtools** [comment]
Enjoy a happy Thanksgiving🎉

**Review by wraithgar — APPROVED** [review]

**Comment by mbtools** [comment]
Thank you for merging 🙏 and expanding the description. 

The issue wasn't so much the newlines but the fact that the spinner kept going while prompting the user for input. Now it shows a normal blinking cursor as one would expect 😉

**Comment by wraithgar** [comment]
Ah, sorry I guess I missed the mark on the PR title a bit.  The changelog entry links here so those interested can dig way into things if they really want.
