### PR TITLE
fix: npm profile refactor

### LINKED ISSUE #164: v7(tests): profile

### PR DESCRIPTION
**Pull request by ruyadorno**
Refactor `npm profile` and added full test coverage, also fixed a couple of minor issues encountered, in summary:

- Fixes using `--otp` config option in `npm profile enable-2fa`
- Prevents trying to enable 2fa if no user is logged in
- Setting email should not require password
- Add `test/lib/profile.js` tests
- Async/await `lib/profile.js` refactor and more
- Fixes: https://github.com/npm/statusboard/issues/164

### CODE REVIEW

File: lib/profile.js [hunk 1]
```diff
@@ -41,35 +42,33 @@ profileCmd.completion = function (opts, cb) {
...
-      withCb(get(args.slice(1)), cb)
-      break
+      return get(opts)
     case 'set':
-      withCb(set(args.slice(1)), cb)
-      break
+      return set(opts)
     default:
-      cb(new Error('Unknown profile command: ' + args[0]))
+      throw new Error('Unknown profile command: ' + args[0])
```
Comment (ljharb) [inline lib/profile.js]:
```suggestion
      throw new Error('Unknown profile command: ' + subcmd)
```

File: lib/profile.js [hunk 2]
```diff
@@ -86,52 +85,63 @@ const knownProfileKeys = [
...
+  if (info.tfa && !info.tfa.pending)
+    cleaned[tfa] = info.tfa.mode
+  else
+    cleaned[tfa] = 'disabled'
+
+  if (args.length) {
+    const values = args // comma or space separated
+      .join(',')
+      .split(/,/)
+      .map((arg) => arg.trim())
```
Comment (ljharb) [inline lib/profile.js]: this map can be removed, and the .trim done in the filter, since you replace the trimmed arg with cleaned[arg] anyways, and you’ll skip one of the intervening arrays.

File: lib/profile.js [hunk 3]
```diff
@@ -144,83 +154,87 @@ const writableProfileKeys = [
...
+
   let value = args.length > 1 ? args.slice(1).join(' ') : null
+
+  const readPasswords = async () => {
+    const newpassword = await readUserInfo.password('New password: ')
+    const confirmedpassword = await readUserInfo.password('       Again:     ')
+
+    if (newpassword !== confirmedpassword) {
+      log.warn('profile', 'Passwords do not match, please try again.')
+      return await readPasswords()
```
Comment (ljharb) [inline lib/profile.js]: return await is redundant here, all things returned from an async fucntuon are already awaited
```suggestion
      return readPasswords()
```

**Comment by ruyadorno** [comment]
Thanks for the review @ljharb! 🙌

**Review by nlf — APPROVED** [review]
LGTM!

File: lib/profile.js (hunk 3 above)
Comment (Sanan1980) [reply lib/profile.js]: ****
