### PR TITLE
fix(outdated): add dependent location in long output

### LINKED ISSUE #7736: [BUG] `npm outdated --json` doesn't provide distinct workspace packages information
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm outdated --json` dependent field contains a non-identifying string for the package. It can't be used to uniquely identify a local workspace it's referring to. Without `--json`, you can determine, but I don't want to rely on that for parsing.

### Expected Behavior

I'd expect `--json`'s dependent field to contain something I can use to uniquely identify the package, whether it a sub-package in the local workspace, the main package, or something on the registry.

### Steps To Reproduce

1. Clone https://github.com/apexskier/npm-outdated-bug-repro
2. Run `npm outdated --json`. 

You'll see the output:

```json
{
  "eslint": [
    {
      "current": "8.57.0",
      "wanted": "8.57.0",
      "latest": "9.9.0",
      "dependent": "a",
      "location": "/Users/cameronlittle/Developer/test/node_modules/eslint"
    },
    {
      "current": "8.57.0",
      "wanted": "8.57.0",
      "latest": "9.9.0",
      "dependent": "a",
      "location": "/Users/cameronlittle/Developer/test/node_modules/eslint"
    }
  ]
}
```

Now imagine one of those eslint installs was up to date. Which package is it actually for?

I'd expect to see:

```json
{
  "eslint": [
    {
      "current": "8.57.0",
      "wanted": "8.57.0",
      "latest": "9.9.0",
      "dependent": "./a",
      "location": "/Users/cameronlittle/Developer/test/node_modules/eslint"
    },
    {
      "current": "8.57.0",
      "wanted": "8.57.0",
      "latest": "9.9.0",
      "dependent": "./nest/a",
      "location": "/Users/cameronlittle/Developer/test/node_modules/eslint"
    }
  ]
}
```

or

```json
{
  "eslint": [
    {
      "current": "8.57.0",
      "wanted": "8.57.0",
      "latest": "9.9.0",
      "dependent": "a",
      "location": "/Users/cameronlittle/Developer/test/node_modules/eslint"
    },
    {
      "current": "8.57.0",
      "wanted": "8.57.0",
      "latest": "9.9.0",
      "dependent": "nested-a",
      "location": "/Users/cameronlittle/Developer/test/node_modules/eslint"
    }
  ]
}
```

### Environment

- npm: 10.8.2
- Node.js: v22.3.0
- OS Name: macOS
- System Model Name: 14.5 (23F79)
- npm config:
```ini
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew"

; "user" config from /Users/cameronlittle/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = /opt/homebrew/Cellar/node/22.3.0/bin/node
; node version = v22.3.0
; npm local prefix = /Users/cameronlittle/Developer/test
; npm version = 10.8.2
; cwd = /Users/cameronlittle/Developer/test
; HOME = /Users/cameronlittle
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by milaninfy**
Add dependent location details when using `--long` version of the output to identify who is the dependent of the outdated dependencies. 
Fixes: https://github.com/npm/cli/issues/7736

Test output
Screenshot 2025-04-02 at 1 27 02 PM

### CODE REVIEW

**Comment by milaninfy** [comment]
Adding this extra filed might be a breaking change here.

**Comment by wraithgar** [comment]
I think "Dependent location" may not be the best phrasing, but don't know off the top of my head what we'd use instead.  Dependent is usually the package that is required by another package, which is the opposite of what we want.  "Depended by" is how we define it in the output already.

**Comment by wraithgar** [comment]
We will also need to update https://docs.npmjs.com/cli/v11/commands/npm-outdated

**Comment by milaninfy** [comment]
Yeah... I completely missed that documentation part.. I am also rethinking whether in cli output it adds any value since we use package id format for DependedBy field which is much cleaner. Change might only makes sense in `--json`

File: lib/commands/outdated.js [hunk 1]
```diff
@@ -226,7 +229,7 @@ class Outdated extends ArboristWorkspaceCmd {
         'Latest',
         'Location',
         'Depended by',
-        ...long ? ['Package Type', 'Homepage'] : [],
+        ...long ? ['Package Type', 'Homepage', 'Depended By Location'] : [],
```
Comment (milaninfy) [inline lib/commands/outdated.js:232]: Not sure if this is the correct name for the label 😆

Comment (wraithgar) [reply lib/commands/outdated.js:232]: The other column is "depended by" so this makes sense to denote that it's the location of that other field.

File: docs/lib/content/commands/npm-outdated.md [hunk 2]
```diff
@@ -37,6 +37,7 @@ In the output:
   included in `package.json` are always marked `dependencies`.
 * `homepage` (when using `--long` / `-l`) is the `homepage` value contained
   in the package's packument
+* `depended by location` (when using `--long` / `-l`) shows location of the package depends on the displayed dependency
```
Comment (wraithgar) [inline docs/lib/content/commands/npm-outdated.md]:
```suggestion
* `depended by location` (when using `--long` / `-l`) shows location of the package that depends on the displayed dependency
```

**Review by wraithgar — APPROVED** [review]
