### PR TITLE
fix: handle missing `time` in packument to prevent crash on `npm view`

### LINKED ISSUE #8132: [BUG] Npm view command issue when private registry return manifest short version
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

We noticed that from npm version 11 we have issue with the view command, the code referenced below doesn't check for time existence property in the manifest output.

https://github.com/npm/cli/blob/cab74ff7c25149d172cf5d612eb0a651eda531e3/lib/commands/view.js#L272

However the time property doesn't exist if the manifest is in the short version, resulting in a null pointer (variable is undefined). Downgrading to latest v10 solves the issue

### Expected Behavior

It should print package info

### Steps To Reproduce

1. Setup a private registry
2. Run `npm show` or `npm view` of a package with the private scope

### Environment

- npm: 11.1.0
- Node.js: 23.8.0
- OS Name: Arch Linux
- System Model Name: Dell latitude
- npm config:
```ini
; copy and paste output from `npm config ls` here
; "user" config from /home/ale/.npmrc

@middleware:registry = "https://gitlab.dvtech.io/api/v4/projects/3928/packages/npm/"
//gitlab.dvtech.io/api/v4/projects/3928/packages/npm/:_authToken = (protected)

; "env" config from environment

prefix = "/home/ale/.local"

; node bin location = /usr/bin/node
; node version = v23.8.0
; npm local prefix = /home/ale
; npm version = 11.1.0
; cwd = /home/ale
; HOME = /home/ale
```

### PR DESCRIPTION
**Pull request by owlstronaut**
fixes https://github.com/npm/cli/issues/8132

Before & After

image

Validated that tests start throwing errors without the fix ✅

### CODE REVIEW

File: test/lib/commands/view.js [hunk 1]
```diff
@@ -769,3 +769,67 @@ t.test('no package completion', async t => {
   t.notOk(res, 'there is no package completion')
   t.end()
 })
+
+t.test('package with multiple dist‑tags and no time', async t => {
+  const gray = {
```
Comment (wraithgar) [inline test/lib/commands/view.js]: can't we just put this in the main mocks?

**Review by wraithgar — APPROVED** [review]

**Comment by wraithgar** [comment]
Test failures are cause the source branch is behind by one commit.  Tests for this PR are ok.
