### PR TITLE
fix(ci): rm workspace node_modules

### LINKED ISSUE #7226: [BUG] `npm ci` does not remove/recreate existing `node_modules` inside workspaces
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running `npm ci` behaves unintuitively in workspaces. When run in a project without workspaces, the behavior is straightforwards and clear:
1. Validate that the `package-lock.json` is in sync
2. Remove `./node_modules` if it exists
3. Install from `package-lock.json`

This makes perfect sense, and aligns with the documentation. However, when you run `npm ci` in a project with workspaces, it runs _the same three steps_. This sounds like it's fine, except that there is one key problem with step 2: it _only deletes the root `node_modules` folder_. Any `node_modules` in workspaces folders are left behind. This leads to a confusing inconsistency in the behavior of the `npm ci` command: on first install (if there are _no_ `node_modules` installed at all), it will install the full tree, including workspaces. However, when running it a second time, it only cleanly reinstalls the root packages.

### Expected Behavior

I would expect that `npm ci` would remove _all_  the `node_modules` folders referenced in `package-lock.json` before trying to install again.

### Steps To Reproduce

Here is a set of commands that illustrate the issue. If you run this script you will see that the hoisted `abbrev` installation gets properly reinstalled (removing `foo.txt`), but the inner one does not.

```sh
npm init -y
npm init -y -w workspace-a
npm init -y -w workspace-b

npm i --save-exact abbrev@1.1.0 -w workspace-a
npm i --save-exact abbrev@1.1.1 -w workspace-b

touch node_modules/abbrev/foo.txt
touch workspace-b/node_modules/abbrev/bar.txt

npm ci

# This will _not_ include foo.txt, as it has been deleted.
ls node_modules/abbrev
# This _will_ include bar.txt, as it has _not_ been deleted.
ls workspace-b/node_modules/abbrev
```

### Environment

- npm: 10.4.0 _and_ 9.8.1
- Node.js: v18.18.0
- OS Name: macOS
- System Model Name: Macbook Pro
- npm config:
```ini
save-exact = true 
save-prefix = ""
```

### PR DESCRIPTION
**Pull request by reggi**
Fixes https://github.com/npm/cli/issues/7226, an issue where the `npm ci` needs to remove `node_modules` within workspace directories.

### CODE REVIEW

File: lib/base-cmd.js [hunk 1]
```diff
@@ -151,6 +151,19 @@ class BaseCommand {
     this.workspaceNames = [...ws.keys()]
     this.workspacePaths = [...ws.values()]
   }
+
+  /** commands like ci use workspace config but not --workspace */
+  async setWorkspaceFlagIndependent () {
```
Comment (wraithgar) [inline lib/base-cmd.js]: This seems a little overwrought at first glance.  `ci` is a special case, why don't we call `get-workspaces` directly inside there with an empty filter and `includeWorkspaceRoot:true` to get this info?

File: lib/commands/ci.js [hunk 2]
```diff
@@ -33,6 +34,13 @@ class CI extends ArboristWorkspaceCmd {
       })
     }
 
+    this.workspaces = await getWorkspaces([], {
+      path: this.npm.localPrefix,
+      includeWorkspaceRoot: true,
+    })
+    this.workspaceNames = [...this.workspaces.keys()]
```
Comment (wraithgar) [inline lib/commands/ci.js]: this isn't used

File: lib/commands/ci.js [hunk 3]
```diff
@@ -33,6 +34,13 @@ class CI extends ArboristWorkspaceCmd {
       })
     }
 
+    this.workspaces = await getWorkspaces([], {
```
Comment (wraithgar) [inline lib/commands/ci.js]:
```suggestion
    const workspaces = await getWorkspaces([], {
```

File: lib/commands/ci.js [hunk 4]
```diff
@@ -79,11 +87,14 @@ class CI extends ArboristWorkspaceCmd {
       // Only remove node_modules after we've successfully loaded the virtual
       // tree and validated the lockfile
       await time.start('npm-ci:rm', async () => {
-        const path = `${where}/node_modules`
-        // get the list of entries so we can skip the glob for performance
-        const entries = await fs.readdir(path, null).catch(() => [])
-        return Promise.all(entries.map(f => fs.rm(`${path}/${f}`,
-          { force: true, recursive: true })))
+        return await Promise.all([where, ...this.workspacePaths].map(async modulePath => {
```
Comment (wraithgar) [inline lib/commands/ci.js]:
```suggestion
        return await Promise.all(workspaces.values().map(async modulePath => {
```

We don't also need `where` in here since we asked `getWorkspaces` to include the workspace root.

File: lib/commands/ci.js [hunk 5]
```diff
@@ -87,7 +87,8 @@ class CI extends ArboristWorkspaceCmd {
       // Only remove node_modules after we've successfully loaded the virtual
       // tree and validated the lockfile
       await time.start('npm-ci:rm', async () => {
-        return await Promise.all([where, ...this.workspacePaths].map(async modulePath => {
+        const paths = new Set([where, ...this.workspacePaths])
```
Comment (wraithgar) [inline lib/commands/ci.js]: `includeWorkspaceRoot: true,` means `where` is redundant, no?

File: lib/commands/ci.js (hunk 2 above)
Comment (reggi) [reply lib/commands/ci.js]: Currently in "latest" the `this.workspaceNames` field seems to be used but not set here:

https://github.com/npm/cli/blob/latest/lib/commands/ci.js#L43

The  code in the previous iteration was an effort to fix this, is this needed? I since removed it.

File: lib/commands/ci.js [hunk 6]
```diff
@@ -74,16 +75,24 @@ class CI extends ArboristWorkspaceCmd {
...
     if (!dryRun) {
       // Only remove node_modules after we've successfully loaded the virtual
       // tree and validated the lockfile
       await time.start('npm-ci:rm', async () => {
-        const path = `${where}/node_modules`
-        // get the list of entries so we can skip the glob for performance
-        const entries = await fs.readdir(path, null).catch(() => [])
-        return Promise.all(entries.map(f => fs.rm(`${path}/${f}`,
-          { force: true, recursive: true })))
+        return await Promise.all([...workspacePaths.values()].map(async modulePath => {
```
Comment (lukekarrys) [inline lib/commands/ci.js:89]:
```suggestion
        return await Promise.all([...(this.workspacePaths || []), where]).map(async modulePath => {
```

File: lib/commands/ci.js [hunk 7]
```diff
@@ -74,16 +75,24 @@ class CI extends ArboristWorkspaceCmd {
       )
     }
 
+    const workspacePaths = await getWorkspaces([], {
+      path: this.npm.localPrefix,
+      includeWorkspaceRoot: true,
+    })
+
```
Comment (lukekarrys) [inline lib/commands/ci.js:82]:
```suggestion
```

**Review by lukekarrys — CHANGES_REQUESTED** [review]
`CI` extends `ArboristWorkspaceCmd` which will call `this.setWorkspaces()` and then `this.exec()`. So we can check if `this.workspacePaths` is set and use that instead of calling `getWorkspaces` directly. Also `ArboristWorkspaceCmd` will always set `includeWorkspaceRoot: false` so we need to explicitly include `where`.

We need to do this because you can run `npm ci -w workspace-a` and have it only install the deps for `workspace-a` but you can't guarantee that the root `node_modules` won't end up populated. So in fixing this bug we want to make sure that we only `rm -rf` the node_modules specified by the workspace config, plus the root.

File: lib/commands/ci.js [hunk 8]
```diff
@@ -74,16 +75,24 @@ class CI extends ArboristWorkspaceCmd {
...
-        // get the list of entries so we can skip the glob for performance
-        const entries = await fs.readdir(path, null).catch(() => [])
-        return Promise.all(entries.map(f => fs.rm(`${path}/${f}`,
-          { force: true, recursive: true })))
+        return await Promise.all([...workspacePaths.values()].map(async modulePath => {
+          const path = `${modulePath}/node_modules`
+          // get the list of entries so we can skip the glob for performance
+          const entries = await fs.readdir(path, null).catch(() => [])
+          return Promise.all(entries.map(f => {
+            return fs.rm(`${path}/${f}`, { force: true, recursive: true })
```
Comment (antongolub) [inline lib/commands/ci.js]: Just curious: why is it important to empty a `node_modules` dir rather than deleting it entirely?

Comment (wraithgar) [reply lib/commands/ci.js]: I think this was done because the directory would need to be created again anyways.

Comment (antongolub) [reply lib/commands/ci.js]: If anyone (like me) thought there is a significant difference in performance: no, there isn't.

```js
{ 'rm + mkdir': 94.04651467499998, 'readdir + rm': 97.85040412499998 }
```

```js
import fs from 'node:fs/promises'

const suite = {
  count: 40,
  delay: 100,
  async prepare() {
    const dir = `temp/t-${rand()}`
    await seed(dir)
    return dir
  },
  cases: {
    async 'rm + mkdir'(dir) {
      await fs.rm(dir, {recursive: true, force: true})
      await fs.mkdir(dir)
    },

    async 'readdir + rm'(dir) {
      const entries = await fs.readdir(dir, null).catch(() => [])
      await Promise.all(entries.map(entry => fs.rm(`${dir}/${entry}`, {recursive: true, force: true})))
    },
  },
  async run () {
    const results = {}
    const entries = Object.entries(this.cases)
    const dirs = await Promise.all(Array.from({length: this.count * entries.length}, () => this.prepare()))

    for (const [name, cb] of Object.entries(this.cases)) {
      let c = this.count
      results[name] = []
      do {
        const dir = dirs.pop()
        const t1 = process.hrtime.bigint()
        await cb(dir)
        const t2 = process.hrtime.bigint()
        results[name].push(Number(t2 - t1) / 1e6)
        await sleep(this.delay)
        c--
      } while (c)
    }

    const summary = Object.fromEntries(Object.entries(results).map(([name, results]) => [name, results.reduce((a, b) => a + b) / results.length]))
    console.log(summary)
  }
}

await suite.run()

async function seed(base = 'temp', length = 100, depth = 1) {
  await Promise.all(Array.from({length}, async () => {
    const dir = `${base}/${rand()}`
    const _length = (length / 10)|0
    await fs.mkdir(dir, {recursive: true})
    await Promise.all(Array.from({length: _length}, () => fs.writeFile(`${dir}/file-${rand()}`, rand())))

    if (depth) {
      await seed(dir, _length, depth - 1)
    }
  }))
}

function rand() {
  return Math.random().toString(36).slice(2)
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}
```

Comment (wraithgar) [reply lib/commands/ci.js]: What OS is this? Windows is almost always the reason for things like this.

Comment (wraithgar) [reply lib/commands/ci.js]: A lot of those old decisions were never benchmarked though, it is not surprising to find that they're (no longer) required.

Comment (antongolub) [reply lib/commands/ci.js]: m3 / macos 14. I think the results will vary on other machines. nvm, I just calmed myself down with this test.

File: lib/commands/ci.js (hunk 6 above)
Comment (reggi) [reply lib/commands/ci.js:89]: this'll always be set now.

File: lib/commands/ci.js (hunk 8 above)
Comment (wraithgar) [reply lib/commands/ci.js]: Never apologize for bringing actual metrics to a discussion that has historically been about "vibes". It's really appreciated.

File: lib/commands/ci.js [hunk 9]
```diff
@@ -3,12 +3,16 @@ const runScript = require('@npmcli/run-script')
 const fs = require('fs/promises')
 const { log, time } = require('proc-log')
 const validateLockfile = require('../utils/validate-lockfile.js')
-const ArboristWorkspaceCmd = require('../arborist-cmd.js')
+const ArboristCmd = require('../arborist-cmd.js')
```
Comment (wraithgar) [inline lib/commands/ci.js]: I think this needs to be an Arborist workspace command. The "clean" part needs to remove all node_modules, but the reify/install still can get workspace flags added to it.

File: lib/commands/ci.js [hunk 10]
```diff
@@ -76,14 +77,22 @@ class CI extends ArboristWorkspaceCmd {
...
       // Only remove node_modules after we've successfully loaded the virtual
       // tree and validated the lockfile
       await time.start('npm-ci:rm', async () => {
-        const path = `${where}/node_modules`
-        // get the list of entries so we can skip the glob for performance
-        const entries = await fs.readdir(path, null).catch(() => [])
-        return Promise.all(entries.map(f => fs.rm(`${path}/${f}`,
-          { force: true, recursive: true })))
+        return await Promise.all([...workspacePaths.values()].map(async modulePath => {
+          const path = `${modulePath}/node_modules`
```
Comment (wraithgar) [inline lib/commands/ci.js]: Probably wanna use path.join for things like this.

File: lib/commands/ci.js [hunk 11]
```diff
@@ -76,14 +77,22 @@ class CI extends ArboristWorkspaceCmd {
...
+          // get the list of entries so we can skip the glob for performance
+          const entries = await fs.readdir(path, null).catch(() => [])
+          return Promise.all(entries.map(f => {
+            return fs.rm(`${path}/${f}`, { force: true, recursive: true })
```
Comment (wraithgar) [inline lib/commands/ci.js]: path.join here too

File: test/fixtures/mock-npm.js [hunk 12]
```diff
@@ -316,104 +316,112 @@ const loadNpmWithRegistry = async (t, opts) => {
...
-    name, version, ...(Object.keys(dependencies).length ? { dependencies } : {}),
-  })
-
-  const asDependency = {
-    [name]: version,
+  const packageInstalled = (target) => {
+    const spec = path.basename(target)
+    const dirname = path.dirname(target)
+    const [name, version = '1.0.0'] = spec.split('@')
+    assert.fileShouldNotExist(`${dirname}/${name}/${name}@${version}.txt`)
```
Comment (wraithgar) [inline test/fixtures/mock-npm.js]: We should probably stick to using `t` for assertions.

File: test/lib/commands/ci.js [hunk 13]
```diff
@@ -230,3 +226,85 @@ t.test('should throw error when ideal inventory mismatches virtual', async t =>
...
+  })
+  await registry.setup({
+    'lodash@1.1.1': path.join(npm.prefix, 'tarballs/lodash@1.1.1'),
+  })
+  registry.nock.post('/-/npm/v1/security/advisories/bulk').reply(200, {})
+  assert.packageDirty('node_modules/abbrev@1.1.0')
+  assert.packageDirty('node_modules/lodash@1.1.1')
+  await npm.exec('ci', [])
+  assert.packageMissing('node_modules/abbrev@1.1.0')
+  assert.packageInstalled('node_modules/lodash@1.1.1')
```
Comment (reggi) [inline test/lib/commands/ci.js:309]: I recently added convince assertion methods around checking `misising`, `dirty`, and `installed` packages before and after the command. I think this makes it a lot easier easier to see what the commands does.

File: test/fixtures/mock-npm.js (hunk 12 above)
Comment (reggi) [reply test/fixtures/mock-npm.js]: This function uses `t` under the hood. I can make this `assert.packageInstalled('workspace-b/node_modules/abbrev@1.1.1').map(v => t.equal(...v))` pretty easily, does that make sense?

File: test/lib/commands/ci.js (hunk 13 above)
Comment (wraithgar) [reply test/lib/commands/ci.js:309]: I think they help a lot too, but I also think under the hood they should use tap's assertions instead of `node:assert`.  Let's stick to a single assertion library here.

**Review by wraithgar — APPROVED** [review]

**Review by wraithgar — APPROVED** [review]

**Comment by leppaott** [comment]
This seems now inconsistent behavior https://github.com/npm/cli/issues/3598
Why would `ci` prune workspaces when it doesn't install them either? It only prunes what it installs back - that is packages not linking. This broke our system as can't first install the workspace to cache it on docker layer and then install the parent after which we fail to run a command on the workspace since its modules are gone...

Revert please? It's unfortunate any of these commands don't really work with workspaces but this behavior shouldn't be changed IMO.

This should use the `--workspaces` flag?

> [workspaces](https://docs.npmjs.com/cli/v8/commands/npm-ci#workspaces)
> Default: null
> Type: null or Boolean
> Set to true to run the command in the context of all configured workspaces.
> 
> Explicitly setting this to false will cause commands like install to ignore workspaces altogether. When not set explicitly:
> 
> Commands that operate on the node_modules tree (install, update, etc.) will link workspaces into the node_modules folder. - Commands that do other things (test, exec, publish, etc.) will operate on the root project, unless one or more workspaces are specified in the workspace config.

>Explicitly setting this to false will cause commands like install to ignore workspaces altogether.

At least this doesn't seem to affect this at all? `--workspaces=false`

@reggi @wraithgar

Seems `postinstall` is run on `ci` but it can be excluded with --workspaces for the nested workspace.

You can test my issue of having let say `copyfiles` package on `postinstall` for a workspace module.

And you should get following when running `npm ci` for the parent module:

```
npm error sh: 1: copyfiles: not found
```

while package.json looks something like:

```
"scripts": {
    "postinstall": "copyfiles . .",
  },
  "dependencies": {
    "copyfiles": "^2.4.1",
```

this shouldn't happen since the workspace module is installed earlier... But now npm ci breaks it...

**Comment by wraithgar** [comment]
@leppaott please do not `@` notify a bunch of people like this, not everyone you just sent a notification to is even on the npm cli team.

I could not fully understand what the problem was from just your comment.  If you think there is a bug in how `npm ci` works please open up a new issue so we can triage it properly.

**Comment by leppaott** [comment]
@wraithgar This should be reverted as it's a breaking change to delete any workspace node_modules. TS compilations need those modules. This should be considered with more thought. It's now doing the `clean` part yes but it's not doing the `install` part on `clean-install`. I was trying to demonstrate that you cannot run a workspace script that calls a binary after the `clean-install` which you surely can if you just use `install` here. If you do a `clean-install` on the workspace it has the binary, after which you do a `clean-install` on the root it for some reason wipes the workspace's packages.
