### PR TITLE
ci: run install scripts for root project

### LINKED ISSUE #1905: [BUG] `npm ci` doesn't run `postinstall` script
### Current Behavior:
`npm ci` doesn't run the `postinstall` script

### Expected Behavior:
`npm ci` should run the `postinstall` script

### Steps To Reproduce:
1. create a new folder and put the following minimal package.json in it:

```json
{
  "scripts": {
    "postinstall": "echo \"it should echo this\""
  }
}


```

2. run `npm install`
3. run `npm ci`
4. notice how `npm ci` DOES NOT run the `postinstall` script

### Environment:
ex.
- OS: Kubuntu 20.04
- Node: 14.13.0
- npm: 7.0.0-rc.0

### PR DESCRIPTION
**Pull request by isaacs**
`npm ci` should run all the same preinstall/install/postinstall/prepare
scripts for the root project just like `npm install`.

Fixes: #1905

### CODE REVIEW

**Review by ruyadorno — APPROVED** [review]

File: lib/ci.js [hunk 1]
```diff
@@ -35,6 +37,27 @@ const ci = async () => {
   ])
   // npm ci should never modify the lockfile or package.json
   await arb.reify({ ...npm.flatOptions, save: false })
+
+  // run the same set of scripts that `npm install` runs.
+  const scripts = [
+    'preinstall',
+    'install',
+    'postinstall',
+    'prepublish', // XXX should we remove this finally??
```
Comment (XhmikosR) [inline lib/ci.js:46]: Just wondering, I thought `prepublish` was deprecated?

Comment (ljharb) [reply lib/ci.js:46]: please don't remove it yet :-) imo the churn isn't worth it. it'd be better to remove prepublishOnly and make `prepublish`, only running on prepublish, the actual behavior.

Comment (isaacs) [reply lib/ci.js:46]: I think since we already shipped v7, we have this on the agenda for npm v8.  It's a breaking change if we remove it, and at least an annoying change (if not actually breaking) if we deprecate it with a warning.

- remove (or deprecate with a warning) `prepublish` on install/ci
- remove (or deprecate with a warning) `prepublishOnly`

Comment (ljharb) [reply lib/ci.js:46]: Given that’s the plan, I’d prefer the former :-D (which, iirc, was the original planned end state)

**Review by darcyclarke — APPROVED** [review]
