### PR TITLE
fix(arborist): omit root dev deps in linked strategy when shared with workspaces

### LINKED ISSUE #9080: [BUG] `--omit=dev` does not omit root devDependencies in linked install strategy when shared with workspace prod deps
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

When using `npm install --omit=dev` with `installStrategy: linked` in a monorepo, dev dependencies declared in the root `package.json` are still symlinked into root's `node_modules/` in two cases:

1. **External packages** that are both a root devDependency and a production dependency (direct or transitive) of a workspace. The package correctly goes into the store (the workspace needs it), but root incorrectly gets a symlink to it.
2. **Workspaces** declared as root devDependencies (e.g. `@wordpress/build` in Gutenberg) are always hoisted to root's `node_modules/` regardless of `--omit=dev`.

Dev dependencies that are *only* referenced as devDependencies (not shared with any workspace prod dep) are correctly omitted by the existing fix in PR #9066.

### Expected Behavior

With `--omit=dev`, root's `devDependencies` should not be symlinked into root's `node_modules/`, even if the same packages are needed by workspaces as production dependencies. The packages should still be in the store (since workspaces need them), but root should not link to them.

### Steps To Reproduce

1. Create a monorepo with linked install strategy:

```json
// package.json
{
  "name": "myapp",
  "workspaces": ["packages/*"],
  "dependencies": { "which": "1.0.0" },
  "devDependencies": { "typescript": "5.0.0" }
}
```

```json
// packages/mylib/package.json
{
  "name": "mylib",
  "dependencies": { "typescript": "5.0.0" }
}
```

2. Add `.npmrc` with `install-strategy=linked`
3. Run `npm install --omit=dev`
4. Observe that `typescript` is symlinked in root `node_modules/` despite being a root devDependency

This also affects **workspaces declared as root devDependencies** (e.g. `@wordpress/build` in Gutenberg). Even with `--omit=dev`, these workspaces get symlinked into root's `node_modules/` because npm auto-creates `workspace` type edges (not `dev` edges) and `#rootDeclaredDeps` unconditionally includes `devDependencies` keys.

### Environment

- npm: v10 and v11 (latest) -- both affected
- Node.js: v22.20.0
- OS Name: macOS (Darwin)
- npm config:
  ```ini
  install-strategy=linked
  ```

### PR DESCRIPTION
**Pull request by manzoorwanijk**
In continuation of our exploration of using `install-strategy=linked` in the [Gutenberg monorepo](https://github.com/WordPress/gutenberg/pull/75814), which powers the WordPress Block Editor.

## Summary

Fixes `--omit=dev` (and `--omit=optional`, `--omit=peer`) not being fully respected in the linked install strategy for monorepos.

PR #9066 added a `shouldOmit()` check during graph traversal in `makeIdealGraph()`, which works for dev deps that are *only* dev deps. However, it missed two cases:

- **Shared external packages**: When a root devDependency is also a workspace prodDependency, the node has `dev=false` (reachable via prod paths), so `shouldOmit()` returns false. The package correctly goes into the store (the workspace needs it), but root incorrectly gets a symlink to it because `#assignCommonProperties()` doesn't filter by edge type.
- **Workspace dev deps**: Workspaces listed in root's `devDependencies` are always hoisted to root's `node_modules/` because `#rootDeclaredDeps` unconditionally includes `devDependencies` keys, and npm auto-creates `workspace` type edges (not `dev` edges) for all workspaces.

### Changes

1. **Filter edges by type in `#assignCommonProperties()`** for root and workspace nodes — dev, optional, and peer edges are excluded when their corresponding `--omit` flag is set.
2. **Exclude omitted dep types from `#rootDeclaredDeps`** — so workspaces declared only as root devDependencies aren't hoisted when `--omit=dev` is set.

## References

Fixes #9080

### CODE REVIEW

**Review by wraithgar — DISMISSED** [review]

File: workspaces/arborist/lib/arborist/isolated-reifier.js [hunk 1]
```diff
@@ -72,15 +73,17 @@ module.exports = cls => class IsolatedReifier extends cls {
...
     // npm auto-creates 'workspace' edges from root to all workspaces.
     // For isolated/linked mode, only include workspaces that root explicitly declares as dependencies.
+    // When omitting dep types, exclude those from the declared set so their workspaces aren't hoisted.
     const rootPkg = idealTree.package
     this.#rootDeclaredDeps = new Set([
       ...Object.keys(rootPkg.dependencies || {}),
-      ...Object.keys(rootPkg.devDependencies || {}),
-      ...Object.keys(rootPkg.optionalDependencies || {}),
+      ...(!omit.has('dev') ? Object.keys(rootPkg.devDependencies || {}) : []),
+      ...(!omit.has('optional') ? Object.keys(rootPkg.optionalDependencies || {}) : []),
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/isolated-reifier.js:86]: I think this is ok but wanted to be sure someone else agreed.  What about peer deps here?

Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js:86]: Good point - we added `#rootDeclaredDeps` in #9076 and didn't include `peerDependencies`. If root declares a workspace as a peer dep, it should be hoisted too. I'll add it with the omit guard for consistency.

Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js:86]: Done in https://github.com/npm/cli/pull/9081/commits/7b9e4a5a1ba5acfae699e5e66ee1812cc7de76f6

**Review by wraithgar — APPROVED** [review]
