### PR TITLE
fix(npm) pass npm context everywhere

### LINKED ISSUE #124: refactor lib/utils/open-url.js
from: https://github.com/npm/cli/pull/1311#discussion_r435628817

> Note: we should make openUrl return a promise. Also, I see that it checks process.argv explicitly for a --no-browser flag, which is not great. (Should just be checking npm.config.get('browser') === false or better yet, npm.flatOptions.browser === false.)

### PR DESCRIPTION
**Pull request by wraithgar**
Instead of files randomly requiring the npm singleton, we pass it where it needs to go so that tests don't need to do so much require mocking everywhere.

Instead of continuing down the path of "Just add a function that wraps another function and adds something new to its context," commands are now proper objects.

Usage output is more correct now, that bugfix had to be in here to get things to work.
open-url had a bug where it was never handling its happy-path callback. That bug went away due to refactoring.
Tests were also added that were missing for install-ci-test and install-test.
Other minor bugfixes like how open-url was not ever handling its happy-path callback had to be fixed.

We are going to have to find a better solution for coverage on the usage and completion functions, when they are accessed through `npm.commands.x` they do not count for coverage, and that is the only way we should ultimately be trying to access them once we have proper tests.

Fixes: https://github.com/npm/statusboard/issues/124

### CODE REVIEW

**Comment by wraithgar** [comment]
This is built off of #2759 but that one should be long since landed by the time this is done.

File: lib/access.js [hunk 1]
```diff
@@ -34,152 +20,200 @@ const subcommands = [
...
-    .then(x => cb(null, x))
-    .catch(err => err.code === 'EUSAGE'
-      ? cb(err.message)
-      : cb(err)
+class Access {
+  constructor (npm) {
+    this.npm = npm
+  }
+
+  // TODO we don't use this, why are we exporting it?
```
Comment (isaacs) [inline lib/access.js]: I don't believe we ever used it for `access`, but some other command(s) did once upon a time, iirc?  Config, I think?

Anyway, let's not export anything we're not using.  I say ditch it.

File: lib/access.js [hunk 2]
```diff
@@ -34,152 +20,200 @@ const subcommands = [
...
+  get subcommands () {
+    return subcommands
+  }
+
+  get usage () {
```
Comment (isaacs) [inline lib/access.js:28]: Could we have all of these inherit from a base `Command` class that DRYs up some of the usageUtil()/completion() repetition?  I'm not sure it's paying rent, seems like just another thing for us to forget to do.  The Command constructor could even have some nice safety nets, like:

```js
const _usage = Symbol.for('usage')
class Command {
  constructor (npm) {
    if (!npm)
      throw new TypeError('should pass in npm instance to constructor')
    if (!this[_usage])
      throw new Error('usage not found for command ' + this.constructor.name)
    if (!this[_completion])
      throw new Error('completion not found for command ' + this.constructor.name)
    if (!this.name)
      throw new Error('name not found for command ' + this.constructor.name)
  }
  // override in subclasses with something
  get name () {
    return null
  }
  get [_usage] () {
    return null
  }
  get [_completion] () {
    return null
  }
  get usage () {
    return usageUtil(this.name, this[_usage])
  }
  completion (opts) {
    doSomethingWith(this[_completion])
  }
}
```

File: lib/access.js [hunk 3]
```diff
@@ -34,152 +20,200 @@ const subcommands = [
...
+      case 'revoke':
+        return []
+      default:
+        throw new Error(argv[2] + ' not recognized')
+    }
+  }
 
-  if (!cmd)
-    throw UsageError('Subcommand is required.')
+  exec (args, cb) {
```
Comment (isaacs) [inline lib/access.js:69]: It looks like you're heading in this direction already, but pretty please can we ditch the callbacks entirely? 😆  I'd love to see `this.access` just be `this.exec()`, and have npm know how to handle that.

File: lib/access.js (hunk 2 above)
Comment (wraithgar) [reply lib/access.js:28]: ~This is a fabulous next step.~

Thinking more about this, those protections belong in a test.  Abstracting those only pushes the "I have to remember to add x" to a class down the chain and adds one more level of hoops to jump through to read the code.

A test for this would look like "load up all the commands from cmd-list.js, instantiate them all, see if they export what's required (completion is not required)"

File: lib/access.js (hunk 3 above)
Comment (wraithgar) [reply lib/access.js:69]: That change was left out of this PR because of the amount of testing changes it would require.  This PR is mostly code change, with minimal test changes.

Making this function async would be a minimal code change, and a larger test change.  It'd be much easier than THIS PR, but still needs to be its own thing.

Comment (wraithgar) [reply lib/access.js:69]: That test already exists in `test/lib/load-all-commands.js`

File: lib/access.js (hunk 2 above)
Comment (wraithgar) [reply lib/access.js:28]: That test already exists in `test/lib/load-all-commands.js`

File: lib/find-dupes.js [hunk 4]
```diff
@@ -2,7 +2,15 @@
...
+class FindDupes {
+  /* istanbul ignore next - see test/lib/load-all-commands.js */
+  get usage () {
+    return usageUtil('find-dupes', 'npm find-dupes')
+  }
 
-module.exports = Object.assign(cmd, { usage })
+  exec (args, cb) {
+    // TODO this should really be this.npm.commands.dedupe
+    dedupe({ dryRun: true }, cb)
```
Comment (ruyadorno) [inline lib/find-dupes.js]: this TODO is pb already unlocked by #2802

**Review by ruyadorno — APPROVED** [review]

File: lib/access.js (hunk 2 above)
Comment (wraithgar) [reply lib/access.js:28]: https://github.com/npm/cli/pull/2821

File: lib/find-dupes.js (hunk 4 above)
Comment (wraithgar) [reply lib/find-dupes.js]: It's been fixed in this PR cause it was a bug
