### PR TITLE
fix(exec):  npx to run specified version if multiple version exist globally 

### LINKED ISSUE #7486: [BUG] npx does not respect version range if a compatible version is found inside any package installed globally
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Installed package is used even if the version range does not match.
```
npm install -g generator-jhipster@8.3.0 generator-jhipster-native@2.1.0
npx generator-jhipster@8.4.0 --version
8.3.0
```

### Expected Behavior

The version range should be respected.
```
npm install -g generator-jhipster@8.3.0
npx generator-jhipster@8.4.0 --version
8.4.0
```

### Steps To Reproduce

_No response_

### Environment

- npm: 10.7.0
- Node.js: v18.20.2
- OS Name: MacOS
- System Model Name: MacBook Air
- npm config:
```ini
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew"

; "user" config from /Users/mshima/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = /usr/local/bin/node
; node version = v18.20.2
; npm local prefix = /Users/mshima/git/test
; npm version = 10.7.0
; cwd = /Users/mshima/git/test
; HOME = /Users/mshima
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by milaninfy**
When multiple version of the same package is exist globally either at top level or at any level as a sub dependency, even though the version specified does not exist at top level it was running top level bin since it matches the bin name. 
This fixes checks for depth of the found node along with already existing specs checks.  

Fixes: #7486

### CODE REVIEW

File: workspaces/libnpmexec/test/local.js [hunk 1]
```diff
@@ -370,3 +370,69 @@ t.test('global scoped pkg', async t => {
...
+    node_modules: {
+      '@npmcli': { B: {
+        node_modules: {
+          '@npmcli': {
+            A: pkgA2.fixtures.packages['@npmcli-A-2.0.0'],
+          } },
+        'package.json': { dependencies: { '@npmcli/A': '2.0.0' } },
+      },
+      },
+    } })
```
Comment (milaninfy) [inline workspaces/libnpmexec/test/local.js]: are there any better ways to setup nested packages?

File: workspaces/libnpmexec/test/local.js [hunk 2]
```diff
@@ -370,3 +370,69 @@ t.test('global scoped pkg', async t => {
...
+  })
+
+  await chmod()
+  await chmod('global/node_modules/@npmcli/B/node_modules/@npmcli/A/bin-file.js')
+  await binLinks()
+  await binLinks({
+    name: '@npmcli/A',
+    path: '@npmcli/B/node_modules/@npmcli/A',
+    bin: { A: 'bin-file.js' },
+  })
```
Comment (milaninfy) [inline workspaces/libnpmexec/test/local.js:414]: better and clean way to set up nested bin links ?

File: workspaces/libnpmexec/lib/index.js [hunk 3]
```diff
@@ -41,6 +41,10 @@ const missingFromTree = async ({ spec, tree, flatOptions, isNpxTree }) => {
     // registry spec that is not a specific tag.
     const nodesBySpec = tree.inventory.query('packageName', spec.name)
     for (const node of nodesBySpec) {
+      // continue if node is not at specified depth, no need to check further
+      if (depth !== undefined && node.depth !== depth) {
```
Comment (wraithgar) [inline workspaces/libnpmexec/lib/index.js]: This is a great solution.  However we are currently not really using `depth` so much as telling this function to only look at depth 0.

It would probably make more sense in the future when reading this if this was called something like `shallow` and was a Boolean.  and then `if (shallow && node.depth)` would be the test for continuing.

Comment (milaninfy) [reply workspaces/libnpmexec/lib/index.js]: Makes sense.. Corrected in latest push.

File: workspaces/libnpmexec/lib/index.js [hunk 4]
```diff
@@ -201,9 +205,10 @@ const exec = async (opts) => {
       // See if the package is installed globally, and run the translated bin
       const globalArb = new Arborist({ ...flatOptions, path: globalPath, global: true })
       const globalTree = await globalArb.loadActual()
-      const { manifest: globalManifest } =
-        await missingFromTree({ spec, tree: globalTree, flatOptions })
-      if (!globalManifest && await fileExists(`${globalBin}/${args[0]}`)) {
+      const { node: globalNode } =
```
Comment (wraithgar) [inline workspaces/libnpmexec/lib/index.js]: Why did we switch from manifest to node here?

Comment (milaninfy) [reply workspaces/libnpmexec/lib/index.js]: Initially I kept both, but the `missingFromTree` function in all code path it returns  either `{ node }` or `{ manifest }` not sure if there ever a case if manifest is null and node is null as well, and also later we were checking for `!manifest` so changed to `node`, but I think now that you pointed it out it wont make a difference even if I keep it as it was earlier.

**Review by wraithgar — APPROVED** [review]
