### PR TITLE
fix: added check for dry-run

### LINKED ISSUE #7239: [BUG] npm ci --dry-run deletes node_modules folders
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ci --dry-run deletes node_modules contents.

### Expected Behavior

Using the --dry-run flag should not delete the contents of node_modules.

Context: See issue #2524 which was closed by @darcyclarke due to it not being able to be replicated in npm 7. However, it has not been reopened despite someone commenting over a year ago that it was still an issue in 9.2.0.  It is still an issue for me in 10.4.0, so I am creating an issue for the current version to get eyes on it again.

### Steps To Reproduce

1. `npm init -y`
2. `npm install redis` (or whatever)
3. `npm ci --dry-run`
4. `ls -la node_modules`
(I would expect the output of step 4 to still list the packages installed in step 2)

### Environment

- npm: 10.4.0
- Node.js: 20.10.0
- OS Name: Windows 10 (but using node/npm in Ubuntu 22.04 in WSL)
- System Model Name: Microsoft Surface Laptop 3
- npm config:
```ini
; node bin location = /home/me/.nvm/versions/node/v20.10.0/bin/node
; node version = v20.10.0
; npm local prefix = /home/me/code/npmtest
; npm version = 10.4.0
; cwd = /home/me/code/npmtest
; HOME = /home/me
```

### PR DESCRIPTION
**Pull request by cod1r**
added a check for dry-run for `npm ci` so that node_modules won't be deleted.

`npm ci --dry-run` currently removes the node_modules folder even though the docs say that dry-run, "Indicates that you don't want npm to make any changes and that it should only report what it would have done".

This commit adds a check for dryRun in the npm.flatOptions object which will be true if `--dry-run` is added on the cli or if `dry-run=true` is set in .npmrc

closes #7239

### CODE REVIEW

File: lib/commands/ci.js [hunk 1]
```diff
@@ -75,14 +75,16 @@ class CI extends ArboristWorkspaceCmd {
...
+    if (!this.npm.flatOptions.dryRun) {
+      // Only remove node_modules after we've successfully loaded the virtual
+      // tree and validated the lockfile
+      await this.npm.time('npm-ci:rm', async () => {
+        const path = `${where}/node_modules`
+        // get the list of entries so we can skip the glob for performance
+        const entries = await fs.readdir(path, null).catch(er => [])
+        return Promise.all(entries.map(f => fs.rm(`${path}/${f}`, { force: true, recursive: true })))
+      })
+    }
```
Comment (ljharb) [inline lib/commands/ci.js]: maybe it'd be better if, when a dry run, it checked that npm has *permissions* to rimraf node_modules?

Comment (cod1r) [reply lib/commands/ci.js]: I am not sure what you mean by 'permissions'. Sorry this is my first time contributing to npm.

Comment (cod1r) [reply lib/commands/ci.js]: It wasn't checking for any permissions before so I am confused.

Comment (ljharb) [reply lib/commands/ci.js]: You’re right, but i meant it’d be useful and match the “dry run” semantics

Comment (wraithgar) [reply lib/commands/ci.js]: Checking permissions in node is mostly done by trying the operation and then reporting to the user if it failed.  It's even discouraged for things like `fs.access` to be used for this purpose.  With that in mind I think it's fine for `dry-run` to simply tell the user what it would try to do.  It is not meant to be a test of if npm will eventually be able to succeed.  Many other things could go wrong (i.e. running out of disk space).

This PR appears fine as-is (I am not done fully reviewing it but at a glance it appears mostly on the right track).

Comment (ljharb) [reply lib/commands/ci.js]: presumably *deleting* files wouldn't cause disk space to run out :-)

def that enhancement could be done as a follow through regardless

**Comment by wraithgar** [comment]
I don't know if this is a problem for this PR to solve, but technically this dry run is meaningless because Arborist isn't being presented with the same scenario as a true `ci` run. So the summary output is very wrong.

This doesn't feel like a blocker, as this is better than before.

**Review by jumoel — APPROVED** [review]
This is a great, thanks for fixing it!
