### PR TITLE
fix(arborist): unwrap Link nodes in legacyPeerDeps for linked strategy

### LINKED ISSUE #9050: [BUG] EEXIST on workspace symlinks with `--install-strategy=linked` and `legacy-peer-deps`
## Is there an existing issue for this?

- [x] I have searched the existing issues

## This issue exists in the latest npm version

- [x] I am using the latest npm

## Current Behavior

We are testing `install-strategy=linked` on the [Gutenberg monorepo](https://github.com/WordPress/gutenberg/pull/75814) (~200 workspace packages).

Running `npm install --install-strategy=linked` a second time in a workspace monorepo that uses `legacy-peer-deps=true` and has workspace-to-workspace peer dependencies fails with:

```
npm error code EEXIST
npm error syscall symlink
npm error path ../../packages/theme
npm error dest /path/to/project/node_modules/@wordpress/theme
npm error errno -17
npm error EEXIST: file already exists, symlink '../../packages/theme' -> '/path/to/project/node_modules/@wordpress/theme'
```

Stack trace points to concurrent `Promise.allSettled` inside `#reifyPackages`:

```
Error: EEXIST: file already exists, symlink ...
    at async symlink (node:internal/fs/promises:1008:10)
    at async #extractOrLink (arborist/lib/arborist/reify.js:646:7)
    at async Promise.allSettled (...)
    at async #reifyPackages (arborist/lib/arborist/reify.js:309:11)
```

Introduced by commit `26fa40eeafdbbb616d48fe254c92544cb13fba60`
("fix: fix workspace-filtered install with linked strategy").

## Expected Behavior

`npm install --install-strategy=linked` should be idempotent — running it a second time on a project where workspace symlinks already exist should succeed without error.

## Steps To Reproduce

**Prerequisites**: `legacy-peer-deps=true` in `.npmrc` and workspaces that have peer dependencies on other workspaces.

1. Create a workspace monorepo where some workspaces peer-depend on others:

   ```
   my-project/
   ├── .npmrc                # legacy-peer-deps=true
   ├── package.json          # { "workspaces": ["packages/*"] }
   ├── packages/
   │   ├── ws-a/
   │   │   └── package.json  # { "name": "ws-a", "peerDependencies": { "ws-b": "*" }, "dependencies": { "abbrev": "1.0.0" } }
   │   └── ws-b/
   │       └── package.json  # { "name": "ws-b", "version": "1.0.0" }
   ```

2. Run first install — succeeds:
   ```sh
   npm install --install-strategy=linked
   ```

3. Run second install — fails with EEXIST:
   ```sh
   npm install --install-strategy=linked
   ```

**Note**: The race condition requires sufficient concurrency to trigger reliably. Projects with many workspaces (e.g. Gutenberg with ~200 workspaces) hit it consistently. A minimal reproduction needs ~20 workspaces with cross peer deps.

<details>
<summary>Full reproduction script (copy-paste into terminal)</summary>

```bash
DIR=/tmp/npm-eexist-repro
rm -rf "$DIR"
mkdir -p "$DIR/packages/ws-"{0..19}

cat > "$DIR/package.json" <<'EOF'
{
  "name": "repro-root",
  "private": true,
  "workspaces": ["packages/*"]
}
EOF

cat > "$DIR/.npmrc" <<'EOF'
legacy-peer-deps=true
EOF

for i in $(seq 0 19); do
  next=$(( (i + 1) % 20 ))
  cat > "$DIR/packages/ws-$i/package.json" <<EOF
{
  "name": "ws-$i",
  "version": "1.0.0",
  "dependencies": { "abbrev": "*" },
  "peerDependencies": { "ws-$next": "*" }
}
EOF
done

cd "$DIR"
echo "==> First install"
npm install --install-strategy=linked

echo "==> Second install (hits EEXIST)"
npm install --install-strategy=linked
```
</details>

## Root Cause

In `isolated-reifier.js`, `assignCommonProperties` resolves legacy peer dependencies via `node.resolve(peerName)` (line 159). For workspace dependencies, `node.resolve()` returns the **Link** node (e.g. at `node_modules/@wordpress/theme`) rather than its **target** (the fsChild at `packages/theme`).

The normal edge-based path correctly unwraps links via `e.to.target` (line 150), but the `legacyPeerDeps` fallback pushes the raw resolved node directly:

```javascript
// line 149-150 — edges correctly unwrap via .target
const nonOptionalDeps = edges.filter(e => !e.optional).map(e => e.to.target)

// line 159-161 — legacyPeerDeps pushes Link node directly (BUG)
const resolved = node.resolve(peerName)
if (resolved && resolved !== node && !resolved.inert) {
    nonOptionalDeps.push(resolved)  // ← Link, not target!
}
```

This causes `workspaceProxy` to be called with the Link node (`location="node_modules/@wordpress/theme"`) instead of the fsChild (`location="packages/theme"`). Since the memoize key is the node object itself and the Link is a different object from the fsChild, a **second** workspace proxy is created with `localLocation="node_modules/@wordpress/theme"`.

When `processEdges` processes this second proxy, it computes:
```
nmFolder = join("node_modules/@wordpress/theme", "node_modules")
```

Store links for the workspace's external deps (e.g. `react`) are then placed at `node_modules/@wordpress/theme/node_modules/react` instead of `packages/theme/node_modules/react`. During reification, these store links' `mkdir(dirname(...), {recursive: true})` creates `node_modules/@wordpress/theme` as a **directory**, racing with the workspace symlink's `rm()` + `symlink()` at the same path — causing EEXIST.

## Fix

In `assignCommonProperties`, unwrap Link nodes when resolving legacy peer deps, consistent with the edge-based path:

```diff
 const resolved = node.resolve(peerName)
 if (resolved && resolved !== node && !resolved.inert) {
-  nonOptionalDeps.push(resolved)
+  nonOptionalDeps.push(resolved.target || resolved)
 }
```

## Environment

- npm: 11.x (latest, built from `latest` branch)
- Node.js: v22
- OS Name: macOS (Darwin 25.3.0)
- System Model Name: (any)

### PR DESCRIPTION
**Pull request by manzoorwanijk**
When `legacyPeerDeps` is enabled and a workspace has a peer dependency on another workspace, `node.resolve()` in `assignCommonProperties` returns the Link node (at `node_modules/<ws>`) rather than its target (at `packages/<ws>`). The normal edge-based path correctly unwraps via `e.to.target`, but the legacyPeerDeps fallback pushed the raw resolved node directly.

This caused `workspaceProxy` to be called with the Link (a different object from the fsChild), creating a second workspace proxy with `localLocation="node_modules/<ws>"`. Store links for that workspace's deps were then placed at `node_modules/<ws>/node_modules/<dep>` instead of `packages/<ws>/node_modules/<dep>`, racing with the workspace symlink at `node_modules/<ws>` and hitting EEXIST on subsequent installs.

Fix: use `resolved.target` to unwrap Link nodes, consistent with the edge-based path.

## References

Fixes #9050

### CODE REVIEW

File: workspaces/arborist/test/isolated-mode.js [hunk 1]
```diff
@@ -368,6 +368,56 @@ tap.test('peer dependencies with legacyPeerDeps', async t => {
...
+tap.test('idempotent install with legacyPeerDeps and workspace peer deps', async t => {
+  // Regression: when legacyPeerDeps is enabled and a workspace has a peer
+  // dependency on another workspace, node.resolve() returns the Link node
+  // (not its target). This caused workspaceProxy to be called with the Link,
+  // producing store links under node_modules/<ws>/node_modules/ that race
+  // with the workspace symlink at node_modules/<ws>, hitting EEXIST on the
+  // second install.
+  //
+  // Use many workspaces with cross-peer-deps to increase concurrency and
+  // make the race window large enough to trigger reliably.
```
Comment (owlstronaut) [inline workspaces/arborist/test/isolated-mode.js]: We try to not break comments among multiple lines when it is one sentence/idea - it causes issues for screen readers. We prefer the line go as long as it needs to. Could you adjust?

**Review by owlstronaut — CHANGES_REQUESTED** [review]
The fix is good - already verified. we try to keep our codebase screen reader friendly when introducing new comments. Can approve and merge after

File: workspaces/arborist/test/isolated-mode.js (hunk 1 above)
Comment (manzoorwanijk) [reply workspaces/arborist/test/isolated-mode.js]: Like this or combine both the sentences?

```suggestion
  // Regression: when legacyPeerDeps is enabled and a workspace has a peer dependency on another workspace, node.resolve() returns the Link node (not its target). This caused workspaceProxy to be called with the Link, producing store links under node_modules/<ws>/node_modules/ that race with the workspace symlink at node_modules/<ws>, hitting EEXIST on the second install.
  // Use many workspaces with cross-peer-deps to increase concurrency and make the race window large enough to trigger reliably.
```

**Review by owlstronaut — APPROVED** [review]
