### PR TITLE
fix!: don't install man pages in system locations

### LINKED ISSUE #1071: stop installing actual man pages
Our help pages will still be in man format, and displayed via man, but we do not need to support `man install` opening npm cli docs.

### PR DESCRIPTION
**Pull request by owlstronaut**
BREAKING CHANGE: npm no longer registers man pages with the system when installed globally. `man npm-install` will no longer work, but `npm help install` is unaffected.
 
 fixes https://github.com/npm/statusboard/issues/1071

### CODE REVIEW

**Comment by wraithgar** [comment]
Putting in draft mode till we're ready to land breaking changes

File: tap-snapshots/test/lib/commands/publish.js.test.cjs [hunk 1]
```diff
@@ -121,10 +121,6 @@ Object {
     "url": "https://github.com/npm/cli/issues",
   },
   "description": "a package manager for JavaScript",
-  "directories": Object {
-    "doc": "./doc",
-    "man": "./man",
```
Comment (wraithgar) [inline tap-snapshots/test/lib/commands/publish.js.test.cjs:128]: When you run `npm help install` where does it pull from?

Comment (owlstronaut) [reply tap-snapshots/test/lib/commands/publish.js.test.cjs:128]: https://github.com/npm/cli/blob/latest/lib/commands/help.js#L64-L66

npm help globs directly from the npm root

File: package.json [hunk 2]
```diff
@@ -32,10 +32,6 @@
   "bugs": {
     "url": "https://github.com/npm/cli/issues"
   },
-  "directories": {
-    "doc": "./doc",
```
Comment (wraithgar) [inline package.json:36]: These are still important!

```sh
$ npm help install
$ ps|grep npm-install
20611 ttys000    0:00.01 /bin/sh /usr/bin/man /Users/gar/.nvm/versions/node/v24.14.0/lib/node_modules/npm/man/man1/npm-install.1

$ npm help install --viewer browser
$ // opens file:///Users/gar/.nvm/versions/node/v24.14.0/lib/node_modules/npm/docs/output/commands/npm-install.html
```

**Comment by wraithgar** [comment]
I think the fix is gonna be deeper than this. We still need these file to exist for `npm help` both in terminal and browser. What we don't need is the code that copies them to global man space.

File: package.json (hunk 2 above)
Comment (wraithgar) [reply package.json:36]: Oh wait I misremembered what "directories" does.

**Comment by wraithgar** [comment]
We'll want to update this copy, haha https://docs.npmjs.com/cli/v11/configuring-npm/package-json#directories

**Comment by owlstronaut** [comment]
> We'll want to update this copy, haha https://docs.npmjs.com/cli/v11/configuring-npm/package-json#directories

done

**Review by wraithgar — APPROVED** [review]
