### PR TITLE
fix(arborist): propagate overrides through Link nodes to targets

### LINKED ISSUE #9197: [BUG] Overrides ignored for transitive dependencies with install-strategy=linked
Found while testing overrides in [WordPress/gutenberg](https://github.com/WordPress/gutenberg/pull/75814). We're switching to `strict-peer-deps` after adopting the linked strategy.

## Is there an existing issue for this?

- [x] I have searched the existing issues

## This issue exists in the latest npm version

- [x] I am using the latest npm

## Current Behavior

Somewhat related to #9109

When using `install-strategy=linked`, npm overrides for transitive dependencies are ignored. The overridden version is installed but the parent's edge still expects the lockfile version, marking the overridden package as `invalid`. With `strict-peer-deps=true`, this causes an `ERESOLVE` error and the install fails completely.

With the default `hoisted` strategy, the same overrides work correctly — the overridden packages are installed and marked as `overridden` in the tree.

## Expected Behavior

Overrides should work the same way regardless of install strategy. The overridden version should satisfy the parent's dependency edge, just like it does with `hoisted`.

### Setup (common to both strategies)

```bash
rm -rf /tmp/npm-override-bug
mkdir -p /tmp/npm-override-bug
cd /tmp/npm-override-bug

cat > package.json << 'EOF'
{
  "name": "override-bug-repro",
  "version": "1.0.0",
  "private": true,
  "devDependencies": {
    "typescript": "5.8.3",
    "@typescript-eslint/utils": "8.51.0"
  }
}
EOF
```

### With linked strategy (BUG)

```bash
echo 'install-strategy=linked' > .npmrc

# 1. Install to create lockfile with 8.51.0 versions
npm install

# 2. Upgrade to TS 6 and add overrides for transitive deps
cat > package.json << 'EOF'
{
  "name": "override-bug-repro",
  "version": "1.0.0",
  "private": true,
  "devDependencies": {
    "typescript": "6.0.2",
    "@typescript-eslint/utils": "8.51.0"
  },
  "overrides": {
    "@typescript-eslint/typescript-estree": "8.58.0",
    "@typescript-eslint/project-service": "8.58.0"
  }
}
EOF

# 3. Reinstall — override is applied but tree is invalid
npm install
npm ls @typescript-eslint/typescript-estree
# Actual:   @typescript-eslint/typescript-estree@8.58.0 invalid: "8.51.0"
# Expected: @typescript-eslint/typescript-estree@8.58.0 overridden
```

### With hoisted strategy (WORKS)

```bash
rm -rf /tmp/npm-override-bug
mkdir -p /tmp/npm-override-bug
cd /tmp/npm-override-bug
# ... same setup as above, without the .npmrc ...
npm install
# ... same package.json change as above ...
npm install
npm ls @typescript-eslint/typescript-estree
# @typescript-eslint/typescript-estree@8.58.0 overridden  ✓
```

### With `strict-peer-deps=true`

Adding `strict-peer-deps=true` to the `.npmrc` makes it worse — step 3 fails outright with `ERESOLVE`, and the override is completely ignored:

```
npm error ERESOLVE could not resolve
npm error While resolving: @typescript-eslint/project-service@8.51.0
npm error Found: typescript@6.0.2
npm error Could not resolve dependency:
npm error peer typescript@">=4.8.4 <6.0.0" from @typescript-eslint/project-service@8.51.0
```

### Cleanup

```bash
rm -rf /tmp/npm-override-bug
```

## Root Cause Analysis

During `loadVirtual` in [load-virtual.js](https://github.com/manzoorwanijk/npm-cli/blob/05dbba5b8d727ddb2c098ce0553714eae791c5f2/workspaces/arborist/lib/arborist/load-virtual.js#L84), nodes loaded from the lockfile are created without override context. When the linked strategy builds the tree, override propagation through parent edges doesn't properly update the edge's expected spec, so the overridden version is treated as invalid rather than overridden.

In `hoisted` mode, when an invalid edge is detected after loading the virtual tree, it gets queued for re-resolution in `#initTree` (build-ideal-tree.js ~line 340). The linked strategy appears to handle these differently, skipping re-resolution for overridden transitive deps.

## Environment

- npm: v11.12.1 (fork, latest branch)
- Node.js: v24.14.0
- OS: macOS (Darwin 25.4.0)
- npm config:
  ```ini
  install-strategy=linked
  strict-peer-deps=true  ; (optional, makes it worse)
  ```

### PR DESCRIPTION
**Pull request by manzoorwanijk**
In continuation of our exploration of using `install-strategy=linked` in the [Gutenberg monorepo](https://github.com/WordPress/gutenberg/pull/75814), which powers the WordPress Block Editor.

When using `install-strategy=linked`, npm overrides for transitive dependencies were ignored.
The overridden version was installed but reported as `invalid` instead of `overridden`, and with `strict-peer-deps` the install failed entirely with `ERESOLVE`.

The root cause is that override propagation stops at Link nodes and never reaches their targets.
Overrides propagate through the tree via `addEdgeIn` -> `updateOverridesEdgeInAdded` -> `recalculateOutEdgesOverrides`.
When a Link node receives overrides, `recalculateOutEdgesOverrides` iterates over `this.edgesOut` — but Links have no `edgesOut` (their targets do).
So overrides never reach the target node's dependency edges, and those edges use `rawSpec` instead of the overridden spec.

In the linked strategy, all packages in `node_modules/` are Links pointing to targets in `.store/`.
This meant no overrides propagated past the first level of the dependency tree.

The fix overrides `recalculateOutEdgesOverrides` in the `Link` class to forward overrides to the target node.
When `buildIdealTree` creates a root Link (e.g. on macOS where `/tmp` -> `/private/tmp`), the target Node is now created with `loadOverrides: true` so it loads override rules from `package.json`.

The `#applyRootOverridesToWorkspaces` workaround method is removed — it was compensating for this exact bug by detaching workspace edges whose specs didn't match. With proper propagation, workspace edges already have the correct overridden spec, making the workaround dead code.

## References

Fixes #9197

### CODE REVIEW

File: workspaces/arborist/lib/link.js [hunk 1]
```diff
@@ -109,6 +109,14 @@ class Link extends Node {
   // so this is a no-op
   [_loadDeps] () {}
 
+  // When a Link receives overrides (via edgesIn), forward them to the target node which holds the actual edgesOut.
+  // Without this, overrides stop at the Link and never reach the target's dependency edges.
+  recalculateOutEdgesOverrides () {
```
Comment (wraithgar) [inline workspaces/arborist/lib/link.js:114]: This is only used in tests which means it's probably something we don't want to exist

Comment (manzoorwanijk) [reply workspaces/arborist/lib/link.js:114]: This is called from production code via polymorphic dispatch. The call chain is:

1. [`Node.addEdgeIn`](https://github.com/npm/cli/blob/05dbba5b8d727ddb2c098ce0553714eae791c5f2/workspaces/arborist/lib/node.js#L1488) calls `this.updateOverridesEdgeInAdded(edge.overrides)`
2. [`Node.updateOverridesEdgeInAdded`](https://github.com/npm/cli/blob/05dbba5b8d727ddb2c098ce0553714eae791c5f2/workspaces/arborist/lib/node.js#L1460-L1462) calls `this.recalculateOutEdgesOverrides()`
3. When `this` is a Link instance, the override in [`link.js:114`](https://github.com/npm/cli/blob/05dbba5b8d727ddb2c098ce0553714eae791c5f2/workspaces/arborist/lib/link.js#L114) is dispatched

This happens whenever an edge resolves to a Link node — e.g. in the linked strategy, root's edge to a package in `node_modules/` points to a Link (symlink into `.store/`). The base [`Node.recalculateOutEdgesOverrides`](https://github.com/npm/cli/blob/05dbba5b8d727ddb2c098ce0553714eae791c5f2/workspaces/arborist/lib/node.js#L1411-L1418) iterates `this.edgesOut`, but Links have no `edgesOut` (their targets do), so without this override the propagation silently stops.

The test calls it directly only to cover the `target === null` guard branch.

Comment (wraithgar) [reply workspaces/arborist/lib/link.js:114]: Ah ok.  Thanks for following the chain through.

**Comment by wraithgar** [comment]
We are waiting to land any PRs until node ships with a newer version of the cli.  CI should be green when that happens.

**Comment by manzoorwanijk** [comment]
CI is now green.

File: workspaces/arborist/lib/arborist/build-ideal-tree.js [hunk 2]
```diff
@@ -1507,32 +1503,6 @@ This is a one-time fix-up, please be patient...
     timeEnd()
   }
 
-  #applyRootOverridesToWorkspaces (tree) {
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/build-ideal-tree.js:1510]: Just to be clear, this code was a bandage over the larger issue that's being fixed here, since workspaces are links themselves. Now that the bug is fixed workspaces should also have overrides applied correctly, right?

Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/build-ideal-tree.js:1510]: Yes, exactly. Workspaces are Links, so they had the same problem — overrides reached the Link but not its target (which holds the `edgesOut`).

`#applyRootOverridesToWorkspaces` worked around this by detaching workspace edges where `edge.spec` (which returned the raw spec since overrides never propagated) didn't match root's resolved version. With the fix, workspace edges now have the correct overridden spec, so the `semver.satisfies` check always passes and the detach path is dead code.

The updated [load-virtual snapshot](https://github.com/npm/cli/pull/9198/files#diff-ce9e8a498cbe160700e5ef5e498e7dd974d63ef0bb7f0e8d0cdf14bda36fb4f0) confirms this: the `workspaces-with-overrides` fixture now shows `"override": "4.1.3"` instead of `"error": "INVALID"`.

**Review by wraithgar — APPROVED** [review]
