### PR TITLE
fix: Remove duplicates in config warnings

### LINKED ISSUE #6404: [BUG] npm invalid config warning duplicates lock file version
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If you have `lockfile-version=5` by mistake (or anything other than missing, 1, 2 or 3) in the .npmrc, npm warnings/errors show a non-uniq list of error cases - null, 1, 2, 3, 1, 2, 3

```
npm WARN invalid config lockfile-version="5" set in /Users/REDACTED/REDACTED/REDACTED-website/.npmrc
npm WARN invalid config Must be one of: null, 1, 2, 3, 1, 2, 3
npm ERR! Invalid lockfileVersion config: 5
```

### Expected Behavior

Should uniq, and return just null, 1, 2, 3

```
npm WARN invalid config lockfile-version="5" set in /Users/REDACTED/REDACTED/REDACTED-website/.npmrc
npm WARN invalid config Must be one of: null, 1, 2, 3
npm ERR! Invalid lockfileVersion config: 5
```

### Steps To Reproduce

With npm 9.6.5

have a package.json and an .npmrc
in the .npmrc, have this

```
lockfile-version=5
```

run npm install

Get the warning

### Environment

- npm: 9.6.5
- Node.js: v18.16.0
- OS Name: Mac

### PR DESCRIPTION
**Pull request by kashyapkaki**
While updating `lockfileVersion` other than the values `null,1,2,3` it's showing a warning with duplicate lock file versions as below.

image

Issue exists in definitions of config utils. I removed the duplicates to fix this issue. Please review and let me know your feedback.
## References

Fixes #6404

### CODE REVIEW

File: lib/utils/config/definitions.js [hunk 1]
```diff
@@ -1239,7 +1239,7 @@ define('location', {
 
 define('lockfile-version', {
   default: null,
-  type: [null, 1, 2, 3, '1', '2', '3'],
+  type: [null, 1, 2, 3],
```
Comment (ljharb) [inline lib/utils/config/definitions.js]: they aren’t duplicates, they’re strings vs numbers.

Comment (wraithgar) [reply lib/utils/config/definitions.js]: Yeah without making a custom data type this has to stay like it is.  We have to support both npmrc file entries which are typed, and cli input which is only ever strings.

Comment (wraithgar) [reply lib/utils/config/definitions.js]: The log warning would be where this could be cleaned up, if at all.

Comment (kashyapkaki) [reply lib/utils/config/definitions.js]: @wraithgar @ljharb 
Thank you for reviewing and feedback. Apologies for misunderstanding the use of `type` here. Now I'm clear on that. However, where should I look for the log warnings? As I'm new to this repo, could you please guide me to look into the correct path?

Comment (wraithgar) [reply lib/utils/config/definitions.js]: Sure thing. It's https://github.com/npm/cli/blob/baae2d60109c3362c38ad09c231a32c84c26f63a/workspaces/config/lib/index.js#L535-L538

Bonus points for every ternary you remove from `invalidHandler` in general.

Comment (kashyapkaki) [reply lib/utils/config/definitions.js]: Hi @wraithgar, have updated the log warning as suggested and reverted back that definition type changes. Also have refactored some of the ternary code. Please review and let me know your comments. Thank you!

**Comment by wraithgar** [comment]
`npm run lintfix` should get things cleaned up automatically for you.

File: workspaces/config/lib/index.js [hunk 2]
```diff
@@ -523,22 +523,33 @@ class Config {
...
-      : mustBe.filter(m => m !== Array)
-        .map(n => typeof n === 'string' ? n : JSON.stringify(n))
-        .join(', ')
+      : [...new Set(mustBe.map(n => typeof n === 'string' ? n : JSON.stringify(n)))].join(', ');
     log.warn('invalid config', msg, desc)
   }
 
+  getOneOfKeywords (mustBe, typeDesc) {
+    let keyword;
+    switch (true) {
```
Comment (wraithgar) [inline workspaces/config/lib/index.js]: We don't have too many switch statements and tend not to make new ones.  A series of early returning `if` statements would be more appropriate here to be inline with how we do things elsewhere.

File: workspaces/config/lib/index.js [hunk 3]
```diff
@@ -523,22 +523,33 @@ class Config {
...
+    const msg = 'Must be' + this.getOneOfKeywords(mustBe,typeDesc);
     const desc = mustBe.length === 1 ? mustBe[0]
-      : mustBe.filter(m => m !== Array)
-        .map(n => typeof n === 'string' ? n : JSON.stringify(n))
-        .join(', ')
+      : [...new Set(mustBe.map(n => typeof n === 'string' ? n : JSON.stringify(n)))].join(', ');
     log.warn('invalid config', msg, desc)
   }
 
+  getOneOfKeywords (mustBe, typeDesc) {
```
Comment (wraithgar) [inline workspaces/config/lib/index.js]:
```suggestion
  #getOneOfKeywords (mustBe, typeDesc) {
```

File: workspaces/config/lib/index.js [hunk 4]
```diff
@@ -523,22 +523,33 @@ class Config {
...
+    const typeDesc = typeDescription(type);
     const mustBe = typeDesc
-      .filter(m => m !== undefined && m !== Array)
-    const oneOf = mustBe.length === 1 && oneOrMore ? ' one or more'
-      : mustBe.length > 1 && oneOrMore ? ' one or more of:'
-      : mustBe.length > 1 ? ' one of:'
-      : ''
-    const msg = 'Must be' + oneOf
+      .filter(m => m !== undefined && m !== Array);
+    const msg = 'Must be' + this.getOneOfKeywords(mustBe,typeDesc);
```
Comment (wraithgar) [inline workspaces/config/lib/index.js]:
```suggestion
    const msg = 'Must be' + this.#getOneOfKeywords(mustBe,typeDesc);
```

**Comment by wraithgar** [comment]
This is a great start.  Typically single use functions are discouraged because of the extra mental load it takes to follow but I think it's probably appropriate here due to all the branching paths it takes.

Just two small suggestions, linting, and it looks good.

Can you run `npm run snap` in the main cli too?  At least *some* test should change here I would hope.

**Comment by kashyapkaki** [comment]
@wraithgar 
When ever I run any command, it's showing me below error. 

ERROR: npm v9.6.6 is known not to run on Node.js v18.16.0.  This version of npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`.

My configurations as below.
Node version : v18.16.0
NPM version : 9.6.6

Not sure, what is the correct node and npm versions compatible to run the application. Could you please guide me on that?

File: workspaces/config/lib/index.js (hunk 2 above)
Comment (kashyapkaki) [reply workspaces/config/lib/index.js]: @wraithgar So, should I change this logic to `if` statements instead of `switch`?

**Comment by kashyapkaki** [comment]
Hi @wraithgar, have addressed those small suggestions and fixed linting issues as well.

I did ran `npm run snap` command, here are the results below.

image

I can see 4 tests failed in publish.js. However, these tests are failing even without my changes. So, please suggest me what to do on this.

**Comment by wraithgar** [comment]
That's fine, we'll dig into any missing test coverage on this if we need to later.  Tested locally and it looks like it should, and other config tests hit those lines already so we have coverage.

File: workspaces/config/lib/index.js [hunk 5]
```diff
@@ -524,21 +524,28 @@ class Config {
...
-        .join(', ')
+      : [...new Set(mustBe.map(n => typeof n === 'string' ? n : JSON.stringify(n)))].join(', ')
     log.warn('invalid config', msg, desc)
   }
 
+  #getOneOfKeywords (mustBe, typeDesc) {
+    let keyword
+    if (mustBe.length === 1 && typeDesc.indexOf(Array) !== -1) {
+      keyword = ' one or more'
+    } else if (mustBe.length > 1 && typeDesc.indexOf(Array) !== -1) {
```
Comment (wraithgar) [inline workspaces/config/lib/index.js]: One last thing I missed in that switch statement.  We can use `.includes` now thanks to our engines declaration.

```suggestion
    if (mustBe.length === 1 && typeDesc.includes(Array)) {
      keyword = ' one or more'
    } else if (mustBe.length > 1 && typeDesc.includes(Array)) {
```

**Comment by wraithgar** [comment]
Sorry I missed that indexOf/includes suggestion before. That should be the last thing.

**Comment by kashyapkaki** [comment]
Hi @wraithgar, have addressed the above changes. Please review and let me know. Thank you!

**Review by wraithgar — APPROVED** [review]
