### PR TITLE
fix: resolve relative file: dependencies correctly with install-strategy=linked

### LINKED ISSUE #7549: [BUG] incorrect resolution of relative paths with install-strategy=linked
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have a package with a relative path dependency.

File `/Users/dan/Source/project1/package.json`
```json
{
  "dependencies": {
    "project2": "file:./project2"
  }
}
```

And the file `/Users/dan/Source/project1/project2/package.json` exists.

This installs fine with every install strategy *except* linked where I receive the below error:

```console
$ npm install --install-strategy linked
npm warn reify The "linked" install strategy is EXPERIMENTAL and may contain bugs.
npm warn tarball tarball data for project2@file:../project2 (null) seems to be corrupted. Trying again.
npm warn tarball tarball data for project2@file:../project2 (null) seems to be corrupted. Trying again.
npm error code ENOENT
npm error syscall open
npm error path /Users/dan/Source/project2/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/dan/Source/project2/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /Users/dan/.npm/_logs/2024-05-22T02_17_21_083Z-debug-0.log
```

Note that:
1. The error mentions `project2@file:../project2`, which is *not* the depended path.
2. The path that it's looking for package.json is at `/Users/dan/Source/project2/package.json`, NOT `/Users/dan/Source/project1/project2/package.json`

### Expected Behavior

The package should install correctly.

### Steps To Reproduce

see above

### Environment

- npm: 10.8.0
- Node.js: 22.2.0
- OS Name: macOS
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

### PR DESCRIPTION
**Pull request by manzoorwanijk**
In continuation of our exploration of using `install-strategy=linked` in the [Gutenberg monorepo](https://github.com/WordPress/gutenberg/pull/75814), which powers the WordPress Block Editor, this is a follow up of the fixes from #8996.

When using `install-strategy=linked`, relative `file:` dependencies (e.g., `file:./project2`) fail with ENOENT because the path is resolved one level above the project root. For example, `file:./project2` becomes `file:../project2`, causing npm to look for `/Users/dan/Source/project2` instead of `/Users/dan/Source/project1/project2`.

In the isolated reifier, non-workspace `file:` dependencies are incorrectly classified as "external" dependencies. This routes them through the store extraction path (`pacote.extract`) instead of symlinking them directly like workspaces. A Link node's `resolved` value is relative to its `node_modules/` location — that relative path becomes invalid when used from the store context.

This PR treats local `file:` dep targets found in `fsChildren` as local dependencies (alongside workspaces) so they get symlinked directly instead of extracted into the store:

- **`_makeIdealGraph`**: Skip nodes from `root.external` if they (or their Link target) are in `idealTree.fsChildren`.
- **`assignCommonProperties`**: Classify deps whose targets are in `node.fsChildren` as local dependencies instead of external.

## References

Fixes #7549

### CODE REVIEW

File: workspaces/arborist/lib/arborist/isolated-reifier.js [hunk 1]
```diff
@@ -67,6 +67,10 @@ module.exports = cls => class IsolatedReifier extends cls {
     root.workspaces = await Promise.all(
       Array.from(idealTree.fsChildren.values(), this.workspaceProxyMemo))
     const processed = new Set()
+    // local file: deps are in fsChildren but are not workspaces.
+    // they are already handled as workspace-like proxies above and
+    // should not go through the external/store extraction path.
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/isolated-reifier.js]:
```suggestion
    // local `file:` deps are in fsChildren but are not workspaces.
    // they are already handled as workspace-like proxies above and should not go through the external/store extraction path.
```

File: workspaces/arborist/lib/arborist/isolated-reifier.js [hunk 2]
```diff
@@ -160,8 +164,13 @@ module.exports = cls => class IsolatedReifier extends cls {
       }
     }
 
-    result.localDependencies = await Promise.all(nonOptionalDeps.filter(n => n.isWorkspace).map(this.workspaceProxyMemo))
-    result.externalDependencies = await Promise.all(nonOptionalDeps.filter(n => !n.isWorkspace && !n.inert).map(this.externalProxyMemo))
+    // local file: deps (non-workspace fsChildren) should be treated as
+    // local dependencies, not external, so they get symlinked directly
+    // instead of being extracted into the store.
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/isolated-reifier.js]:
```suggestion
    // local file: deps (non-workspace fsChildren) should be treated as local dependencies, not external, so they get symlinked directly instead of being extracted into the store.
```

File: workspaces/arborist/test/isolated-mode.js [hunk 3]
```diff
@@ -1693,6 +1693,51 @@ tap.test('bins are installed', async t => {
   t.ok(binFromBarToWhich)
 })
 
+tap.test('file: dependency with linked strategy', async t => {
+  /*
+   * Regression test for https://github.com/npm/cli/issues/7549
+   *
+   * A relative file: dependency (file:./project2) was incorrectly
+   * resolved as file:../project2, causing ENOENT errors because
+   * the path was resolved one level above the project root.
```
Comment (manzoorwanijk) [inline workspaces/arborist/test/isolated-mode.js]:
```suggestion
   * A relative file: dependency (file:./project2) was incorrectly resolved as file:../project2, causing ENOENT errors because the path was resolved one level above the project root.
```

File: workspaces/arborist/lib/arborist/isolated-reifier.js [hunk 4]
```diff
@@ -67,6 +67,10 @@ module.exports = cls => class IsolatedReifier extends cls {
     root.workspaces = await Promise.all(
       Array.from(idealTree.fsChildren.values(), this.workspaceProxyMemo))
     const processed = new Set()
+    // local file: deps are in fsChildren but are not workspaces.
+    // they are already handled as workspace-like proxies above and
+    // should not go through the external/store extraction path.
+    const localFsChildren = new Set(idealTree.fsChildren)
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/isolated-reifier.js]: This is already a set. Does `idealTree.fsChildren` mutate?  Why do we need a copy?

File: workspaces/arborist/lib/arborist/isolated-reifier.js [hunk 5]
```diff
@@ -160,8 +163,11 @@ module.exports = cls => class IsolatedReifier extends cls {
       }
     }
 
-    result.localDependencies = await Promise.all(nonOptionalDeps.filter(n => n.isWorkspace).map(this.workspaceProxyMemo))
-    result.externalDependencies = await Promise.all(nonOptionalDeps.filter(n => !n.isWorkspace && !n.inert).map(this.externalProxyMemo))
+    // local file: deps (non-workspace fsChildren) should be treated as local dependencies, not external, so they get symlinked directly instead of being extracted into the store.
+    const fsChildSet = new Set(node.fsChildren)
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/isolated-reifier.js]: Same question as before, does `node.fsChildren` mutate?

**Comment by wraithgar** [comment]
manually applied just the code changes to my refactor branch and tests all passed.


```
$ git diff
diff --git a/workspaces/arborist/lib/arborist/isolated-reifier.js b/workspaces/arborist/lib/arborist/isolated-reifier.js
index 4fafe7736..dd0adb954 100644
--- a/workspaces/arborist/lib/arborist/isolated-reifier.js
+++ b/workspaces/arborist/lib/arborist/isolated-reifier.js
@@ -100,6 +100,9 @@ module.exports = cls => class IsolatedReifier extends cls {
 
     this.idealGraph.workspaces = await Promise.all(Array.from(idealTree.fsChildren.values(), w => this.workspaceProxy(w)))
     const processed = new Set()
+    // local `file:` deps are in fsChildren but are not workspaces.
+    // they are already handled as workspace-like proxies above and should not go through the external/store extraction path.
+    const localFsChildren = new Set(idealTree.fsChildren)
     const queue = [idealTree, ...idealTree.fsChildren]
     while (queue.length !== 0) {
       const next = queue.pop()
@@ -112,7 +115,7 @@ module.exports = cls => class IsolatedReifier extends cls {
           queue.push(edge.to)
         }
       })
-      if (!next.isProjectRoot && !next.isWorkspace && !next.inert) {
+      if (!next.isProjectRoot && !next.isWorkspace && !next.inert && !localFsChildren.has(next) && !localFsChildren.has(next.target)) {
         this.idealGraph.external.push(await this.externalProxy(next))
       }
     }
@@ -208,8 +211,11 @@ module.exports = cls => class IsolatedReifier extends cls {
 
     if (populateDeps) {
       const optionalDeps = edges.filter(edge => edge.optional).map(edge => edge.to.target)
-      result.localDependencies = await Promise.all(nonOptionalDeps.filter(n => n.isWorkspace).map(n => this.workspaceProxy(n)))
-      result.externalDependencies = await Promise.all(nonOptionalDeps.filter(n => !n.isWorkspace && !n.inert).map(n => this.externalProxy(n)))
+      // local file: deps (non-workspace fsChildren) should be treated as local dependencies, not external, so they get symlinked directly instead of being extracted into the store.
+      const fsChildSet = new Set(node.fsChildren)
+      const isLocal = (n) => n.isWorkspace || fsChildSet.has(n)
+      result.localDependencies = await Promise.all(nonOptionalDeps.filter(isLocal).map(n => this.workspaceProxy(n)))
+      result.externalDependencies = await Promise.all(nonOptionalDeps.filter(n => !isLocal(n) && !n.inert).map(n => this.externalProxy(n)))
       result.externalOptionalDependencies = await Promise.all(optionalDeps.filter(n => !n.inert).map(n => this.externalProxy(n)))
       result.dependencies = [
         ...result.externalDependencies,
```

File: workspaces/arborist/lib/arborist/isolated-reifier.js (hunk 4 above)
Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js]: Looking a bit deeper, there is no mutation and we don't need a copy. Will fix. Thank you.

Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js]: Updated.

File: workspaces/arborist/lib/arborist/isolated-reifier.js (hunk 5 above)
Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/isolated-reifier.js]: Updated.

**Comment by wraithgar** [comment]
We landed the refactor which means it's time to resolve conflicts.  If you're comfortable doing that go ahead.  If you're not just let us know and we'll help.

**Review by wraithgar — APPROVED** [review]
