### PR TITLE
fix(arborist): avoid full reinstall on subsequent linked strategy runs

### LINKED ISSUE #6100: [BUG] Subsequent runs of `npm install --install-strategy=linked` are slow
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running `npm install --install-strategy=linked` immediately following an invocation of the same command isn't as fast as the default hoisted mode. It appears to be running a clean installation of the entire package tree each time.

This also seems to impact adding packages, which means that adding a package takes as much time as installing without a `node_modules` folder.

### Expected Behavior

Subsequent calls to `npm install --install-strategy=linked` don't do as much work as the initial call, resulting in a faster run.

### Steps To Reproduce

[Reproduction](https://github.com/dstaley/npm-linked-slow-install)

1. `npm install` (to prime the local cache)
2. `rm -rf node_modules && time npm install --install-strategy=linked`
3. `time npm install --install-strategy=linked`
4. `rm -rf node_modules && time npm install`
5. `time npm install`

### Environment

- npm: 9.4.0
- Node.js: v16.19.0
- OS Name: Linux
- System Model Name: N/A
- npm config:
```ini
; node bin location = /usr/bin/node
; node version = v16.19.0
; npm local prefix = /home/dstaley/git/dstaley/npm-linked-slow-install
; npm version = 9.4.0
; cwd = /home/dstaley/git/dstaley/npm-linked-slow-install
; HOME = /home/dstaley
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by manzoorwanijk**
In continuation of our exploration of using `install-strategy=linked` in the [Gutenberg monorepo](https://github.com/WordPress/gutenberg/pull/75814), which powers the WordPress Block Editor, this is a follow-up of the fixes from #8996.

Running `npm install --install-strategy=linked` a second time (with nothing changed) performs a full reinstall instead of recognizing everything is up-to-date. This is because the flat proxy tree built by `_createIsolatedTree()` doesn't match the nested actual tree from `loadActual()`, so the diff marks every package as needing work.

There are a few things going wrong:

1. Proxy link objects created in `processDeps()` were missing `version`, so the diff always saw a version mismatch (`undefined !== "4.1.2"`) and marked every top-level link as CHANGE.

2. Proxy links used the registry tarball URL for `resolved`, but actual links loaded from disk have `file:.store/...` URLs. Even with version fixed, the resolved mismatch triggered CHANGE.

3. The proxy tree is flat — all store entries and links are direct children of root. But `loadActual()` produces a nested tree where store entries are deep link targets, not visible to `allChildren(actual)`. So every store entry looked like an ADD.

4. `binPaths` were computed one directory level too deep (`join(from.realpath, 'node_modules', '.bin', bn)` instead of `join(nmFolder, '.bin', bn)`), so the bin existence check always failed for store entries with bins.

The fix:

- Set `version` and correct `resolved` on proxy link objects in `isolated-reifier.js`
- Fix `binPaths` to point at the right directory level
- Add `#buildLinkedActualForDiff()` in `reify.js` that wraps the actual tree with synthetic entries for store nodes and store links that already exist on disk, so the diff can match them

On a project with 20 direct deps (457 total nodes), a second `npm install --install-strategy=linked` now reports "up to date" in ~0.2s instead of reinstalling everything in ~1.5s.

This fix also surfaced a related gap: because the old code always did a full reinstall, it inadvertently cleaned up the `.store/` directory on every run. With subsequent installs now correctly skipping unchanged packages, old store entries from updated or removed dependencies would accumulate on disk. A new `#cleanOrphanedStoreEntries()` method is added to scan `node_modules/.store/` after each linked install and remove any directories not referenced by the current ideal tree.

## References

Fixes #6100

### CODE REVIEW

**Comment by wraithgar** [comment]
We landed the refactor which means it's time to resolve conflicts.  If you're comfortable doing that go ahead.  If you're not just let us know and we'll help.

File: workspaces/arborist/lib/arborist/reify.js [hunk 1]
```diff
@@ -426,9 +433,15 @@ module.exports = cls => class Reifier extends cls {
           if (ideal) {
             filterNodes.push(ideal)
           }
-          const actual = this.actualTree.children.get(ws)
-          if (actual) {
-            filterNodes.push(actual)
+          // Skip actual-side filterNodes when using the linked diff wrapper —
+          // those nodes have root===actualTree, not root===linkedActualForDiff,
+          // and Diff.calculate requires filterNode.root to match actual.
+          // The ideal filterNode alone is sufficient to scope the workspace diff.
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/reify.js]:
```suggestion
          // Skip actual-side filterNodes when using the linked diff wrapper.
          // Those nodes have root===actualTree, not root===linkedActualForDiff, and Diff.calculate requires filterNode.root to match actual.
          // The ideal filterNode alone is sufficient to scope the workspace diff.
```

File: workspaces/arborist/lib/arborist/reify.js [hunk 2]
```diff
@@ -573,6 +586,7 @@ module.exports = cls => class Reifier extends cls {
       // if the directory already exists, made will be undefined. if that's the case
       // we don't want to remove it because we aren't the ones who created it so we
       // omit it from the #sparseTreeRoots
+      /* istanbul ignore next -- mkdir returns path only when dir is new */
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/reify.js]: This ignore is a little scary.  Is `made` always `true` or `false` in tests?

File: workspaces/arborist/lib/arborist/reify.js (hunk 1 above)
Comment (wraithgar) [reply workspaces/arborist/lib/arborist/reify.js]: The rest of the comments added need unwrapping too. I'll not put suggestions on all of them, and let you fix them up.

File: workspaces/arborist/lib/arborist/reify.js [hunk 3]
```diff
@@ -789,6 +803,104 @@ module.exports = cls => class Reifier extends cls {
     return join(filePath)
   }
 
+  // Build a flat actual tree wrapper for linked installs so the diff can
+  // correctly match store entries that already exist on disk. The proxy
+  // tree from _createIsolatedTree() is flat (all children on root), but
+  // loadActual() produces a nested tree where store entries are deep link
+  // targets. This wrapper surfaces them at the root level for comparison.
+  #buildLinkedActualForDiff (idealTree, actualTree) {
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/reify.js:806]: This *feels* like it should be in the isolated reifier file, but I can appreciate that putting it here is cleaner for where the concerns are separated.

Not sure if this is actionable now but I am filing this away for later when we try to unpack the "6 files all extending one class" model.

File: workspaces/arborist/lib/arborist/reify.js (hunk 1 above)
Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/reify.js]: Yes, will update. Thanks

File: workspaces/arborist/lib/arborist/reify.js (hunk 2 above)
Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/reify.js]: `made` is covered in both directions when running `test/arborist/reify.js` alone (this line doesn't appear in its uncovered list), but shows as uncovered in the aggregate tap run — likely a nyc coverage merge artifact across test processes. The branch itself is pre-existing and not introduced by this PR; our new branches just shifted the denominator enough to make it visible. I will update the comment there. Happy to make any adjustments if needed.

File: workspaces/arborist/lib/arborist/reify.js (hunk 3 above)
Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/reify.js:806]: Agreed, it does feel like it belongs there. Kept it in `reify.js` for now since it needs access to `#linkedActualForDiff` and the diff wiring, but happy to move it when the class hierarchy gets reworked.

File: workspaces/arborist/lib/arborist/reify.js (hunk 2 above)
Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/reify.js]: Updated the comment in https://github.com/npm/cli/pull/9031/commits/e0f909f81761d061d411a2daea7a8400bf3a0c09

Comment (wraithgar) [reply workspaces/arborist/lib/arborist/reify.js]: Thanks for the due diligence research. All ok.

File: workspaces/arborist/lib/arborist/reify.js [hunk 4]
```diff
@@ -1245,6 +1352,41 @@ module.exports = cls => class Reifier extends cls {
     timeEnd()
   }
 
+  // After a linked install, scan node_modules/.store/ and remove any directories that are not referenced by the current ideal tree.
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/reify.js:1355]: This is gonna help immensely with [this future TODO](https://github.com/npm/cli/blob/16fbe135b86908426ffb8d4caa73e66cd7a679b1/workspaces/arborist/lib/arborist/isolated-reifier.js#L23)

**Review by wraithgar — APPROVED** [review]

**Comment by wraithgar** [comment]
The code here looks good.  All I see are future TODOs built around all these "pretend" links and nodes we are generating.
