### PR TITLE
fix: never use cached npm ping request

### LINKED ISSUE #5870: [BUG] `npm ping` uses cache when registry is offline
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When using `npm ping` to check if a private registry was online, I noticed that it would claim a successful response after approximately 70000ms when the registry was definitely offline.  I'm not sure if it's currently possible to configure the timeout period, but it would be very useful to be able to do so.

The private registry was a [Verdaccio](https://verdaccio.org/) registry hosted on the local machine (launched with `verdaccio --listen 127.0.0.1:4873`), although I'm not sure this is of relevance for this issue.

Suspecting that there might be some sort of caching involved, I ran `npm cache ls`, which confirmed there was an entry in there for the ping request.

Interestingly, after cleaning the entry out of the cache, the next `npm ping` call still succeeds.  It is only the subsequent ones (after the first ping since removing the entry from the cache) which fail as they should.

The commands and their output demonstrating the problem:

### 1) npm ping where the private registry is online:
`npm ping --registry=http://127.0.0.1:4873/ --verbose`
```
npm verb cli C:\Program Files\nodejs\node.exe C:\Users\<REDACTED>\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@9.1.2
npm info using node@v18.12.1
npm verb title npm ping
npm verb argv "ping" "--registry" "http://127.0.0.1:4873/" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_05_12_706Z-
npm verb logfile C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_05_12_706Z-debug-0.log
npm notice PING http://127.0.0.1:4873/
npm http fetch GET 200 http://127.0.0.1:4873/-/ping?write=true 33ms (cache miss)
npm notice PONG 35ms
npm verb exit 0
npm info ok
```

### 2) npm ping where the private registry is offline:
`npm ping --registry=http://127.0.0.1:4873/ --verbose`
```
npm verb cli C:\Program Files\nodejs\node.exe C:\Users\<REDACTED>\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@9.1.2
npm info using node@v18.12.1
npm verb title npm ping
npm verb argv "ping" "--registry" "http://127.0.0.1:4873/" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_05_56_431Z-
npm verb logfile C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_05_56_431Z-debug-0.log
npm notice PING http://127.0.0.1:4873/
npm http fetch GET 200 http://127.0.0.1:4873/-/ping?write=true 70061ms (cache stale)
npm notice PONG 70062ms
npm verb exit 0
npm info ok
```

### 3) npm cache clean the ping entry:
`npm cache clean make-fetch-happen:request-cache:http://127.0.0.1:4873/-/ping?write=true --verbose`
```
npm verb cli C:\Program Files\nodejs\node.exe C:\Users\<REDACTED>\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@9.1.2
npm info using node@v18.12.1
npm verb title npm cache clean make-fetch-happen:request-cache:http://127.0.0.1:4873/-/ping?write=true
npm verb argv "cache" "clean" "make-fetch-happen:request-cache:http://127.0.0.1:4873/-/ping?write=true" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_08_04_190Z-
npm verb logfile C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_08_04_190Z-debug-0.log
Deleted: make-fetch-happen:request-cache:http://127.0.0.1:4873/-/ping?write=true
npm verb exit 0
npm info ok
```

### 4) npm ping where the private registry is offline:
`npm ping --registry=http://127.0.0.1:4873/ --verbose`
```
npm verb cli C:\Program Files\nodejs\node.exe C:\Users\<REDACTED>\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@9.1.2
npm info using node@v18.12.1
npm verb title npm ping
npm verb argv "ping" "--registry" "http://127.0.0.1:4873/" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_09_01_885Z-
npm verb logfile C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_09_01_885Z-debug-0.log
npm notice PING http://127.0.0.1:4873/
npm notice PONG 70076ms
npm verb exit 0
npm info ok
```

### 5) npm ping where the private registry is offline:
`npm ping --registry=http://127.0.0.1:4873/ --verbose`
```
npm ping --registry=http://127.0.0.1:4873/ --verbose
npm verb cli C:\Program Files\nodejs\node.exe C:\Users\<REDACTED>\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@9.1.2
npm info using node@v18.12.1
npm verb title npm ping
npm verb argv "ping" "--registry" "http://127.0.0.1:4873/" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_10_51_182Z-
npm verb logfile C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_10_51_182Z-debug-0.log
npm notice PING http://127.0.0.1:4873/
npm verb type system
npm verb stack FetchError: request to http://127.0.0.1:4873/-/ping?write=true failed, reason: connect ECONNREFUSED 127.0.0.1:4873
npm verb stack     at ClientRequest.<anonymous> (C:\Users\<REDACTED>\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
npm verb stack     at ClientRequest.emit (node:events:513:28)
npm verb stack     at Socket.socketErrorListener (node:_http_client:494:9)
npm verb stack     at Socket.emit (node:events:525:35)
npm verb stack     at emitErrorNT (node:internal/streams/destroy:151:8)
npm verb stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm verb cwd C:\Users\<REDACTED>
npm verb Windows_NT 10.0.22621
npm verb node v18.12.1
npm verb npm  v9.1.2
npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to http://127.0.0.1:4873/-/ping?write=true failed, reason: connect ECONNREFUSED 127.0.0.1:4873
npm ERR!     at ClientRequest.<anonymous> (C:\Users\<REDACTED>\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:494:9)
npm ERR!     at Socket.emit (node:events:525:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!  FetchError: request to http://127.0.0.1:4873/-/ping?write=true failed, reason: connect ECONNREFUSED 127.0.0.1:4873
npm ERR!     at ClientRequest.<anonymous> (C:\Users\<REDACTED>\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:494:9)
npm ERR!     at Socket.emit (node:events:525:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 4873,
npm ERR!   type: 'system'
npm ERR! }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
npm verb exit 1
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<REDACTED>\AppData\Local\npm-cache\_logs\2022-11-18T16_10_51_182Z-debug-0.log
```

### Expected Behavior

`npm ping` responses should not be cached.  It should accurately report whether or not the specified registry is actually online, rather than returning a cached response after timing out.

### Steps To Reproduce

1. With the private registry **online**, run the following command: `npm ping --registry=http://127.0.0.1:4873/ --verbose`
2. Shut down the private registry.
3. With the private registry **offline**, run the following command: `npm ping --registry=http://127.0.0.1:4873/ --verbose`

### Environment

- **npm**: 9.1.2
- **Node.js**: 18.12.1
- **OS Name**: Windows 11 22H2 (OS Build 22621.674)
- **System Model Name**: N/A
- **npm config**:
```
; "builtin" config from C:\Users\<REDACTED>\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\<REDACTED>\\AppData\\Roaming\\npm"

; "cli" config from command line options

location = "project"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.12.1
; npm local prefix = C:\Users\<REDACTED>
; npm version = 9.1.2
; cwd = C:\Users\<REDACTED>
; HOME = C:\Users\<REDACTED>
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by milaninfy**
Ping: Don't use cache so ping does not report ping sucess incorrectly if it's offline or no internet
Doctor: Don't use cache for pinging the registry. 

Fixes: https://github.com/npm/cli/issues/5870, https://github.com/npm/cli/issues/3576, https://github.com/npm/cli/issues/4112

<details>
<summary>Testing of ping and doctor </summary>

```sh
# -- current npm last ping resuts in cached request replying PONG

~/workarea/npm-cli $ npm ping --registry=http://localhost:4873 -ddd
npm verbose cli /Users/milaninfy/.nvm/versions/node/v22.9.0/bin/node /Users/milaninfy/.nvm/versions/node/v22.9.0/bin/npm
npm info using npm@10.8.3
npm info using node@v22.9.0
npm silly config load:file:/Users/milaninfy/.nvm/versions/node/v22.9.0/lib/node_modules/npm/npmrc
npm silly config load:file:/Users/milaninfy/workarea/npm-cli/.npmrc
npm silly config load:file:/Users/milaninfy/.npmrc
npm silly config load:file:/Users/milaninfy/.nvm/versions/node/v22.9.0/etc/npmrc
npm verbose title npm ping
npm verbose argv "ping" "--registry" "http://localhost:4873" "--loglevel" "silly"
npm verbose logfile logs-max:10 dir:/Users/milaninfy/.npm/_logs/2024-09-26T20_37_04_583Z-
npm verbose logfile /Users/milaninfy/.npm/_logs/2024-09-26T20_37_04_583Z-debug-0.log
npm notice PING http://localhost:4873/
npm silly logfile start cleaning logs, removing 1 files
npm silly logfile done cleaning log files
npm http fetch GET http://localhost:4873/-/ping?write=true attempt 1 failed with ECONNREFUSED
npm http fetch GET http://localhost:4873/-/ping?write=true attempt 2 failed with ECONNREFUSED
npm http fetch GET http://localhost:4873/-/ping?write=true attempt 3 failed with ECONNREFUSED
npm http fetch GET 200 http://localhost:4873/-/ping?write=true 70045ms (cache stale)
npm notice PONG 70046ms
npm verbose cwd /Users/milaninfy/workarea/npm-cli
npm verbose os Darwin 23.6.0
npm verbose node v22.9.0
npm verbose npm  v10.8.3
npm verbose exit 0
npm info ok


# -- After the change npm last ping resuts in failure after retries

~/workarea/npm-cli $ lnpm ping --registry=http://localhost:4873 -ddd
npm verbose cli /Users/milaninfy/.nvm/versions/node/v22.9.0/bin/node /Users/milaninfy/workarea/npm-cli/index.js
npm info using npm@10.8.3
npm info using node@v22.9.0
npm silly config load:file:/Users/milaninfy/workarea/npm-cli/npmrc
npm silly config load:file:/Users/milaninfy/workarea/npm-cli/.npmrc
npm silly config load:file:/Users/milaninfy/.npmrc
npm silly config load:file:/Users/milaninfy/.nvm/versions/node/v22.9.0/etc/npmrc
npm verbose title npm ping
npm verbose argv "ping" "--registry" "http://localhost:4873" "--loglevel" "silly"
npm verbose logfile logs-max:10 dir:/Users/milaninfy/.npm/_logs/2024-09-26T20_38_51_059Z-
npm verbose logfile /Users/milaninfy/.npm/_logs/2024-09-26T20_38_51_059Z-debug-0.log
npm notice PING http://localhost:4873/
npm silly logfile start cleaning logs, removing 1 files
npm http fetch GET http://localhost:4873/-/ping?write=true attempt 1 failed with ECONNREFUSED
npm silly logfile done cleaning log files
npm http fetch GET http://localhost:4873/-/ping?write=true attempt 2 failed with ECONNREFUSED
npm http fetch GET http://localhost:4873/-/ping?write=true attempt 3 failed with ECONNREFUSED
npm verbose type system
npm verbose stack FetchError: request to http://localhost:4873/-/ping?write=true failed, reason: 
npm verbose stack     at ClientRequest.<anonymous> (/Users/milaninfy/workarea/npm-cli/node_modules/minipass-fetch/lib/index.js:130:14)
npm verbose stack     at ClientRequest.emit (node:events:519:28)
npm verbose stack     at emitErrorEvent (node:_http_client:103:11)
npm verbose stack     at _destroy (node:_http_client:886:9)
npm verbose stack     at onSocketNT (node:_http_client:906:5)
npm verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
npm error code ECONNREFUSED
npm error errno ECONNREFUSED
npm error FetchError: request to http://localhost:4873/-/ping?write=true failed, reason: 
npm error     at ClientRequest.<anonymous> (/Users/milaninfy/workarea/npm-cli/node_modules/minipass-fetch/lib/index.js:130:14)
npm error     at ClientRequest.emit (node:events:519:28)
npm error     at emitErrorEvent (node:_http_client:103:11)
npm error     at _destroy (node:_http_client:886:9)
npm error     at onSocketNT (node:_http_client:906:5)
npm error     at process.processTicksAndRejections (node:internal/process/task_queues:91:21) {
npm error   code: 'ECONNREFUSED',
npm error   errno: 'ECONNREFUSED',
npm error   type: 'system'
npm error }
npm error
npm error If you are behind a proxy, please make sure that the
npm error 'proxy' config is set properly.  See: 'npm help config'
npm verbose cwd /Users/milaninfy/workarea/npm-cli
npm verbose os Darwin 23.6.0
npm verbose node v22.9.0
npm verbose npm  v10.8.3
npm verbose exit 1
npm verbose code 1
npm error A complete log of this run can be found in: /Users/milaninfy/.npm/_logs/2024-09-26T20_38_51_059Z-debug-0.log





# -- npm doctor ping resuts in success due to cache hit


~/workarea/npm-cli $ npm doctor --registry=http://localhost:4873 -ddd
npm verbose cli /Users/milaninfy/.nvm/versions/node/v22.9.0/bin/node /Users/milaninfy/.nvm/versions/node/v22.9.0/bin/npm
npm info using npm@10.8.3
npm info using node@v22.9.0
npm silly config load:file:/Users/milaninfy/.nvm/versions/node/v22.9.0/lib/node_modules/npm/npmrc
npm silly config load:file:/Users/milaninfy/workarea/npm-cli/.npmrc
npm silly config load:file:/Users/milaninfy/.npmrc
npm silly config load:file:/Users/milaninfy/.nvm/versions/node/v22.9.0/etc/npmrc
npm verbose title npm doctor
npm verbose argv "doctor" "--registry" "http://localhost:4873" "--loglevel" "silly"
npm verbose logfile logs-max:10 dir:/Users/milaninfy/.npm/_logs/2024-09-26T20_40_30_672Z-
npm verbose logfile /Users/milaninfy/.npm/_logs/2024-09-26T20_40_30_672Z-debug-0.log
npm info doctor Running checkup
Connecting to the registry
npm info doctor Pinging registry
npm silly logfile start cleaning logs, removing 1 files
npm silly logfile done cleaning log files
npm http fetch GET http://localhost:4873/-/ping?write=true attempt 1 failed with ECONNREFUSED
npm http fetch GET 200 http://localhost:4873/-/ping?write=true 48ms (cache stale)
Ok



# -- after the changes npm doctor ping correctly resuts in failure after retires

~/workarea/npm-cli $ lnpm doctor --registry=http://localhost:4873 -ddd
npm verbose cli /Users/milaninfy/.nvm/versions/node/v22.9.0/bin/node /Users/milaninfy/workarea/npm-cli/index.js
npm info using npm@10.8.3
npm info using node@v22.9.0
npm silly config load:file:/Users/milaninfy/workarea/npm-cli/npmrc
npm silly config load:file:/Users/milaninfy/workarea/npm-cli/.npmrc
npm silly config load:file:/Users/milaninfy/.npmrc
npm silly config load:file:/Users/milaninfy/.nvm/versions/node/v22.9.0/etc/npmrc
npm verbose title npm doctor
npm verbose argv "doctor" "--registry" "http://localhost:4873" "--loglevel" "silly"
npm verbose logfile logs-max:10 dir:/Users/milaninfy/.npm/_logs/2024-09-26T20_41_05_904Z-
npm verbose logfile /Users/milaninfy/.npm/_logs/2024-09-26T20_41_05_904Z-debug-0.log
npm info doctor Running checkup
Connecting to the registry
npm info doctor Pinging registry
npm silly logfile start cleaning logs, removing 1 files
npm http fetch GET http://localhost:4873/-/ping?write=true attempt 1 failed with ECONNREFUSED
npm silly logfile done cleaning log files
npm http fetch GET http://localhost:4873/-/ping?write=true attempt 2 failed with ECONNREFUSED
npm http fetch GET http://localhost:4873/-/ping?write=true attempt 3 failed with ECONNREFUSED
Not ok
request to http://localhost:4873/-/ping?write=true failed, reason: 

```

</detail>

### CODE REVIEW

**Comment by wraithgar** [comment]
https://github.com/npm/cli/issues/4112#issuecomment-1265750820 Has more info on this bug.  This was originally "fixed" by adding a `?write=true` query to the request, which effectively already sets this config value of `cache: false`.  What ends up happening is that mode allows for stale responses to be returned on request failures (since it puts the mode into `no-store` which is different that a purely "no cache" mode).

The fix for this is gonna be a bit more than setting this flag.

**Comment by wraithgar** [comment]
Reopening, didn't see your testing there.  Looks like the `write=true` behavior is different than `cache: false`!


This should work.  This really should have a test though since we thought this was fixed already and it wasn't.

File: lib/commands/doctor.js [hunk 1]
```diff
@@ -139,7 +139,7 @@ class Doctor extends BaseCommand {
   async checkPing () {
     log.info('doctor', 'Pinging registry')
     try {
-      await ping({ ...this.npm.flatOptions, retry: false })
+      await ping({ ...this.npm.flatOptions, cache: false, retry: false })
```
Comment (wraithgar) [inline lib/commands/doctor.js]: This should go directly into `lib/utils/ping.js` instead of us having to remember to pass it in everywhere.

Comment (wraithgar) [reply lib/commands/doctor.js]: While we're in `lib/utils/ping.js` we should remove the `?write=true` since that doesn't actually address this bug.

Comment (milaninfy) [reply lib/commands/doctor.js]: Makes sense.. Initially I kept it separate because it's being used in two different places and incase we intended to use this for something else, but yes I'll add test and make a central change in `utils/ping.js`.

Comment (milaninfy) [reply lib/commands/doctor.js]: Removed `?write=true` in favour of `cache:false`

- `write=true` works for success response without disabling cache as it would sent options as `no-cache` in `make-fetch-happen` and forces it to revalidate the request, however when there is a ENOTFOUND error code it falls back to cached version of the response. ( from quick analysis )
- making `cache: false` will result in cache policy of `not storable`  making it new request and not the cached one.

File: test/lib/commands/ping.js [hunk 2]
```diff
@@ -74,3 +76,19 @@ t.test('invalid json', async t => {
     details: {},
   })
 })
+t.test('fail when registry is unreachable', async t => {
```
Comment (wraithgar) [inline test/lib/commands/ping.js]:
```suggestion
t.test('fail when registry is unreachable even if request is cached', async t => {
```

Comment (milaninfy) [reply test/lib/commands/ping.js]: 👍  Updated..

**Review by wraithgar — APPROVED** [review]
