### PR TITLE
fix!: remove old audit fallback request

### LINKED ISSUE #900: Remove npm audit fallback request
When the new audit endpoint was added, in order for the cli to ship it without having to wait for a new semver major it was done with a fallback to the old endpoint:

https://github.com/npm/cli/blob/63d6a732c3c0e9c19fd4d147eaa5cc27c29b168d/workspaces/arborist/lib/audit-report.js#L332-L345

As far as we can tell, nobody has implemented an audit endpoint that relies on the old URL, and the new one works just fine on the npm registry.

This code should be removed in a semver-major release of npm.

### PR DESCRIPTION
**Pull request by wraithgar**
BREAKING CHANGE: npm will no longer fall back to the old audit endpoint
if the bulk advisory request fails.

This legacy code has a long tail in npm.  Getting rid of it was
difficult because of how load-bearing some of those requests were in
tests.  This PR removes the old "mock server" that arborist tests spun
up, and moved that logic into the existing mock registry that the cli
uses.  This will allow us to consolidate our logic in tests, and also
outline more granularly which tests actually make registry requests.

A few tests that were testing just the fallback behavior were also
removed.

Closes: https://github.com/npm/statusboard/issues/900

### CODE REVIEW

**Comment by wraithgar** [comment]
Test coverage failures are due to two things:  Two functions which always get passed an object, and never get defaulted now, and uncovered lines in the packument cache because of missing headers in the mock registry.

File: mock-registry/lib/index.js [hunk 1]
```diff
@@ -66,14 +90,14 @@ class MockRegistry {
       // find mistakes quicker instead of waiting for the entire test to end
       t.afterEach((t) => {
         t.strictSame(server.pendingMocks(), [], 'no pending mocks after each')
-        t.strictSame(server.activeMocks(), [], 'no active mocks after each')
```
Comment (wraithgar) [inline mock-registry/lib/index.js:69]: According to nock's docs we almost certainly didn't want this, and the persistent mocks interceptor makes this fail.

File: workspaces/arborist/package.json [hunk 2]
```diff
@@ -82,7 +83,7 @@
     "test-env": [
       "LC_ALL=sk"
     ],
-    "timeout": "360",
+    "timeout": "720",
```
Comment (wraithgar) [inline workspaces/arborist/package.json:86]: My computer has security programs on it that make disk access painfully slow, this was the only way to get tests to pass locally for me.

File: mock-registry/lib/index.js [hunk 3]
```diff
@@ -453,6 +479,48 @@ class MockRegistry {
...
+      } else if (await exists(`${f}.json`)) {
+        file = `${f}.json`
+        contentType = 'application/json'
+      } else if (await exists(`${f}/index.json`)) {
+        file = `${f}index.json`
+        contentType = 'application/json'
+      }
+      const stats = await exists(file)
+      if (stats) {
+        const body = require('node:fs').createReadStream(file)
```
Comment (hashtagchris) [inline mock-registry/lib/index.js]: I prefer keeping the requires at the top of the file. You could use destructuring to reference `createReadStream` directly.

File: workspaces/arborist/test/arborist/audit.js [hunk 4]
```diff
@@ -29,7 +35,9 @@ t.test('audit finds the bad deps', async t => {
 
 t.test('no package lock finds no bad deps', async t => {
   const path = resolve(fixtures, 'deprecated-dep')
-  t.teardown(auditResponse(resolve(fixtures, 'audit-nyc-mkdirp/audit.json')))
```
Comment (hashtagchris) [inline workspaces/arborist/test/arborist/audit.js:32]: Should we generally avoid path strings with slashes in tests, and use `resolve` instead to traverse the path?

File: workspaces/arborist/test/arborist/build-ideal-tree.js [hunk 5]
```diff
@@ -4,34 +4,39 @@ if (process.platform === 'win32') {
...
   const list = []
   const onlog = (...msg) => msg[0] === 'warn' && list.push(msg)
   process.on('log', onlog)
-  return () => {
+  t.teardown(() => {
     process.removeListener('log', onlog)
-    return list
-  }
+  })
+  return () => list
```
Comment (hashtagchris) [inline workspaces/arborist/test/arborist/build-ideal-tree.js]: "returns a function" comment above is out of date now

**Review by hashtagchris — DISMISSED** [review]
LGTM. I think I'm able to follow the new `MockRegistry`-based code better than the old code.

File: scripts/dependency-graph.js [hunk 6]
```diff
@@ -11,6 +11,31 @@ const { run, CWD, pkg, fs, EOL } = require('./util.js')
 // npx -p @npmcli/stafftools gh repos --json | json -a name | sort > scripts/npm-cli-repos.txt
 const repos = readFileSync(join(CWD, 'scripts', 'npm-cli-repos.txt'), 'utf-8').trim().split(os.EOL)
 
+// Packages with known circular dependencies.  This is typically something with arborist as a dependency which is also in arborist's dev dependencies.  Not a problem if they're workspaces so we ignore repeats
+const circular = new Set(['@npmcli/mock-registry'])
```
Comment (hashtagchris) [inline scripts/dependency-graph.js:15]: Should we just ignore devDependencies in the dependency graph, rather than opening the door to allowing circular dependencies?

Also it looks to me like https://github.com/npm/cli/blob/latest/DEPENDENCIES.md only lists dev dependencies for packages in this repo. For example, I don't see `minipass-fetch-->npmcli-eslint-config["@npmcli/eslint-config"];` listed, despite https://github.com/npm/minipass-fetch/blob/e4df956af7c79cecc7dff8f3edb98cc263e0064c/package.json#L27.

File: mock-registry/lib/index.js (hunk 3 above)
Comment (wraithgar) [reply mock-registry/lib/index.js]: Good point, this was a last-minute change where I was testing if streams would even work.

File: scripts/dependency-graph.js (hunk 6 above)
Comment (wraithgar) [reply scripts/dependency-graph.js:15]: Yes, it only evaluates the tree in the cli itself.  We can have this discussion outside this issue, and it's probably a good idea.

File: workspaces/arborist/test/arborist/audit.js (hunk 4 above)
Comment (wraithgar) [reply workspaces/arborist/test/arborist/audit.js:32]: Yes, but these were copy/paste from the existing tests and I didn't want to scope creep. It was already quite a change in this PR

File: workspaces/arborist/test/arborist/reify.js [hunk 7]
```diff
@@ -122,64 +112,86 @@ const {
 
 const cwd = normalizePath(process.cwd())
 t.cleanSnapshot = s => s.split(cwd).join('{CWD}')
-  .split(registry).join('https://registry.npmjs.org/')
 
 const fixture = (t, p) => require('../fixtures/reify-cases/' + p)(t)
 
 const printReified = (path, opt) => reify(path, opt).then(printTree)
+const fixtures = join(__dirname, '..', 'fixtures')
+const createRegistry = (t, mocks) => {
```
Comment (reggi) [inline workspaces/arborist/test/arborist/reify.js:120]: *just a thought, no action required*

This is convenient on one hand but tedious to remember to include for each test on the other. I'd suggest in the future using a `beforeEach` (and when needed, scoping `registry` to `describe()`) and group tests by `describe()`, that way it wouldn't need to be defined every test. This is especially relevant if the test itself doesn't use the returned value. 

This would group the tests into four different types of `describe()` "buckets" :

1. `createRegistry(t, true)`
2. `createRegistry(t)`
3. `const registry = createRegistry(t)`
4. `const registry = createRegistry(t, true)`

And you'd never need to use this within the file again. There is a caveat for one of the below examples that calls this with a loop, that would need to be handled differently.

**Review by reggi — APPROVED** [review]
This is a much needed, heavy lift and is a really elegant way of mocking and handling the audit endpoints. Thanks for this! 👍 🚀

File: workspaces/arborist/test/arborist/reify.js (hunk 7 above)
Comment (wraithgar) [reply workspaces/arborist/test/arborist/reify.js:120]: I envisioned these mocks moving into the mock-registry folder and then being hard set when you called `registry.mocks`.  The changes in this PR were the smallest possible to get things moved over.
