### PR TITLE
fix: much clearer npx 'canceled' error

### LINKED ISSUE #6215: [BUG] npx 'canceled' error reason lacks clarity
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Using npm version 9.5.0 running the command:

```bash
npx --no-install esbuild --bundle "~/typescript-graphql-service/service/src/lambda.ts" --target=node18 --platform=node --outfile="~/typescript-graphql-service/AWS/cdk.out/bundling-temp-d2395ea5f5b16624b9255daf70671b29ee231644c99ea4f7718828f55c1a0f13/index.js" --external="@aws-sdk/*" --loader:.graphql=file
```

I get 

```bash
npm ERR! canceled

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lancegliser/.npm/_logs/2023-03-01T18_11_17_043Z-debug-0.log
```

### Expected Behavior

A more useful explanation of why it was cancelled. It was unclear what module was throwing an error or canceling at first.

```bash
npm ERR! npx canceled due to missing packages and no YES option: ["esbuild@0.17.10"]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lancegliser/.npm/_logs/2023-03-01T18_11_17_043Z-debug-0.log
```

### Steps To Reproduce

1. In a general termal
2. Without `esbuild` in path
3. Run `npx --no-install esbuild --bundle`
4. See error...

### Environment

- npm: 9.5.1
- Node.js: 18.13.0
- OS Name: MacOS 12.6.3
- System Model Name: Mackbook Pro
- npm config: 
```ini
; "user" config from /Users/lancegliser/.npmrc

init-author-name = "Lance Gliser" 

; node bin location = /usr/local/bin/node
; node version = v18.13.0
; npm local prefix = /Users/lancegliser
; npm version = 9.5.1
; cwd = /Users/lancegliser
; HOME = /Users/lancegliser
; Run `npm config ls -l` to show all defaults.```

### PR DESCRIPTION
**Pull request by rahulio96**
## Summary
Currently, when running npx --no-install on a package that is not installed will return a vague error message that says, “canceled.”

Added accompanying tap test to ensure the expected error is outputted.

This solution gives the error message more clarity to make debugging easier. 

image

### Reproduce Original Error:
- Enter in terminal:
    - ```npx --no-install <missing_package>```
Please Note: ```<missing_package>``` is either not installed or in path

### Tap Test (exec.js only)
- Enter in terminal:
    - ```node . run test test/lib/commands/exec.js```

### Run entire test:
- Enter in terminal:
    - ```node . run test```
    
### Alias Test
- Enter in terminal:
    - ```alias localnpx="node /workspaces/cli/bin/npx-cli.js"```  
    - ```localnpx --no-install esbuild```

## References
  Fixes #6215

### CODE REVIEW

File: workspaces/libnpmexec/lib/index.js [hunk 1]
```diff
@@ -245,9 +245,11 @@ const exec = async (opts) => {
 
     if (add.length) {
       if (!yes) {
+        const missingPackages = add.map(a => `${a.replace(/@$/, '')}`)
```
Comment (wraithgar) [inline workspaces/libnpmexec/lib/index.js:248]: What's the thinking behind stripping the `@` here?

Comment (wraithgar) [reply workspaces/libnpmexec/lib/index.js:248]: Oh I see this is stripping `foo@` which is what it normalizes to.

File: workspaces/libnpmexec/lib/index.js [hunk 2]
```diff
@@ -245,9 +245,11 @@ const exec = async (opts) => {
...
         // set -n to always say no
         if (yes === false) {
-          throw new Error('canceled')
+          // Error message lists missing package(s) when process is canceled
+          throw new Error(`npx canceled due to missing packages and no YES option: ${JSON.stringify(missingPackages)}`)
```
Comment (wraithgar) [inline workspaces/libnpmexec/lib/index.js:253]:
```suggestion
          /* eslint-disable-next-line max-len */
          throw new Error(`npx canceled due to missing packages and no YES option: ${JSON.stringify(missingPackages)}`)
```

**Comment by wraithgar** [comment]
Can you please add the max-len override for the thrown error, then run `npm run lintfix -w libnpmexec --include-workspace-root`

**Comment by AaronHamilton965** [comment]
Thanks for the feedback, we made the appropriate changes that you suggested!

**Review by wraithgar — APPROVED** [review]
Thank you

**Comment by DevBrent** [comment]
What does "no YES option" mean? How can you correct this if you encounter this error? What is the option you need to add?

**Comment by rahulio96** [comment]
The “no YES option” is what `--no-install` is doing. It means that npx will not install any missing packages and will try to run the command as is. If you are getting the `npx canceled due to missing packages and no YES option` error, it means you are missing the required packages/dependencies for the command to run properly. 

If you want your command to execute, instead of using `--no-install` try using `install` instead. If that does not work, try installing the missing packages mentioned in the error message using `npm install`.
