### PR TITLE
fix: clear exclusive param siblings when setting from CLI

### LINKED ISSUE #9005: [BUG] `min-release-age` config error if any dependencies use `~` version range
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

If any dependencies use a `~` version range, `min-release-age` seems to trigger an incorrect config ordering check:
* It correctly sets `--before` with the expected date
* But then fails with `--min-release-age cannot be provided when using --before` (even though `--min-release-age` does not appear in the list of arguments passed to `npm-cli.js`)

### Expected Behavior

Setting `min-release-age` (e.g. `npm install --min-release-age=2` or with `min-release-age=2` in `.npmrc`) without *explicitly* setting `--before` should not trigger the error under any circumstances.

### Steps To Reproduce

1. On any OS (tested AlmaLinux 9.7 and Windows 11)
2. With this package.json:
```json
{
  "name": "test",
  "private": true,
	"devDependencies": {
		"@vue/language-server": "~3.0.10"
	}
}
```
3. Run `npm install --min-release-age=2`
4. See the following error:
```
npm error code 1
npm error git dep preparation failed
npm error command /home/user/.nvm/versions/node/v24.13.1/bin/node /home/user/.nvm/versions/node/v24.13.1/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/user/.npm --prefer-offline=false --prefer-online=false --offline=false --before=2026-02-18T09:43:39.679Z --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm error Exit prior to config file resolving
npm error cause
npm error --min-release-age cannot be provided when using --before
npm error A complete log of this run can be found in: /home/user/.npm/_logs/2026-02-20T09_43_39_662Z-debug-0.log
```

Full log:
<details><summary>Details</summary>

```
0 verbose cli /home/user/.nvm/versions/node/v24.13.1/bin/node /home/user/.nvm/versions/node/v24.13.1/bin/npm
1 info using npm@11.10.1
2 info using node@v24.13.1
3 silly config load:file:/home/user/.nvm/versions/node/v24.13.1/lib/node_modules/npm/npmrc
4 silly config load:file:/path/of/test/.npmrc
5 silly config load:file:/home/user/.npmrc
6 silly config load:file:/home/user/.nvm/versions/node/v24.13.1/etc/npmrc
7 verbose title npm install
8 verbose argv "install" "--min-release-age" "2"
9 verbose logfile logs-max:10 dir:/home/user/.npm/_logs/2026-02-20T09_43_39_662Z-
10 verbose logfile /home/user/.npm/_logs/2026-02-20T09_43_39_662Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly packumentCache heap:4496293888 maxSize:1124073472 maxEntrySize:562036736
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest @vue/language-server@~3.0.10
16 silly packumentCache full:https://registry.npmjs.org/@vue%2flanguage-server cache-miss
17 http cache https://registry.npmjs.org/@vue%2flanguage-server 12ms (cache hit)
18 silly packumentCache full:https://registry.npmjs.org/@vue%2flanguage-server set size:212794 disposed:false
19 silly fetch manifest typescript@*
20 silly packumentCache full:https://registry.npmjs.org/typescript cache-miss
21 http cache https://registry.npmjs.org/typescript 49ms (cache hit)
22 silly packumentCache full:https://registry.npmjs.org/typescript set size:15268880 disposed:false
23 silly placeDep ROOT @vue/language-server@3.0.10 OK for:  want: ~3.0.10
24 silly placeDep ROOT typescript@5.9.3 OK for: @vue/language-server@3.0.10 want: *
25 silly fetch manifest vscode-uri@^3.0.8
26 silly packumentCache full:https://registry.npmjs.org/vscode-uri cache-miss
27 silly fetch manifest @vue/language-core@3.0.10
28 silly packumentCache full:https://registry.npmjs.org/@vue%2flanguage-core cache-miss
29 silly fetch manifest @vue/language-service@3.0.10
30 silly packumentCache full:https://registry.npmjs.org/@vue%2flanguage-service cache-miss
31 silly fetch manifest @volar/language-server@2.4.23
32 silly packumentCache full:https://registry.npmjs.org/@volar%2flanguage-server cache-miss
33 silly fetch manifest @vue/typescript-plugin@3.0.10
34 silly packumentCache full:https://registry.npmjs.org/@vue%2ftypescript-plugin cache-miss
35 http cache https://registry.npmjs.org/@vue%2flanguage-core 22ms (cache hit)
36 silly packumentCache full:https://registry.npmjs.org/@vue%2flanguage-core set size:228776 disposed:false
37 http cache https://registry.npmjs.org/@vue%2flanguage-service 27ms (cache hit)
38 silly packumentCache full:https://registry.npmjs.org/@vue%2flanguage-service set size:276156 disposed:false
39 http cache https://registry.npmjs.org/@volar%2flanguage-server 31ms (cache hit)
40 silly packumentCache full:https://registry.npmjs.org/@volar%2flanguage-server set size:531195 disposed:false
41 http cache https://registry.npmjs.org/@vue%2ftypescript-plugin 37ms (cache hit)
42 silly packumentCache full:https://registry.npmjs.org/@vue%2ftypescript-plugin set size:131318 disposed:false
43 http cache https://registry.npmjs.org/vscode-uri 42ms (cache hit)
44 silly packumentCache full:https://registry.npmjs.org/vscode-uri set size:75646 disposed:false
45 silly placeDep ROOT @volar/language-server@2.4.23 OK for: @vue/language-server@3.0.10 want: 2.4.23
46 silly placeDep ROOT @vue/language-core@3.0.10 OK for: @vue/language-server@3.0.10 want: 3.0.10
47 silly placeDep ROOT @vue/language-service@3.0.10 OK for: @vue/language-server@3.0.10 want: 3.0.10
48 silly placeDep ROOT @vue/typescript-plugin@3.0.10 OK for: @vue/language-server@3.0.10 want: 3.0.10
49 silly placeDep ROOT vscode-uri@3.1.0 OK for: @vue/language-server@3.0.10 want: ^3.0.8
50 silly fetch manifest request-light@^0.7.0
51 silly packumentCache full:https://registry.npmjs.org/request-light cache-miss
52 silly fetch manifest path-browserify@^1.0.1
53 silly packumentCache full:https://registry.npmjs.org/path-browserify cache-miss
54 silly fetch manifest @volar/typescript@2.4.23
55 silly packumentCache full:https://registry.npmjs.org/@volar%2ftypescript cache-miss
56 silly fetch manifest @volar/language-core@2.4.23
57 silly packumentCache full:https://registry.npmjs.org/@volar%2flanguage-core cache-miss
58 silly fetch manifest vscode-languageserver@^9.0.1
59 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver cache-miss
60 silly fetch manifest @volar/language-service@2.4.23
61 silly packumentCache full:https://registry.npmjs.org/@volar%2flanguage-service cache-miss
62 silly fetch manifest vscode-languageserver-protocol@^3.17.5
63 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-protocol cache-miss
64 http cache https://registry.npmjs.org/request-light 14ms (cache hit)
65 silly packumentCache full:https://registry.npmjs.org/request-light set size:72930 disposed:false
66 silly fetch manifest vscode-languageserver-textdocument@^1.0.11
67 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-textdocument cache-miss
68 http cache https://registry.npmjs.org/path-browserify 16ms (cache hit)
69 silly packumentCache full:https://registry.npmjs.org/path-browserify set size:17399 disposed:false
70 silly fetch manifest picomatch@^4.0.2
71 silly packumentCache full:https://registry.npmjs.org/picomatch cache-miss
72 http cache https://registry.npmjs.org/@volar%2flanguage-service 16ms (cache hit)
73 silly packumentCache full:https://registry.npmjs.org/@volar%2flanguage-service set size:493688 disposed:false
74 silly fetch manifest @vue/shared@^3.5.0
75 silly packumentCache full:https://registry.npmjs.org/@vue%2fshared cache-miss
76 http cache https://registry.npmjs.org/@volar%2ftypescript 22ms (cache hit)
77 silly packumentCache full:https://registry.npmjs.org/@volar%2ftypescript set size:422945 disposed:false
78 silly fetch manifest alien-signals@^2.0.5
79 silly packumentCache full:https://registry.npmjs.org/alien-signals cache-miss
80 http cache https://registry.npmjs.org/@volar%2flanguage-core 26ms (cache hit)
81 silly packumentCache full:https://registry.npmjs.org/@volar%2flanguage-core set size:443157 disposed:false
82 silly fetch manifest muggle-string@^0.4.1
83 silly packumentCache full:https://registry.npmjs.org/muggle-string cache-miss
84 http cache https://registry.npmjs.org/vscode-languageserver-protocol 28ms (cache hit)
85 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-protocol set size:487789 disposed:false
86 silly fetch manifest @vue/compiler-dom@^3.5.0
87 silly packumentCache full:https://registry.npmjs.org/@vue%2fcompiler-dom cache-miss
88 http cache https://registry.npmjs.org/vscode-languageserver 36ms (cache hit)
89 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver set size:712757 disposed:false
90 silly fetch manifest @vue/compiler-vue2@^2.7.16
91 silly packumentCache full:https://registry.npmjs.org/@vue%2fcompiler-vue2 cache-miss
92 http cache https://registry.npmjs.org/vscode-languageserver-textdocument 35ms (cache hit)
93 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-textdocument set size:66497 disposed:false
94 silly fetch manifest @vue/shared@^3.5.0
95 silly packumentCache full:https://registry.npmjs.org/@vue%2fshared cache-miss
96 http cache https://registry.npmjs.org/muggle-string 24ms (cache hit)
97 silly packumentCache full:https://registry.npmjs.org/muggle-string set size:19006 disposed:false
98 silly fetch manifest volar-service-css@0.0.65
99 silly packumentCache full:https://registry.npmjs.org/volar-service-css cache-miss
100 http cache https://registry.npmjs.org/alien-signals 31ms (cache hit)
101 silly packumentCache full:https://registry.npmjs.org/alien-signals set size:183262 disposed:false
102 silly fetch manifest volar-service-pug@0.0.65
103 silly packumentCache full:https://registry.npmjs.org/volar-service-pug cache-miss
104 http cache https://registry.npmjs.org/@vue%2fshared 41ms (cache hit)
105 silly packumentCache full:https://registry.npmjs.org/@vue%2fshared set size:674634 disposed:false
106 silly fetch manifest volar-service-html@0.0.65
107 silly packumentCache full:https://registry.npmjs.org/volar-service-html cache-miss
108 http cache https://registry.npmjs.org/picomatch 50ms (cache hit)
109 silly packumentCache full:https://registry.npmjs.org/picomatch set size:118818 disposed:false
110 silly fetch manifest volar-service-json@0.0.65
111 silly packumentCache full:https://registry.npmjs.org/volar-service-json cache-miss
112 http cache https://registry.npmjs.org/@vue%2fcompiler-vue2 26ms (cache hit)
113 silly packumentCache full:https://registry.npmjs.org/@vue%2fcompiler-vue2 set size:9811 disposed:false
114 silly fetch manifest volar-service-emmet@0.0.65
115 silly packumentCache full:https://registry.npmjs.org/volar-service-emmet cache-miss
116 http cache https://registry.npmjs.org/@vue%2fcompiler-dom 38ms (cache hit)
117 silly packumentCache full:https://registry.npmjs.org/@vue%2fcompiler-dom set size:799701 disposed:false
118 silly fetch manifest volar-service-typescript@0.0.65
119 silly packumentCache full:https://registry.npmjs.org/volar-service-typescript cache-miss
120 http cache https://registry.npmjs.org/@vue%2fshared 34ms (cache hit)
121 silly packumentCache full:https://registry.npmjs.org/@vue%2fshared set size:674634 disposed:false
122 silly packumentCache full:https://registry.npmjs.org/@vue%2fshared dispose
123 silly fetch manifest volar-service-pug-beautify@0.0.65
124 silly packumentCache full:https://registry.npmjs.org/volar-service-pug-beautify cache-miss
125 http cache https://registry.npmjs.org/volar-service-css 37ms (cache hit)
126 silly packumentCache full:https://registry.npmjs.org/volar-service-css set size:127313 disposed:false
127 silly fetch manifest vscode-html-languageservice@^5.2.0
128 silly packumentCache full:https://registry.npmjs.org/vscode-html-languageservice cache-miss
129 http cache https://registry.npmjs.org/volar-service-html 28ms (cache hit)
130 silly packumentCache full:https://registry.npmjs.org/volar-service-html set size:128521 disposed:false
131 http cache https://registry.npmjs.org/volar-service-json 28ms (cache hit)
132 silly packumentCache full:https://registry.npmjs.org/volar-service-json set size:126576 disposed:false
133 http cache https://registry.npmjs.org/volar-service-pug 38ms (cache hit)
134 silly packumentCache full:https://registry.npmjs.org/volar-service-pug set size:130230 disposed:false
135 http cache https://registry.npmjs.org/volar-service-typescript 22ms (cache hit)
136 silly packumentCache full:https://registry.npmjs.org/volar-service-typescript set size:146252 disposed:false
137 http cache https://registry.npmjs.org/volar-service-emmet 32ms (cache hit)
138 silly packumentCache full:https://registry.npmjs.org/volar-service-emmet set size:129736 disposed:false
139 http cache https://registry.npmjs.org/volar-service-pug-beautify 17ms (cache hit)
140 silly packumentCache full:https://registry.npmjs.org/volar-service-pug-beautify set size:125688 disposed:false
141 http cache https://registry.npmjs.org/vscode-html-languageservice 16ms (cache hit)
142 silly packumentCache full:https://registry.npmjs.org/vscode-html-languageservice set size:519558 disposed:false
143 silly placeDep ROOT @volar/language-core@2.4.23 OK for: @volar/language-server@2.4.23 want: 2.4.23
144 silly placeDep ROOT @volar/language-service@2.4.23 OK for: @volar/language-server@2.4.23 want: 2.4.23
145 silly placeDep ROOT @volar/typescript@2.4.23 OK for: @volar/language-server@2.4.23 want: 2.4.23
146 silly placeDep ROOT path-browserify@1.0.1 OK for: @volar/language-server@2.4.23 want: ^1.0.1
147 silly placeDep ROOT request-light@0.7.0 OK for: @volar/language-server@2.4.23 want: ^0.7.0
148 silly placeDep ROOT vscode-languageserver@9.0.1 OK for: @volar/language-server@2.4.23 want: ^9.0.1
149 silly placeDep ROOT vscode-languageserver-protocol@3.17.5 OK for: @volar/language-server@2.4.23 want: ^3.17.5
150 silly placeDep ROOT vscode-languageserver-textdocument@1.0.12 OK for: @volar/language-server@2.4.23 want: ^1.0.11
151 silly fetch manifest @volar/source-map@2.4.23
152 silly packumentCache full:https://registry.npmjs.org/@volar%2fsource-map cache-miss
153 silly fetch manifest vscode-languageserver-protocol@3.17.5
154 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-protocol cache-hit
155 silly fetch manifest vscode-jsonrpc@8.2.0
156 silly packumentCache full:https://registry.npmjs.org/vscode-jsonrpc cache-miss
157 silly fetch manifest vscode-languageserver-types@3.17.5
158 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-types cache-miss
159 http cache https://registry.npmjs.org/vscode-languageserver-types 6ms (cache hit)
160 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-types set size:307629 disposed:false
161 http cache https://registry.npmjs.org/vscode-jsonrpc 12ms (cache hit)
162 silly packumentCache full:https://registry.npmjs.org/vscode-jsonrpc set size:384137 disposed:false
163 http cache https://registry.npmjs.org/@volar%2fsource-map 20ms (cache hit)
164 silly packumentCache full:https://registry.npmjs.org/@volar%2fsource-map set size:790040 disposed:false
165 silly placeDep ROOT @volar/source-map@2.4.23 OK for: @volar/language-core@2.4.23 want: 2.4.23
166 silly placeDep ROOT @vue/compiler-dom@3.5.28 OK for: @vue/language-core@3.0.10 want: ^3.5.0
167 silly placeDep ROOT @vue/compiler-vue2@2.7.16 OK for: @vue/language-core@3.0.10 want: ^2.7.16
168 silly placeDep ROOT @vue/shared@3.5.28 OK for: @vue/language-core@3.0.10 want: ^3.5.0
169 silly placeDep ROOT alien-signals@2.0.8 OK for: @vue/language-core@3.0.10 want: ^2.0.5
170 silly placeDep ROOT muggle-string@0.4.1 OK for: @vue/language-core@3.0.10 want: ^0.4.1
171 silly placeDep ROOT picomatch@4.0.3 OK for: @vue/language-core@3.0.10 want: ^4.0.2
172 silly fetch manifest @vue/shared@3.5.28
173 silly packumentCache full:https://registry.npmjs.org/@vue%2fshared cache-hit
174 silly fetch manifest @vue/compiler-core@3.5.28
175 silly packumentCache full:https://registry.npmjs.org/@vue%2fcompiler-core cache-miss
176 silly fetch manifest he@^1.2.0
177 silly packumentCache full:https://registry.npmjs.org/he cache-miss
178 silly fetch manifest de-indent@^1.0.2
179 silly packumentCache full:https://registry.npmjs.org/de-indent cache-miss
180 http cache https://registry.npmjs.org/he 14ms (cache hit)
181 silly packumentCache full:https://registry.npmjs.org/he set size:58773 disposed:false
182 http cache https://registry.npmjs.org/de-indent 16ms (cache hit)
183 silly packumentCache full:https://registry.npmjs.org/de-indent set size:4379 disposed:false
184 http cache https://registry.npmjs.org/@vue%2fcompiler-core 20ms (cache hit)
185 silly packumentCache full:https://registry.npmjs.org/@vue%2fcompiler-core set size:794352 disposed:false
186 silly placeDep ROOT @vue/compiler-core@3.5.28 OK for: @vue/compiler-dom@3.5.28 want: 3.5.28
187 silly fetch manifest entities@^7.0.1
188 silly packumentCache full:https://registry.npmjs.org/entities cache-miss
189 silly fetch manifest @babel/parser@^7.29.0
190 silly packumentCache full:https://registry.npmjs.org/@babel%2fparser cache-miss
191 silly fetch manifest estree-walker@^2.0.2
192 silly packumentCache full:https://registry.npmjs.org/estree-walker cache-miss
193 silly fetch manifest source-map-js@^1.2.1
194 silly packumentCache full:https://registry.npmjs.org/source-map-js cache-miss
195 http cache https://registry.npmjs.org/estree-walker 6ms (cache hit)
196 silly packumentCache full:https://registry.npmjs.org/estree-walker set size:60887 disposed:false
197 http cache https://registry.npmjs.org/source-map-js 7ms (cache hit)
198 silly packumentCache full:https://registry.npmjs.org/source-map-js set size:62640 disposed:false
199 http cache https://registry.npmjs.org/entities 11ms (cache hit)
200 silly packumentCache full:https://registry.npmjs.org/entities set size:99038 disposed:false
201 http cache https://registry.npmjs.org/@babel%2fparser 15ms (cache hit)
202 silly packumentCache full:https://registry.npmjs.org/@babel%2fparser set size:714217 disposed:false
203 silly placeDep ROOT @babel/parser@7.29.0 OK for: @vue/compiler-core@3.5.28 want: ^7.29.0
204 silly placeDep ROOT entities@7.0.1 OK for: @vue/compiler-core@3.5.28 want: ^7.0.1
205 silly placeDep ROOT estree-walker@2.0.2 OK for: @vue/compiler-core@3.5.28 want: ^2.0.2
206 silly placeDep ROOT source-map-js@1.2.1 OK for: @vue/compiler-core@3.5.28 want: ^1.2.1
207 silly fetch manifest @babel/types@^7.29.0
208 silly packumentCache full:https://registry.npmjs.org/@babel%2ftypes cache-miss
209 http cache https://registry.npmjs.org/@babel%2ftypes 4ms (cache hit)
210 silly packumentCache full:https://registry.npmjs.org/@babel%2ftypes set size:485839 disposed:false
211 silly placeDep ROOT @babel/types@7.29.0 OK for: @babel/parser@7.29.0 want: ^7.29.0
212 silly fetch manifest @babel/helper-string-parser@^7.27.1
213 silly packumentCache full:https://registry.npmjs.org/@babel%2fhelper-string-parser cache-miss
214 silly fetch manifest @babel/helper-validator-identifier@^7.28.5
215 silly packumentCache full:https://registry.npmjs.org/@babel%2fhelper-validator-identifier cache-miss
216 http cache https://registry.npmjs.org/@babel%2fhelper-string-parser 4ms (cache hit)
217 silly packumentCache full:https://registry.npmjs.org/@babel%2fhelper-string-parser set size:80211 disposed:false
218 http cache https://registry.npmjs.org/@babel%2fhelper-validator-identifier 4ms (cache hit)
219 silly packumentCache full:https://registry.npmjs.org/@babel%2fhelper-validator-identifier set size:114475 disposed:false
220 silly placeDep ROOT @babel/helper-string-parser@7.27.1 OK for: @babel/types@7.29.0 want: ^7.27.1
221 silly placeDep ROOT @babel/helper-validator-identifier@7.28.5 OK for: @babel/types@7.29.0 want: ^7.28.5
222 silly placeDep ROOT de-indent@1.0.2 OK for: @vue/compiler-vue2@2.7.16 want: ^1.0.2
223 silly placeDep ROOT he@1.2.0 OK for: @vue/compiler-vue2@2.7.16 want: ^1.2.0
224 silly placeDep ROOT volar-service-css@0.0.65 OK for: @vue/language-service@3.0.10 want: 0.0.65
225 silly placeDep ROOT volar-service-emmet@0.0.65 OK for: @vue/language-service@3.0.10 want: 0.0.65
226 silly placeDep ROOT volar-service-html@0.0.65 OK for: @vue/language-service@3.0.10 want: 0.0.65
227 silly placeDep ROOT volar-service-json@0.0.65 OK for: @vue/language-service@3.0.10 want: 0.0.65
228 silly placeDep ROOT volar-service-pug@0.0.65 OK for: @vue/language-service@3.0.10 want: 0.0.65
229 silly placeDep ROOT volar-service-pug-beautify@0.0.65 OK for: @vue/language-service@3.0.10 want: 0.0.65
230 silly placeDep ROOT volar-service-typescript@0.0.65 OK for: @vue/language-service@3.0.10 want: 0.0.65
231 silly placeDep ROOT vscode-html-languageservice@5.6.1 OK for: @vue/language-service@3.0.10 want: ^5.2.0
232 silly fetch manifest vscode-css-languageservice@^6.3.0
233 silly packumentCache full:https://registry.npmjs.org/vscode-css-languageservice cache-miss
234 silly fetch manifest @emmetio/css-parser@ramya-rao-a/css-parser#vscode
235 silly fetch manifest @vscode/emmet-helper@^2.9.3
236 silly packumentCache full:https://registry.npmjs.org/@vscode%2femmet-helper cache-miss
237 silly fetch manifest @emmetio/html-matcher@^1.3.0
238 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fhtml-matcher cache-miss
239 silly fetch manifest vscode-html-languageservice@^5.3.0
240 silly packumentCache full:https://registry.npmjs.org/vscode-html-languageservice cache-hit
241 silly fetch manifest vscode-json-languageservice@^5.4.0
242 silly packumentCache full:https://registry.npmjs.org/vscode-json-languageservice cache-miss
243 silly fetch manifest pug-lexer@^5.0.1
244 silly packumentCache full:https://registry.npmjs.org/pug-lexer cache-miss
245 silly fetch manifest pug-parser@^6.0.0
246 silly packumentCache full:https://registry.npmjs.org/pug-parser cache-miss
247 http cache https://registry.npmjs.org/vscode-css-languageservice 21ms (cache hit)
248 silly packumentCache full:https://registry.npmjs.org/vscode-css-languageservice set size:684047 disposed:false
249 silly fetch manifest @johnsoncodehk/pug-beautify@^0.2.2
250 silly packumentCache full:https://registry.npmjs.org/@johnsoncodehk%2fpug-beautify cache-miss
251 http cache https://registry.npmjs.org/@vscode%2femmet-helper 34ms (cache hit)
252 silly packumentCache full:https://registry.npmjs.org/@vscode%2femmet-helper set size:54004 disposed:false
253 silly fetch manifest semver@^7.6.2
254 silly packumentCache full:https://registry.npmjs.org/semver cache-miss
255 http cache https://registry.npmjs.org/@emmetio%2fhtml-matcher 36ms (cache hit)
256 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fhtml-matcher set size:40469 disposed:false
257 silly fetch manifest vscode-nls@^5.2.0
258 silly packumentCache full:https://registry.npmjs.org/vscode-nls cache-miss
259 http cache https://registry.npmjs.org/vscode-json-languageservice 37ms (cache hit)
260 silly packumentCache full:https://registry.npmjs.org/vscode-json-languageservice set size:538614 disposed:false
261 silly fetch manifest typescript-auto-import-cache@^0.3.5
262 silly packumentCache full:https://registry.npmjs.org/typescript-auto-import-cache cache-miss
263 http cache https://registry.npmjs.org/pug-parser 40ms (cache hit)
264 silly packumentCache full:https://registry.npmjs.org/pug-parser set size:37400 disposed:false
265 silly fetch manifest @vscode/l10n@^0.0.18
266 silly packumentCache full:https://registry.npmjs.org/@vscode%2fl10n cache-miss
267 http cache https://registry.npmjs.org/pug-lexer 43ms (cache hit)
268 silly packumentCache full:https://registry.npmjs.org/pug-lexer set size:68153 disposed:false
269 silly fetch manifest vscode-languageserver-types@^3.17.5
270 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-types cache-hit
271 http cache https://registry.npmjs.org/@johnsoncodehk%2fpug-beautify 23ms (cache hit)
272 silly packumentCache full:https://registry.npmjs.org/@johnsoncodehk%2fpug-beautify set size:4669 disposed:false
273 http cache https://registry.npmjs.org/vscode-nls 12ms (cache hit)
274 silly packumentCache full:https://registry.npmjs.org/vscode-nls set size:100194 disposed:false
275 http cache https://registry.npmjs.org/@vscode%2fl10n 7ms (cache hit)
276 silly packumentCache full:https://registry.npmjs.org/@vscode%2fl10n set size:58396 disposed:false
277 http cache https://registry.npmjs.org/semver 16ms (cache hit)
278 silly packumentCache full:https://registry.npmjs.org/semver set size:229678 disposed:false
279 http cache https://registry.npmjs.org/typescript-auto-import-cache 13ms (cache hit)
280 silly packumentCache full:https://registry.npmjs.org/typescript-auto-import-cache set size:20069 disposed:false
281 silly placeDep ROOT vscode-css-languageservice@6.3.9 OK for: volar-service-css@0.0.65 want: ^6.3.0
282 silly placeDep ROOT @emmetio/css-parser@0.4.0 OK for: volar-service-emmet@0.0.65 want: ramya-rao-a/css-parser#vscode
283 silly placeDep ROOT @emmetio/html-matcher@1.3.0 OK for: volar-service-emmet@0.0.65 want: ^1.3.0
284 silly placeDep ROOT @vscode/emmet-helper@2.11.0 OK for: volar-service-emmet@0.0.65 want: ^2.9.3
285 silly fetch manifest @emmetio/stream-reader@^2.2.0
286 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fstream-reader cache-miss
287 silly fetch manifest @emmetio/stream-reader-utils@^0.1.0
288 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fstream-reader-utils cache-miss
289 silly fetch manifest @emmetio/scanner@^1.0.0
290 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fscanner cache-miss
291 silly fetch manifest emmet@^2.4.3
292 silly packumentCache full:https://registry.npmjs.org/emmet cache-miss
293 silly fetch manifest jsonc-parser@^2.3.0
294 silly packumentCache full:https://registry.npmjs.org/jsonc-parser cache-miss
295 silly fetch manifest vscode-languageserver-types@^3.15.1
296 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-types cache-hit
297 http cache https://registry.npmjs.org/@emmetio%2fstream-reader-utils 7ms (cache hit)
298 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fstream-reader-utils set size:2497 disposed:false
299 http cache https://registry.npmjs.org/@emmetio%2fscanner 8ms (cache hit)
300 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fscanner set size:36737 disposed:false
301 http cache https://registry.npmjs.org/@emmetio%2fstream-reader 10ms (cache hit)
302 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fstream-reader set size:11059 disposed:false
303 http cache https://registry.npmjs.org/emmet 8ms (cache hit)
304 silly packumentCache full:https://registry.npmjs.org/emmet set size:165698 disposed:false
305 http cache https://registry.npmjs.org/jsonc-parser 11ms (cache hit)
306 silly packumentCache full:https://registry.npmjs.org/jsonc-parser set size:122731 disposed:false
307 silly placeDep ROOT @emmetio/stream-reader@2.2.0 OK for: @emmetio/css-parser@0.4.0 want: ^2.2.0
308 silly placeDep ROOT @emmetio/stream-reader-utils@0.1.0 OK for: @emmetio/css-parser@0.4.0 want: ^0.1.0
309 silly placeDep ROOT @emmetio/scanner@1.0.4 OK for: @emmetio/html-matcher@1.3.0 want: ^1.0.0
310 silly placeDep ROOT emmet@2.4.11 OK for: @vscode/emmet-helper@2.11.0 want: ^2.4.3
311 silly placeDep ROOT jsonc-parser@2.3.1 OK for: @vscode/emmet-helper@2.11.0 want: ^2.3.0
312 silly placeDep ROOT vscode-languageserver-types@3.17.5 OK for: @vscode/emmet-helper@2.11.0 want: ^3.15.1
313 silly fetch manifest @emmetio/abbreviation@^2.3.3
314 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fabbreviation cache-miss
315 silly fetch manifest @emmetio/css-abbreviation@^2.1.8
316 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fcss-abbreviation cache-miss
317 http cache https://registry.npmjs.org/@emmetio%2fcss-abbreviation 2ms (cache hit)
318 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fcss-abbreviation set size:75438 disposed:false
319 http cache https://registry.npmjs.org/@emmetio%2fabbreviation 5ms (cache hit)
320 silly packumentCache full:https://registry.npmjs.org/@emmetio%2fabbreviation set size:115399 disposed:false
321 silly placeDep ROOT @emmetio/abbreviation@2.3.3 OK for: emmet@2.4.11 want: ^2.3.3
322 silly placeDep ROOT @emmetio/css-abbreviation@2.1.8 OK for: emmet@2.4.11 want: ^2.1.8
323 silly placeDep ROOT vscode-json-languageservice@5.7.1 OK for: volar-service-json@0.0.65 want: ^5.4.0
324 silly fetch manifest jsonc-parser@^3.3.1
325 silly packumentCache full:https://registry.npmjs.org/jsonc-parser cache-hit
326 silly placeDep ROOT pug-lexer@5.0.1 OK for: volar-service-pug@0.0.65 want: ^5.0.1
327 silly placeDep ROOT pug-parser@6.0.0 OK for: volar-service-pug@0.0.65 want: ^6.0.0
328 silly fetch manifest character-parser@^2.2.0
329 silly packumentCache full:https://registry.npmjs.org/character-parser cache-miss
330 silly fetch manifest is-expression@^4.0.0
331 silly packumentCache full:https://registry.npmjs.org/is-expression cache-miss
332 silly fetch manifest pug-error@^2.0.0
333 silly packumentCache full:https://registry.npmjs.org/pug-error cache-miss
334 silly fetch manifest pug-error@^2.0.0
335 silly packumentCache full:https://registry.npmjs.org/pug-error cache-miss
336 silly fetch manifest token-stream@1.0.0
337 silly packumentCache full:https://registry.npmjs.org/token-stream cache-miss
338 http cache https://registry.npmjs.org/is-expression 6ms (cache hit)
339 silly packumentCache full:https://registry.npmjs.org/is-expression set size:16083 disposed:false
340 http cache https://registry.npmjs.org/pug-error 6ms (cache hit)
341 silly packumentCache full:https://registry.npmjs.org/pug-error set size:28904 disposed:false
342 http cache https://registry.npmjs.org/character-parser 8ms (cache hit)
343 silly packumentCache full:https://registry.npmjs.org/character-parser set size:54906 disposed:false
344 http cache https://registry.npmjs.org/pug-error 8ms (cache hit)
345 silly packumentCache full:https://registry.npmjs.org/pug-error set size:28904 disposed:false
346 silly packumentCache full:https://registry.npmjs.org/pug-error dispose
347 http cache https://registry.npmjs.org/token-stream 9ms (cache hit)
348 silly packumentCache full:https://registry.npmjs.org/token-stream set size:5598 disposed:false
349 silly placeDep ROOT character-parser@2.2.0 OK for: pug-lexer@5.0.1 want: ^2.2.0
350 silly placeDep ROOT is-expression@4.0.0 OK for: pug-lexer@5.0.1 want: ^4.0.0
351 silly placeDep ROOT pug-error@2.1.0 OK for: pug-lexer@5.0.1 want: ^2.0.0
352 silly fetch manifest is-regex@^1.0.3
353 silly packumentCache full:https://registry.npmjs.org/is-regex cache-miss
354 silly fetch manifest acorn@^7.1.1
355 silly packumentCache full:https://registry.npmjs.org/acorn cache-miss
356 silly fetch manifest object-assign@^4.1.1
357 silly packumentCache full:https://registry.npmjs.org/object-assign cache-miss
358 http cache https://registry.npmjs.org/object-assign 3ms (cache hit)
359 silly packumentCache full:https://registry.npmjs.org/object-assign set size:28988 disposed:false
360 http cache https://registry.npmjs.org/is-regex 5ms (cache hit)
361 silly packumentCache full:https://registry.npmjs.org/is-regex set size:42924 disposed:false
362 http cache https://registry.npmjs.org/acorn 7ms (cache hit)
363 silly packumentCache full:https://registry.npmjs.org/acorn set size:379626 disposed:false
364 silly placeDep ROOT is-regex@1.2.1 OK for: character-parser@2.2.0 want: ^1.0.3
365 silly fetch manifest call-bound@^1.0.2
366 silly packumentCache full:https://registry.npmjs.org/call-bound cache-miss
367 silly fetch manifest gopd@^1.2.0
368 silly packumentCache full:https://registry.npmjs.org/gopd cache-miss
369 silly fetch manifest has-tostringtag@^1.0.2
370 silly packumentCache full:https://registry.npmjs.org/has-tostringtag cache-miss
371 silly fetch manifest hasown@^2.0.2
372 silly packumentCache full:https://registry.npmjs.org/hasown cache-miss
373 http cache https://registry.npmjs.org/gopd 5ms (cache hit)
374 silly packumentCache full:https://registry.npmjs.org/gopd set size:11458 disposed:false
375 http cache https://registry.npmjs.org/has-tostringtag 6ms (cache hit)
376 silly packumentCache full:https://registry.npmjs.org/has-tostringtag set size:13945 disposed:false
377 http cache https://registry.npmjs.org/call-bound 7ms (cache hit)
378 silly packumentCache full:https://registry.npmjs.org/call-bound set size:15317 disposed:false
379 http cache https://registry.npmjs.org/hasown 7ms (cache hit)
380 silly packumentCache full:https://registry.npmjs.org/hasown set size:12476 disposed:false
381 silly placeDep ROOT acorn@7.4.1 OK for: is-expression@4.0.0 want: ^7.1.1
382 silly placeDep ROOT object-assign@4.1.1 OK for: is-expression@4.0.0 want: ^4.1.1
383 silly placeDep ROOT call-bound@1.0.4 OK for: is-regex@1.2.1 want: ^1.0.2
384 silly placeDep ROOT gopd@1.2.0 OK for: is-regex@1.2.1 want: ^1.2.0
385 silly placeDep ROOT has-tostringtag@1.0.2 OK for: is-regex@1.2.1 want: ^1.0.2
386 silly placeDep ROOT hasown@2.0.2 OK for: is-regex@1.2.1 want: ^2.0.2
387 silly fetch manifest call-bind-apply-helpers@^1.0.2
388 silly packumentCache full:https://registry.npmjs.org/call-bind-apply-helpers cache-miss
389 silly fetch manifest get-intrinsic@^1.3.0
390 silly packumentCache full:https://registry.npmjs.org/get-intrinsic cache-miss
391 silly fetch manifest has-symbols@^1.0.3
392 silly packumentCache full:https://registry.npmjs.org/has-symbols cache-miss
393 silly fetch manifest function-bind@^1.1.2
394 silly packumentCache full:https://registry.npmjs.org/function-bind cache-miss
395 http cache https://registry.npmjs.org/has-symbols 4ms (cache hit)
396 silly packumentCache full:https://registry.npmjs.org/has-symbols set size:21550 disposed:false
397 http cache https://registry.npmjs.org/get-intrinsic 5ms (cache hit)
398 silly packumentCache full:https://registry.npmjs.org/get-intrinsic set size:60985 disposed:false
399 http cache https://registry.npmjs.org/function-bind 5ms (cache hit)
400 silly packumentCache full:https://registry.npmjs.org/function-bind set size:15733 disposed:false
401 http cache https://registry.npmjs.org/call-bind-apply-helpers 7ms (cache hit)
402 silly packumentCache full:https://registry.npmjs.org/call-bind-apply-helpers set size:12744 disposed:false
403 silly placeDep ROOT call-bind-apply-helpers@1.0.2 OK for: call-bound@1.0.4 want: ^1.0.2
404 silly placeDep ROOT get-intrinsic@1.3.0 OK for: call-bound@1.0.4 want: ^1.3.0
405 silly fetch manifest es-errors@^1.3.0
406 silly packumentCache full:https://registry.npmjs.org/es-errors cache-miss
407 silly fetch manifest es-errors@^1.3.0
408 silly packumentCache full:https://registry.npmjs.org/es-errors cache-miss
409 silly fetch manifest get-proto@^1.0.1
410 silly packumentCache full:https://registry.npmjs.org/get-proto cache-miss
411 silly fetch manifest has-symbols@^1.1.0
412 silly packumentCache full:https://registry.npmjs.org/has-symbols cache-hit
413 silly fetch manifest es-object-atoms@^1.1.1
414 silly packumentCache full:https://registry.npmjs.org/es-object-atoms cache-miss
415 silly fetch manifest math-intrinsics@^1.1.0
416 silly packumentCache full:https://registry.npmjs.org/math-intrinsics cache-miss
417 silly fetch manifest es-define-property@^1.0.1
418 silly packumentCache full:https://registry.npmjs.org/es-define-property cache-miss
419 http cache https://registry.npmjs.org/es-errors 17ms (cache hit)
420 silly packumentCache full:https://registry.npmjs.org/es-errors set size:16918 disposed:false
421 http cache https://registry.npmjs.org/get-proto 18ms (cache hit)
422 silly packumentCache full:https://registry.npmjs.org/get-proto set size:8300 disposed:false
423 http cache https://registry.npmjs.org/es-errors 20ms (cache hit)
424 silly packumentCache full:https://registry.npmjs.org/es-errors set size:16918 disposed:false
425 silly packumentCache full:https://registry.npmjs.org/es-errors dispose
426 http cache https://registry.npmjs.org/math-intrinsics 18ms (cache hit)
427 silly packumentCache full:https://registry.npmjs.org/math-intrinsics set size:9265 disposed:false
428 http cache https://registry.npmjs.org/es-define-property 18ms (cache hit)
429 silly packumentCache full:https://registry.npmjs.org/es-define-property set size:8542 disposed:false
430 http cache https://registry.npmjs.org/es-object-atoms 20ms (cache hit)
431 silly packumentCache full:https://registry.npmjs.org/es-object-atoms set size:15304 disposed:false
432 silly placeDep ROOT es-errors@1.3.0 OK for: call-bind-apply-helpers@1.0.2 want: ^1.3.0
433 silly placeDep ROOT function-bind@1.1.2 OK for: call-bind-apply-helpers@1.0.2 want: ^1.1.2
434 silly placeDep ROOT es-define-property@1.0.1 OK for: get-intrinsic@1.3.0 want: ^1.0.1
435 silly placeDep ROOT es-object-atoms@1.1.1 OK for: get-intrinsic@1.3.0 want: ^1.1.1
436 silly placeDep ROOT get-proto@1.0.1 OK for: get-intrinsic@1.3.0 want: ^1.0.1
437 silly placeDep ROOT has-symbols@1.1.0 OK for: get-intrinsic@1.3.0 want: ^1.1.0
438 silly placeDep ROOT math-intrinsics@1.1.0 OK for: get-intrinsic@1.3.0 want: ^1.1.0
439 silly fetch manifest dunder-proto@^1.0.1
440 silly packumentCache full:https://registry.npmjs.org/dunder-proto cache-miss
441 http cache https://registry.npmjs.org/dunder-proto 2ms (cache hit)
442 silly packumentCache full:https://registry.npmjs.org/dunder-proto set size:8256 disposed:false
443 silly placeDep ROOT dunder-proto@1.0.1 OK for: get-proto@1.0.1 want: ^1.0.1
444 silly placeDep ROOT token-stream@1.0.0 OK for: pug-parser@6.0.0 want: 1.0.0
445 silly placeDep ROOT @johnsoncodehk/pug-beautify@0.2.2 OK for: volar-service-pug-beautify@0.0.65 want: ^0.2.2
446 silly placeDep ROOT semver@7.7.4 OK for: volar-service-typescript@0.0.65 want: ^7.6.2
447 silly placeDep ROOT typescript-auto-import-cache@0.3.6 OK for: volar-service-typescript@0.0.65 want: ^0.3.5
448 silly placeDep ROOT vscode-nls@5.2.0 OK for: volar-service-typescript@0.0.65 want: ^5.2.0
449 silly placeDep ROOT @vscode/l10n@0.0.18 OK for: vscode-css-languageservice@6.3.9 want: ^0.0.18
450 silly placeDep node_modules/vscode-json-languageservice jsonc-parser@3.3.1 OK for: vscode-json-languageservice@5.7.1 want: ^3.3.1
451 silly placeDep ROOT vscode-jsonrpc@8.2.0 OK for: vscode-languageserver-protocol@3.17.5 want: 8.2.0
452 silly reify moves {}
453 silly audit bulk request {
453 silly audit   '@vue/language-server': [ '3.0.10' ],
453 silly audit   typescript: [ '5.9.3' ],
453 silly audit   '@volar/language-server': [ '2.4.23' ],
453 silly audit   '@vue/language-core': [ '3.0.10' ],
453 silly audit   '@vue/language-service': [ '3.0.10' ],
453 silly audit   '@vue/typescript-plugin': [ '3.0.10' ],
453 silly audit   'vscode-uri': [ '3.1.0' ],
453 silly audit   '@volar/language-core': [ '2.4.23' ],
453 silly audit   '@volar/language-service': [ '2.4.23' ],
453 silly audit   '@volar/typescript': [ '2.4.23' ],
453 silly audit   'path-browserify': [ '1.0.1' ],
453 silly audit   'request-light': [ '0.7.0' ],
453 silly audit   'vscode-languageserver': [ '9.0.1' ],
453 silly audit   'vscode-languageserver-protocol': [ '3.17.5' ],
453 silly audit   'vscode-languageserver-textdocument': [ '1.0.12' ],
453 silly audit   '@volar/source-map': [ '2.4.23' ],
453 silly audit   '@vue/compiler-dom': [ '3.5.28' ],
453 silly audit   '@vue/compiler-vue2': [ '2.7.16' ],
453 silly audit   '@vue/shared': [ '3.5.28' ],
453 silly audit   'alien-signals': [ '2.0.8' ],
453 silly audit   'muggle-string': [ '0.4.1' ],
453 silly audit   picomatch: [ '4.0.3' ],
453 silly audit   '@vue/compiler-core': [ '3.5.28' ],
453 silly audit   '@babel/parser': [ '7.29.0' ],
453 silly audit   entities: [ '7.0.1' ],
453 silly audit   'estree-walker': [ '2.0.2' ],
453 silly audit   'source-map-js': [ '1.2.1' ],
453 silly audit   '@babel/types': [ '7.29.0' ],
453 silly audit   '@babel/helper-string-parser': [ '7.27.1' ],
453 silly audit   '@babel/helper-validator-identifier': [ '7.28.5' ],
453 silly audit   'de-indent': [ '1.0.2' ],
453 silly audit   he: [ '1.2.0' ],
453 silly audit   'volar-service-css': [ '0.0.65' ],
453 silly audit   'volar-service-emmet': [ '0.0.65' ],
453 silly audit   'volar-service-html': [ '0.0.65' ],
453 silly audit   'volar-service-json': [ '0.0.65' ],
453 silly audit   'volar-service-pug': [ '0.0.65' ],
453 silly audit   'volar-service-pug-beautify': [ '0.0.65' ],
453 silly audit   'volar-service-typescript': [ '0.0.65' ],
453 silly audit   'vscode-html-languageservice': [ '5.6.1' ],
453 silly audit   'vscode-css-languageservice': [ '6.3.9' ],
453 silly audit   '@emmetio/css-parser': [ '0.4.0' ],
453 silly audit   '@emmetio/html-matcher': [ '1.3.0' ],
453 silly audit   '@vscode/emmet-helper': [ '2.11.0' ],
453 silly audit   '@emmetio/stream-reader': [ '2.2.0' ],
453 silly audit   '@emmetio/stream-reader-utils': [ '0.1.0' ],
453 silly audit   '@emmetio/scanner': [ '1.0.4' ],
453 silly audit   emmet: [ '2.4.11' ],
453 silly audit   'jsonc-parser': [ '2.3.1', '3.3.1' ],
453 silly audit   'vscode-languageserver-types': [ '3.17.5' ],
453 silly audit   '@emmetio/abbreviation': [ '2.3.3' ],
453 silly audit   '@emmetio/css-abbreviation': [ '2.1.8' ],
453 silly audit   'vscode-json-languageservice': [ '5.7.1' ],
453 silly audit   'pug-lexer': [ '5.0.1' ],
453 silly audit   'pug-parser': [ '6.0.0' ],
453 silly audit   'character-parser': [ '2.2.0' ],
453 silly audit   'is-expression': [ '4.0.0' ],
453 silly audit   'pug-error': [ '2.1.0' ],
453 silly audit   'is-regex': [ '1.2.1' ],
453 silly audit   acorn: [ '7.4.1' ],
453 silly audit   'object-assign': [ '4.1.1' ],
453 silly audit   'call-bound': [ '1.0.4' ],
453 silly audit   gopd: [ '1.2.0' ],
453 silly audit   'has-tostringtag': [ '1.0.2' ],
453 silly audit   hasown: [ '2.0.2' ],
453 silly audit   'call-bind-apply-helpers': [ '1.0.2' ],
453 silly audit   'get-intrinsic': [ '1.3.0' ],
453 silly audit   'es-errors': [ '1.3.0' ],
453 silly audit   'function-bind': [ '1.1.2' ],
453 silly audit   'es-define-property': [ '1.0.1' ],
453 silly audit   'es-object-atoms': [ '1.1.1' ],
453 silly audit   'get-proto': [ '1.0.1' ],
453 silly audit   'has-symbols': [ '1.1.0' ],
453 silly audit   'math-intrinsics': [ '1.1.0' ],
453 silly audit   'dunder-proto': [ '1.0.1' ],
453 silly audit   'token-stream': [ '1.0.0' ],
453 silly audit   '@johnsoncodehk/pug-beautify': [ '0.2.2' ],
453 silly audit   semver: [ '7.7.4' ],
453 silly audit   'typescript-auto-import-cache': [ '0.3.6' ],
453 silly audit   'vscode-nls': [ '5.2.0' ],
453 silly audit   '@vscode/l10n': [ '0.0.18' ],
453 silly audit   'vscode-jsonrpc': [ '8.2.0' ]
453 silly audit }
454 http cache vscode-jsonrpc@https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.0.tgz 0ms (cache hit)
455 http cache @vscode/l10n@https://registry.npmjs.org/@vscode/l10n/-/l10n-0.0.18.tgz 0ms (cache hit)
456 http cache typescript-auto-import-cache@https://registry.npmjs.org/typescript-auto-import-cache/-/typescript-auto-import-cache-0.3.6.tgz 0ms (cache hit)
457 http cache vscode-nls@https://registry.npmjs.org/vscode-nls/-/vscode-nls-5.2.0.tgz 0ms (cache hit)
458 http cache semver@https://registry.npmjs.org/semver/-/semver-7.7.4.tgz 0ms (cache hit)
459 http cache token-stream@https://registry.npmjs.org/token-stream/-/token-stream-1.0.0.tgz 0ms (cache hit)
460 http cache dunder-proto@https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz 0ms (cache hit)
461 http cache @johnsoncodehk/pug-beautify@https://registry.npmjs.org/@johnsoncodehk/pug-beautify/-/pug-beautify-0.2.2.tgz 0ms (cache hit)
462 http cache has-symbols@https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz 0ms (cache hit)
463 http cache math-intrinsics@https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz 0ms (cache hit)
464 http cache es-object-atoms@https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.1.tgz 1ms (cache hit)
465 http cache get-proto@https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz 0ms (cache hit)
466 http cache es-define-property@https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz 0ms (cache hit)
467 http cache function-bind@https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz 0ms (cache hit)
468 http cache es-errors@https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz 0ms (cache hit)
469 http cache get-intrinsic@https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.0.tgz 0ms (cache hit)
470 http cache call-bind-apply-helpers@https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz 0ms (cache hit)
471 http cache hasown@https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz 0ms (cache hit)
472 http cache has-tostringtag@https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.2.tgz 0ms (cache hit)
473 http cache gopd@https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz 0ms (cache hit)
474 http cache object-assign@https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz 0ms (cache hit)
475 http cache call-bound@https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz 0ms (cache hit)
476 http cache acorn@https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz 0ms (cache hit)
477 http cache is-regex@https://registry.npmjs.org/is-regex/-/is-regex-1.2.1.tgz 0ms (cache hit)
478 http cache character-parser@https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz 0ms (cache hit)
479 http cache pug-parser@https://registry.npmjs.org/pug-parser/-/pug-parser-6.0.0.tgz 0ms (cache hit)
480 http cache pug-error@https://registry.npmjs.org/pug-error/-/pug-error-2.1.0.tgz 0ms (cache hit)
481 http cache is-expression@https://registry.npmjs.org/is-expression/-/is-expression-4.0.0.tgz 0ms (cache hit)
482 http cache vscode-json-languageservice@https://registry.npmjs.org/vscode-json-languageservice/-/vscode-json-languageservice-5.7.1.tgz 0ms (cache hit)
483 http cache pug-lexer@https://registry.npmjs.org/pug-lexer/-/pug-lexer-5.0.1.tgz 0ms (cache hit)
484 http cache @emmetio/css-abbreviation@https://registry.npmjs.org/@emmetio/css-abbreviation/-/css-abbreviation-2.1.8.tgz 0ms (cache hit)
485 http cache vscode-languageserver-types@https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz 0ms (cache hit)
486 http cache @emmetio/abbreviation@https://registry.npmjs.org/@emmetio/abbreviation/-/abbreviation-2.3.3.tgz 0ms (cache hit)
487 http cache jsonc-parser@https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-2.3.1.tgz 0ms (cache hit)
488 http cache emmet@https://registry.npmjs.org/emmet/-/emmet-2.4.11.tgz 0ms (cache hit)
489 http cache @emmetio/scanner@https://registry.npmjs.org/@emmetio/scanner/-/scanner-1.0.4.tgz 0ms (cache hit)
490 http cache @emmetio/stream-reader-utils@https://registry.npmjs.org/@emmetio/stream-reader-utils/-/stream-reader-utils-0.1.0.tgz 0ms (cache hit)
491 http cache @emmetio/stream-reader@https://registry.npmjs.org/@emmetio/stream-reader/-/stream-reader-2.2.0.tgz 0ms (cache hit)
492 http cache @vscode/emmet-helper@https://registry.npmjs.org/@vscode/emmet-helper/-/emmet-helper-2.11.0.tgz 0ms (cache hit)
493 http cache @emmetio/html-matcher@https://registry.npmjs.org/@emmetio/html-matcher/-/html-matcher-1.3.0.tgz 0ms (cache hit)
494 http cache vscode-html-languageservice@https://registry.npmjs.org/vscode-html-languageservice/-/vscode-html-languageservice-5.6.1.tgz 0ms (cache hit)
495 http cache vscode-css-languageservice@https://registry.npmjs.org/vscode-css-languageservice/-/vscode-css-languageservice-6.3.9.tgz 0ms (cache hit)
496 http cache volar-service-typescript@https://registry.npmjs.org/volar-service-typescript/-/volar-service-typescript-0.0.65.tgz 0ms (cache hit)
497 http cache volar-service-pug-beautify@https://registry.npmjs.org/volar-service-pug-beautify/-/volar-service-pug-beautify-0.0.65.tgz 0ms (cache hit)
498 http cache volar-service-pug@https://registry.npmjs.org/volar-service-pug/-/volar-service-pug-0.0.65.tgz 0ms (cache hit)
499 http cache volar-service-json@https://registry.npmjs.org/volar-service-json/-/volar-service-json-0.0.65.tgz 0ms (cache hit)
500 http cache he@https://registry.npmjs.org/he/-/he-1.2.0.tgz 0ms (cache hit)
501 http cache volar-service-html@https://registry.npmjs.org/volar-service-html/-/volar-service-html-0.0.65.tgz 0ms (cache hit)
502 http cache de-indent@https://registry.npmjs.org/de-indent/-/de-indent-1.0.2.tgz 0ms (cache hit)
503 http cache @babel/helper-validator-identifier@https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.28.5.tgz 0ms (cache hit)
504 http cache @babel/types@https://registry.npmjs.org/@babel/types/-/types-7.29.0.tgz 0ms (cache hit)
505 http cache @babel/helper-string-parser@https://registry.npmjs.org/@babel/helper-string-parser/-/helper-string-parser-7.27.1.tgz 0ms (cache hit)
506 http cache volar-service-emmet@https://registry.npmjs.org/volar-service-emmet/-/volar-service-emmet-0.0.65.tgz 0ms (cache hit)
507 http cache source-map-js@https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz 0ms (cache hit)
508 http cache estree-walker@https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz 0ms (cache hit)
509 http cache entities@https://registry.npmjs.org/entities/-/entities-7.0.1.tgz 0ms (cache hit)
510 http cache @babel/parser@https://registry.npmjs.org/@babel/parser/-/parser-7.29.0.tgz 0ms (cache hit)
511 http cache @vue/compiler-core@https://registry.npmjs.org/@vue/compiler-core/-/compiler-core-3.5.28.tgz 0ms (cache hit)
512 http cache picomatch@https://registry.npmjs.org/picomatch/-/picomatch-4.0.3.tgz 0ms (cache hit)
513 http cache volar-service-css@https://registry.npmjs.org/volar-service-css/-/volar-service-css-0.0.65.tgz 0ms (cache hit)
514 http cache muggle-string@https://registry.npmjs.org/muggle-string/-/muggle-string-0.4.1.tgz 0ms (cache hit)
515 http cache alien-signals@https://registry.npmjs.org/alien-signals/-/alien-signals-2.0.8.tgz 0ms (cache hit)
516 http cache @vue/shared@https://registry.npmjs.org/@vue/shared/-/shared-3.5.28.tgz 0ms (cache hit)
517 http cache @vue/compiler-vue2@https://registry.npmjs.org/@vue/compiler-vue2/-/compiler-vue2-2.7.16.tgz 0ms (cache hit)
518 http cache @vue/compiler-dom@https://registry.npmjs.org/@vue/compiler-dom/-/compiler-dom-3.5.28.tgz 0ms (cache hit)
519 http cache @volar/source-map@https://registry.npmjs.org/@volar/source-map/-/source-map-2.4.23.tgz 0ms (cache hit)
520 http cache vscode-languageserver-textdocument@https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.12.tgz 0ms (cache hit)
521 http cache vscode-languageserver-protocol@https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.5.tgz 0ms (cache hit)
522 http cache vscode-languageserver@https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-9.0.1.tgz 0ms (cache hit)
523 http cache request-light@https://registry.npmjs.org/request-light/-/request-light-0.7.0.tgz 0ms (cache hit)
524 http cache path-browserify@https://registry.npmjs.org/path-browserify/-/path-browserify-1.0.1.tgz 0ms (cache hit)
525 http cache @volar/language-service@https://registry.npmjs.org/@volar/language-service/-/language-service-2.4.23.tgz 1ms (cache hit)
526 http cache @volar/typescript@https://registry.npmjs.org/@volar/typescript/-/typescript-2.4.23.tgz 0ms (cache hit)
527 http cache @volar/language-core@https://registry.npmjs.org/@volar/language-core/-/language-core-2.4.23.tgz 0ms (cache hit)
528 http cache vscode-uri@https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.1.0.tgz 0ms (cache hit)
529 http cache @vue/typescript-plugin@https://registry.npmjs.org/@vue/typescript-plugin/-/typescript-plugin-3.0.10.tgz 0ms (cache hit)
530 http cache @volar/language-server@https://registry.npmjs.org/@volar/language-server/-/language-server-2.4.23.tgz 0ms (cache hit)
531 http cache @vue/language-service@https://registry.npmjs.org/@vue/language-service/-/language-service-3.0.10.tgz 0ms (cache hit)
532 http cache @vue/language-core@https://registry.npmjs.org/@vue/language-core/-/language-core-3.0.10.tgz 0ms (cache hit)
533 http cache typescript@https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz 0ms (cache hit)
534 http cache @vue/language-server@https://registry.npmjs.org/@vue/language-server/-/language-server-3.0.10.tgz 0ms (cache hit)
535 http cache jsonc-parser@https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.3.1.tgz 0ms (cache hit)
536 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 477ms
537 silly audit report {}
538 http fetch GET 200 https://codeload.github.com/ramya-rao-a/css-parser/tar.gz/370c480ac103bd17c7bcfb34bf5d577dc40d3660 199ms (cache revalidated)
539 verbose stack Error: git dep preparation failed
539 verbose stack     at promiseSpawn (/home/user/.nvm/versions/node/v24.13.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
539 verbose stack     at module.exports (/home/user/.nvm/versions/node/v24.13.1/lib/node_modules/npm/node_modules/pacote/lib/util/npm.js:13:10)
539 verbose stack     at /home/user/.nvm/versions/node/v24.13.1/lib/node_modules/npm/node_modules/pacote/lib/git.js:191:14
539 verbose stack     at async withTempDir (/home/user/.nvm/versions/node/v24.13.1/lib/node_modules/npm/node_modules/@npmcli/fs/lib/with-temp-dir.js:21:14)
540 error code 1
541 error git dep preparation failed
542 error command /home/user/.nvm/versions/node/v24.13.1/bin/node /home/user/.nvm/versions/node/v24.13.1/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/user/.npm --prefer-offline=false --prefer-online=false --offline=false --before=2026-02-18T09:43:39.679Z --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
543 error Exit prior to config file resolving
543 error cause
543 error --min-release-age cannot be provided when using --before
544 silly unfinished npm timer reify 1771580619872
545 silly unfinished npm timer reify:unpack 1771580621397
546 silly unfinished npm timer reifyNode:node_modules/@emmetio/css-parser 1771580621397
547 verbose cwd /path/of/test
548 verbose os Linux 5.14.0-611.24.1.el9_7.x86_64
549 verbose node v24.13.1
550 verbose npm  v11.10.1
551 verbose exit 1
552 verbose code 1
553 error A complete log of this run can be found in: /home/user/.npm/_logs/2026-02-20T09_43_39_662Z-debug-0.log
```

</details> 

### Environment

- npm: 11.10.1
- Node.js: 24.13.1
- OS Name: AlmaLinux 9.7 or Windows 11 (probably any OS)
- System Model Name: Any
- npm config:
```ini
; node bin location = /home/user/.nvm/versions/node/v24.13.1/bin/node
; node version = v24.13.1
; npm local prefix = /path/of/test
; npm version = 11.10.1
; cwd = /path/of/test
; HOME = /home/user
```

### PR DESCRIPTION
**Pull request by umeshmore45**
# fix: clear exclusive sibling configs from env when one is set via CLI

## What's the problem?

If you set an exclusive param via CLI (e.g. `--save-prod`) but a sibling
(`npm_config_save_dev=true`) is already in the environment, child processes
inherit both and crash with a conflict. This was also the root cause of the
`--min-release-age` + `--before` issue in #9005.

## What changed

When `setEnvs` exports a non-default exclusive config, it now resets that
param's siblings to their defaults in the env — so child processes never
see a conflict. Works generically for all exclusive pairs, not just this one.

## Tests

Added a test for the case where `save-prod` is set via CLI while `save-dev`
is already in env — verifies `save-dev` gets reset to its default.

## References

Fixes #9005

### CODE REVIEW

**Comment by owlstronaut** [comment]
Thanks for working on this @umeshmore45  — the approach of fixing it generically in set-envs.js for all exclusive params is the right direction per @wraithgar's feedback.

  However, the bug is still reproducible with this PR applied. The core issue is what the child process sees when pacote prepares a git dep, which you can test directly:

```bash
   npm_config_min_release_age=2 node bin/npm-cli.js install --before=2026-02-23T00:00:00.000Z --dry-run
   # => --min-release-age cannot be provided when using --before
```

  This fails identically with and without the PR. The fix resets npm_config_before="" in the parent's env, but the child's loadEnv skips empty strings, so it has no effect. The actual conflict is between npm_config_min_release_age (still in env) and --before (CLI arg added by pacote) — the fix clears the sibling, but the original config causing the conflict is untouched.

**Review by owlstronaut — CHANGES_REQUESTED** [review]
~~

**Comment by umeshmore45** [comment]
Thanks for the detailed explanation. I see the distinction now.

My `set-envs.js` fix clears the sibling (`npm_config_before`), but the actual problem is `npm_config_min_release_age` persisting in env when `--before` is added by pacote as a CLI arg in the child process.

However, I also have a fix in `index.js` that handles this at load time — when `where === 'env'`, the exclusive check is skipped, so CLI args always take precedence over env configs. This means the child process won't throw even if both are present, because `min-release-age` comes from env and `before` comes from CLI.

I tested this with a git dependency (`ini: git+https://github.com/npm/ini.git`) and the child process installed successfully without any exclusive conflict error.

Could you try reproducing the failure with both changes applied (`index.js` + `set-envs.js`)? The `index.js` change is the one that actually prevents the child process conflict.

File: workspaces/config/lib/index.js [hunk 1]
```diff
@@ -590,6 +590,10 @@ class Config {
           if (this.definitions[key]?.exclusive) {
             for (const exclusive of this.definitions[key].exclusive) {
               if (!this.isDefault(exclusive)) {
+                // when loading from env, skip exclusive check — already-set values take precedence
+                if (where === 'env') {
```
Comment (owlstronaut) [inline workspaces/config/lib/index.js]: I think this is too broad. it'll silently accept `npm_config_before=2026-01-01 npm_config_min_release_age=2 npm
  install`

**Review by owlstronaut — CHANGES_REQUESTED** [review]

**Comment by wraithgar** [comment]
This is a tricky one because realistically `before` is the one that is being used in flatOptions, and persisted to submodules.  The min release age flag is an attempt at an "alias" which means it should never be exported or imported.

There is a flag that should solve this already: `envExport`.  It's set to `false` on a few other config items that have aggregation issues or other issues.


Setting it to `true` for `min-release-age` may solve this.

**Comment by umeshmore45** [comment]
Hey, quick question on an edge case I ran into while testing.

Right now with my changes, `npm_config_min_release_age=2 npm_config_before=2026-01-01 npm install` doesn't throw — it silently lets `before` win since `min-release-age` converts to `before` during flatten anyway.

Should this still be an error? If so, I can add a separate validation step post-load rather than catching it during env loading. Let me know how you'd like me to handle this.

**Comment by owlstronaut** [comment]
Yeah, that should still be an error, the user is explicitly setting two conflicting options. The current check is still too broad because `this.list[0]` has a prototype chain that walks through all config levels, not just CLI.

**Comment by umeshmore45** [comment]
Hey, I’ve updated everything based on your feedback

**Changes**
- Using `Object.hasOwn(this.data.get('cli').data, exclusive)` instead of `this.list[0]` to avoid prototype chain checks.
- Switched `continue` to `continue outer` so the env entry gets skipped entirely.
- Added `envExport: false` to `min-release-age` as suggested by @wraithgar.

**Tested**
- `npm_config_min_release_age=2 npm install --before=...` → env value skipped
- `npm_config_min_release_age=2 npm_config_before=... npm install` → throws as expected
- Child process (git dep with pacote) → no conflict

Let me know if anything else should be adjusted.

**Review by owlstronaut — APPROVED** [review]
@umeshmore45 this looks great. Thank you for putting the work in and incorporating our feedbacks!
