### PR TITLE
fix: Validate username at get-identity

### LINKED ISSUE #5867: [BUG] npm whoami allow empty username
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```sh
npm whoami

undefined
```

https://github.com/npm/cli/blob/dc8e6bdd1d9e3416846c4f0624705cb42a7fb067/lib/utils/get-identity.js#L12-L21

### Expected Behavior

```sh
npm whoami

npm ERR! This command requires you to be logged in.
```

It seems to me, that there should be condition on return at line 15
```js
if (registryData?.username) {
  return registryData.username;
}
```

### Steps To Reproduce

1. Config registry=https://verdaccio.example.com
2. Run 'npm whoami'
3. See result

### Environment

- npm: 8.19.2
- Node.js: 18.12.1
- OS Name: Windows 11
- System Model Name: Other
- npm config:
```ini
registry=https://verdaccio.example.com
```

### PR DESCRIPTION
**Pull request by sosoba**
Currently `npm` accept null / undefined / empty string as valid username.
Client should validate incomming data.

## References
  Fixes #5867 (prevent undefined username)

### CODE REVIEW

File: lib/utils/get-identity.js [hunk 1]
```diff
@@ -12,7 +12,9 @@ module.exports = async (npm, opts) => {
   // No username, but we have other credentials; fetch the username from registry
   if (creds.token || creds.certfile && creds.keyfile) {
     const registryData = await npmFetch.json('/-/whoami', { ...opts })
-    return registryData.username
+    if (typeof registryData?.username === 'string')
+      return registryData.username
+    )
```
Comment (nlf) [inline lib/utils/get-identity.js]:
```suggestion
    if (typeof registryData?.username === 'string') {
      return registryData.username
    }
```

**Review by nlf — APPROVED** [review]
