### PR TITLE
fix: dep flag calculation

### LINKED ISSUE #8535: [BUG] npm install produces different results on first and second run
Note:

> Use npm >= 11.6.3 to avoid (these) issues!

More info in this comment: https://github.com/npm/cli/issues/8535#issuecomment-3627452551

### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

Discovered here: https://github.com/electron-userland/electron-builder/issues/9259

A clean `npm install` produces different results on the first and second run.

### Expected Behavior

`npm install` should produce the same results each time.

### Steps To Reproduce

On mac, ignoring scripts just in case:
```sh
npm install -g npm@latest
mkdir test && cd test
npm init -y
npm install --ignore-scripts @abandonware/noble
# added 156 packages, and audited 157 packages in 972ms
npm install --ignore-scripts
# changed 12 packages, and audited 157 packages in 542ms
```
The second install shows "changed 12 packages" which is unexpected. This is also reproducible installing from package/lock files.
```sh
rm -rf node_modules
npm install --ignore-scripts
# added 156 packages, and audited 157 packages in 1s
npm install --ignore-scripts
# changed 12 packages, and audited 157 packages in 553ms
```
The different results are visible in the FS by diffing the output of `find node_modules` before and after.

### Environment

- npm: 11.5.2
- Node.js: v22.14.0
- OS Name: MacOS
- System Model Name: Macbook Pro M4
- npm config:
```ini
; node bin location = /Users/liam.mitchell/.local/share/fnm/node-versions/v22.14.0/installation/bin/node
; node version = v22.14.0
; npm local prefix = /Users/liam.mitchell/npm-install
; npm version = 11.5.2
; cwd = /Users/liam.mitchell/npm-install
; HOME = /Users/liam.mitchell
```

### PR DESCRIPTION
**Pull request by liamcmitchell**
- reverts pruning added in https://github.com/npm/cli/pull/8431, which incorrectly prunes deps flagged as `peer` and `optional` - these flags don't mean that this node is an optional peer!
- reverts much of https://github.com/npm/cli/pull/8579, which I think mistakenly changed peer dep calculation logic
- rewrites calcDepFlags
- adds logic to avoid unsetting `extraneous` when following optional peer edges (how https://github.com/npm/cli/pull/8431, should have been fixed)
- updates my prev fix to avoid looking for missing optional peer deps (`if ((!edge.to && edge.type !== 'peerOptional') || !edge.valid) {`)
- refactors dep flag unsetting and resetting into Node methods
- removes `shake out Link target timing issue` test, which was testing code [removed](https://github.com/npm/cli/commit/2db6c085ea08ee639767d37e6fd83a1ca0fbd9ce#diff-6778dbd4bbfddaeb827a8d2aa7248d4c9b329229f69e407d5fd487abe16dd942L333) a while back
- avoids omitting flaky`selflink` fixture when writing snapshots

Fixes https://github.com/npm/cli/issues/8535, the last issue being that `encoding` was incorrectly pruned on subsequent installs. See the below dependency diagram produced from `latest` branch (since 11.6.1).

```mermaid
flowchart
encoding_0_1_13["`encoding@0.1.13 (peer, optional)`"]
node_fetch_2_7_0["`node-fetch@2.7.0 (optional)`"]
node_fetch_2_7_0-.->|peerOptional|encoding_0_1_13
_mapbox_node_pre_gyp_1_0_11["`@mapbox/node-pre-gyp@1.0.11 (optional)`"]
_mapbox_node_pre_gyp_1_0_11-->|prod|node_fetch_2_7_0
_abandonware_bluetooth_hci_socket_0_5_3_12["`@abandonware/bluetooth-hci-socket@0.5.3-12 (optional)`"]
_abandonware_bluetooth_hci_socket_0_5_3_12-->|prod|_mapbox_node_pre_gyp_1_0_11
_abandonware_bluetooth_hci_socket_0_5_3_12-->|prod|node_gyp_10_3_1
_abandonware_noble_1_9_2_26["`@abandonware/noble@1.9.2-26 (prod)`"]
_abandonware_noble_1_9_2_26-.->|optional|_abandonware_bluetooth_hci_socket_0_5_3_12
minipass_fetch_3_0_5["`minipass-fetch@3.0.5 (optional)`"]
minipass_fetch_3_0_5-.->|optional|encoding_0_1_13
make_fetch_happen_13_0_1["`make-fetch-happen@13.0.1 (optional)`"]
make_fetch_happen_13_0_1-->|prod|minipass_fetch_3_0_5
node_gyp_10_3_1["`node-gyp@10.3.1 (optional)`"]
node_gyp_10_3_1-->|prod|make_fetch_happen_13_0_1
```

<details>
<summary>Code to generate</summary>

```js
function graph (tree) {
  const safe = (id) => id.replace(/[^\w]/g, '_')
  let code = 'flowchart\n'
  const set = new Set()
  const collect = (node) => {
    set.add(node)
    for (const edge of node.edgesIn) {
      if (!set.has(edge.from)) {
        collect(edge.from)
      }
    }
  }
  for (const node of tree.inventory.values()) {
    if (node.name === 'encoding') {
      collect(node)
    }
  }
  set.delete(tree.root)
  for (const node of set) {
    const flags = node.extraneous && ['extraneous']
      || [
        node.peer && 'peer',
        ...(node.devOptional && !node.dev && !node.optional
          ? ['devOptional']
          : [
            node.dev && 'dev',
            node.optional && 'optional',
          ]),
      ].filter(Boolean).join(', ')
      || 'prod'
    code += `${safe(node.pkgid)}["\`${node.pkgid} (${flags})\`"]\n`
    for (const edge of node.edgesOut.values()) {
      if (!set.has(edge.to)) continue
      code += `${safe(node.pkgid)}-${edge.optional ? '.' : ''}->|${[edge.type, edge.error].filter(Boolean).join(' ')}|${safe(edge.to?.pkgid || `${edge.name}@${edge.spec}`)}\n`
    }
  }
  const mermaid = JSON.stringify({ theme: 'neutral' })
  require('child_process').execSync(`open https://mermaid.live/edit#pako:${require('zlib').deflateSync(JSON.stringify({ code, mermaid })).toString('base64')}`)
}
```

</details>

Note that `encoding` should not have the `peer` flag. This incorrect flag plus the incorrect pruning of `optional && peer` when building ideal tree from shrinkwrap causes this node to be removed from the tree. `encoding`s de-deduped deps (not shown) were NOT removed and when `checkEngineAndPlatform` marks `@abandonware/bluetooth-hci-socket` as `inert`, it cannot follow the removed node to also mark these deps as `inert`. No longer `inert`, the diff algorithm now sees them as missing and they are installed.

### CODE REVIEW

**Comment by liamcmitchell** [comment]
A few more words on dep flags...

Their intention is documented here: https://github.com/npm/cli/blob/latest/workspaces/arborist/README.md#package-dependency-flags

> relevant when pruning nodes from the tree

Pruning means both the `prune` command which removes `extraneous` nodes and the `production`/`omit`/`include` flags which filter a subset of deps.

The `optional` flag is _also_ used to decide if a dep installation failure can be ignored but because of the intended use in pruning, the `optional` flag might not always allow failure as expected.

Consider the following
```
tree (dev A, optional B)
+-- A (prod C) dev: true
+-- B (optional C) optional: true
+-- C dev: false, optional: false, devOptional: true
```

`C` is not `dev` or `optional` because it won't be pruned as either. It is `devOptional` because it will be pruned if both `dev` and `optional` are omitted together.

If `C` installation fails in `npm install --omit=dev`... the failure will be fatal because `C` is not optional - even though the only prod dependent wasn't installed.

Maybe another edge case that can be fixed by recalculating dep flags again after diffing? Or is it before diffing? After we check if a package is omitted but before we check if it is installable?

I think there are a lot of subtle bugs caused by this fragile pre-calculation of dep flags and trying to keep it in sync.

Why are dep flags pre-calculated at all? We only need them when pruning or handling install failures. Could this be done lazily in diff/reify?

Why are dep flags persisted to lockfiles and not just re-calculated? Performance? Curiosity? Preserving inconsistent dep flag calculations across different npm versions? 🤔

**Comment by wraithgar** [comment]
> Why are dep flags persisted to lockfiles and not just re-calculated?

I believe the reason is so that things like `--omit=dev` work from the shrinkwrap and not from re-calculating the tree.

ref:
https://github.com/npm/npm/commit/1eabcd16bf2590364ca20831096350073539bf3a
and
https://github.com/npm/npm/pull/10073


> Why are dep flags pre-calculated at all? We only need them when pruning or handling install failures. Could this be done lazily in diff/reify?

Do we have enough info from a shrinkwrap install to still calculate all of this without the flags IN the shrinkwrap?  Does this question even make sense anymore (i.e. are we currently still pulling in the same info anyways that we would if the flags weren't in the shrinkwrap?)

These are all good questions you have.  I think this is a case of things making sense at the time, and the software having iterated enough over time that we can rethink some decisions.

Removing these flags from the lockfile is a pretty significant breaking change, however.  Making changes that aren't breaking would be the challenge here.  Can we still persist them but have the new code ignore them?

**Comment by liamcmitchell** [comment]
> Do we have enough info from a shrinkwrap install to still calculate all of this without the flags IN the shrinkwrap?

Yes, flags are always calculated from a tree. If shrinkwrap provides a tree, deps can be calculated.

There are already many checks in shrinkwrap load that may set `flagsSuspect` and trigger re-calc of dep flags.

> Can we still persist them but have the new code ignore them?

Yes, very possible. Would be interesting to see if there is much of a performance difference too.

I definitely won't be doing this in this PR and doubt I'll have any time for this in the near future.

**Comment by wraithgar** [comment]
> I definitely won't be doing this in this PR and doubt I'll have any time for this in the near future.

Yep understood, that's a much larger task than these cleanup PRs.

File: workspaces/arborist/lib/arborist/load-virtual.js [hunk 1]
```diff
@@ -93,11 +89,7 @@ module.exports = cls => class VirtualLoader extends cls {
...
           continue
         }
-        node.extraneous = true
-        node.dev = true
-        node.optional = true
-        node.devOptional = true
-        node.peer = true
+        node.resetDepFlags()
       }
       calcDepFlags(this.virtualTree, !this.#rootOptionProvided)
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/load-virtual.js:94]: I don't think it needs to be part of this PR but we definitely have some duplicate/inefficient logic going on w/ this `#rootOptionProvided` flag and the `resetRoot` parameter.  I will make a note to follow up after this PR clean some things up.

For instance in this block `flagsSuspect` is only true if `rootOptionProvided` is not true.

**Review by wraithgar — APPROVED** [review]

**Comment by ebachle** [comment]
I'm wondering if this might also be what fixes https://github.com/npm/cli/issues/8669.  I can't quite figure out how they'd be related, but there's a lot of stuff in really similar spaces.
