### PR TITLE
fix(config): make prefer-offline and prefer-online exclusive

### LINKED ISSUE #9113: [BUG] Silent conflict when both prefer-offline=true and prefer-online=true are set, causing npm view to return stale cached data
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

When both prefer-offline=true and prefer-online=true are set in the .npmrc configuration, npm silently prioritizes prefer-offline. Commands that query the registry, such as npm view <package> version, skip the network request entirely and return stale cached data. The CLI provides no warning or error message indicating that these mutually exclusive flags are conflicting or that prefer-online is being ignored.

### Expected Behavior

npm should detect when mutually exclusive flags like prefer-offline and prefer-online are active simultaneously. It should either output a clear warning message to the console (e.g., WARN config: mutually exclusive flags prefer-offline and prefer-online detected) so the user is aware of the conflict, or ensure that explicitly setting prefer-online overrides the offline preference to force a network validation.

### Steps To Reproduce

_No response_

### Environment

_No response_

### PR DESCRIPTION
**Pull request by mvanhorn**
## Summary

Adds a warning when both `prefer-offline` and `prefer-online` are set to `true` in config, telling the user that `prefer-offline` takes precedence.

## Why this matters

When both flags are active, npm silently prioritizes `prefer-offline`, causing commands like `npm view <package> version` to return stale cached data with no indication that `prefer-online` is being ignored ([#9113](https://github.com/npm/cli/issues/9113)). Users end up debugging registry connectivity, token issues, or package naming when the actual problem is a config conflict.

## Changes

- `workspaces/config/lib/index.js`: After all config sources are loaded, check if both `prefer-offline` and `prefer-online` are truthy. If so, emit a warning via `queueWarning()` so it follows the standard warning lifecycle.
- `workspaces/config/test/index.js`: Added test that passes both `--prefer-offline` and `--prefer-online` via CLI args and verifies the warning is emitted.

## Testing

- New test passes: "warn when both prefer-offline and prefer-online are set"
- Warning text: `config Both prefer-offline and prefer-online are set. prefer-offline takes precedence.`
- Warning fires once at config load, not on every command invocation

Fixes #9113

This contribution was developed with AI assistance (Claude Code).

### CODE REVIEW

**Comment by wraithgar** [comment]
We have a precedent in config to label config items as mutually exclusive. Probably best to do that than to throw a very specific `if` statement in to our main config loop for one condition.

Example: https://github.com/npm/cli/blob/7e9d53841be2a944739b7e226647b68f68b5742e/workspaces/config/lib/definitions/definitions.js#L249

**Comment by mvanhorn** [comment]
Updated - moved to `exclusive` definitions on both `prefer-offline` and `prefer-online` instead of the one-off check. Removed the custom `if` from config load.

File: workspaces/config/test/index.js [hunk 1]
```diff
@@ -1749,12 +1749,8 @@ t.test('warn false with invalid flag and warning removal', async t => {
   t.equal(afterSecondLog.length, beforeSecondLog, 'no new warnings after removal and logWarnings')
 })
 
-t.test('warn when both prefer-offline and prefer-online are set', async t => {
+t.test('error when both prefer-offline and prefer-online are set', async t => {
```
Comment (wraithgar) [inline workspaces/config/test/index.js]: we don't need a test for config settings.  We have tests that make sure that `exclusive` works but it doesn't make a lot of sense to add tests for each thing we've added an exclusive tag for.  The config is the config.

Comment (mvanhorn) [reply workspaces/config/test/index.js]: Makes sense - I'll remove the test. The `exclusive` mechanism is already covered generically so a per-field test is redundant.

**Review by wraithgar — APPROVED** [review]

**Review by wraithgar — APPROVED** [review]

**Comment by mvanhorn** [comment]
Thanks for the review and the pointer to the exclusive config pattern - much cleaner than the one-off check.
