### PR TITLE
fix(ls): suppress false UNMET DEPENDENCYs in linked strategy

### LINKED ISSUE #9090: [BUG] linked strategy: `npm ls` reports undeclared workspaces as UNMET DEPENDENCY
## Is there an existing issue for this?

- [x] I have searched the existing issues

## This issue exists in the latest npm version

- [x] I am using the latest npm

## Current Behavior

In linked mode, workspaces not explicitly declared as root dependencies are intentionally not hoisted to root `node_modules/`. However, `npm ls` reports them as `UNMET DEPENDENCY` and exits with error code 1.

This happens because the lockfile always records auto-created edges from root to all workspaces regardless of install strategy.

## Expected Behavior

`npm ls` should understand that undeclared workspaces are intentionally not hoisted in linked mode and should not report them as missing. The command should exit with code 0.

## Steps To Reproduce

1. Create a workspace project where only some workspaces are declared as root dependencies:

```bash
mkdir -p test-ls/packages/{workspace-a,workspace-b}

cat > test-ls/package.json << 'EOF'
{
  "name": "test-ls",
  "version": "1.0.0",
  "workspaces": ["packages/*"],
  "dependencies": { "workspace-a": "*" }
}
EOF

cat > test-ls/packages/workspace-a/package.json << 'EOF'
{ "name": "workspace-a", "version": "1.0.0" }
EOF

cat > test-ls/packages/workspace-b/package.json << 'EOF'
{ "name": "workspace-b", "version": "1.0.0" }
EOF
```

2. Install and run ls:

```bash
cd test-ls
npm install --install-strategy=linked
npm ls --install-strategy=linked
```

3. Output:

```
test-ls@1.0.0
├── workspace-a@1.0.0 -> ./packages/workspace-a
└── UNMET DEPENDENCY workspace-b@file:.../packages/workspace-b

npm error missing: workspace-b@file:.../packages/workspace-b, required by test-ls@1.0.0
```

## Environment

- npm: 11.11.0
- Node.js: v22.20.0
- OS Name: macOS (Darwin 25.3.0)
- System Model Name: Mac
- npm config:
```ini
install-strategy=linked
```

### LINKED ISSUE #9092: [BUG] linked strategy: `npm ls --all` reports false UNMET DEPENDENCYs for devDeps of store packages
## Is there an existing issue for this?

- [x] I have searched the existing issues

## This issue exists in the latest npm version

- [x] I am using the latest npm

## Current Behavior

`npm ls --all --install-strategy=linked` reports devDependencies of installed packages (e.g. `tap`, `@npmcli/eslint-config`, `@npmcli/template-oss`) as `UNMET DEPENDENCY`. These are correctly omitted during install but `npm ls --all` reads the full `package.json` from the store and reports them as missing.

This affects both workspace and non-workspace projects. It does not happen with the hoisted strategy.

## Expected Behavior

`npm ls --all` should not report devDependencies of non-root packages as UNMET DEPENDENCY. The hoisted strategy handles this correctly.

## Steps To Reproduce

1. Create a simple project:

```bash
mkdir test-lsall && cd test-lsall

cat > package.json << 'EOF'
{
  "name": "test-lsall",
  "version": "1.0.0",
  "dependencies": { "nopt": "^7.0.0" }
}
EOF
```

2. Install and run ls --all:

```bash
npm install --install-strategy=linked
npm ls --all --install-strategy=linked
```

3. Output:

```
test-lsall@1.0.0
└─┬ nopt@7.2.1 -> ./node_modules/.store/nopt@7.2.1-.../node_modules/nopt
  ├── UNMET DEPENDENCY @npmcli/eslint-config@^4.0.0
  ├── UNMET DEPENDENCY @npmcli/template-oss@4.22.0
  ├─┬ abbrev@2.0.0 -> ./node_modules/.store/abbrev@2.0.0-.../node_modules/abbrev
  │ ├── UNMET DEPENDENCY @npmcli/eslint-config@^4.0.0
  │ ├── UNMET DEPENDENCY @npmcli/template-oss@4.8.0
  │ └── UNMET DEPENDENCY tap@^16.3.0
  └── UNMET DEPENDENCY tap@^16.3.0
```

The `UNMET DEPENDENCY` entries (`tap`, `@npmcli/eslint-config`, `@npmcli/template-oss`) are devDependencies of nopt and abbrev that were correctly not installed.

## Environment

- npm: 11.11.0
- Node.js: v22.20.0
- OS Name: macOS (Darwin 25.3.0)
- System Model Name: Mac
- npm config:
```ini
install-strategy=linked
```

### PR DESCRIPTION
**Pull request by manzoorwanijk**
In continuation of our exploration of using `install-strategy=linked` in the [Gutenberg monorepo](https://github.com/WordPress/gutenberg/pull/75814), which powers the WordPress Block Editor.

In linked install strategy, `npm ls` reports two types of false UNMET DEPENDENCYs:

1. **Undeclared workspaces**: The root node always creates workspace edges for all workspaces (from the `workspaces` field in package.json), but in linked mode only workspaces explicitly declared in dependencies are hoisted to `root/node_modules/`. Undeclared workspaces are intentionally absent, yet `npm ls` reports them as missing.

2. **devDependencies of store packages**: Store package link targets (at `.store/<key>/node_modules/<name>`) have no parent in the node tree, so they are treated as "top" nodes and their `devDependencies` are loaded as edges. Those devDeps are never installed, but `npm ls --all` reports them as UNMET DEPENDENCY.

This PR adds a `filterLinkedStrategyEdges` filter in `ls.js` that is only active when `installStrategy === 'linked'`. It skips workspace edges for undeclared workspaces at the root level and skips dev edges for non-root packages (store packages).

## References

Fixes #9090
Fixes #9092

### CODE REVIEW

File: lib/commands/ls.js [hunk 1]
```diff
@@ -403,6 +407,36 @@ const getJsonOutputItem = (node, { global, long }) => {
   return augmentItemWithIncludeMetadata(node, item)
 }
 
+// In linked strategy, two types of edges produce false UNMET DEPENDENCYs:
+// 1. Workspace edges for undeclared workspaces: the lockfile records edges from root to ALL workspaces, but only declared workspaces are hoisted to root/node_modules in linked mode.  Undeclared ones are intentionally absent.
+// 2. Dev edges on non-root packages: store package link targets have no parent in the node tree, so they are treated as "top" nodes and their devDependencies are loaded as edges.  Those devDeps are never installed.
+const filterLinkedStrategyEdges = ({ node, currentDepth }) => {
+  const declaredDeps = currentDepth === 0
+    ? new Set(Object.keys(Object.assign({},
```
Comment (wraithgar) [inline lib/commands/ls.js]: I think this approach is cleaner than what we're doing with things like `this.#rootDeclaredDeps` in `makeIdealGraph`.

```javascript
    this.#rootDeclaredDeps = new Set([
      ...Object.keys(rootPkg.dependencies || {}),
      ...(!omit.has('dev') ? Object.keys(rootPkg.devDependencies || {}) : []),
      ...(!omit.has('optional') ? Object.keys(rootPkg.optionalDependencies || {}) : []),
      ...(!omit.has('peer') ? Object.keys(rootPkg.peerDependencies || {}) : []),
    ])
```

could become

```javascript
    this.#rootDeclaredDeps = new Set(Object.keys(Object.assign({},
      rootPkg.dependencies,
      (!omit.has('dev') && rootPkg.devDependencies),
      (!omit.has('optional') && rootPkg.optionalDependencies),
      (!omit.has('peer') && rootPkg.peerDependencies),
    )))
```

File: lib/commands/ls.js [hunk 2]
```diff
@@ -403,6 +407,36 @@ const getJsonOutputItem = (node, { global, long }) => {
...
+      node.target.package.dependencies,
+      node.target.package.devDependencies,
+      node.target.package.optionalDependencies,
+      node.target.package.peerDependencies
+    )))
+    : null
```
Comment (wraithgar) [inline lib/commands/ls.js]: I think this will throw because we call `declaredDeps.has` later.  This should either be an empty set or we have to guard all use of `declaredDeps` with something like `declaredDeps?.has`

File: lib/commands/ls.js (hunk 1 above)
Comment (manzoorwanijk) [reply lib/commands/ls.js]: Yes! That refactor in `isolated-reifier.js` would be a nice follow-up.

File: lib/commands/ls.js (hunk 2 above)
Comment (manzoorwanijk) [reply lib/commands/ls.js]: Good point!

Updated in dff40311a4a3ec6069eda7f4c3dad67160debaf6. `declaredDeps` is now always initialized as a Set regardless of `currentDepth`.

Comment (wraithgar) [reply lib/commands/ls.js]: Yeah much better. It was odd to have that AND a `currentDepth === 0` check in the returned function.  Dead code in there at the very least.

Comment (manzoorwanijk) [reply lib/commands/ls.js]: Yeah, thank you for the pointer.

File: lib/commands/ls.js (hunk 1 above)
Comment (manzoorwanijk) [reply lib/commands/ls.js]: Or should I make that change here? It doesn't seem to affect the coverage, so the changes should be minimal.

**Review by wraithgar — APPROVED** [review]

File: lib/commands/ls.js (hunk 1 above)
Comment (manzoorwanijk) [reply lib/commands/ls.js]: Updated in #9097
