### PR TITLE
fix: use lru-cache for packuments

### LINKED ISSUE #7276: [BUG] npm 10.4.0+ running out of memory with no `package-lock.json`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

It appears the latest dependency resolving algorithm is taking more memory than before. The following fails:
```
npm install -g npm@10.4.0; rm -rf node_modules/ package-lock.json; npm install
```
as does
```
npm install -g npm@10.5.0; rm -rf node_modules/ package-lock.json; npm install
```
with
```
jan@jan-lite:~/src/my-ui$ npm install -g npm@10.4.0; rm -rf node_modules/ package-lock.json; npm install

removed 13 packages, and changed 28 packages in 2s

24 packages are looking for funding
  run `npm fund` for details
npm WARN using --force Recommended protections disabled.
(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠼ idealTree:@angular/core: sill placeDep ROOT zone.js@0.14.4 OK for: my-ui@3.4.0 want: ^0.14.4
<--- Last few GCs --->

[11434:0x7323c70]    33445 ms: Scavenge (reduce) 2045.6 (2082.1) -> 2045.6 (2083.1) MB, 7.5 / 0.0 ms  (average mu = 0.634, current mu = 0.776) allocation failure; 
[11434:0x7323c70]    33785 ms: Mark-sweep (reduce) 2046.6 (2083.1) -> 2046.1 (2083.6) MB, 167.1 / 0.0 ms  (+ 70.6 ms in 16 steps since start of marking, biggest step 7.7 ms, walltime since start of marking 255 ms) (average mu = 0.507, current mu = 0.339) 

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb95be0 node::Abort() [npm install]
 2: 0xa9a7f8  [npm install]
 3: 0xd6f5b0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [npm install]
 4: 0xd6f957 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [npm install]
 5: 0xf4ceb5  [npm install]
 6: 0xf5f38d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [npm install]
 7: 0xf39a7e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [npm install]
 8: 0xf3ae47 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [npm install]
 9: 0xf1b3c0 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [npm install]
10: 0xf12e34 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [npm install]
11: 0xf150e8 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [npm install]
12: 0x1055349 v8::internal::JsonParser<unsigned short>::MakeString(v8::internal::JsonString const&, v8::internal::Handle<v8::internal::String>) [npm install]
13: 0x1057066 v8::internal::JsonParser<unsigned short>::ParseJsonValue() [npm install]
14: 0x1057b4f v8::internal::JsonParser<unsigned short>::ParseJson() [npm install]
15: 0xdf5213 v8::internal::Builtin_JsonParse(int, unsigned long*, v8::internal::Isolate*) [npm install]
16: 0x170e179  [npm install]
Aborted (core dumped)
```

I have [described this issue on SO as well](https://stackoverflow.com/questions/78144116/npm-install-oom-when-package-lock-json-is).

### Expected Behavior

The following succeeds:
```
npm install -g npm@10.3.0; rm -rf node_modules/ package-lock.json; npm install
```
as does:
```
npm install -g npm@10.2.5; rm -rf node_modules/ package-lock.json; npm install
```

### Steps To Reproduce

```
npm install -g npm@10.4.0; rm -rf node_modules/ package-lock.json; npm install --force
```
or
```
npm install -g npm@10.5.0; rm -rf node_modules/ package-lock.json; npm install --force
```
with
```
{
  "name": "npm-oom",
  "version": "0.0.1",
  "dependencies": {
    "@angular/animations": "^16.2.12",
    "@angular/cdk": "^16.2.14",
    "@angular/cli": "^16.2.12",
    "@angular/common": "^16.2.12",
    "@angular/compiler": "^16.2.12",
    "@angular/compiler-cli": "^16.2.12",
    "@angular/core": "^16.2.12",
    "@angular/flex-layout": "^15.0.0-beta.42",
    "@angular/forms": "^16.2.12",
    "@angular/language-service": "^16.2.12",
    "@angular/material": "^16.2.14",
    "@angular/platform-browser": "^16.2.12",
    "@angular/platform-browser-dynamic": "^16.2.12",
    "@angular/router": "^16.2.12",
    "@sendgrid/mail": "^8.1.1",
    "@stomp/stompjs": "^7.0.0",
    "@types/file-saver-es": "^2.0.3",
    "cross-var": "^1.1.0",
    "enhanced-resolve": "^5.15.1",
    "file-saver-es": "^2.0.5",
    "jwt-decode": "^4.0.0",
    "ng-storages": "^1.1.5",
    "npm": "^10.5.0",
    "reflect-metadata": "^0.2.1",
    "reinstall": "^2.0.0",
    "rxjs": "^7.4.0",
    "tslib": "^2.0.0",
    "typescript": "^5.1.6",
    "zone.js": "^0.14.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.12",
    "@angular-eslint/builder": "^16.3.1",
    "@angular-eslint/eslint-plugin": "^16.3.1",
    "@angular-eslint/eslint-plugin-template": "^16.3.1",
    "@angular-eslint/schematics": "^16.3.1",
    "@angular-eslint/template-parser": "^16.3.1",
    "@types/jasmine": "^5.1.4",
    "@types/node": "^20",
    "@typescript-eslint/eslint-plugin": "^7.1.1",
    "@typescript-eslint/parser": "^7.1.1",
    "jasmine-core": "^5.1.2",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "^6.3.14",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "^3.0.2",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.1.0",
    "protractor": "^7.0.0",
    "ts-node": "^10.0.0",
    "webdriver-manager": "^12.1.9"
  }
}
```

### Environment

- npm: 10.5.0 or 10.4.0
- Node.js: 18.19.1
- OS Name: Ubuntu 23.10
- System Model Name: Dell XPS 13 9310 (0991) 64-bit w/ 8Gb RAM 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
- npm config:
```ini
npm WARN using --force Recommended protections disabled.
; "project" config from /home/jan/src/qm/fm-ui/.npmrc

force = true 

; node bin location = /home/jan/.nvm/versions/node/v18.19.1/bin/node
; node version = v18.19.1
; npm local prefix = /home/jan/src/my-ui
; npm version = 10.4.0
; cwd = /home/jan/src/my-ui
; HOME = /home/jan
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by wraithgar**
Fixes https://github.com/npm/cli/issues/7276

### CODE REVIEW

File: workspaces/arborist/lib/arborist/index.js [hunk 1]
```diff
@@ -82,7 +83,10 @@ class Arborist extends Base {
       installStrategy: options.global ? 'shallow' : (options.installStrategy ? options.installStrategy : 'hoisted'),
       lockfileVersion: lockfileVersion(options.lockfileVersion),
       packageLockOnly: !!options.packageLockOnly,
-      packumentCache: options.packumentCache || new Map(),
+      packumentCache: options.packumentCache || new LRUCache({
+        maxSize: Math.floor(require('node:v8').getHeapStatistics().heap_size_limit * .25),
+        sizeCalculation: p => p._contentLength,
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/index.js]: this doesn't actually represent the size in memory

File: workspaces/arborist/lib/arborist/index.js [hunk 2]
```diff
@@ -82,7 +83,10 @@ class Arborist extends Base {
       installStrategy: options.global ? 'shallow' : (options.installStrategy ? options.installStrategy : 'hoisted'),
       lockfileVersion: lockfileVersion(options.lockfileVersion),
       packageLockOnly: !!options.packageLockOnly,
-      packumentCache: options.packumentCache || new Map(),
+      packumentCache: options.packumentCache || new LRUCache({
+        maxSize: Math.floor(require('node:v8').getHeapStatistics().heap_size_limit * .25),
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/index.js]: `.25` is just a random guess right now

**Comment by wraithgar** [comment]
In a sample size of 1 this makes the example in https://github.com/npm/cli/issues/7276 not crash node when calling it with `--max-old-space-size=500`

File: workspaces/arborist/lib/arborist/index.js [hunk 3]
```diff
@@ -82,7 +140,10 @@ class Arborist extends Base {
       installStrategy: options.global ? 'shallow' : (options.installStrategy ? options.installStrategy : 'hoisted'),
       lockfileVersion: lockfileVersion(options.lockfileVersion),
       packageLockOnly: !!options.packageLockOnly,
-      packumentCache: options.packumentCache || new Map(),
+      // XXX: Does it make a difference to create the packumentCache as a global singleton?
+      // Meaning: do we want to share this cache between all arborist constructors or not?
+      // If so we could move this to the CLI and pass it down when we create new arborist instances
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/index.js]: The cache is currently unaware of packument type, it would currently risk mixing packuments with corgis.

Comment (wraithgar) [reply workspaces/arborist/lib/arborist/index.js]: We have so many caching layers in npm, surely some of them are not helping as much as we think.

**Comment by wraithgar** [comment]
`_contentLength` is `0` when revalidating the cache with new content.  This needs to be fixed before we can trust `_contentLength`.

**Comment by wraithgar** [comment]
Packument size to memory ratio (units are 1000 not 1024):

```
44.19% | [mean contentLength < 10k]
46.89% | [median contentLength < 10k]
61.59% | [mean contentLength < 1M]
60.48% | [median contentLength < 1M]
74.53% | [mean contentLength > 1M]
80.35% | [median contentLength > 1M]
```

The current tradeoff here is that we are swapping memory for disk reads (the cache reads from disk).  On modern machines with large amounts of memory this is likely not a very big tradeoff, most high-memory high-end systems use ssd disks.  This is more impactful of low memory systems, where running out of memory means the process dies.

I suggest an initial limit of 1M for the maximum packument we'll put in the cache, and then we use a multiplier of .6 for all packuments when reporting their size to lru-cache.  This will over-report smaller packuments in favor of not accidentally under reporting medium sized ones an accidentally going further over the desired memory usage.

I don't have a good way to calculate what percentage of the `heap_size_limit` we should allow this cache to use.  Again this is a memory/disk read tradeoff.  Perhaps conservatively limiting the lru cache is best here.

File: workspaces/arborist/lib/arborist/index.js [hunk 4]
```diff
@@ -35,6 +35,55 @@ const { log, time } = require('proc-log')
...
+  }
+
+  constructor ({ heapFactor = 0.25, maxEntryFactor = 0.5, sizeKey = '_contentLength' } = {}) {
+    const maxSize = Math.floor(PackumentCache.#heapLimit * heapFactor)
+    const maxEntrySize = maxSize * maxEntryFactor
+    super({
+      maxSize,
+      maxEntrySize,
+      // Don't cache if we dont know the size
+      sizeCalculation: (p) => p[sizeKey] || maxEntrySize + 1,
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/index.js]: We can now tweak this based on the findings of memory usage to size correlation.

Under 10k = .45
Under 1M = .6

max entry size should floor at 1M, above that the tradeoff is not worth the memory.

**Comment by lukekarrys** [comment]
This is ready for tweaking based on your findings @wraithgar. I was able to get all the tests passing with the new packument cache in place. The only changes were to logging and a few tests with the mock-registry needed `times: N` to be set since packuments aren't cached as aggressively as before.

File: workspaces/arborist/lib/arborist/index.js [hunk 5]
```diff
@@ -31,10 +31,10 @@ const { homedir } = require('os')
 const { depth } = require('treeverse')
 const mapWorkspaces = require('@npmcli/map-workspaces')
 const { log, time } = require('proc-log')
-
 const { saveTypeMap } = require('../add-rm-pkg-deps.js')
 const AuditReport = require('../audit-report.js')
 const relpath = require('../relpath.js')
+const PackumentCache = require('../packument-cache.js')
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/index.js:37]: TODO: pacote currently puts all packuments here regardless of `fullMetadata`, it needs to differentiate the two.

File: workspaces/arborist/lib/packument-cache.js [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+    super({
+      maxSize,
+      maxEntrySize,
+      sizeCalculation: (p) => {
+        // Don't cache if we dont know the size
+        if (!p[sizeKey]) {
+          return maxEntrySize + 1
+        }
+        // content under 10k has a ratio of size to memory of 0.45
+        if (p[sizeKey] < 10000) {
```
Comment (lukekarrys) [inline workspaces/arborist/lib/packument-cache.js]:
```suggestion
        if (p[sizeKey] < 10_000) {
```

File: workspaces/arborist/lib/packument-cache.js [hunk 7]
```diff
@@ -0,0 +1,79 @@
...
+          return p[sizeKey] * 0.45
+        }
+        if (p[sizeKey] < 1000000) {
```
Comment (lukekarrys) [inline workspaces/arborist/lib/packument-cache.js]:
```suggestion
        if (p[sizeKey] < 1_000_000) {
```

File: workspaces/arborist/lib/packument-cache.js [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+      maxSize,
+      maxEntrySize,
+      sizeCalculation: (p) => {
+        // Don't cache if we dont know the size
+        if (!p[sizeKey]) {
+          return maxEntrySize + 1
+        }
+        // content under 10k has a ratio of size to memory of 0.45
+        if (p[sizeKey] < 10000) {
+          return p[sizeKey] * 0.45
```
Comment (lukekarrys) [inline workspaces/arborist/lib/packument-cache.js]:
```suggestion
          return Math.floor(p[sizeKey] * 0.45)
```

File: workspaces/arborist/lib/packument-cache.js [hunk 9]
```diff
@@ -0,0 +1,79 @@
...
+        }
+        if (p[sizeKey] < 1000000) {
+          // content between 10k and 1M has a ratio of size to memory of 0.6
+          return p[sizeKey] * 0.6
```
Comment (lukekarrys) [inline workspaces/arborist/lib/packument-cache.js]:
```suggestion
          return Math.floor(p[sizeKey] * 0.6)
```

**Review by lukekarrys — APPROVED** [review]

**Comment by lukekarrys** [comment]
@wraithgar Approved and ready to land I think. Can you squash with an appropriate body message that closes #7276?

**Comment by wraithgar** [comment]
https://github.com/npm/pacote/pull/369 is still an issue but this doesn't make that issue any worse so it shouldn't block this PR

**Comment by wraithgar** [comment]
Here is the research used to calculate the multipliers.

[packument size profiling.xlsx](https://github.com/npm/cli/files/15238350/packument.size.profiling.xlsx)

File: workspaces/arborist/lib/arborist/index.js (hunk 5 above)
Comment (wraithgar) [reply workspaces/arborist/lib/arborist/index.js:37]: https://github.com/npm/pacote/pull/369

**Comment by melroy89** [comment]
> The current tradeoff here is that we are swapping memory for disk reads (the cache reads from disk) 

We could of course also try to increase the default node memory limit? Or is that a bad idea.

**Comment by wraithgar** [comment]
> We could of course also try to increase the default node memory limit? Or is that a bad idea.

That's up to you.  This was built to react to that value, so scaling it would mean npm using more memory in this cache.  It would take doing some benchmarking but I suspect that on modern systems w/ lots of memory and ssd drives the tradeoff isn't very large.
