### PR TITLE
ls: do not warn on missing optional deps

### LINKED ISSUE #3137: [BUG] `npm ls` reports missing optional peer deps as missing deps
### Current Behavior:

Missing optional peer deps are reported as problems, even though npm does not install them by default.

### Expected Behavior:

Since these are all optional peer deps, they should not be reported as problems.

### Steps To Reproduce:
In the cli project right now:

```
npm run resetdeps
npm prune
npm ls -a
```

Prints the following warnings:

```
npm ERR! code ELSPROBLEMS
npm ERR! missing: flow-remove-types@>=2.112.0, required by tap@15.0.4
npm ERR! missing: ts-node@>=8.5.2, required by tap@15.0.4
npm ERR! missing: typescript@>=3.7.2, required by tap@15.0.4
npm ERR! missing: bufferutil@^4.0.1, required by ws@7.4.5
npm ERR! missing: utf-8-validate@^5.0.2, required by ws@7.4.5
```

### Environment:
npm 7.10.0

### PR DESCRIPTION
**Pull request by isaacs**
There was code checking node[_type], but we didn't include that field on
the object that is actually checked when we are looking for problems.

Fix: #3137

### CODE REVIEW

File: test/lib/ls.js [hunk 1]
```diff
@@ -2352,6 +2352,102 @@ t.test('ls --parseable', (t) => {
...
+
+  config.all = true
+  t.test('--json', t => {
+    config.json = true
+    config.parseable = false
+    ls.exec([], (err) => {
+      t.match(err, { code: 'ELSPROBLEMS' })
+      result = JSON.parse(result)
+      const problems = result.problems.map(p => p.split(npm.prefix).join('{project}'))
+      t.matchSnapshot(problems, 'ls --json problems')
```
Comment (ruyadorno) [inline test/lib/ls.js:2431]: looks like the `{project}` replacement is not working on windows targets

File: lib/ls.js [hunk 2]
```diff
@@ -414,6 +414,7 @@ const augmentNodesWithMetadata = ({
       path: node.path,
       isLink: node.isLink,
       realpath: node.realpath,
+      [_type]: node[_type],
```
Comment (ruyadorno) [inline lib/ls.js:417]: good catch! 😅

**Review by ruyadorno — APPROVED** [review]

File: test/lib/ls.js (hunk 1 above)
Comment (isaacs) [reply test/lib/ls.js:2431]: Yeah.  Time to fire up the microsoft brand laptop!
