### PR TITLE
fix: prefix in .npmrc error log

### LINKED ISSUE #6081: [BUG] Prefix in .npmrc ignored
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm trying to change the prefix for the current project using a .npmrc file.

The prefix in the .npmrc file is ignored. Tested with `npm install` and `npm prefix`.

The output of `node prefix` is the current directory instead of the configured directory.

### Expected Behavior

I expected `npm` to use the prefix in the .npmrc file.

### Steps To Reproduce

1. Create file `.npmrc` with contents `prefix=./vendor`.
2. Run `npm prefix` or `npm install`.
3. The first command shows the current directory and install creates `./node_modules` in the current directory.

### Environment

- npm: 9.3.1
- Node.js: v14.21.2
- OS Name: Debian GNU/Linux 11.5
- System Model Name: PC
- npm config:
```ini
; "project" config from /home/xxxx/yyyy/.npmrc

prefix = "/home/xxxx/yyyy/vendor" 

; node bin location = /usr/bin/node
; node version = v14.21.2
; npm local prefix = /home/xxxx/yyyy
; npm version = 9.3.1
; cwd = /home/xxxx/yyyy
; HOME = /home/xxxx
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by rahulio96**
## Summary
The original issue (#6081) wanted the project's .npmrc to set a prefix value for npm to use in both ```npm prefix``` and ```npm install <package>``` However, we made the changes according to wraithgar's comment.

Currently, when running ```npm prefix``` or ```npm install```, there is no error logged communicating to the user that prefix cannot be changed in the project config.

This solution gives the error message more clarity to make debugging easier and lets the user know that prefix cannot be changed from the project level.

Screenshot

Also added the accompanying tap test to ensure the expected error is outputted.

### PLEASE NOTE: 
**If prefix is set to a value, the error will be logged anytime a user enters in a npm or npx command, which means that the logging is not specific to just ```npm prefix``` or ```npm install <package>```, but also applies to commands such as ```npm exec```.**

### Reproduce Original Issue:

1. Add .npmrc file into your project’s directory
2. Set prefix to some location e.g. prefix=./vendor
3. Run ```npm prefix``` or ```npm install <package>```
4. ```npm prefix``` will give the current directory’s prefix, and ```npm install <package>``` will install the package in the current directory.
5. No error would be logged to tell user that prefix cannot be changed from project level

### File tap test:
- Enter in terminal:
- ```TAP_SNAPSHOT=1 node . run test workspaces/config/test/index.js```

### Run the entire tap test:
- Enter in terminal:
- ```node . run test```

### Dummy Project Test:

- Made a dummy project with a vendor folder and a .npmrc file with prefix=./vendor
- Used aliasing to see if the error is being logged:
- Enter in terminal: 
- ```alias localnpm="node /workspaces/cli/"```
- ```localnpm prefix```
- ```localnpm install <package>```

## References
  Fixes #6081

### CODE REVIEW

File: workspaces/config/lib/index.js [hunk 1]
```diff
@@ -610,7 +610,17 @@ class Config {
...
+        const parsedConfig = ini.parse(data)
+        if (type === 'project') {
+          const parsedConfigPrefix = parsedConfig.prefix
+          // Log error if prefix is mentioned in project .npmrc
+          if (parsedConfigPrefix) {
+            log.error(`prefix=${parsedConfigPrefix} cannot be changed from project config: ${file}`)
+          }
+        }
+        return this.#loadObject(parsedConfig, type, file)
+      },
```
Comment (wraithgar) [inline workspaces/config/lib/index.js]:
```suggestion
        if (type === 'project' && parsedConfig.prefix) {
          // Log error if prefix is mentioned in project .npmrc
          log.error('config', `prefix=${parsedConfigPrefix} cannot be changed from project config: ${file}.`)
        }
        return this.#loadObject(parsedConfig, type, file)
      },
```

We don't need to cast a whole new variable for one if statement, just assess it in place.

Comment (wraithgar) [reply workspaces/config/lib/index.js]: Also added the logging prefix to the log output

Comment (rahulio96) [reply workspaces/config/lib/index.js]: However, parsedConfigPrefix is also used for the logged error, would you still prefer if we got rid of it?

Comment (wraithgar) [reply workspaces/config/lib/index.js]: Yeah that's one lest instance where we're logging user input which is always a good thing to avoid.

Comment (wraithgar) [reply workspaces/config/lib/index.js]: I had originally removed it and added it back at the last second, I should have trusted my first instinct.

Comment (rahulio96) [reply workspaces/config/lib/index.js]: Ok, are you suggesting that we change the log error to be: 
``log.error('config', `prefix cannot be changed from project config: ${file}.`)``

Or are you suggesting this?
``log.error('config', `prefix=${parsedConfig.prefix} cannot be changed from project config: ${file}.`)``

Comment (wraithgar) [reply workspaces/config/lib/index.js]:
```
log.error('config', `prefix cannot be changed from project config: ${file}.`)
```

Comment (rahulio96) [reply workspaces/config/lib/index.js]: Got it, appreciate the response.

**Comment by wraithgar** [comment]
Adding `config` to that logging statement changed the shape of the array in the test.  Update the test to expect the new format and this should be good to ship

**Comment by rahulio96** [comment]
Yeah just noticed that too, thanks!

**Review by wraithgar — APPROVED** [review]
This is very helpful thank you.

**Comment by rahulio96** [comment]
No problem, hope it helps.
