### PR TITLE
fix: make pack and exec work with git hash refs

### LINKED ISSUE #6723: [BUG] `npm pack <git-dependency>#<commit-hash>` fails in npm >= 9.6.5
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm pack` with a specific commit of a git dependency fails as follows:
```shell
$ npm pack vercel/ms#1304f150b38027e0818cc122106b5c7322d68d0c                                   
npm ERR! GitFetcher requires an Arborist constructor to pack a tarball

npm ERR! A complete log of this run can be found in: /home/acmiel/.npm/_logs/2023-08-21T08_27_53_861Z-debug-0.log
```

### Expected Behavior

Expected `npm pack` to succeed (like it does in version <= 9.6.4).

Note that it still works for things that are not commit hashes:

```shell
$ npm pack vercel/ms#3.0.0-canary.1
...
ms-3.0.0-canary.1.tgz
```

### Steps To Reproduce

1. With `npm` version 9.6.5 or higher
2. Run `npm pack vercel/ms#1304f150b38027e0818cc122106b5c7322d68d0c` or any other git dependency + commit hash
3. And get `npm ERR! GitFetcher requires an Arborist constructor to pack a tarball`

### Environment

- npm: 9.8.1
- Node.js: 18.17.1
- OS Name: Fedora 37
- System Model Name: Lenovo ThinkPad X1 Carbon
- npm config:

```ini
; node bin location = /usr/bin/node-18
; node version = v18.17.1
; npm local prefix = /tmp/test
; npm version = 9.8.1
; cwd = /tmp/test
; HOME = /home/acmiel
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by milaninfy**
Passing arborist constructor to pacote.manifest call because internally when fetching git deps DirFetcher requires Arborist constructor from GitFetcher  https://github.com/npm/pacote/blob/main/CHANGELOG.md#1400-pre3-2022-09-28

- [x] Trying to add some tests 

Fixes: https://github.com/npm/cli/issues/6723

### CODE REVIEW

File: workspaces/libnpmpack/test/index.js [hunk 1]
```diff
@@ -7,6 +7,7 @@ const spawk = tspawk(t)
 
 const fs = require('node:fs')
 const path = require('node:path')
+const { resolve } = require('node:path')
```
Comment (wraithgar) [inline workspaces/libnpmpack/test/index.js:10]: we're already requiring `node:path` in line 9.

File: test/lib/commands/exec.js [hunk 2]
```diff
@@ -254,3 +254,27 @@ t.test('npx --no-install @npmcli/npx-test', async t => {
     )
   }
 })
+
+t.test('packs from git spec', async t => {
+  const spec = 'test/test#111111aaaaaaaabbbbbbbbccccccdddddddeeeee'
+  const pkgPath = path.resolve(__dirname, '../../fixtures/git-test.tgz')
```
Comment (wraithgar) [inline test/lib/commands/exec.js:260]: I'm not the biggest fan of having this tgz file in fixtures, but if I weigh it against the effort required to build it during tests it makes sense.

**Review by wraithgar — APPROVED** [review]

File: workspaces/libnpmpack/test/index.js (hunk 1 above)
Comment (milaninfy) [reply workspaces/libnpmpack/test/index.js:10]: I'll correct it as chore in next pr whenever I get chance.
