### PR TITLE
publish semver checking bugfixes

### LINKED ISSUE #8017: [BUG] npm 11 publish pre-release does not take publishConfig.tag into account
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running `npm publish` with the following `package.json`:

```json
{
    "name": "@hug/eslint-config",
    "version": "21.0.0-beta.8",
    "publishConfig": {
        "access": "public",
        "tag": "beta"
    },
    ...
}
```

produces the following error with `npm@11.x`:

```sh
npm error You must specify a tag using --tag when publishing a prerelease version.
npm error A complete log of this run can be found in: ....
```

----

@reggi, @wraithgar, I think the issue lies here, where manifest should also be used to retrieve the tag:

https://github.com/npm/cli/blob/7f6c9973dc9a4dfebd76e52e060a9d8496b8bd98/lib/commands/publish.js#L114-L120

### Expected Behavior

I expect the package to be published successfully.

### Steps To Reproduce

1. Create a `package.json` file
2. Add a pre-release `version` (ex: "2.0.0-beta.1")
3. Add a `publishConfig` with a `tag` (ex: "beta")
5. Run `npm publish`
6. See error ```npm error You must specify a tag using --tag when publishing a prerelease version.```

### Environment

- npm: 11.0.0
- Node.js: v22.12.0
- OS Name: macOS 15.2 (24C101)
- System Model Name: Macbook Pro

### PR DESCRIPTION
**Pull request by wraithgar**
This fixes two bugs with how publish checks the highest semver version of existing packages.  

First, it allows for the presence of `publishConfig.tag` to be considered "not default", allowing publish in that situation.

Second, it disregards deprecated versions from consideration when finding if there are any higher versions extant.

Other commits in this PR updates `@npmcli/eslint-config` and removes some max-len bypasses that are no longer needed thanks to that update.

Finally, a scope was added to the test package name in the publish tests.

## References
Closes: https://github.com/npm/cli/issues/8017

### CODE REVIEW

File: lib/commands/publish.js [hunk 1]
```diff
@@ -204,7 +202,7 @@ class Publish extends BaseCommand {
     }
   }
 
-  async #latestPublishedVersion (spec, registry) {
+  async #highestPublishedVersion (spec, registry) {
```
Comment (hashtagchris) [inline lib/commands/publish.js:205]: thank you

File: test/lib/commands/publish.js [hunk 2]
```diff
@@ -876,49 +876,61 @@ t.test('latest dist tag', (t) => {
     // this needs more than one item in it to cover the sort logic
     { version: '50.0.0' },
     { version: '100.0.0' },
+    { version: '101.0.0', deprecated: 'oops' },
     { version: '105.0.0-pre' },
   ]
 
-  t.test('PREVENTS publish when latest version is HIGHER than publishing version', async t => {
+  await t.test('PREVENTS publish when highest version is HIGHER than publishing version', async t => {
```
Comment (hashtagchris) [inline test/lib/commands/publish.js:883]: `await` is needed for nested async tests I take it? Did a linter catch this?

File: test/lib/commands/publish.js [hunk 3]
```diff
@@ -876,49 +876,61 @@ t.test('latest dist tag', (t) => {
     // this needs more than one item in it to cover the sort logic
     { version: '50.0.0' },
     { version: '100.0.0' },
+    { version: '101.0.0', deprecated: 'oops' },
```
Comment (hashtagchris) [inline test/lib/commands/publish.js]: 101.0.0 is used in a test below.
```suggestion
    { version: '102.0.0', deprecated: 'oops' },
```

File: test/lib/commands/publish.js (hunk 2 above)
Comment (wraithgar) [reply test/lib/commands/publish.js:883]: I don't think it's absolutely required, this is the "least likely to surprise us" way of doing things.  tap itself accounts for this, but it shouldn't have to.

File: test/lib/commands/publish.js (hunk 3 above)
Comment (wraithgar) [reply test/lib/commands/publish.js]: Good catch, I'll amend my commit since this PR has multiples I'll be rebasing.

**Review by hashtagchris — APPROVED** [review]
