### PR TITLE
fix(arborist): omit failed optional dependencies from installed deps

### LINKED ISSUE #4828: [BUG] Platform-specific optional dependencies not being included in `package-lock.json` when reinstalling with `node_modules` present
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
[user@host:foo] $ npm -v
8.8.0
[user@host:foo] $ node
Welcome to Node.js v16.14.2.
Type ".help" for more information.
> process.arch
'arm64'
```

I'm working on a team that utilizes a mix of x64-based and m1-based macs, and has CI build processes that uses musl. We're seeing that `npm` is skipping platform-specific optional dependencies for packages such as [`@swc/core`](https://github.com/swc-project/swc/blob/1d1e7dcea5abc8aed5de75ec0326cc72d76dd1d4/package.json#L123-L137) as a result of the `package-lock.json` file being generated without all of them included. In our case, this then causes linting to throw an exception, because one of our eslint plugins depends on @swc, which depends on having the platform specific @swc package also installed.

There seems to be at least two stages of cause to this. Firstly, when installing `@swc/core` from a clean slate working directory `npm` generates a `package-lock.json` with all of the optional dependencies for `@swc/core` listed:

```
[user@host:foo] $ npm install @swc/core
[user@host:foo] $ grep 'node_modules/@swc/core-*' package-lock.json
    "node_modules/@swc/core": {
    "node_modules/@swc/core-android-arm-eabi": {
    "node_modules/@swc/core-android-arm64": {
    "node_modules/@swc/core-darwin-arm64": {
    "node_modules/@swc/core-darwin-x64": {
    "node_modules/@swc/core-freebsd-x64": {
    "node_modules/@swc/core-linux-arm-gnueabihf": {
    "node_modules/@swc/core-linux-arm64-gnu": {
    "node_modules/@swc/core-linux-arm64-musl": {
    "node_modules/@swc/core-linux-x64-gnu": {
    "node_modules/@swc/core-linux-x64-musl": {
    "node_modules/@swc/core-win32-arm64-msvc": {
    "node_modules/@swc/core-win32-ia32-msvc": {
    "node_modules/@swc/core-win32-x64-msvc": {
```

And it only installs the platform specific package:

```
[user@host:foo] $ ls -l node_modules/@swc/
total 0
drwxr-xr-x  22 user  staff  704 Apr 29 15:39 core
drwxr-xr-x   6 user  staff  192 Apr 29 15:39 core-darwin-arm64
```

If I then remove my `package-lock.json`, leave my `node_modules` directory as-is, and then reinstall, I get:

```
[user@host:foo] $ rm -rf package-lock.json
[user@host:foo] $ npm install
[user@host:foo] $ grep 'node_modules/@swc/core-*' package-lock.json
    "node_modules/@swc/core": {
    "node_modules/@swc/core-darwin-arm64": {
```

That is, it **then generates a package-lock.json with only the platform-specific dependency that was installed on this machine, and not with the other optional dependencies that should also be listed**. 

If you delete **both** `node_modules` AND `package-lock.json`, and then re-run `npm install`, it generates the correct lockfile with all of those optional dependencies listed. 

The problem is that then, If the `package-lock.json` with the missing optional platform-specific dependencies gets checked into git and an x64 user pulls it down, or vice-versa, `npm` fails to detect that your platform's optional dependencies are missing in the lockfile and just silently skips installing the platform-specific dependency. For example, when I've got a package-lock.json that only contains the x64 @swc package because of the above problem (generated by my coworker on his x64 machine):

```
[user@host:foo] $ node
Welcome to Node.js v16.14.2.
Type ".help" for more information.
> process.arch
'arm64'
>
[user@host:foo] $ grep 'node_modules/@swc/core-*' package-lock.json
    "node_modules/@swc/core": {
    "node_modules/@swc/core-darwin-x64": {
[user@host:foo] $ ls
package-lock.json package.json
```

And I then install:

```
[user@host:foo] $ npm install
added 1 package in 341ms

1 package is looking for funding
  run `npm fund` for details
[user@host:foo] $ ls node_modules/@swc/
core
```

You can see that it fails to install the arm64 dependency or warn me in any way that the `package-lock.json` is missing my platform's dependency. 

So yeah, two problems:
1. npm is generating an inconsistent package-lock.json when node_modules has your platform-specific dependency installed. 
2. When installing from this inconsistent package-lock.json, npm fails to try to correct the problem by comparing the optional dependencies to what's listed upstream

### Expected Behavior

1. `npm` should preserve the full set of platform-specific optional deps for a package like @swc when rebuilding `package-lock.json` from an existing `node_modules` tree
2. `npm install` should warn if the `package-lock.json` becomes inconsistent because of the first case

### Steps To Reproduce

See above.

### Environment

- npm: 8.8.0
- Node.js:
- OS Name: OSX 
- System Model Name: Macbook Pro

```
[user@host:foo] $ npm -v
8.8.0
[user@host:foo] $ node -v
v16.14.2
[user@host:foo] $ uname -a
Darwin host.foo.com. 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
```

```
[user@host] $ npm config ls
; "user" config from /Users/user/.npmrc
; node bin location = /Users/user/.nvm/versions/node/v16.14.2/bin/node
; node version = v16.14.2
; npm local prefix = /Users/user/Development/foo
; npm version = 8.8.0
; cwd = /Users/user/Development/foo
; HOME = /Users/user
; Run `npm config ls -l` to show all defaults.
```

### LINKED ISSUE #7961: [BUG] optional dependencies for OS/CPU package variants are being pruned unexpectedly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Starting from npm v10.3.0, optional dependencies for OS and CPU package variants are being pruned from `package-lock.json` when running `npm install` and a `node_modules` folder is present. This breaks npm installs when the resulting lockfile is pulled onto other platforms - such as devs working on their Macs (darwin/arm64) who are pushing their code to CI (linux/x64). This change in behaviour does not appear to be intentional as it is not documented or  referenced anywhere. Possibly related to #7543. Possibly a dupe of #4828 and #7750.

The issue may be mitigated by deleting `node_modules/` before running the install command.

### Expected Behavior

Optional OS and CPU package variants should not be pruned from `package-lock.json` as was the behaviour prior to npm v10.3.0 to allow the lockfile to be used for cross-platform installs.

### Steps To Reproduce

[Unexpected behaviour](https://github.com/npm/cli/issues/7961#issuecomment-2526390091) ❌:

1. `mkdir test && cd test`
2. `npm init -y`
3. `npm i -D rollup`
4. Read `package-lock.json` - observe 18 OS/CPU`@rollup/*` package variants are listed
5. `rm package-lock.json`
6. `npm i`
7. Read `package-lock.json` - observe only 1 OS/CPU `@rollup/*` package variant is now listed for the current platform

Expected behaviour test 1 ✅:

1. `mkdir test && cd test`
2. `npm init -y`
3. `npm i -D rollup`
4. Read `package-lock.json` - observe 18 OS/CPU`@rollup/*` package variants are listed
5. `rm -rf node_modules`
7. `npm i`
8. Read `package-lock.json` - observe 18 OS/CPU`@rollup/*` package variants are listed

Expected behaviour test 2 ✅:

1. `mkdir test && cd test`
2. `npm init -y`
3. `npm i -D rollup`
4. Read `package-lock.json` - observe 18 OS/CPU`@rollup/*` package variants are listed
5. `npm i -D esbuild`
6. Read `package-lock.json` - observe 18 OS/CPU`@rollup/*` package variants are listed

### Environment

- npm: 10.9.2
- Node.js: 22.17 
- OS Name: macOS 14.5
- System Model Name: M1 Macbook Pro
- npm config:

```ini
; node bin location = /Users/xxx/.nvm/versions/node/v20.17.0/bin/node
; node version = v20.17.0
; npm local prefix = /Users/xxx/Projects/test
; npm version = 10.9.2
; cwd = /Users/xxx/Projects/test
; HOME = /Users/xxx
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by owlstronaut**
… but keep them 'in the tree'

This PR was authored by @zkat 

Fixes: https://github.com/npm/cli/issues/4828
Fixes: https://github.com/npm/cli/issues/7961
Replaces: https://github.com/npm/cli/pull/8127
Replaces: https://github.com/npm/cli/pull/8077

When optional dependencies fail, we don't want to install them, for whatever reason. The way this "uninstallation" is done right now is by simply removing the dependencies from the ideal tree during reification.

Unfortunately, this means that what gets saved to the "hidden lockfile" is the edited ideal tree as well, and when npm runs next, it'll use that when regenerating the "real" package-lock.

This PR tags failed optional deps such that they're still added to the "trash list" (and thus have their directories cleaned up by the reifier), but prevents Arborist from removing them altogether from the ideal tree (which is usually done by setting their parent to `null`, making them unreachable, and letting them get GC'd).

PS: It's Friday, this is what I managed to get done together. I'm making this a draft PR for now so folks can look at it, but I want to make sure both reifiers work well, fix some messaging issues, and clean stuff up (I'm pretty sure I'm guarding `ideallyInert` in more places than I need to, because I was trying to find the right spot). Still, feel free to talk about the approach. I'll get back to this on Monday.

PPS: also hi

### CODE REVIEW

File: workspaces/arborist/lib/shrinkwrap.js [hunk 1]
```diff
@@ -144,7 +144,7 @@ const assertNoNewer = async (path, data, lockTime, dir, seen) => {
   let entries
   if (dir === path) {
     entries = [{ name: 'node_modules', isDirectory: () => true }]
-  } else if (!inert) {
+  } else {
```
Comment (owlstronaut) [inline workspaces/arborist/lib/shrinkwrap.js]: I removed this check because of the `if (inert) return` on line 140

File: workspaces/arborist/lib/arborist/reify.js [hunk 2]
```diff
@@ -240,9 +240,9 @@ module.exports = cls => class Reifier extends cls {
 
     // Preserve inertness for failed stuff.
     if (this.actualTree) {
-      for (const [loc, actual] of this.actualTree.inventory.entries()) {
+      for (const actual of this.actualTree.inventory.values()) {
         if (actual.ideallyInert) {
-          const ideal = this.idealTree.inventory.get(loc)
+          const ideal = this.idealTree.inventory.get(actual.name)
```
Comment (owlstronaut) [inline workspaces/arborist/lib/arborist/reify.js]: I wasn't able to get this working (the tests) with the loc. Is it possible we wanted the name for the idealTree inventory?

File: workspaces/arborist/lib/arborist/reify.js [hunk 3]
```diff
@@ -243,6 +243,7 @@ module.exports = cls => class Reifier extends cls {
       for (const actual of this.actualTree.inventory.values()) {
         if (actual.ideallyInert) {
           const ideal = this.idealTree.inventory.get(actual.name)
+          /* istanbul ignore else */
```
Comment (owlstronaut) [inline workspaces/arborist/lib/arborist/reify.js]: once I made the change to `name` above, I wasn't able to make it _not_ work

**Comment by owlstronaut** [comment]
@zkat I did what I could here. Had a couple of comments/lack of my own clarity in things I changed - see above.

File: workspaces/arborist/lib/arborist/reify.js (hunk 3 above)
Comment (wraithgar) [reply workspaces/arborist/lib/arborist/reify.js]: add a comment to the code itself as to why this is ignored please

**Comment by wraithgar** [comment]
Other than the comment we really really should re-use the exceptional description from https://github.com/npm/cli/pull/8177, either by copying it into this issue now or when we merge.  Probably easier to do now.  I'll do it now.

File: workspaces/arborist/lib/arborist/reify.js (hunk 2 above)
Comment (zkat) [reply workspaces/arborist/lib/arborist/reify.js]: that's pretty strange, but something doesn't feel right about using the `actual.name`. Isn't that the *package* name? In that case, this is absolutely not what you want. You want the full path of the dependency in the tree (which I've been assuming is what loc is).

What was wrong with loc? My local testing made everything seem ok.

File: workspaces/arborist/lib/arborist/reify.js (hunk 3 above)
Comment (owlstronaut) [reply workspaces/arborist/lib/arborist/reify.js]: https://github.com/npm/cli/pull/8184/commits/b96a5cbc618206416dd683c6269a2b1f02af9065

File: workspaces/arborist/lib/arborist/reify.js (hunk 2 above)
Comment (owlstronaut) [reply workspaces/arborist/lib/arborist/reify.js]: @zkat https://github.com/npm/cli/pull/8184/commits/64b838401a58381e9c9327a6f82bef853a24448a

Okay, I reverted it - but struggling to get the tests set up to find a value there

Comment (zkat) [reply workspaces/arborist/lib/arborist/reify.js]: Yeah, I'm looking now and I think I realized my mistake: look at line 198 and its comment.

This might just need an extra guard against entries that happen to be in the actualTree, but not the idealTree.

Comment (zkat) [reply workspaces/arborist/lib/arborist/reify.js]: ah hmmm

Comment (zkat) [reply workspaces/arborist/lib/arborist/reify.js]: update: sussed this out with @owlstronaut over DMs. :)

tl;dr the failing coverage is because we need a test that covers "install w/ a failing optional, then rerun a 'no-op' install", since that's what'll trigger this block of code that's just meant to preserve the ideallyInert flag in that specific situation.

File: workspaces/arborist/lib/arborist/reify.js (hunk 3 above)
Comment (owlstronaut) [reply workspaces/arborist/lib/arborist/reify.js]: https://github.com/npm/cli/pull/8184/commits/f635c978a3045bcb35322717c656a02e2ceafeb4

even better, doing things the correct way means I could get rid of it and have coverage

File: workspaces/arborist/lib/arborist/reify.js (hunk 2 above)
Comment (owlstronaut) [reply workspaces/arborist/lib/arborist/reify.js]: https://github.com/npm/cli/pull/8184/commits/f635c978a3045bcb35322717c656a02e2ceafeb4

Done! Thank you :)

File: workspaces/arborist/lib/arborist/build-ideal-tree.js [hunk 4]
```diff
@@ -1527,7 +1528,7 @@ This is a one-time fix-up, please be patient...
 
       const set = optionalSet(node)
       for (const node of set) {
-        node.parent = null
+        node.ideallyInert = true
```
Comment (zkat) [inline workspaces/arborist/lib/arborist/build-ideal-tree.js:1531]: I've been thinking about this, and maybe it's better to just call it `inert` instead of `ideallyInert`. I think putting the `ideally` in there is probably a bit too much clever inside baseball and it's more verbose to boot. :)

Some other name would be good, too, as long as it communicates that this is in the tree, but we don't physically install it.

**Comment by paulrutter** [comment]
Thanks for pulling this work forward, much appreciated @zkat @owlstronaut @wraithgar.
Happy to see this is almost ready to get merged.

**Review by wraithgar — APPROVED** [review]

**Comment by jakebailey** [comment]
Amazing, I'm so excited for this to be fixed. Thank you @zkat @owlstronaut @wraithgar 🎉

**Comment by JounQin** [comment]
@jakebailey Can this be back ported into old versions?

**Comment by wraithgar** [comment]
This is not going to be backported.

**Comment by domino14** [comment]
I still get this bug btw, despite updating node, npm, AND deleting my package-lock.json and node_modules and reinstalling.

```
Error: Cannot find module @rollup/rollup-linux-arm64-musl. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
```


I even added this to package.json:

```
    "optionalDependencies": {
        "@rollup/rollup-linux-arm64-musl": "^4.46.0",
        "@rollup/rollup-linux-x64-gnu": "^4.46.0"
    },
```

The only way I got it to work is by doing this:

```
docker compose run --rm my_service_name
 sh -c "rm -rf package-lock.json node_modules && npm install"
```

which is dumb because i have to get all our devs to do it and all the other issues with deleting lockfiles and reinstalling everything. help!
