### PR TITLE
fix(npx): properly look for local bins when there are more than one

### LINKED ISSUE #5777: [BUG] `exec`/`npx`: npm v8.8+/9+ break with a self-reference
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

In a package `foo` with a bin, run `npx foo`, and you'll see `sh: foo: command not found`.

### Expected Behavior

In a package `foo` with a bin, run `npx foo`, and the bin is invoked.

### Steps To Reproduce

1. Clone any repo, presumably, but in this case, https://github.com/ljharb/publishers
2. Run `npx npm@8.7 exec publishers`, see that it invokes the binary properly.
3. Run `npx npm@8.8 exec publishers`, see that it errors.

### Environment

- npm: <= 8.7, >= 8.8
- Node.js: 19

### PR DESCRIPTION
**Pull request by wraithgar**
npx still thought it had to translate the bin name after it found one in the local package.

Closes https://github.com/npm/cli/issues/5777
again

### CODE REVIEW

**Comment by lukekarrys** [comment]
Edit: I opened #5848 instead of fixing up this branch. Only one of this PR and #5848 should be landed in the current form. 

---

I pushed some fixups to this branch with an idea I had and I think it works? It's my first time working in `libnpmexec`, so correct me if I'm wrong here.

I attempted to make the logic for the local manifest lookup the same as the logic for local and global bins.

So it no longer does any `arborist.loadActual()` calls and instead calls the bin file directly if it exists via the `@npmcli/run-script` `call` option. This made it go from `~2.5s` to `~0.7s` to call a mostly empty bin script.

File: workspaces/libnpmexec/test/index.js [hunk 1]
```diff
@@ -28,6 +28,7 @@ t.test('bin in local pkg', async t => {
   const pkg = {
     name: '@npmcli/local-pkg-bin-test',
     bin: {
+      b: 'echo this is something else',
```
Comment (nlf) [inline workspaces/libnpmexec/test/index.js:31]: should this be used in the test? how are we proving that it found this bin?

Comment (nlf) [reply workspaces/libnpmexec/test/index.js:31]: also this isn't a bin, it's a script, so that's weird a little

Comment (wraithgar) [reply workspaces/libnpmexec/test/index.js:31]: The whole point of this bugfix was that if there are multiple bin entries things still work.  So a second bin entry that's just an echo sufficed for the tests.

Comment (wraithgar) [reply workspaces/libnpmexec/test/index.js:31]: It's supposed to find `a`. `b` existing is enough to satisfy the regression this is fixing.

Comment (nlf) [reply workspaces/libnpmexec/test/index.js:31]: disregard, the test throwing before the fix and not throwing after is fine for now :+1:

**Review by nlf — APPROVED** [review]
