### PR TITLE
Use configured registry when checking manifest for npm install

### LINKED ISSUE #3758: [BUG] Changing NPM version when on 7.23.0 ignores registry option
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use an internal network for development. Because of this, I have a mirror of the npm registry. After I updated npm to version 7.23.0 and attempted to downgrade npm to version 7.22.0 using `npm install --global npm@7.22.0`, I noticed the install would fail because npm was ignoring the registry I specified. This operation was forced to use the default registry `https://registry.npmjs.org/npm` during one of it's checks.

### Expected Behavior

I would expect that if an alternative registry is provided, the npm install checks would use that registry and continue the install process.

### Steps To Reproduce

1. In this environment...
  a. Any OS without an internet connection that uses a mirror of the npm registry on an internal network.
  b. Need to be using npm version 7.23.0.
2. With this config...
```
registry = "https://my.awesome.npm.mirror/npm"
```
3. Run `npm install --global npm@7.22.0`
4. See error...
```
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/npm failed, reason getaddrinfo ENOTFOUND registry.npmjs.org
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

### Environment

- OS: Any
- Node: v12.14.0
- npm: 7.23.0

### PR DESCRIPTION
**Pull request by yacoman89**
This fix resolves #3758.

The package pacote accepts options as it's second parameter for the manifest call and these options allow you to pass the desired registry to use. The npm config object already has this information, so it's just passed in now.

### CODE REVIEW

File: lib/install.js [hunk 1]
```diff
@@ -135,7 +135,7 @@ class Install extends ArboristWorkspaceCmd {
     // be very strict about engines when trying to update npm itself
     const npmInstall = args.find(arg => arg.startsWith('npm@') || arg === 'npm')
     if (isGlobalInstall && npmInstall) {
-      const npmManifest = await pacote.manifest(npmInstall)
+      const npmManifest = await pacote.manifest(npmInstall, { registry: this.npm.config.get('registry') })
```
Comment (wraithgar) [inline lib/install.js]:
```suggestion
      const npmManifest = await pacote.manifest(npmInstall, this.npm.flatOptions)
```

**Comment by wraithgar** [comment]
Good catch!  The `flatOptions` attribute is a flattened form of the config intended to be passed to other components.  Looks like this call got missed.

**Comment by wraithgar** [comment]
Looks like linting failed. Max line length is 80, line is 81.  We're upping that limit soon but for today you'll have to break it up.

**Comment by wraithgar** [comment]
That worked!  Thank you very much for submitting this PR.
