### PR TITLE
fix(config): use redact on config output

### LINKED ISSUE #3867: [BUG] Password in plain text when getting the proxy details from config through CLI
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever we set the proxy in our config through CLI command
`npm config set proxy "http://username:password@servername:port/"` 
It is stored in plain text in our config, so whenever we fire the following command
`npm get proxy`
the sensitive information like password is shown on CLI, which I think is a security vulnerability. 
Also, the password is also stored in your local config file as a plain text.

### Expected Behavior

When `npm get proxy` is fired, the password should not be shown or should be encrypted. Password in your local npm config file also should be encrypted. 

### Steps To Reproduce

first run the command to setup your proxy for npm
`npm config set proxy "http://domain\username:password@servername:port/"`
then run
`npm get proxy`

### Environment

- OS:  Windows
- Node:  12.16.3
- npm: 6.14.4

### PR DESCRIPTION
**Pull request by lukekarrys**
Fixes #3867

### CODE REVIEW

File: lib/commands/config.js [hunk 1]
```diff
@@ -73,6 +74,10 @@ const publicVar = k => {
       }
     }
   }
+  // Hide proxy url if it contains basic auth
+  if (k === 'proxy') {
```
Comment (wraithgar) [inline lib/commands/config.js]: This is confusing to me.  This function is a true/false test of whether or not npm should hide the value altogether.  This makes the function try to do two things, and I don't think it's doing it correctly down below.   Or if it is, I don't understand how.

Comment (wraithgar) [reply lib/commands/config.js]: Ooooh I see, it's comparing it to the redacted value.  If it has private info it won't return.

Can we redact this and display it instead?  Showing it sometimes and not others seems weird to me.

**Comment by wraithgar** [comment]
I think if we're gonna redact we redact.  We should acknowledge that there are some values that aren't worth showing at all (and they are currently accounted for) but some that may contain urls with passwords.  Proxy and registry come to mind.  If we simply pass all of the displayed values through redact (now that we are using it) this would help

**Comment by lukekarrys** [comment]
+1 for treating registry however we end up treating proxy

File: lib/commands/config.js (hunk 1 above)
Comment (lukekarrys) [reply lib/commands/config.js]: Yeah it doesn't feel perfect to me either but better than what we do currently.

If we show a redacted value, do we treat "redacted" vs "protected" differently in the different forms of output?

You can get a config value with `config ls`, `config get <key>`, and `config ls --json`. Here's an example with proxy before and after what's currently in this PR:

```sh
# before
❯ npm config ls | grep proxy
proxy = "http://username:password@servername.com"
❯ npm config get proxy
http://username:password@servername.com
❯ npm config ls --json | jq .proxy
"http://username:password@servername.com"

# after
❯ npmlocal config ls | grep proxy
proxy = (protected)
❯ npmlocal config get proxy
npm error The proxy option is protected, and can not be retrieved in this way
npm error A complete log of this run can be found in: /Users/lukekarrys/.npm/_logs/2024-05-14T17_24_43_600Z-debug-0.log
❯ npmlocal config ls --json | jq .proxy
null
```

My vote would be to treat "redacted" and "protected" the same for `config get <key>` and `config ls --json`, but to show the redacted value in `config ls`. Wdyt?

Comment (lukekarrys) [reply lib/commands/config.js]: Took another attempt at this and made a new function in addition to `publicVar` that determines how to display a field. It will treat redacted and protected fields the same (so no individual getting, excluding from json) except in the case of `npm config ls` in which case it will show the redacted string like `http://u:***@registry.com` instead of `(protected)`.

Comment (wraithgar) [reply lib/commands/config.js]: > If we show a redacted value, do we treat "redacted" vs "protected" differently in the different forms of output

Yes.  Some fields we know are always not to be shown, and also unlikely to be caught by our very limited redaction attempts.  Those can not be trusted to be redacted and will always need to show `protected`

Comment (lukekarrys) [reply lib/commands/config.js]: 👍🏼 That's what I did in my latest commit.

File: lib/commands/config.js [hunk 2]
```diff
@@ -73,9 +81,25 @@ const publicVar = k => {
       }
     }
   }
+  // Redacted fields are public unless they contain redacted info
+  if (redacted.includes(k)) {
```
Comment (wraithgar) [inline lib/commands/config.js:85]: hot take: why limit this to these fields?

File: lib/commands/config.js [hunk 3]
```diff
@@ -73,9 +81,25 @@ const publicVar = k => {
...
+    return redact(v) === v
+  }
   return true
 }
 
+const displayVar = (k, v) => {
+  let value
+  if (publicVar(k, v)) {
+    value = JSON.stringify(v)
+  } else if (redacted.includes(k)) {
```
Comment (wraithgar) [inline lib/commands/config.js]: What would be the harm in just redacting everything on display?

Comment (lukekarrys) [reply lib/commands/config.js]: We've already determined within `publicVar` that if it returns `true` then `redact(v) === v`, but I think it does make the code clearer by eliminating an if branch. So it would look like:

```js
const displayVar = (k, v) => {
  let value
  if (publicVar(k, v) || redacted.includes(k)) {
    value = JSON.stringify(redact(v))
  } else {
    value = '(protected)'
  }
  return `${k} = ${value}`
}
```

Comment (wraithgar) [reply lib/commands/config.js]: `publicVar` already looks in `redacted` and only returns true if it's not needed you don't need to check `redacted` again.

Comment (lukekarrys) [reply lib/commands/config.js]: But we want to display `redacted` differently than `protected`, and both states are a subset of non-public.

File: lib/commands/config.js [hunk 4]
```diff
@@ -338,18 +346,17 @@ ${defData}
         continue
       }
 
-      const keys = Object.keys(data).sort(localeCompare)
+      const keys = Object.entries(data).sort(([a], [b]) => localeCompare(a, b))
```
Comment (lukekarrys) [inline lib/commands/config.js]:
```suggestion
      const entries = Object.entries(data).sort(([a], [b]) => localeCompare(a, b))
```

**Review by wraithgar — APPROVED** [review]
