### PR TITLE
fix(arborist): workspaces correctly path to file: packages from over…

### LINKED ISSUE #5584: [BUG] `npm install` generates wrong `overrides` link
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`node_modules/print` is linked to `../hello/print`

### Expected Behavior

`node_modules/print` should be linked to `../print`

### Steps To Reproduce

```bash
git clone https://github.com/szmarczak/npm-overrides-bug && cd npm-overrides-bug

# This does not work, but should
cp package.json.error package.json && npm install && node index.js

# This works
cp package.json.ok package.json && npm install && node index.js
```

If successful, it will output `Hello, world!`. If not successful, it will output `Error: Cannot find module 'print'`

### Environment

- npm: 8.19.1
- Node.js: v18.9.0
- OS Name: Ubuntu
- System Model Name: doesn't matter
- npm config:
```ini
$ npm config ls
; "user" config from /home/szm/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /home/szm/.nvm/versions/node/v18.9.0/bin/node
; node version = v18.9.0
; npm local prefix = /tmp/test
; npm version = 8.19.1
; cwd = /tmp/test
; HOME = /home/szm
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by owlstronaut**
Fixes: https://github.com/npm/cli/issues/5584

This pull request introduces changes to the `Reifier` class in `workspaces/arborist/lib/arborist/reify.js` to handle root overrides with `file:` paths and adds a corresponding test case. The most important changes include the addition of a new method to calculate relative paths and the inclusion of a test to verify the new functionality.

I learned about how windows does symlinks in this (junctions). Interesting difference.

### CODE REVIEW

File: workspaces/arborist/lib/arborist/reify.js [hunk 1]
```diff
@@ -825,7 +825,14 @@ module.exports = cls => class Reifier extends cls {
     // symlink
     const dir = dirname(node.path)
     const target = node.realpath
-    const rel = relative(dir, target)
+
+    let rel
+    if (node.resolved && node.resolved.startsWith('file:')) {
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/reify.js]:
```suggestion
    if (node.resolved?.startsWith('file:')) {
```

**Review by wraithgar — APPROVED** [review]
