### PR TITLE
fix: ignore implict workspace for some commands

### LINKED ISSUE #4404: [BUG] `npm adduser` fails in workspace.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Since 8.5.0, running `npm adduser` from a workspace fails with `ENOWORKSPACES`.

### Expected Behavior

Running `npm adduser` from a workspace should be as-if it was run from the top-level directory.

### Steps To Reproduce

1. Scaffold npm workspace project:
```
mdkir testproject
cd testproject
npm init -y
npm init -y -w ./packages/a
```
2. cd into the workspace: `cd packages/a`
3. Run `npm adduser`
4. See error:
```
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.
```

### Environment

- npm: npm 8.5.0
- Node.js: 16.14.0
- OS Name: Windows 10
- System Model Name: N.A.
- npm config: N.A.

### PR DESCRIPTION
**Pull request by fritzy**
For some commands, ignore implicit cwd workspace config and run as if no workspace filter is set.

'adduser', 'access', 'login', 'bin', 'birthday', 'bugs', 'cache', 'help-search', 'help', 'hook', 'logout', 'org', 'ping', 'prefix', 'profile', 'root', 'search', 'token'

closes #4404

Special thanks to @mshima for submitting a similar PR #4439

### CODE REVIEW

File: lib/npm.js [hunk 1]
```diff
@@ -24,6 +24,28 @@ const _tmpFolder = Symbol('_tmpFolder')
 const _title = Symbol('_title')
 const pkg = require('../package.json')
 
+const ignoreWorkspacesCommands = new Set([
```
Comment (wraithgar) [inline lib/npm.js]: This set is pretty decoupled from the commands themselves.  Can we have a static attribute on the commands to inform npm what to do instead?

File: lib/base-command.js [hunk 2]
```diff
@@ -20,6 +20,10 @@ class BaseCommand {
     return this.constructor.description
   }
 
+  get ignoreImplicitWorkspace () {
+    return !!this.constructor.ignoreImplicitWorkspace
+  }
```
Comment (ljharb) [inline lib/base-command.js]: why not just `static ignoreImplicitWorkspace = false`? subclasses can override it the same.

Comment (wraithgar) [reply lib/base-command.js]: This follows the pattern we have for the other static attributes.  The `!!` isn't really needed. But we need to add to the tests that check that every command has a name, et al defined so that this attribute is on that list.

Comment (ljharb) [reply lib/base-command.js]: sure - but how would that not be the case with a static field on the base command?

Comment (wraithgar) [reply lib/base-command.js]: We don't currently define any static fields on the base command.  The pattern today is that every command has to define them, and we enforce that constraint in tests.  It's our current decision for balancing intentionality and dry/terseness.

Comment (fritzy) [reply lib/base-command.js]: The pattern right now has no static properties in the base command. Following the pattern of other static properties, added it as a required property in the implementation test, removed the `!!`, and updated all of the commands.

Comment (ljharb) [reply lib/base-command.js]: I'm pretty confused; i must just not understand what a "base command" is.

**Comment by antongolub** [comment]
Shouldn't `ignoreImplicitWorkspace` be set `true` for `whoami`?

**Comment by wraithgar** [comment]
> Shouldn't `ignoreImplicitWorkspace` be set `true` for `whoami`?

What if a workspace has an alternate registry or auth config?

File: lib/npm.js [hunk 3]
```diff
@@ -113,12 +113,18 @@ class Npm extends EventEmitter {
...
     if (workspacesEnabled === false && workspacesFilters.length > 0) {
       throw new Error('Can not use --no-workspaces and --workspace at the same time')
     }
 
-    const filterByWorkspaces = workspacesEnabled || workspacesFilters.length > 0
+    // only call execWorkspaces when we have workspaces explicitly set
+    // or when it is implicit and not in our ignore list
+    const filterByWorkspaces =
+      (workspacesEnabled || workspacesFilters.length > 0)
+      && (!implicitWorkspace || !command.ignoreImplicitWorkspace)
```
Comment (mshima) [inline lib/npm.js:126]: Adjust the comment:
```suggestion
    // only call execWorkspaces when we have workspaces explicitly set
    // and when it is not implicit or not marked as ignore implicit workspace
    const filterByWorkspaces =
      (workspacesEnabled || workspacesFilters.length > 0)
      && (!implicitWorkspace || !command.ignoreImplicitWorkspace)
```

Comment (mshima) [reply lib/npm.js:126]: And `implicitWorkspace` shouldn't conflict with explicit workspace? Or explicit shouldn't take precedence?

Comment (fritzy) [reply lib/npm.js:126]: There's a lot of ways we could slice it. Right now, if your cwd is a workspace, it'll run the command and ignore any explicit workspace you specify. This makes sense for something like `bin`, which has always worked on cwd, but it could be confusing for other commands. If you're not in a workspace and and you specify one, many commands will still fail.

We could go back and forth on the best way to handle these edge cases, but ultimately, I'd rather ship and iterate. If there are cases and commands that need more tweaking, we could patch the behavior again. But for now, this gets us back to running commands that don't really care about workspaces, but generally still errors if you try to explicitly set a workspace on a command that doesn't support them.

File: lib/npm.js [hunk 4]
```diff
@@ -113,12 +113,18 @@ class Npm extends EventEmitter {
     }
 
     const workspacesEnabled = this.config.get('workspaces')
+    /* istanbul ignore next */
```
Comment (wraithgar) [inline lib/npm.js]: Why is this ignored?

Comment (fritzy) [reply lib/npm.js]: The config module runs mapWorkspaces when setting the local prefix, and should set the default workspace value to an array. However, that is within a few layers of flow control deep on a dependency. As such, the next line ensures that the value is at least an empty array before proceeding. There's no good way to force it to not be an array without being entirely artificial and self-exercising. As such, this guard is in place, and we don't have a meaningful way of testing the case in which it would be executed.

**Review by wraithgar — APPROVED** [review]

File: lib/commands/whoami.js [hunk 5]
```diff
@@ -5,6 +5,7 @@ class Whoami extends BaseCommand {
   static description = 'Display npm username'
   static name = 'whoami'
   static params = ['registry']
+  static ignoreImplicitWorkspace = false
```
Comment (jedwards1211) [inline lib/commands/whoami.js:8]: @fritzy is there a reason `whoami` depends on workspaces?

**Comment by jedwards1211** [comment]
@wraithgar

> What if a workspace has an alternate registry or auth config?

What would such a config look like?  I'm having trouble finding anything about it in the npm docs

And also if so, I must fundamentally misunderstand something:
- wouldn't the alternate registry also apply to `adduser`, `login`, `logout`, etc?
- why does `whoami` say it doesn't support workspaces?  Shouldn't it just get the  user associated with the workspace's registry/auth config?
