### PR TITLE
fix: pass strings to JSON.stringify in --json mode

### LINKED ISSUE #7537: [BUG] `npm view` returning string without quotes with version 10.8.0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When using `npm view <package> <selector> --json`, I expect only to receive JSON data types. Unfortunately, for `npm@10.8.0` that's not the case anymore.

Running `npm view expo-template-bare-minimum@sdk-51 dist.tarball --json` now yields the `tarball` string, without quotes, making it not a JSON result anymore.

image

### Expected Behavior

When using this same command with `npm@10.7.0`, the response is wrapped in quotes, making it a valid JSON response (or at least parsable through `JSON.parse(...)`.

image

### Steps To Reproduce

Result that's _not_ parsable with `JSON.parse`:
1. `$ npm i -g npm@10.8.0`
2. `$ npm -v` → Should return `10.8.0`
3. `$ npm view expo-template-bare-minimum@sdk-51 dist.tarball --json`
  → Should return `https://...` _(without quotes)_

Result that _is_ parsable with `JSON.parse`:
1. `$ npm i -g npm@10.7.0`
2. `$ npm -v` → Should return `10.7.0`
4. `$ npm view expo-template-bare-minimum@sdk-51 dist.tarball --json`
  → Should return `"https://..."` _(with quotes)_

### Environment

- npm: 10.8.0
- Node.js: 22.2.0
- OS Name: macOS Sanoma 14.4.1
- System Model Name: MacBook Pro (14" 2023)
- npm config:
```ini
; "user" config from /Users/cedric/.npmrc

//registry.npmjs.org/:_authToken = (protected)
store-dir = "/Users/cedric/.pnpm"

; node bin location = /Users/cedric/.nvm/versions/node/v22.2.0/bin/node
; node version = v22.2.0
; npm local prefix = /Users/cedric/Desktop
; npm version = 10.8.0
; cwd = /Users/cedric/Desktop
; HOME = /Users/cedric
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by lukekarrys**
In refactoring this behavior previously plain strings were no longer
being passed through JSON.stringify even in json mode. This commit
changes that to the previous behavior which fixes the bug in `npm view`.
This also required changing the behavior of `npm pkg` which relied on this.

Fixes #7537

### CODE REVIEW

**Review by wraithgar — APPROVED** [review]

File: lib/utils/display.js [hunk 1]
```diff
@@ -82,26 +82,31 @@ const ERROR_KEY = 'error'
...
+    }
+    // We use objects with 0,1,2,etc keys to merge array
+    if (items.every((o, i) => Object.hasOwn(o, i))) {
+      return Object.assign([], ...items)
+    }
   }
-  // Otherwise its an object with all items merged together
-  return Object.assign({}, ...items)
+  // Otherwise its an object with all object items merged together
+  return Object.assign({}, ...items.filter(o => isPlainObject(o)))
```
Comment (ljharb) [inline lib/utils/display.js:100]:
```suggestion
  return { ...items.filter(o => isPlainObject(o)) }
```
not a huge deal, but this should be slightly faster

**Review by ljharb — APPROVED** [review]

File: lib/utils/display.js (hunk 1 above)
Comment (lukekarrys) [reply lib/utils/display.js:100]: items is an array of objects, so i dont think it can be spread within another object in the same way as arguments to a function

```js
> Object.assign({}, ...[{a:1},{b:2}])
{ a: 1, b: 2 }
> { ...[{a:1},{b:2}] }
{ '0': { a: 1 }, '1': { b: 2 } }
```

Comment (ljharb) [reply lib/utils/display.js:100]: ahhh you're totally right
