### PR TITLE
fix some flat options

### LINKED ISSUE #2747: [BUG] `npm install --package-lock-only` does not imply `--package-lock`
### Current Behavior:
put `package-lock=false` in `.npmrc`.

Run `npm install --package-lock-only`.

### Expected Behavior:
a package-lock.json is generated.

### Steps To Reproduce:
See above.

### Environment:
- npm: 7.5.4

This is a regression from https://github.com/npm/cli/pull/146 / v6.9.0.

(possibly related to #2358)

### LINKED ISSUE #3572: [BUG] npm set does not respect -g flag in 7.20.0 onwards
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
npm set -g foo bar
```

In npm < 7.20.0, this writes `foo=bar` to the _global_ npm config file (`/usr/local/etc/npmrc`).

In npm >= 7.20.0, the `-g` flag is not respected and `foo=bar` is written to the _user_ npm config file (`~/.npmrc`).

### Expected Behavior

The `-g` flag should result in a modification to the global config, not the user config.

### Steps To Reproduce

1. Run `npm set -g foo bar`.
2. Run `npm get`.
3. Note that `foo` has been set in the user config rather than the global config.

### Environment

- OS: macOS 10.15.7
- Node: 14.17.3
- npm: 7.20.0

### PR DESCRIPTION
**Pull request by nlf**
This corrects two things,

`--global` implies `--location=global` and `--package-lock-only` implies `--package-lock`

it also introduces a new sandbox runner for testing purposes. it's not the prettiest thing i've ever written, but it seems to do the job pretty nicely and doesn't require keeping track of wild shenanigans everywhere.

## References

Fixes #2747
Fixes #3572

### CODE REVIEW

File: lib/config.js [hunk 1]
```diff
@@ -121,7 +121,7 @@ class Config extends BaseCommand {
           break
         case 'list':
         case 'ls':
-          await (this.npm.config.get('json') ? this.listJson() : this.list())
+          await (this.npm.flatOptions.json ? this.listJson() : this.list())
```
Comment (wraithgar) [inline lib/config.js:124]: We really really really need to answer the "what do derived config values look like" question.

File: test/lib/config.js [hunk 2]
```diff
@@ -1,659 +1,379 @@
...
-const Config = t.mock('../../lib/config.js', mocks)
-const config = new Config(npm)
-
-t.test('config no args', t => {
-  config.exec([], (err) => {
-    t.match(err, /usage instructions/, 'should not error out on empty locations')
-    t.end()
-  })
-})
+spawk.preventUnmatched()
```
Comment (wraithgar) [inline test/lib/config.js:7]: Does this ever get unset? I could see this causing problems w/ other tests unexpectedly.

**Review by wraithgar — APPROVED** [review]
