### PR TITLE
fix: move run-script banners to stderr when in json mode

### LINKED ISSUE #7354: [BUG] npm-pack --json emits prepare script commands, making json invalid
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```npm pack --json``` in the latest npm version  (10.5.0) emits prepare script commands and thus making the output invalid json.
This is a breaking change from previous npm version, which broke our deploy workflows. 

image

### Expected Behavior

```npm pack --json``` should always output valid json, as it was in the previous versions.

image

### Steps To Reproduce

Create a package which includes a prepare script.
Run ```npm pack --json```

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

### PR DESCRIPTION
**Pull request by lukekarrys**
Fixes #7354

### CODE REVIEW

File: docs/bin/build.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ const run = require('../lib/build.js')
 const { paths } = require('../lib/index')
 
 run(paths)
-  .then((res) => console.log(`Wrote ${res.length} files`))
+  .then((res) => console.error(`Wrote ${res.length} files`))
```
Comment (lukekarrys) [inline docs/bin/build.js:19]: This change was made so that our `prepack` script doesn't log anything to stdout, so that a smoke-test could be added that running `node . pack --json` only ends up with json parseable output on stdout.

This highlights an important note about this change, as it only redirects the banner from `@npmcli/run-script` to stderr when --json is set. The user's `run-script` is spawned with `stdio: inherit` so if that process sends output to stdout it could still break in json mode. This is not something npm should change since we want to allow spawned process to write to whatever stream they want.

If a user really wants to ensure that the script cannot output anything, they should also use `--foreground-scripts=false` or `--silent`.

**Review by wraithgar — APPROVED** [review]
