### PR TITLE
fix: correctly handle object licenses in SBOM generation

### LINKED ISSUE #6966: [BUG] SBOM generation for SPDX generates invalid format for licenses - `Invalid type. Expected: string, given: object`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The generated SPDX SBOM cannot be parsed by tools, as it generates incorrectly structured JSON.

### Expected Behavior

An SPDX v2.3 SBOM generated from a repository can be parsed correctly.

### Steps To Reproduce

1. Clone https://gitlab.com/tanna.dev/renovate-graph
2. Run `npm  sbom --sbom-format spdx > spdx.json`
3. Run through an SPDX validator i.e. `go run github.com/CycloneDX/sbom-utility@latest validate --input-file spdx.json`

[renovate-graph.spdx.json](https://github.com/npm/cli/files/13260551/renovate-graph.spdx.json)

### Environment

- npm: 10.2.3
- Node.js: v18.17.1
- OS Name: Linux
- System Model Name:
- npm config:
```ini
; "user" config from /home/jamie/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /usr/bin/node
; node version = v18.17.1
; npm local prefix = /home/jamie/workspaces/renovate-graph
; npm version = 10.2.3
; cwd = /home/jamie/workspaces/renovate-graph
; HOME = /home/jamie
; Run `npm config ls -l` to show all defaults.

```

### PR DESCRIPTION
**Pull request by jamietanna**
As a means to resolve #6966, we can tweak the way we handle licenses,
where receiving a license object, instead of license string, results in
a malformed SPDX JSON SBOM.

While working on this, it was noted that CycloneDX also needed to be
amended, as it was omitting any license objects.

Closes #6966.

Also, document current license SPDX behaviour.

## References

Closes #6966.

### CODE REVIEW

File: test/lib/utils/sbom-cyclonedx.js [hunk 1]
```diff
@@ -190,6 +190,21 @@ t.test('single node - with license expression', t => {
...
+  const pkg = {
+    ...rootPkg,
+    license: {
+      type: 'MIT',
+      url: 'http://github.com/kriskowal/q/raw/master/LICENSE',
+    },
+  }
+  const node = { ...root, package: pkg }
+  const res = cyclonedxOutput({ npm, nodes: [node] })
+  console.log({ res })
```
Comment (wraithgar) [inline test/lib/utils/sbom-cyclonedx.js]: rogue console.log

Comment (jamietanna) [reply test/lib/utils/sbom-cyclonedx.js]: :sweat_smile: Sorry!

**Comment by jamietanna** [comment]
Should be able to re-run now :crossed_fingers:

**Comment by jamietanna** [comment]
Sorry, that'll teach me not running the build locally :disappointed:

**Review by bdehamer — APPROVED** [review]
LGTM. Thanks for the fix.

**Comment by jamietanna** [comment]
Very welcome, thanks for the support as it stands 👏🏽

**Comment by wraithgar** [comment]
@jamietanna if you want this backported to npm@9 you can cherry-pick [the commit](https://github.com/npm/cli/commit/0f7008851f1c250405e8dc326f15d535e8fc1eae) into a new PR made against the [v9 branch](https://github.com/npm/cli/tree/release/v9)
