### PR TITLE
fix(publish): skip private workspaces

### LINKED ISSUE #3268: [BUG] publish with workspaces doesn't respect access controls
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running the following command:

```bash
publish --workspaces --access public
```

And I'm getting errors because it's trying to publish workspace packages that are marked as both private and restricted (I have an examples folder that is part of my workspace).

```
npm ERR! code EPRIVATE
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
```

I believe this references #3231 @ruyadorno @wraithgar

### Expected Behavior

It should respect the access controls.

### Steps To Reproduce

1. In this environment create two workspace packages and mark one as public and one as restricted (as well as include a `"private": true`
2. run `publish --workspaces --access public`
3. See error published above

For a real life example see this: https://github.com/exceptionless/Exceptionless.JavaScript/tree/f492ef2daf5c5930542e9b4ecc76dbcfd937488d

### Environment

- OS: Ubuntu
- Node: latest (16.x)
- npm: latest (7.13)

### PR DESCRIPTION
**Pull request by ruyadorno**
Allow users to publish all workspaces with `npm publish --ws` while also
skipping any workspace that might have been intentionally marked as
private, using `"private": true` in its package.json file.

## References
Fixes: https://github.com/npm/cli/issues/3268

### CODE REVIEW

**Comment by wraithgar** [comment]
So if I understand this correctly, what happens right now on a single package is that they would normally get this error from the publish action, but because it was a single operation it didn't need to be specially handled.  Now, because we are publishing multiple packages in one action we are starting to have a set (currently of one) of errors that we need to gracefully handle and not end the operation on.

This is a good start, but we may want to think about coming up with a more robust approach to this. For instance, only aborting on auth related errors, and catching and reporting all others at the end, after trying every workspace.

File: lib/publish.js [hunk 1]
```diff
@@ -154,10 +155,29 @@ class Publish extends BaseCommand {
     const results = {}
     const json = this.npm.config.get('json')
     const silent = log.level === 'silent'
+    const noop = a => a
+    const color = this.npm.color ? chalk : { green: noop, bold: noop }
```
Comment (wraithgar) [inline lib/publish.js:159]: One of these days we should pull this repeated logic into npm.js itself.

**Review by wraithgar — APPROVED** [review]

File: lib/publish.js [hunk 2]
```diff
@@ -154,10 +155,29 @@ class Publish extends BaseCommand {
...
+            'publish',
+            `Skipping workspace ${
+              color.green(name)
+            }, marked as ${
+              color.bold('private')
+            }`
+          )
+          continue
+        }
+        throw err
```
Comment (wraithgar) [inline lib/publish.js:179]: This line does not have code coverage

**Review by wraithgar — CHANGES_REQUESTED** [review]

File: lib/publish.js (hunk 1 above)
Comment (ruyadorno) [reply lib/publish.js:159]: 👍 either that or maybe it ought to live in one of the base commands parent classes to be reused

File: lib/publish.js (hunk 2 above)
Comment (ruyadorno) [reply lib/publish.js:179]: ooops, done ✅ thanks!

**Review by wraithgar — APPROVED** [review]
