### PR TITLE
Include prerelease versions when deprecating an entire package.

### LINKED ISSUE #1615: [BUG] Unable to deprecate package with - (hyphen) in the version number
# What / Why

> When deprecating a package with a `-` (hyphen) in the name, the process fails silently, allowing the package to still be installed without a deprecation warning.

npm support suggested this as the cause:
> There seems to be a bug that will cause a silent fail when the latest version of a package has `-` ( 1.0.0-alpha.1).

## When

* When deprecating a package with a `-` (hyphen) in the name; see steps below 

## Where

* npm public registry

### Current Behavior

* `npm deprecate` appears to succeed (aside from when #1469 occurs if not logged in) but the given package can still be installed without warning via `npm install`

### Steps to Reproduce

Try and deprecate the package:

```sh
$ npm deprecate @example/package 'This package is deprecated'
This operation requires a one-time password.
Enter OTP: XXXXXXX
```

Now, in a separate directory:

```sh
$ npm install @example/package
+ @example/package@1.0.0-alpha.1
updated 1 package and audited 1 package in 6.137s
found 0 vulnerabilities
```

Note that no deprecation message is visible.

### Expected Behavior

* Output should show deprecated message

Workaround is to do the following:

```sh
# Undeprecate
npm deprecate @example/package ''
# Edit package.json, change version to 0.0.0, then republish
npm publish
# Now redeprecate
npm deprecate @example/package 'This is deprecated'
# And tag the 
npm dist-tag add @example/package@1.0.0-alpha.1 latest
```

After you do so, the result looks like this:

```sh
$ npm install @example/package
npm WARN deprecated @example/package@1.0.0-alpha.1: This package has been deprecated 
+ @example/package@1.0.0-alpha.1
updated 1 package and audited 1 package in 6.137s
found 0 vulnerabilities
```

## Who

* n/a

## References

* n/a

### PR DESCRIPTION
**Pull request by tiegz**
The [NPM docs](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions) say:

```
To deprecate an entire package, run the following command, replacing <package-name> 
with  the name of your package, and "<message>" with your deprecation message:

npm deprecate <package-name> "<message>"
```

This **should** mark all versions as deprecated, but it currently excludes any prerelease versions.

The filtering of versions in the deprecate command is done by passing a version range to `semver.satisfies()`. A wildcard `*` is passed as the version range when deprecating an entire package, but wildcards [don't include prereleases by the semver library's rules](https://github.com/npm/node-semver#prerelease-tags), so we need to pass the `includePrerelease: true` option so that all prereleases are included in the deprecated versions.

## References
Fixes https://github.com/npm/cli/issues/1615

### CODE REVIEW

File: lib/deprecate.js [hunk 1]
```diff
@@ -45,6 +45,7 @@ const deprecate = async ([pkg, msg]) => {
   // npa makes the default spec "latest", but for deprecation
   // "*" is the appropriate default.
   const spec = p.rawSpec === '' ? '*' : p.fetchSpec
+  const options = spec === '*' ? {includePrerelease: true} : {}
```
Comment (isaacs) [inline lib/deprecate.js]: 🤔 

Should this check be `const options = p.rawSpec === '' ? { includePrerelease: true } : {}`?

Ie, if you did `npm deprecate foo@*` should that include prereleases?  Or only if you do `npm deprecate foo`?

Comment (isaacs) [reply lib/deprecate.js]: If so, these lines can be condensed a little cuter:

```js
const [spec, options] = p.rawSpec ? [p.fetchSpec, {}]
  : ['*', { includePrerelease: true }]
```

**Review by isaacs — COMMENTED** [review]
Seems good to me, just a comment about whether `npm deprecate pkg@*` should include prereleases as well.

File: lib/deprecate.js (hunk 1 above)
Comment (ljharb) [reply lib/deprecate.js]: I’d expect both. Excluding prereleases is generally the surprising case for non-installs.

Comment (tiegz) [reply lib/deprecate.js]: I'd expect both too, but I didn't know about the prerelease rules in the semver library until this week 🤯 

What if I added @isaacs 's recommendation and then a note was added to the docs, e.g. `note that passing a range '*' will not deprecate prereleases versions.`?

**Comment by tiegz** [comment]
Thanks @isaacs !
