### PR TITLE
fix(pack, publish): default foreground-scripts to true

### LINKED ISSUE #6816: [BUG] prepack/postpack output is incorrectly suppressed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

With this example `package.json` in an empty dir:
```json
{
  "private": true,
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "prepack": "echo prepack!",
    "postpack": "echo postpack!"
  }
}
```

and run `npm pack --dry-run`. You should see the following output, which appears in npm < 9:
```sh
> foo@0.0.0 prepack
> echo prepack!

prepack!

> foo@0.0.0 postpack
> echo postpack!

postpack!
npm notice 
npm notice 📦  foo@0.0.0
npm notice === Tarball Contents === 
npm notice 234B package.json
npm notice === Tarball Details === 
npm notice name:          foo                                     
npm notice version:       0.0.0                                   
npm notice filename:      foo-0.0.0.tgz                           
npm notice package size:  236 B                                   
npm notice unpacked size: 234 B                                   
npm notice shasum:        ba4102210bf70a017cd510276f01cc0c4b5f68d0
npm notice integrity:     sha512-/s4lXyjWKoW7y[...]adUe23zB6HEkw==
npm notice total files:   1                                       
npm notice 
foo-0.0.0.tgz
```

However, in npm >= 9.0, i get this output:
```sh
npm notice 
npm notice 📦  foo@0.0.0
npm notice === Tarball Contents === 
npm notice 234B package.json
npm notice === Tarball Details === 
npm notice name:          foo                                     
npm notice version:       0.0.0                                   
npm notice filename:      foo-0.0.0.tgz                           
npm notice package size:  236 B                                   
npm notice unpacked size: 234 B                                   
npm notice shasum:        ba4102210bf70a017cd510276f01cc0c4b5f68d0
npm notice integrity:     sha512-/s4lXyjWKoW7y[...]adUe23zB6HEkw==
npm notice total files:   1                                       
npm notice 
foo-0.0.0.tgz
```

### Expected Behavior

npm 9+ doesn't suppress output in prepack/postpack scripts (and more broadly, in *any* lifecycle script that wouldn't be shown to a user who runs `npm install`/`npm ci` such that this project is installed (meaning, *my own* postinstall/preinstall/prepare scripts should always show output, but nobody else's should)

### Steps To Reproduce

see above

### Environment

- npm: 10.1.0
- Node.js: 20.5.1
- OS Name: Mac OS
- System Model Name: Macbook Pro
- npm config: n/a as long as `ignore-scripts` isn't set

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #6816

This fixes a regression in both npm 9 and 10.

An alternative approach to adding a constructor could be, add something in BaseCommand that runs super, and then reads the default from the derived command class, and then sets the default - that way it'd be more declarative. Happy to change to something like that, if preferred.

### CODE REVIEW

File: lib/commands/pack.js [hunk 1]
```diff
@@ -21,6 +21,11 @@ class Pack extends BaseCommand {
   static workspaces = true
   static ignoreImplicitWorkspace = false
 
+  constructor (...args) {
+    super(...args)
+    this.npm.config.set('foreground-scripts', true, 'default')
```
Comment (wraithgar) [inline lib/commands/pack.js]: This doesn't allow folks to explicitly disable foreground scripts.

Comment (ljharb) [reply lib/commands/pack.js]: Hmm - i assumed because of the third argument, it would set the default but still be overridden by any of the config methods. If that’s not the case, what does “default” here do?

Comment (wraithgar) [reply lib/commands/pack.js]: Or if it does, it's an approach we've never used before we've historically checked for if the user has overridden the default and then manually set it..  In  either case we need a test showing that folks can still override it.

Comment (wraithgar) [reply lib/commands/pack.js]: the `save` config is different in `npm update` and you can see how we've done it there


```js
     const save = this.npm.config.isDefault('save')
         ? false
         : this.npm.config.get('save')
```

This is an interesting approach, setting a default for the command, and may even be the right one.  We need to think through documentation on this too.

**Comment by wraithgar** [comment]
Check out the `save` config for how we are overriding the defaultDescription to describe subtleties like this.

**Comment by wraithgar** [comment]
Let's put a pin in the base command update, since we'd want to include the other things for which the default is different (like save).

File: lib/commands/pack.js (hunk 1 above)
Comment (ljharb) [reply lib/commands/pack.js]: I found it by looking at other commands, but I’m happy to change it to the pattern you’re describing; within the next hour and change.

Comment (wraithgar) [reply lib/commands/pack.js]: If we already do this elsewhere i'm less concerned about a new precedent.  Where did you find it?

**Comment by wraithgar** [comment]
Smoke tests will likely need snapshots updated.

File: lib/commands/pack.js (hunk 1 above)
Comment (ljharb) [reply lib/commands/pack.js]: ahhh actually i found some *get*s with `default`, and then looked at Config see that it accepted a "where" of confTypes, and then just assumed it worked with `set` (which it may not, currently).

I'll make the change.

**Comment by ljharb** [comment]
How do I update smoke test snapshots?

**Comment by wraithgar** [comment]
```sh
npm run snap -w smoke-tests
```

**Comment by ljharb** [comment]
I've updated the smoke test snapshots but they're still failing.

**Comment by lukekarrys** [comment]
Smoke tests were failing because they made an assumption that the output of `npm pack` would only include the name of the resulting tarball which is no longer true with this change.

I fixed this in #7256. Once that lands, this PR can be rebased and should go green.

For reference here's what `node . pack` now looks like with this PR:
```sh
❯ node . pack 2> /dev/null

> npm@10.4.0 prepack
> node . run build -w docs


> @npmcli/docs@1.0.0 build
> node bin/build.js

Wrote 251 files
npm-10.4.0.tgz
```

**Review by lukekarrys — APPROVED** [review]

**Comment by simonhaenisch** [comment]
This change is problematic imo and it actually broke our tooling, because the stdout even with the `--json` flag now also contains the stdout of the pre/post hooks.

With `--json` i'd assume that you would be able to pipe the stdout and it only contains the command's json output, not some random output of lifecycle hooks.

(We were actually using the fact that it just used to print the tarball name to stdout, and I can see how that is maybe not the most robust idea since it's not a guaranteed API but with the `--json` flag I somehow expected it to work).

Edit: I just realized that `--json` doesn't print into a single line, so my initial idea of fixing it by piping through `tail -n 1` doesn't work either. This change makes it very hard to separate the `npm pack` command's output with the one from the lifecycle hooks. ~Does adding sth like a `--silent` flag make sense?~ There's actually the (global?) `--silent` flag, and using it to prevent printing stdout of hooks would probably make sense to me.

Update: should have looked up before posting, there's already a bug linked there that was closed and mentions using `--foreground-scripts=false` which actually does what i need (but somehow isn't documented in the command's help).

**Comment by ljharb** [comment]
@simonhaenisch the hooks are under your control - you can silence their output however you like unrelated to npm. You can also set `--no-foreground-scripts` if you want it to be false and restore the previous behavior, as you indicated.
