### PR TITLE
fix(npx): always save true when installing to npx cache

### LINKED ISSUE #8151: [BUG] since npm 11.2.0 update, npx fails to run http-server
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

I have used `npx http-server ./ -p 8080` as a command probably a zillion times, never had a problem.

I just recently updated npm to 11.2.0, and now that command is failing. I've tried clearing the _npx cache and re-installing. Installation of the package and its dependencies works, but then npx refuses to execute, complaining about a missing `package.json` in its cache.

`http-server` hasn't changed at all, no new published versions in 3 years, so this is a breakage/breaking change in npm.

### Expected Behavior

I expect to be able to run `npx http-server ./ -p 8080` and it *just work* the way it has for years.

### Steps To Reproduce

`npx http-server ./ -p 8080` now reports this:

```cmd
Need to install the following packages:
http-server@14.1.1
Ok to proceed? (y) y

npm error code ENOENT
npm error syscall open
npm error path /home/getify/.npm/_npx/e5196fa6dc3cecbc/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/getify/.npm/_npx/e5196fa6dc3cecbc/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /home/getify/.npm/_logs/2025-03-07T16_48_34_953Z-debug-0.log
```

<details>
<summary>And that long error log file includes this:</summary>

```cmd
0 verbose cli /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@11.2.0
2 info using node@v22.14.0
3 silly config load:file:/usr/local/lib/node_modules/npm/npmrc
4 silly config load:file:/home/getify/tmp/.npmrc
5 silly config load:file:/home/getify/.npmrc
6 silly config load:file:/usr/local/etc/npmrc
7 verbose title npm exec http-server ./ -p 8080
8 verbose argv "exec" "--" "http-server" "./" "-p" "8080"
9 verbose logfile logs-max:10 dir:/home/getify/.npm/_logs/2025-03-07T16_48_34_953Z-
10 verbose logfile /home/getify/.npm/_logs/2025-03-07T16_48_34_953Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly packumentCache heap:2105278464 maxSize:526319616 maxEntrySize:263159808
13 silly logfile done cleaning log files
14 http fetch GET 200 https://registry.npmjs.org/http-server 160ms (cache updated)
15 silly packumentCache heap:2105278464 maxSize:526319616 maxEntrySize:263159808
16 silly packumentCache heap:2105278464 maxSize:526319616 maxEntrySize:263159808
17 silly idealTree buildDeps
18 silly fetch manifest http-server@14.1.1
19 silly packumentCache full:https://registry.npmjs.org/http-server cache-miss
20 http cache https://registry.npmjs.org/http-server 15ms (cache hit)
21 silly packumentCache full:https://registry.npmjs.org/http-server set size:133786 disposed:false
22 silly placeDep ROOT http-server@14.1.1 OK for:  want: 14.1.1
23 silly fetch manifest he@^1.2.0
24 silly packumentCache full:https://registry.npmjs.org/he cache-miss
25 silly fetch manifest mime@^1.6.0
26 silly packumentCache full:https://registry.npmjs.org/mime cache-miss
27 silly fetch manifest chalk@^4.1.2
28 silly packumentCache full:https://registry.npmjs.org/chalk cache-miss
29 silly fetch manifest union@~0.5.0
30 silly packumentCache full:https://registry.npmjs.org/union cache-miss
31 silly fetch manifest corser@^2.0.1
32 silly packumentCache full:https://registry.npmjs.org/corser cache-miss
33 silly fetch manifest opener@^1.5.1
34 silly packumentCache full:https://registry.npmjs.org/opener cache-miss
35 silly fetch manifest minimist@^1.2.6
36 silly packumentCache full:https://registry.npmjs.org/minimist cache-miss
37 silly fetch manifest url-join@^4.0.1
38 silly packumentCache full:https://registry.npmjs.org/url-join cache-miss
39 silly fetch manifest basic-auth@^2.0.1
40 silly packumentCache full:https://registry.npmjs.org/basic-auth cache-miss
41 silly fetch manifest http-proxy@^1.18.1
42 silly packumentCache full:https://registry.npmjs.org/http-proxy cache-miss
43 silly fetch manifest portfinder@^1.0.28
44 silly packumentCache full:https://registry.npmjs.org/portfinder cache-miss
45 http cache https://registry.npmjs.org/chalk 19ms (cache hit)
46 silly packumentCache full:https://registry.npmjs.org/chalk set size:122561 disposed:false
47 silly fetch manifest secure-compare@3.0.1
48 silly packumentCache full:https://registry.npmjs.org/secure-compare cache-miss
49 http cache https://registry.npmjs.org/url-join 20ms (cache hit)
50 silly packumentCache full:https://registry.npmjs.org/url-join set size:22958 disposed:false
51 silly fetch manifest html-encoding-sniffer@^3.0.0
52 silly packumentCache full:https://registry.npmjs.org/html-encoding-sniffer cache-miss
53 http cache https://registry.npmjs.org/http-proxy 21ms (cache hit)
54 silly packumentCache full:https://registry.npmjs.org/http-proxy set size:183156 disposed:false
55 http cache https://registry.npmjs.org/basic-auth 23ms (cache hit)
56 silly packumentCache full:https://registry.npmjs.org/basic-auth set size:21697 disposed:false
57 http cache https://registry.npmjs.org/he 25ms (cache hit)
58 silly packumentCache full:https://registry.npmjs.org/he set size:58773 disposed:false
59 http cache https://registry.npmjs.org/mime 26ms (cache hit)
60 silly packumentCache full:https://registry.npmjs.org/mime set size:114268 disposed:false
61 http cache https://registry.npmjs.org/opener 27ms (cache hit)
62 silly packumentCache full:https://registry.npmjs.org/opener set size:21206 disposed:false
63 http cache https://registry.npmjs.org/union 29ms (cache hit)
64 silly packumentCache full:https://registry.npmjs.org/union set size:49652 disposed:false
65 http cache https://registry.npmjs.org/portfinder 28ms (cache hit)
66 silly packumentCache full:https://registry.npmjs.org/portfinder set size:84500 disposed:false
67 http cache https://registry.npmjs.org/minimist 30ms (cache hit)
68 silly packumentCache full:https://registry.npmjs.org/minimist set size:77097 disposed:false
69 http cache https://registry.npmjs.org/corser 33ms (cache hit)
70 silly packumentCache full:https://registry.npmjs.org/corser set size:22714 disposed:false
71 http cache https://registry.npmjs.org/secure-compare 16ms (cache hit)
72 silly packumentCache full:https://registry.npmjs.org/secure-compare set size:3978 disposed:false
73 http cache https://registry.npmjs.org/html-encoding-sniffer 16ms (cache hit)
74 silly packumentCache full:https://registry.npmjs.org/html-encoding-sniffer set size:18552 disposed:false
75 silly placeDep ROOT basic-auth@2.0.1 OK for: http-server@14.1.1 want: ^2.0.1
76 silly placeDep ROOT chalk@4.1.2 OK for: http-server@14.1.1 want: ^4.1.2
77 silly placeDep ROOT corser@2.0.1 OK for: http-server@14.1.1 want: ^2.0.1
78 silly placeDep ROOT he@1.2.0 OK for: http-server@14.1.1 want: ^1.2.0
79 silly placeDep ROOT html-encoding-sniffer@3.0.0 OK for: http-server@14.1.1 want: ^3.0.0
80 silly placeDep ROOT http-proxy@1.18.1 OK for: http-server@14.1.1 want: ^1.18.1
81 silly placeDep ROOT mime@1.6.0 OK for: http-server@14.1.1 want: ^1.6.0
82 silly placeDep ROOT minimist@1.2.8 OK for: http-server@14.1.1 want: ^1.2.6
83 silly placeDep ROOT opener@1.5.2 OK for: http-server@14.1.1 want: ^1.5.1
84 silly placeDep ROOT portfinder@1.0.33 OK for: http-server@14.1.1 want: ^1.0.28
85 silly placeDep ROOT secure-compare@3.0.1 OK for: http-server@14.1.1 want: 3.0.1
86 silly placeDep ROOT union@0.5.0 OK for: http-server@14.1.1 want: ~0.5.0
87 silly placeDep ROOT url-join@4.0.1 OK for: http-server@14.1.1 want: ^4.0.1
88 silly fetch manifest safe-buffer@5.1.2
89 silly packumentCache full:https://registry.npmjs.org/safe-buffer cache-miss
90 silly fetch manifest ansi-styles@^4.1.0
91 silly packumentCache full:https://registry.npmjs.org/ansi-styles cache-miss
92 silly fetch manifest supports-color@^7.1.0
93 silly packumentCache full:https://registry.npmjs.org/supports-color cache-miss
94 silly fetch manifest whatwg-encoding@^2.0.0
95 silly packumentCache full:https://registry.npmjs.org/whatwg-encoding cache-miss
96 silly fetch manifest eventemitter3@^4.0.0
97 silly packumentCache full:https://registry.npmjs.org/eventemitter3 cache-miss
98 silly fetch manifest requires-port@^1.0.0
99 silly packumentCache full:https://registry.npmjs.org/requires-port cache-miss
100 silly fetch manifest follow-redirects@^1.0.0
101 silly packumentCache full:https://registry.npmjs.org/follow-redirects cache-miss
102 silly fetch manifest async@^2.6.4
103 silly packumentCache full:https://registry.npmjs.org/async cache-miss
104 silly fetch manifest debug@^3.2.7
105 silly packumentCache full:https://registry.npmjs.org/debug cache-miss
106 silly fetch manifest mkdirp@^0.5.6
107 silly packumentCache full:https://registry.npmjs.org/mkdirp cache-miss
108 silly fetch manifest qs@^6.4.0
109 silly packumentCache full:https://registry.npmjs.org/qs cache-miss
110 http cache https://registry.npmjs.org/requires-port 18ms (cache hit)
111 silly packumentCache full:https://registry.npmjs.org/requires-port set size:8110 disposed:false
112 http cache https://registry.npmjs.org/ansi-styles 18ms (cache hit)
113 silly packumentCache full:https://registry.npmjs.org/ansi-styles set size:66356 disposed:false
114 http cache https://registry.npmjs.org/async 19ms (cache hit)
115 silly packumentCache full:https://registry.npmjs.org/async set size:230496 disposed:false
116 http cache https://registry.npmjs.org/eventemitter3 23ms (cache hit)
117 silly packumentCache full:https://registry.npmjs.org/eventemitter3 set size:86060 disposed:false
118 http cache https://registry.npmjs.org/safe-buffer 24ms (cache hit)
119 silly packumentCache full:https://registry.npmjs.org/safe-buffer set size:41183 disposed:false
120 http cache https://registry.npmjs.org/qs 24ms (cache hit)
121 silly packumentCache full:https://registry.npmjs.org/qs set size:264677 disposed:false
122 http cache https://registry.npmjs.org/supports-color 28ms (cache hit)
123 silly packumentCache full:https://registry.npmjs.org/supports-color set size:115466 disposed:false
124 http cache https://registry.npmjs.org/follow-redirects 28ms (cache hit)
125 silly packumentCache full:https://registry.npmjs.org/follow-redirects set size:182478 disposed:false
126 http cache https://registry.npmjs.org/whatwg-encoding 30ms (cache hit)
127 silly packumentCache full:https://registry.npmjs.org/whatwg-encoding set size:24764 disposed:false
128 http cache https://registry.npmjs.org/debug 30ms (cache hit)
129 silly packumentCache full:https://registry.npmjs.org/debug set size:191220 disposed:false
130 http cache https://registry.npmjs.org/mkdirp 32ms (cache hit)
131 silly packumentCache full:https://registry.npmjs.org/mkdirp set size:116455 disposed:false
132 silly placeDep ROOT safe-buffer@5.1.2 OK for: basic-auth@2.0.1 want: 5.1.2
133 silly placeDep ROOT ansi-styles@4.3.0 OK for: chalk@4.1.2 want: ^4.1.0
134 silly placeDep ROOT supports-color@7.2.0 OK for: chalk@4.1.2 want: ^7.1.0
135 silly fetch manifest color-convert@^2.0.1
136 silly packumentCache full:https://registry.npmjs.org/color-convert cache-miss
137 silly fetch manifest has-flag@^4.0.0
138 silly packumentCache full:https://registry.npmjs.org/has-flag cache-miss
139 http cache https://registry.npmjs.org/has-flag 5ms (cache hit)
140 silly packumentCache full:https://registry.npmjs.org/has-flag set size:15180 disposed:false
141 http cache https://registry.npmjs.org/color-convert 7ms (cache hit)
142 silly packumentCache full:https://registry.npmjs.org/color-convert set size:66477 disposed:false
143 silly placeDep ROOT color-convert@2.0.1 OK for: ansi-styles@4.3.0 want: ^2.0.1
144 silly fetch manifest color-name@~1.1.4
145 silly packumentCache full:https://registry.npmjs.org/color-name cache-miss
146 http cache https://registry.npmjs.org/color-name 6ms (cache hit)
147 silly packumentCache full:https://registry.npmjs.org/color-name set size:16325 disposed:false
148 silly placeDep ROOT color-name@1.1.4 OK for: color-convert@2.0.1 want: ~1.1.4
149 silly placeDep ROOT whatwg-encoding@2.0.0 OK for: html-encoding-sniffer@3.0.0 want: ^2.0.0
150 silly fetch manifest iconv-lite@0.6.3
151 silly packumentCache full:https://registry.npmjs.org/iconv-lite cache-miss
152 http cache https://registry.npmjs.org/iconv-lite 3ms (cache hit)
153 silly packumentCache full:https://registry.npmjs.org/iconv-lite set size:115994 disposed:false
154 silly placeDep ROOT eventemitter3@4.0.7 OK for: http-proxy@1.18.1 want: ^4.0.0
155 silly placeDep ROOT follow-redirects@1.15.9 OK for: http-proxy@1.18.1 want: ^1.0.0
156 silly placeDep ROOT requires-port@1.0.0 OK for: http-proxy@1.18.1 want: ^1.0.0
157 silly placeDep ROOT async@2.6.4 OK for: portfinder@1.0.33 want: ^2.6.4
158 silly placeDep ROOT debug@3.2.7 OK for: portfinder@1.0.33 want: ^3.2.7
159 silly placeDep ROOT mkdirp@0.5.6 OK for: portfinder@1.0.33 want: ^0.5.6
160 silly fetch manifest lodash@^4.17.14
161 silly packumentCache full:https://registry.npmjs.org/lodash cache-miss
162 silly fetch manifest ms@^2.1.1
163 silly packumentCache full:https://registry.npmjs.org/ms cache-miss
164 http cache https://registry.npmjs.org/lodash 6ms (cache hit)
165 silly packumentCache full:https://registry.npmjs.org/lodash set size:242370 disposed:false
166 http cache https://registry.npmjs.org/ms 8ms (cache hit)
167 silly packumentCache full:https://registry.npmjs.org/ms set size:84883 disposed:false
168 silly placeDep ROOT lodash@4.17.21 OK for: async@2.6.4 want: ^4.17.14
169 silly placeDep ROOT ms@2.1.3 OK for: debug@3.2.7 want: ^2.1.1
170 silly placeDep ROOT has-flag@4.0.0 OK for: supports-color@7.2.0 want: ^4.0.0
171 silly placeDep ROOT qs@6.14.0 OK for: union@0.5.0 want: ^6.4.0
172 silly fetch manifest side-channel@^1.1.0
173 silly packumentCache full:https://registry.npmjs.org/side-channel cache-miss
174 http cache https://registry.npmjs.org/side-channel 5ms (cache hit)
175 silly packumentCache full:https://registry.npmjs.org/side-channel set size:24660 disposed:false
176 silly placeDep ROOT side-channel@1.1.0 OK for: qs@6.14.0 want: ^1.1.0
177 silly fetch manifest es-errors@^1.3.0
178 silly packumentCache full:https://registry.npmjs.org/es-errors cache-miss
179 silly fetch manifest object-inspect@^1.13.3
180 silly packumentCache full:https://registry.npmjs.org/object-inspect cache-miss
181 silly fetch manifest side-channel-list@^1.0.0
182 silly packumentCache full:https://registry.npmjs.org/side-channel-list cache-miss
183 silly fetch manifest side-channel-map@^1.0.1
184 silly packumentCache full:https://registry.npmjs.org/side-channel-map cache-miss
185 silly fetch manifest side-channel-weakmap@^1.0.2
186 silly packumentCache full:https://registry.npmjs.org/side-channel-weakmap cache-miss
187 http cache https://registry.npmjs.org/side-channel-list 6ms (cache hit)
188 silly packumentCache full:https://registry.npmjs.org/side-channel-list set size:6005 disposed:false
189 http cache https://registry.npmjs.org/side-channel-weakmap 7ms (cache hit)
190 silly packumentCache full:https://registry.npmjs.org/side-channel-weakmap set size:12620 disposed:false
191 http cache https://registry.npmjs.org/es-errors 9ms (cache hit)
192 silly packumentCache full:https://registry.npmjs.org/es-errors set size:16918 disposed:false
193 http cache https://registry.npmjs.org/side-channel-map 8ms (cache hit)
194 silly packumentCache full:https://registry.npmjs.org/side-channel-map set size:9126 disposed:false
195 http cache https://registry.npmjs.org/object-inspect 9ms (cache hit)
196 silly packumentCache full:https://registry.npmjs.org/object-inspect set size:101912 disposed:false
197 silly placeDep ROOT es-errors@1.3.0 OK for: side-channel@1.1.0 want: ^1.3.0
198 silly placeDep ROOT object-inspect@1.13.4 OK for: side-channel@1.1.0 want: ^1.13.3
199 silly placeDep ROOT side-channel-list@1.0.0 OK for: side-channel@1.1.0 want: ^1.0.0
200 silly placeDep ROOT side-channel-map@1.0.1 OK for: side-channel@1.1.0 want: ^1.0.1
201 silly placeDep ROOT side-channel-weakmap@1.0.2 OK for: side-channel@1.1.0 want: ^1.0.2
202 silly fetch manifest call-bound@^1.0.2
203 silly packumentCache full:https://registry.npmjs.org/call-bound cache-miss
204 silly fetch manifest get-intrinsic@^1.2.5
205 silly packumentCache full:https://registry.npmjs.org/get-intrinsic cache-miss
206 silly fetch manifest call-bound@^1.0.2
207 silly packumentCache full:https://registry.npmjs.org/call-bound cache-miss
208 silly fetch manifest get-intrinsic@^1.2.5
209 silly packumentCache full:https://registry.npmjs.org/get-intrinsic cache-miss
210 http cache https://registry.npmjs.org/call-bound 6ms (cache hit)
211 silly packumentCache full:https://registry.npmjs.org/call-bound set size:15317 disposed:false
212 http cache https://registry.npmjs.org/call-bound 8ms (cache hit)
213 silly packumentCache full:https://registry.npmjs.org/call-bound set size:15317 disposed:false
214 silly packumentCache full:https://registry.npmjs.org/call-bound dispose
215 http cache https://registry.npmjs.org/get-intrinsic 8ms (cache hit)
216 silly packumentCache full:https://registry.npmjs.org/get-intrinsic set size:57687 disposed:false
217 http cache https://registry.npmjs.org/get-intrinsic 8ms (cache hit)
218 silly packumentCache full:https://registry.npmjs.org/get-intrinsic set size:57687 disposed:false
219 silly packumentCache full:https://registry.npmjs.org/get-intrinsic dispose
220 silly placeDep ROOT call-bound@1.0.4 OK for: side-channel-map@1.0.1 want: ^1.0.2
221 silly placeDep ROOT get-intrinsic@1.3.0 OK for: side-channel-map@1.0.1 want: ^1.2.5
222 silly fetch manifest call-bind-apply-helpers@^1.0.2
223 silly packumentCache full:https://registry.npmjs.org/call-bind-apply-helpers cache-miss
224 silly fetch manifest get-intrinsic@^1.3.0
225 silly packumentCache full:https://registry.npmjs.org/get-intrinsic cache-hit
226 silly fetch manifest call-bind-apply-helpers@^1.0.2
227 silly packumentCache full:https://registry.npmjs.org/call-bind-apply-helpers cache-miss
228 silly fetch manifest es-define-property@^1.0.1
229 silly packumentCache full:https://registry.npmjs.org/es-define-property cache-miss
230 silly fetch manifest es-object-atoms@^1.1.1
231 silly packumentCache full:https://registry.npmjs.org/es-object-atoms cache-miss
232 silly fetch manifest function-bind@^1.1.2
233 silly packumentCache full:https://registry.npmjs.org/function-bind cache-miss
234 silly fetch manifest get-proto@^1.0.1
235 silly packumentCache full:https://registry.npmjs.org/get-proto cache-miss
236 silly fetch manifest gopd@^1.2.0
237 silly packumentCache full:https://registry.npmjs.org/gopd cache-miss
238 silly fetch manifest has-symbols@^1.1.0
239 silly packumentCache full:https://registry.npmjs.org/has-symbols cache-miss
240 silly fetch manifest hasown@^2.0.2
241 silly packumentCache full:https://registry.npmjs.org/hasown cache-miss
242 silly fetch manifest math-intrinsics@^1.1.0
243 silly packumentCache full:https://registry.npmjs.org/math-intrinsics cache-miss
244 http cache https://registry.npmjs.org/call-bind-apply-helpers 15ms (cache hit)
245 silly packumentCache full:https://registry.npmjs.org/call-bind-apply-helpers set size:12744 disposed:false
246 http cache https://registry.npmjs.org/es-define-property 16ms (cache hit)
247 silly packumentCache full:https://registry.npmjs.org/es-define-property set size:8542 disposed:false
248 http cache https://registry.npmjs.org/es-object-atoms 16ms (cache hit)
249 silly packumentCache full:https://registry.npmjs.org/es-object-atoms set size:15304 disposed:false
250 http cache https://registry.npmjs.org/call-bind-apply-helpers 18ms (cache hit)
251 silly packumentCache full:https://registry.npmjs.org/call-bind-apply-helpers set size:12744 disposed:false
252 silly packumentCache full:https://registry.npmjs.org/call-bind-apply-helpers dispose
253 http cache https://registry.npmjs.org/get-proto 17ms (cache hit)
254 silly packumentCache full:https://registry.npmjs.org/get-proto set size:8300 disposed:false
255 http cache https://registry.npmjs.org/function-bind 18ms (cache hit)
256 silly packumentCache full:https://registry.npmjs.org/function-bind set size:15733 disposed:false
257 http cache https://registry.npmjs.org/math-intrinsics 18ms (cache hit)
258 silly packumentCache full:https://registry.npmjs.org/math-intrinsics set size:9265 disposed:false
259 http cache https://registry.npmjs.org/gopd 19ms (cache hit)
260 silly packumentCache full:https://registry.npmjs.org/gopd set size:11458 disposed:false
261 http cache https://registry.npmjs.org/has-symbols 19ms (cache hit)
262 silly packumentCache full:https://registry.npmjs.org/has-symbols set size:21550 disposed:false
263 http cache https://registry.npmjs.org/hasown 20ms (cache hit)
264 silly packumentCache full:https://registry.npmjs.org/hasown set size:12476 disposed:false
265 silly placeDep ROOT call-bind-apply-helpers@1.0.2 OK for: call-bound@1.0.4 want: ^1.0.2
266 silly placeDep ROOT function-bind@1.1.2 OK for: call-bind-apply-helpers@1.0.2 want: ^1.1.2
267 silly placeDep ROOT es-define-property@1.0.1 OK for: get-intrinsic@1.3.0 want: ^1.0.1
268 silly placeDep ROOT es-object-atoms@1.1.1 OK for: get-intrinsic@1.3.0 want: ^1.1.1
269 silly placeDep ROOT get-proto@1.0.1 OK for: get-intrinsic@1.3.0 want: ^1.0.1
270 silly placeDep ROOT gopd@1.2.0 OK for: get-intrinsic@1.3.0 want: ^1.2.0
271 silly placeDep ROOT has-symbols@1.1.0 OK for: get-intrinsic@1.3.0 want: ^1.1.0
272 silly placeDep ROOT hasown@2.0.2 OK for: get-intrinsic@1.3.0 want: ^2.0.2
273 silly placeDep ROOT math-intrinsics@1.1.0 OK for: get-intrinsic@1.3.0 want: ^1.1.0
274 silly fetch manifest dunder-proto@^1.0.1
275 silly packumentCache full:https://registry.npmjs.org/dunder-proto cache-miss
276 http cache https://registry.npmjs.org/dunder-proto 2ms (cache hit)
277 silly packumentCache full:https://registry.npmjs.org/dunder-proto set size:8256 disposed:false
278 silly placeDep ROOT dunder-proto@1.0.1 OK for: get-proto@1.0.1 want: ^1.0.1
279 silly placeDep ROOT iconv-lite@0.6.3 OK for: whatwg-encoding@2.0.0 want: 0.6.3
280 silly fetch manifest safer-buffer@>= 2.1.2 < 3.0.0
281 silly packumentCache full:https://registry.npmjs.org/safer-buffer cache-miss
282 http cache https://registry.npmjs.org/safer-buffer 5ms (cache hit)
283 silly packumentCache full:https://registry.npmjs.org/safer-buffer set size:18521 disposed:false
284 silly placeDep ROOT safer-buffer@2.1.2 OK for: iconv-lite@0.6.3 want: >= 2.1.2 < 3.0.0
285 silly reify moves {}
286 silly audit bulk request {
286 silly audit   'http-server': [ '14.1.1' ],
286 silly audit   'basic-auth': [ '2.0.1' ],
286 silly audit   chalk: [ '4.1.2' ],
286 silly audit   corser: [ '2.0.1' ],
286 silly audit   he: [ '1.2.0' ],
286 silly audit   'html-encoding-sniffer': [ '3.0.0' ],
286 silly audit   'http-proxy': [ '1.18.1' ],
286 silly audit   mime: [ '1.6.0' ],
286 silly audit   minimist: [ '1.2.8' ],
286 silly audit   opener: [ '1.5.2' ],
286 silly audit   portfinder: [ '1.0.33' ],
286 silly audit   'secure-compare': [ '3.0.1' ],
286 silly audit   union: [ '0.5.0' ],
286 silly audit   'url-join': [ '4.0.1' ],
286 silly audit   'safe-buffer': [ '5.1.2' ],
286 silly audit   'ansi-styles': [ '4.3.0' ],
286 silly audit   'supports-color': [ '7.2.0' ],
286 silly audit   'color-convert': [ '2.0.1' ],
286 silly audit   'color-name': [ '1.1.4' ],
286 silly audit   'whatwg-encoding': [ '2.0.0' ],
286 silly audit   eventemitter3: [ '4.0.7' ],
286 silly audit   'follow-redirects': [ '1.15.9' ],
286 silly audit   'requires-port': [ '1.0.0' ],
286 silly audit   async: [ '2.6.4' ],
286 silly audit   debug: [ '3.2.7' ],
286 silly audit   mkdirp: [ '0.5.6' ],
286 silly audit   lodash: [ '4.17.21' ],
286 silly audit   ms: [ '2.1.3' ],
286 silly audit   'has-flag': [ '4.0.0' ],
286 silly audit   qs: [ '6.14.0' ],
286 silly audit   'side-channel': [ '1.1.0' ],
286 silly audit   'es-errors': [ '1.3.0' ],
286 silly audit   'object-inspect': [ '1.13.4' ],
286 silly audit   'side-channel-list': [ '1.0.0' ],
286 silly audit   'side-channel-map': [ '1.0.1' ],
286 silly audit   'side-channel-weakmap': [ '1.0.2' ],
286 silly audit   'call-bound': [ '1.0.4' ],
286 silly audit   'get-intrinsic': [ '1.3.0' ],
286 silly audit   'call-bind-apply-helpers': [ '1.0.2' ],
286 silly audit   'function-bind': [ '1.1.2' ],
286 silly audit   'es-define-property': [ '1.0.1' ],
286 silly audit   'es-object-atoms': [ '1.1.1' ],
286 silly audit   'get-proto': [ '1.0.1' ],
286 silly audit   gopd: [ '1.2.0' ],
286 silly audit   'has-symbols': [ '1.1.0' ],
286 silly audit   hasown: [ '2.0.2' ],
286 silly audit   'math-intrinsics': [ '1.1.0' ],
286 silly audit   'dunder-proto': [ '1.0.1' ],
286 silly audit   'iconv-lite': [ '0.6.3' ],
286 silly audit   'safer-buffer': [ '2.1.2' ]
286 silly audit }
287 http cache safer-buffer@https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz 0ms (cache hit)
288 http cache iconv-lite@https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz 0ms (cache hit)
289 http cache dunder-proto@https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz 0ms (cache hit)
290 http cache math-intrinsics@https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz 0ms (cache hit)
291 http cache hasown@https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz 0ms (cache hit)
292 http cache gopd@https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz 0ms (cache hit)
293 http cache get-proto@https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz 0ms (cache hit)
294 http cache es-object-atoms@https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.1.tgz 0ms (cache hit)
295 http cache es-define-property@https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz 0ms (cache hit)
296 http cache function-bind@https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz 0ms (cache hit)
297 http cache call-bind-apply-helpers@https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz 0ms (cache hit)
298 http cache get-intrinsic@https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.0.tgz 0ms (cache hit)
299 http cache call-bound@https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz 0ms (cache hit)
300 http cache side-channel-weakmap@https://registry.npmjs.org/side-channel-weakmap/-/side-channel-weakmap-1.0.2.tgz 0ms (cache hit)
301 http cache has-symbols@https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz 0ms (cache hit)
302 http cache side-channel-list@https://registry.npmjs.org/side-channel-list/-/side-channel-list-1.0.0.tgz 0ms (cache hit)
303 http cache object-inspect@https://registry.npmjs.org/object-inspect/-/object-inspect-1.13.4.tgz 0ms (cache hit)
304 http cache side-channel-map@https://registry.npmjs.org/side-channel-map/-/side-channel-map-1.0.1.tgz 0ms (cache hit)
305 http cache es-errors@https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz 0ms (cache hit)
306 http cache side-channel@https://registry.npmjs.org/side-channel/-/side-channel-1.1.0.tgz 0ms (cache hit)
307 http cache has-flag@https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz 0ms (cache hit)
308 http cache ms@https://registry.npmjs.org/ms/-/ms-2.1.3.tgz 0ms (cache hit)
309 http cache lodash@https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz 0ms (cache hit)
310 http cache mkdirp@https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.6.tgz 0ms (cache hit)
311 http cache debug@https://registry.npmjs.org/debug/-/debug-3.2.7.tgz 0ms (cache hit)
312 http cache async@https://registry.npmjs.org/async/-/async-2.6.4.tgz 0ms (cache hit)
313 http cache requires-port@https://registry.npmjs.org/requires-port/-/requires-port-1.0.0.tgz 0ms (cache hit)
314 http cache follow-redirects@https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.9.tgz 0ms (cache hit)
315 http cache eventemitter3@https://registry.npmjs.org/eventemitter3/-/eventemitter3-4.0.7.tgz 0ms (cache hit)
316 http cache whatwg-encoding@https://registry.npmjs.org/whatwg-encoding/-/whatwg-encoding-2.0.0.tgz 0ms (cache hit)
317 http cache color-name@https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz 0ms (cache hit)
318 http cache color-convert@https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz 0ms (cache hit)
319 http cache supports-color@https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz 0ms (cache hit)
320 http cache ansi-styles@https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz 0ms (cache hit)
321 http cache safe-buffer@https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz 0ms (cache hit)
322 http cache union@https://registry.npmjs.org/union/-/union-0.5.0.tgz 0ms (cache hit)
323 http cache portfinder@https://registry.npmjs.org/portfinder/-/portfinder-1.0.33.tgz 0ms (cache hit)
324 http cache url-join@https://registry.npmjs.org/url-join/-/url-join-4.0.1.tgz 0ms (cache hit)
325 http cache opener@https://registry.npmjs.org/opener/-/opener-1.5.2.tgz 0ms (cache hit)
326 http cache minimist@https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz 0ms (cache hit)
327 http cache mime@https://registry.npmjs.org/mime/-/mime-1.6.0.tgz 0ms (cache hit)
328 http cache secure-compare@https://registry.npmjs.org/secure-compare/-/secure-compare-3.0.1.tgz 0ms (cache hit)
329 http cache http-proxy@https://registry.npmjs.org/http-proxy/-/http-proxy-1.18.1.tgz 0ms (cache hit)
330 http cache html-encoding-sniffer@https://registry.npmjs.org/html-encoding-sniffer/-/html-encoding-sniffer-3.0.0.tgz 0ms (cache hit)
331 http cache qs@https://registry.npmjs.org/qs/-/qs-6.14.0.tgz 0ms (cache hit)
332 http cache he@https://registry.npmjs.org/he/-/he-1.2.0.tgz 0ms (cache hit)
333 http cache corser@https://registry.npmjs.org/corser/-/corser-2.0.1.tgz 0ms (cache hit)
334 http cache chalk@https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz 0ms (cache hit)
335 http cache basic-auth@https://registry.npmjs.org/basic-auth/-/basic-auth-2.0.1.tgz 0ms (cache hit)
336 http cache http-server@https://registry.npmjs.org/http-server/-/http-server-14.1.1.tgz 0ms (cache hit)
337 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 891ms
338 silly audit report {}
339 verbose stack Error: Could not read package.json: Error: ENOENT: no such file or directory, open '/home/getify/.npm/_npx/e5196fa6dc3cecbc/package.json'
339 verbose stack     at async open (node:internal/fs/promises:638:25)
339 verbose stack     at async readFile (node:internal/fs/promises:1242:14)
339 verbose stack     at async read (/usr/local/lib/node_modules/npm/node_modules/@npmcli/package-json/lib/read-package.js:9:18)
339 verbose stack     at async PackageJson.load (/usr/local/lib/node_modules/npm/node_modules/@npmcli/package-json/lib/index.js:131:31)
339 verbose stack     at async exec (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:299:21)
339 verbose stack     at async Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:208:9)
339 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:67:5)
340 error code ENOENT
341 error syscall open
342 error path /home/getify/.npm/_npx/e5196fa6dc3cecbc/package.json
343 error errno -2
344 error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/getify/.npm/_npx/e5196fa6dc3cecbc/package.json'
345 error enoent This is related to npm not being able to find a file.
345 error enoent
346 verbose cwd /home/getify/tmp
347 verbose os Linux 5.15.167.4-microsoft-standard-WSL2
348 verbose node v22.14.0
349 verbose npm  v11.2.0
350 verbose exit -2
351 verbose code -2
352 error A complete log of this run can be found in: /home/getify/.npm/_logs/2025-03-07T16_48_34_953Z-debug-0.log
```

</details>

### Environment

- npm: 11.2.0
- Node.js: 22.14.0
- OS Name: Windows 11 (wsl2 with debian linux)
- System Model Name:
- npm config:
```ini
; "user" config from /home/getify/.npmrc

//registry.npmjs.org/:_authToken = (protected)
//registry.npmjs.org/:username = (protected)
init-license = "MIT"
package-lock = false
save = false
umask = 1

; node bin location = /usr/local/bin/node
; node version = v22.14.0
; npm local prefix = /home/getify/tmp
; npm version = 11.2.0
; cwd = /home/getify/tmp
; HOME = /home/getify
; Run `npm config ls -l` to show all defaults.```

### PR DESCRIPTION
**Pull request by milaninfy**
Override config `save` to always be `true` when installing to the npx cache.

fixes: https://github.com/npm/cli/issues/8151

### CODE REVIEW

File: workspaces/libnpmexec/test/registry.js [hunk 1]
```diff
@@ -297,3 +297,25 @@ t.test('npx tree triggers manifest fetch when local version does satisfy range u
...
+
+  await package({ registry, path })
+
+  await exec({
+    args: ['@npmcli/create-index'],
+    globalPath: resolve(path, 'global'),
+    save: false,
+  })
+
+  t.match(await readOutput('@npmcli-create-index'), {
```
Comment (wraithgar) [inline workspaces/libnpmexec/test/registry.js:327]: the test should be the existence of the package.json file.  I believe thanks to @owlstronaut there is code in the libnpmexec tests that let you calculate the cache directory.

Comment (milaninfy) [reply workspaces/libnpmexec/test/registry.js:327]: Added assertion to test existence of package.json file. 👍

**Review by owlstronaut — APPROVED** [review]
