### PR TITLE
fix: prune optional peer dependencies that are no longer explicitly depended on

### LINKED ISSUE #4737: [BUG] uninstalling an optional peer dep doesnt remove it
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Uninstalling a package does not remove it from the `node_modules` folder, and does not remove it from package-lock.json.

### Expected Behavior

https://docs.npmjs.com/cli/v8/commands/npm-uninstall

> This uninstalls a package, completely removing everything npm installed on its behalf.
>
> It also removes the package from the dependencies, devDependencies, optionalDependencies, and peerDependencies objects in your package.json.
>
> Further, if you have an npm-shrinkwrap.json or package-lock.json, npm will update those files as well.

### Steps To Reproduce

1. Run:

```shell
mkdir npm-uninstall-test && cd npm-uninstall-test
npm init -y
npm install typeorm sqlite3
npm uninstall sqlite3
[ -e node_modules/sqlite3 ] && echo package still in node_modules
grep -q node_modules/sqlite3 package-lock.json && echo package still in package-lock.json
```

### Environment

- npm: 8.6.0
- Node.js: v16.14.0
- OS Name: Fedora 35
- System Model Name: HP Laptop
- npm config:
```ini
; "user" config from /home/user/.npmrc

prefix = "/home/user/.local" 

; node bin location = /usr/bin/node
; cwd = /home/user/npm-uninstall-test
; HOME = /home/user
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by G-Rath**
Currently optional peer dependencies are retained so long as at least one package in the tree has them as an optional peer dependency, meaning once added they become non-optional even though `npm` does actually seem to mark such dependencies.

To resolve this, I've modified the pruning logic to check for nodes that are both `optional` and `peer`, in addition to `extraneous` nodes.

## References

Resolves #4737

### CODE REVIEW

**Comment by G-Rath** [comment]
so the Windows tests are failing because my new test results in a request for the `dedent` package and if I've understood all the other tests they don't result in a package after pruning so they avoid needing to do any mocking - I don't mind removing `dedent` from my test too if thats ok; otherwise I'll need guidance on how to address this as my attempts so far (mainly around mocking out the dependency / registry) have failed.

I've kept the adding of the tgz file in case that will be useful - I'm also not sure why this fails only on Windows 😕

File: workspaces/arborist/lib/arborist/build-ideal-tree.js [hunk 1]
```diff
@@ -1516,7 +1516,7 @@ This is a one-time fix-up, please be patient...
 
   #idealTreePrune () {
     for (const node of this.idealTree.inventory.values()) {
-      if (node.extraneous) {
+      if (node.extraneous || (node.peer && node.optional)) {
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/build-ideal-tree.js:1524]: Doesn't this prune ALL optional peer dependencies, not just ones that are extraneous?

Comment (G-Rath) [reply workspaces/arborist/lib/arborist/build-ideal-tree.js:1524]: No because optional peer dependencies are meant to be added to the tree by having an explicit dependent (either in the root `package.json` or by another package that has it as a direct dependency), at which point they stop being an optional peer dependency so will lose at least one of these two flags (most commonly both, but I think technically it could be possible to lose just one).

That's what I mean by "npm does actually seem to mark such dependencies.".

(actually put another way: ALL optional peer dependencies in the tree are extraneous 😄)

Comment (G-Rath) [reply workspaces/arborist/lib/arborist/build-ideal-tree.js:1524]: i.e. this is a snippet of the diff from my local test/exploring repo

image

Comment (wraithgar) [reply workspaces/arborist/lib/arborist/build-ideal-tree.js:1524]: > at which point they stop being an optional peer dependency so will lose at least one of these two flags

Well that is definitely worth a brief clarifying comment above this if statement.

Comment (G-Rath) [reply workspaces/arborist/lib/arborist/build-ideal-tree.js:1524]: done - let me know if you want it tweaked

**Comment by wraithgar** [comment]
>  I'm also not sure why this fails only on Windows

Yeah this is a GOOD thing cause answering this question will help us know if this PR is right.

**Comment by G-Rath** [comment]
@wraithgar so I've spent a few hours trying to dig into this without much luck, though I'm still pretty sure the failure is about the test setup rather than the fix being wrong - if I revert the fix, then all the tests fail with the same kind of error though there's more of them because it's resolving about 20 more packages.

I think the issue is something on the lines of dependencies (not) being cached - the error gets raised when calling this:

https://github.com/npm/cli/blob/c457c7599afa430e3b0eb01bf9fee61464f6b8b7/workspaces/arborist/lib/arborist/reify.js#L799-L803

I also feel like when I revert the fix, the Windows test fail about different packages e.g. it complains about `json-parse-even-better-errors` whereas the Linux tests don't which could make sense if its related to caches and such because that package is a dependency used by NPM.

I don't think I'll be able to dig into this much further by myself I'm afraid as I've not found any solid difference between Windows and Linux 😞

**Comment by G-Rath** [comment]
I hadn't realized that `node_modules/pacote` is actually included in git, so that made it easy to patch in some logging and doing so shows this is because of caching:

image

What's interesting is that this patching also applies to the rest of the CI so I can see that `dedent` is being installed as part of the "reset deps" step which I assume is how it ends up in the cache resulting in the Linux and macOS CIs running...

**Comment by G-Rath** [comment]
ok so the issue is that the wrong cache directory is being used on Windows:

image

`pacote` looks in the home directory for the cache, but on Windows the cache is being stored in `C:\npm`

image

**Comment by G-Rath** [comment]
@wraithgar I've got the tests passing in a manner that you might not be too impressed by, but that I think at least shows the issue isn't with my change

**Comment by wraithgar** [comment]
The workaround is very intentional and well commented.  It's always these one-line tweaks that get so far off the rails when it comes to testing.  Thank you for seeing this through.

**Review by wraithgar — APPROVED** [review]

**Comment by wraithgar** [comment]
It's possible the mock npm fixture has a quirk in windows with this caching but fixing that is way outside the scope of this PR.

**Comment by lkraav** [comment]
Is there a chance of this getting backported?

**Comment by wraithgar** [comment]
@lkraav we typically don't actively do backports but this would probably be something we would consider if a PR was made against the [v10 branch](https://github.com/npm/cli/tree/release/v10)

**Comment by G-Rath** [comment]
I have opened #8449 backporting this, unfortunately CI for Linux and macOS is failing - since (ironically) Windows is passing, I'm guessing it's cache related and I wasn't able to figure out the root cause for this PR.

My very hacky work for exploring this is in https://github.com/G-Rath/cli/tree/prune-optional-peer2 if someone wants to have a crack at digging further - I'm not sure if I'll have the time this week

**Comment by baileympearson** [comment]
Hey @G-Rath , I'm pretty sure this change broke our CI.  I don't think this is a desirable way to fix the linked issue because with this change, it is no longer possible to _install_  a peer optional dependency that isn't tracked as a dependency.  This seems like a regression.  Can we revert this change? 

Context: I maintain the mongodb pacakge, which has a number of peer optional dependencies.  Some of these are native packages with native addons.  One of these dependencies (kerberos) doesn't support the full platform matrix that the mongodb package supports.  So we don't track it as a dependency because if we did `npm i` would fail when we run our test suite on these platforms.  Instead, we explicitly install this dependency before we use it in our test suite (`npm i && npm i kerberos`).  On npm 11.5.0+, explicitly installing the dependency succeeds (exit code 0) but the dependency is not present (`node -p "require('kerberos')"` throws an error because `kerberos` was never installed).

**Comment by billyjanitsch** [comment]
Suppose my package A depends on package B which peer-depends on package C which optionally depends on package D.

This change causes D to be removed from package-lock.json and node_modules.

That doesn't seem correct. D should still be installed.

I think this PR has conflated the concept of optional peer dependencies with the concepts of peer dependencies + optional dependencies.

**Comment by silverwind** [comment]
This change broke my CI as well where I verify that npm generates no diff in the lockfile. With v11.4.2 such optional peer dependencies were present in the lockfile, but since v11.5.0, they are now absent.

The change is fine in itself I guess, but I wonder if npm could better communicate such lockfile-breaking changes better.

**Comment by jenseng** [comment]
Yeah, this change should be reverted or revisited. We tried upgrading our repos to npm 11.5.x, and this broke `npm install` in many of them, since esbuild has some postinstall logic to ensure that the correct versions of platform-specific optional deps are present. Since npm now incorrectly prunes them, that postinstall script fails. See #8536 for more details and a repro.

**Comment by jenseng** [comment]
A potential forward fix is hinted at by [this comment](https://github.com/npm/cli/issues/8464#issuecomment-3161313912), as well as #8489:

> the tl;dr is that npm at least since latest v10 seems to use the "last" encounter with a particular dependency as the final resolution of whether it's optional/dev/peer/etc, so my particular optional (non-peer) dev dep is getting flagged as an optional peer dep because the "last" workspace in my setup happens to only depend on it as an optional peer.

I.e. it sounds like the ideal tree is incorrect, and so these deps end up getting pruned. If we can fix the ideal tree, then this PR may not actually be problematic.

**Comment by silverwind** [comment]
I think there is still some bug that causes unstable lockfile content for optional peer dependencies. I don't think it's related to platform-specific dependencies, seen it with any kind of optional peer dependencies.

**Comment by liamcmitchell** [comment]
> so the Windows tests are failing because my new test results in a request for the `dedent` package and if I've understood all the other tests they don't result in a package after pruning so they avoid needing to do any mocking - I don't mind removing `dedent` from my test too if thats ok; otherwise I'll need guidance on how to address this as my attempts so far (mainly around mocking out the dependency / registry) have failed.
> 
> I've kept the adding of the tgz file in case that will be useful - I'm also not sure why this fails only on Windows 😕

Your workaround didn't work for me running tests locally. I avoided network by adding the dep to fixture `node_modules` in https://github.com/npm/cli/pull/8540

**Comment by owlstronaut** [comment]
@G-Rath my current leaning is to revert this change. I think it is correct, and a good change, but the side effects of other bugs have made this a pretty wide-reaching breaking change for folks. Since the flag fixes are pretty deep internals, I'm not confident we can get a fix for how peer/optional flags flow through the system working correctly quickly. I know that would be disappointing - do you have thoughts about that or alternatives?

**Comment by G-Rath** [comment]
@owlstronaut if you think that's best, then go for it - frankly, not meaning to be rude but what would be most disappointing about that is I don't expect it'll get prioritized anytime soon given the original issue (like some of my others) was open for 2+ years with seemingly next to no maintainer discussion or indication that it had been considered for trying to address 🙃

I would be interested in knowing if you're saying this primarily because of the feedback in this repo or if you've also received other feedback elsewhere (such as from enterprise folks).

**Comment by wraithgar** [comment]
As of https://github.com/npm/cli/pull/8579 it looks like we are not going to have to revert this.  Huge thanks to @owlstronaut for tracking down the last step here to fix the bugs this fix surfaced.  It can be frustrating when this happens, and it does happen more often with projects like npm that have some complex stuff in it that has grown organically over time and has a LOT of users.  Huge thanks to @G-Rath for the initial PR that started us down this road to getting things fixed.  Thanks also to @liamcmitchell and @jenseng for helping with triaging, suggesting fixes, and testing things on their end.

Looking forward to landing that other PR and moving forward, not backward.
