### PR TITLE
fix: local transitive dependencies with --install-links=true

### LINKED ISSUE #5733: [BUG] local transitive dependencies cannot be installed with --install-links=true
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

cannot install my project which has local transitive dependencies.
`npm install` crashes with an error message 

### Expected Behavior

i can install my project which has local transitive dependencies, all local packages are symlinked into the "node_modules" dir.

### Steps To Reproduce

i am using this dummy project: <https://github.com/CycloneDX/cyclonedx-node-npm/tree/main/demo/local-dependencies/project>

1. git clone <https://github.com/CycloneDX/cyclonedx-node-npm.git>
2. cd `demo/local-dependencies/project`
3. run `npm i`
   ```text
   npm ERR! code ENOENT
   npm ERR! syscall open
   npm ERR! path /.../cyclonedx-node-npm/demo/local-dependencies/project/node_modules/my-local-b/package.json
   npm ERR! errno -2
   npm ERR! enoent ENOENT: no such file or directory, open '/.../cyclonedx-node-npm/demo/local-dependencies/project/node_modules/my-local-b/package.json'
   npm ERR! enoent This is related to npm not being able to find a file.
   npm ERR! enoent
   ```

### Environment

- npm: 9.0.0
- Node.js: v16.18.0
- OS Name: ubuntu 22.04 
- System Model Name: some old thinkpad
- npm config:
```ini
; node bin location = /usr/bin/node
; node version = v16.18.0
; npm local prefix = /.../cyclonedx-node-npm/demo/local-dependencies/project
; npm version = 9.0.0
; cwd = /.../cyclonedx-node-npm/demo/local-dependencies/project/packages
; HOME = /home/...
; Run `npm config ls -l` to show all defaults.
```

----

additionally i had the reproducible steps running in a matrix: 
see https://github.com/CycloneDX/cyclonedx-node-npm/actions/runs/3306123198

This setup worked as expected in a test matrix of npm{6,7,8} {windows,macos,ubuntu} node{14,16,18} (=27 passes)

This setup failed with a matrix of npm{9} {windows,macos,ubuntu} node{16,18}  (=6 fails)

### LINKED ISSUE #8342: [BUG] `--install-links` fails when local package has nested local dependencies
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

When installing a local package with `--install-links`, if that package has its own local dependencies, the installation fails. Is this behavior by design?

In this example, package `b` depends on package `a`, both located in sibling directories:

```
$ tree . -I node_modules
.
├── a
│   ├── package-lock.json
│   └── package.json
├── b
│   ├── package-lock.json
│   └── package.json
└── mainpkg
    ├── package-lock.json
    └── package.json

4 directories, 6 files

$ cat b/package.json 
{"name":"b","dependencies":{"a":"file:../a"}}
```

The npm CLI attempts to resolve `../a` from within `node_modules/b` or `node_modules/a`, which does not exist. This results in an `ENOENT` error:

```
$ cd mainpkg && npm install --install-links ../b
npm error code ENOENT
npm error syscall open
npm error path /home/mukai/Documents/mainpkg/node_modules/a/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/mukai/Documents/mainpkg/node_modules/a/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /home/mukai/.npm/_logs/2025-06-03T11_28_04_990Z-debug-0.log
```

### Expected Behavior

The dependency `a`, as listed in `b`'s `package.json`, should be resolved relative to `b` itself (i.e., `../a` from `b`). As a result, the structure of `mainpkg/node_modules` should look like this:

~~~
$ tree mainpkg/node_modules
mainpkg/node_modules
├── a -> ../../a
└── b -> ../../b

3 directories, 0 files
~~~

### Steps To Reproduce

~~~
$ mkdir a b mainpkg
$ echo '{"name":"a"}' > a/package.json
$ echo '{"name":"b"}' > b/package.json
$ cd b && npm install ../a && cd ../
$ cd mainpkg && npm init --yes
$ npm install --install-links ../b
~~~

### Environment

- npm: 11.4.1
- Node.js: v22.14.0
- OS Name: Ubuntu 24.04
- System Model Name: ThinkPad-X1-Carbon-7th
- npm config:
```ini
; "user" config from /home/mukai/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = /home/mukai/.nvm/versions/node/v22.14.0/bin/node
; node version = v22.14.0
; npm local prefix = /home/mukai/Documents/mainpkg
; npm version = 11.4.1
; cwd = /home/mukai/Documents/mainpkg
; HOME = /home/mukai
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by owlstronaut**
# Fix: Local transitive dependencies with --install-links=true

closes #8342
closes #5733

## Problem Statement

Issue #5733: `npm install --install-links=true` fails when projects have local transitive dependencies (file dependencies that reference other packages within the same project root).

**Root Cause**: When `installLinks=true`, the dependency resolution logic copied all file: dependencies instead of symlinking them. For project-internal dependencies, copying breaks transitive dependency resolution because the copied package loses its relative path context to other parts of the project.

## Solution

This PR adds logic to detect project-internal file dependencies and ensures they are always symlinked, regardless of the `installLinks` setting, while external file dependencies continue to respect the user's preference.

### Key Changes

**File**: `workspaces/arborist/lib/arborist/build-ideal-tree.js`

```javascript
    let isProjectInternalFileSpec = false
    if (edge && edge.rawSpec && edge.rawSpec.startsWith('file:') &&
        (edge.rawSpec.startsWith('file:../') || edge.rawSpec.startsWith('file:./'))) {
      const targetPath = resolve(parent.realpath, edge.rawSpec.replace(/^file:/, ''))
      const resolvedProjectRoot = resolve(this.idealTree.realpath)
      // Check if the target is within the project root
      isProjectInternalFileSpec = targetPath.startsWith(resolvedProjectRoot + sep) || targetPath === resolvedProjectRoot
    }
    // Decide whether to link or copy the dependency
    const shouldLink = isWorkspace || isProjectInternalFileSpec || (!isProjectInternalFileSpec && !installLinks)
    if (spec.type === 'directory' && shouldLink) {
      return this.#linkFromSpec(name, spec, parent, edge)
    }
```

## Behavior Matrix

| Dependency Type | installLinks=true | installLinks=false |
|----------------|-------------------|-------------------|
| **Workspace** | LINK | LINK |
| **Project-internal file** (file:./..., file:../... within project) | LINK ⭐ (New Behavior) | LINK |
| **External file** (file:../... outside project) | COPY | LINK |
| **Registry package** | COPY | LINK |

## Technical Details

**Detection Logic**: A file dependency is considered project-internal if its resolved target path is within or equal to the project root directory.

**Integration Point**: The fix integrates cleanly into the existing `#nodeFromSpec()` method's link vs copy decision logic without requiring changes to other parts of the codebase.

## Risk Assessment

**Low Risk**: This is a targeted fix that only affects the specific broken use case. All existing functionality is preserved, and the change is isolated to a single decision point in the dependency resolution flow.

<details>
<summary>FlowChart</summary>

```mermaid
flowchart TD
    A[Directory Dependency Found] --> B{Is it a Workspace?}
    B -->|Yes| LINK1[🔗 LINK - Workspace]
    B -->|No| C{Is it file: dependency?}
    
    C -->|No| D{installLinks setting?}
    C -->|Yes| E{Relative path?<br/>file:../ or file:./}
    
    E -->|No| D
    E -->|Yes| F[Resolve target path]
    F --> G{Target within<br/>project root?}
    
    G -->|Yes| LINK2[🔗 LINK - Project Internal<br/>⭐ NEW BEHAVIOR]
    G -->|No| D
    
    D -->|installLinks=false| LINK3[🔗 LINK - External]
    D -->|installLinks=true| COPY[📁 COPY - External]
```

</details>

### CODE REVIEW

File: workspaces/arborist/lib/arborist/build-ideal-tree.js [hunk 1]
```diff
@@ -1226,9 +1226,22 @@ This is a one-time fix-up, please be patient...
...
-    // spec is a directory, link it unless installLinks is set or it's a workspace
+    // spec is a directory, link it if:
+    // - it's a workspace, OR
+    // - it's a project-internal file: dependency (always linked), OR
+    // - it's external and installLinks is false
     // TODO post arborist refactor, will need to check for installStrategy=linked
-    if (spec.type === 'directory' && (isWorkspace || !installLinks)) {
+    let isProjectInternalFileSpec = false
+    if (edge && edge.rawSpec && edge.rawSpec.startsWith('file:') &&
+        (edge.rawSpec.startsWith('file:../') || edge.rawSpec.startsWith('file:./'))) {
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/build-ideal-tree.js]:
```suggestion
    if (edge?.rawSpec.startsWith('file:../') || edge?.rawSpec.startsWith('file:./')) {
```

I don't *think* we need `rawSpec?.` I think if it exists it's a string thanks to npm-package-arg.

File: workspaces/arborist/lib/arborist/build-ideal-tree.js [hunk 2]
```diff
@@ -1226,9 +1226,22 @@ This is a one-time fix-up, please be patient...
...
+      const targetPath = resolve(parent.realpath, edge.rawSpec.replace(/^file:/, ''))
+      const resolvedProjectRoot = resolve(this.idealTree.realpath)
+      // Check if the target is within the project root
+      isProjectInternalFileSpec = targetPath.startsWith(resolvedProjectRoot + sep) || targetPath === resolvedProjectRoot
+    }
+    // Decide whether to link or copy the dependency
+    const shouldLink = isWorkspace || isProjectInternalFileSpec || (!isProjectInternalFileSpec && !installLinks)
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/build-ideal-tree.js]:
```suggestion
    const shouldLink = isWorkspace || isProjectInternalFileSpec || !installLinks
```

Boolean logic is fun!  If we get to the last `||` we already know that `!isWorkspace` and `!isProjectInternalFileSpec`

File: workspaces/arborist/lib/arborist/build-ideal-tree.js [hunk 3]
```diff
@@ -1226,9 +1226,22 @@ This is a one-time fix-up, please be patient...
...
+    // spec is a directory, link it if:
+    // - it's a workspace, OR
+    // - it's a project-internal file: dependency (always linked), OR
+    // - it's external and installLinks is false
     // TODO post arborist refactor, will need to check for installStrategy=linked
-    if (spec.type === 'directory' && (isWorkspace || !installLinks)) {
+    let isProjectInternalFileSpec = false
+    if (edge && edge.rawSpec && edge.rawSpec.startsWith('file:') &&
+        (edge.rawSpec.startsWith('file:../') || edge.rawSpec.startsWith('file:./'))) {
+      const targetPath = resolve(parent.realpath, edge.rawSpec.replace(/^file:/, ''))
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/build-ideal-tree.js]:
```suggestion
      const targetPath = resolve(parent.realpath, edge.rawSpec.slice(5))
```

**Review by wraithgar — APPROVED** [review]
Very clean, yay.
