### PR TITLE
fix: show more information during publish dry-run

### LINKED ISSUE #4317: [BUG] npm registry not showed on publish --dry-run
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running:

```
npm publish --verbose --access restricted --dry-run
```

does not show the registry information added in https://github.com/npm/cli/pull/4143

Running the `publish` command without the `--dry-run` flag the registry is shown as expected.

### Expected Behavior

The npm cli should show the registry information

### Steps To Reproduce

Just run:

```
npm publish --verbose --access restricted --dry-run
```

### Environment

- npm: 8.3.1 <-- edit: fix version
- Node.js: 17.4.0
- OS Name: macos
- System Model Name:
- npm config:
```ini
; "user" config from /Users/mspigolon/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
access = null 
if-present = true 
init-license = "MIT" 

; "project" config from /Users/mspigolon/workspace/xxxcutxxxxx/.npmrc

@xxxcutxxxxx:registry = "https://npm.xxxcutxxxxx.net" 
//npm.xxxcutxxxxx.net/:_authToken = (protected) 

; node bin location = /Users/mspigolon/.nvm/versions/node/v17.4.0/bin/node
; cwd = /Users/mspigolon/workspace/xxxcutxxxxx
; HOME = /Users/mspigolon
; Run `npm config ls -l` to show all defaults.

; "publishConfig" from /Users/mspigolon/workspace/xxxcutxxxxx/package.json
; This set of config values will be used at publish-time.

registry = "https://npm.xxxcutxxxxx.net"
```

### PR DESCRIPTION
**Pull request by lukekarrys**
Fixes #4317

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
awesome

**Comment by wraithgar** [comment]
Dry-run not checking credentials was an intentional thing, to keep compatibility with npm6 https://github.com/npm/cli/pull/2422

File: lib/commands/publish.js [hunk 1]
```diff
@@ -102,19 +102,20 @@ class Publish extends BaseCommand {
...
+    const registry = npmFetch.pickRegistry(resolved, opts)
+    const creds = this.npm.config.getCredentialsByURI(registry)
+    const outputRegistry = replaceInfo(registry)
+    if (!creds.token && !creds.username) {
+      throw Object.assign(
+        new Error(`This command requires you to be logged in to ${outputRegistry}`), {
+          code: 'ENEEDAUTH',
+        }
+      )
+    }
```
Comment (ljharb) [inline lib/commands/publish.js]: then perhaps just this part could be in the non-dry-run branch?

Comment (lukekarrys) [reply lib/commands/publish.js]: @wraithgar do you have an opinion on if only the error should be thrown during non-dry-run? or if this line should be guarded too

```
const creds = this.npm.config.getCredentialsByURI(registry)
```

Comment (wraithgar) [reply lib/commands/publish.js]: It should not throw in dry-run. If we want to add an error message saying "hey this would fail auth" that's fine, but the rest of the output is important too even if auth is missing.

**Comment by lukekarrys** [comment]
```
❯ node . publish --dry-run 
...
npm notice bundled deps:  195                                     
npm notice bundled files: 0                                       
npm notice own files:     1752                                    
npm notice total files:   1752                                    
npm notice 
npm notice Publishing to https://registry.npmjs.org/ (dry-run)
+ npm@8.6.0
```

```
node . publish --dry-run --registry=https://npm.pkg.github.com
...
npm notice bundled deps:  195                                     
npm notice bundled files: 0                                       
npm notice own files:     1752                                    
npm notice total files:   1752                                    
npm notice 
npm WARN This command requires you to be logged in to https://npm.pkg.github.com/ (dry-run)
npm notice Publishing to https://npm.pkg.github.com/ (dry-run)
+ npm@8.6.0
```

**Review by wraithgar — APPROVED** [review]
