### PR TITLE
fix: `$npm_execpath` always points to npm, even when running npx

### LINKED ISSUE #6662: [BUG] `npm_execpath` is set to the path of `npx` instead of `npm`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The env `npm_execpath` can be path of `npx`  instead of `npm` if the user runs a command with `npx`, e.g. `npx node -e "console.log(process.env.npm_execpath)"`, the output will be `/path/to/npm/9.8.1/bin/npx-cli.js`

https://github.com/npm/cli/blob/4689ae4d2167712d893b6193a4347b26779acf9e/workspaces/config/lib/set-envs.js#L106

I did not find the official definition for `npm_execpath`, but I assume it should only be the path of `npm` based its name, not the path of `npx`.

Some popular libraries, e.g `npm-run-all`, using `npm_execpath` and assuming it's the package manager path and add `run` arg to it, so if you run `npx npm-run-all test`, it is the same as `npx run test` which will install a package called [`run`](https://www.npmjs.com/package/run) and [throw errors](https://github.com/mysticatea/npm-run-all/issues/209).

Yarn also suggests use `$npm_execpath run <name>` which can cause the same problem: https://yarnpkg.com/advanced/rulebook#published-packages-should-avoid-using-npm-run-in-their-scripts

### Expected Behavior

`npm_execpath` should always be set as the path of `npm`.

### Steps To Reproduce

Run `npx node -e "console.log(process.env.npm_execpath)"`

The output will be `/path/to/npm/9.8.1/bin/npx-cli.js`

### Environment

- npm: 9.8.1
- Node.js: 20.4.0
- OS Name:  MacOS
- System Model Name: Macbook Pro
- npm config:
```ini
n/a
```

### PR DESCRIPTION
**Pull request by rotu**
When running a script with `npx` (but *not* with `npm exec`), `$npm_execpath` is set to ".../npm/bin/npx-cli.js". This causes packages to fail to detect the package manager.

Now `$npm_execpath` will always be the path to `npm-cli.js`.

## References
Fixes #6662

### CODE REVIEW

**Comment by Islam260301** [comment]
sadasd

File: workspaces/config/lib/definitions/index.js [hunk 1]
```diff
@@ -19,10 +19,6 @@ const flatten = (obj, flat = {}) => {
     }
   }
 
-  // XXX make this the bin/npm-cli.js file explicitly instead
-  // otherwise using npm programmatically is a bit of a pain.
-  flat.npmBin = require.main ? require.main.filename
```
Comment (wraithgar) [inline workspaces/config/lib/definitions/index.js:24]: we still need this set on the flatOptions.  Modules like [`pacote`](https://github.com/npm/pacote/blob/18e760f5c438155c1b8af8aa1ffbead874732058/lib/fetcher.js#L112) use this to spawn npm for scripts

Comment (rotu) [reply workspaces/config/lib/definitions/index.js:24]: Can do. BTW, on flatOptions, the `nodeBin` property is set basically as `process.env.NODE || process.execPath` but in set-envs, the environment variable `$NODE` is set to `process.execPath`.

Do you know why? Is this environment variable supposed to be clobbered?

Comment (wraithgar) [reply workspaces/config/lib/definitions/index.js:24]: In `set-envs.js` it's set to `config.execPath`.  It's changed by [npm itself](https://github.com/npm/cli/blob/latest/lib/npm.js#L188-L192) if it detects it's running from a symlink

File: workspaces/config/lib/index.js [hunk 2]
```diff
@@ -232,6 +232,8 @@ class Config {
     for (const { data } of this.data.values()) {
       this.#flatten(data, this.#flatOptions)
     }
+    this.#flatOptions.nodeBin = process.env.NODE || this.execPath
```
Comment (wraithgar) [inline workspaces/config/lib/index.js]: Oh yes very much thank you.  When reading the flatten code for this PR it stuck out that we were doing this in the flatten command.

**Comment by wraithgar** [comment]
Not sure why CI is having the specific errors it is, but when I run config tests locally they don't pass, and there are coverage issues.  Does `npm test -w @npmcli/config` pass locally for you?

**Comment by rotu** [comment]
I'm surprised it's trying to run against node <18. This commit definitely broke the runs on node 14: https://github.com/npm/cli/commit/b8a5764db60cb2b3edb7887cf4379f48411a0b55

No, the CI is not currently passing for me locally. ~~I suspect it has to do with this gotcha [from the docs](https://nodejs.org/api/modules.html#requiremain):~~

~~> When the entry point is not a CommonJS module, require.main is undefined, and the main module is out of reach.~~

I had to adjust some tests to account for moving logic out of the flatten helper.

I'll figure out the coverage issue once I verify the tests run as expected.

**Comment by rotu** [comment]
The last commit (https://github.com/npm/cli/pull/6762/commits/b8b1db3974112d784df3475fb57338975ee65874#) I'm slightly unsure about.

This commit started writing to the variable: https://github.com/npm/cli/commit/c3ba1daf7cd335d72aeba80ae0e9f9d215ca9ea5
But I can't figure out why we would ever read *from* this variable. It seems to maybe have originated in testing code here and accidentally copied into the main code flow: https://github.com/npm/config/commit/fd6432eb242b2b427d1fdef19274c1ca6fea37dd

EDIT: it also seems like inheriting this value is probably unexpected, given https://github.com/npm/config/pull/12 for the closely related `$INIT_CWD` (which you may remember from the above-mentioned https://github.com/npm/cli/commit/c3ba1daf7cd335d72aeba80ae0e9f9d215ca9ea5)

Your thoughts are much appreciated.

**Comment by rotu** [comment]
BTW, as of now, test cases all pass for me and coverage is at 100%.

**Comment by wraithgar** [comment]
I agree that the `process.env.NODE` is in all likelihood a dependency injection leftover from a test.  I don't know if that means we can remove it.

Historically we have been removing the ability to change things like this, for instance in npm 10 re removed the `ci-name` config.  Previously we also did not allow folks to change what the path to `npm` was in scripts.

However, removing this could be a [breaking change to folks](https://xkcd.com/1172/).  We're gonna have to leave it in.  *However* I also think we shouldn't worry about covering that in testing.  Can you add `/* istanbul ignore next */` to the line before it, and put it back in?

I'll add a note to the [npm 11 roadmap](https://github.com/npm/statusboard/issues/488) to remove it for real.

File: workspaces/config/lib/set-envs.js [hunk 3]
```diff
@@ -101,10 +101,7 @@ const setEnvs = (config) => {
   if (cliConf['node-options']) {
     env.NODE_OPTIONS = cliConf['node-options']
   }
-
-  if (require.main && require.main.filename) {
-    env.npm_execpath = require.main.filename
-  }
+  env.npm_execpath = config.npmBin
   env.NODE = env.npm_node_execpath = config.execPath
```
Comment (wraithgar) [inline workspaces/config/lib/set-envs.js:105]: We are setting process.env.NODE here, this could be why we later short circuit to reading back from it in the `nodeBin` variable.  This is another place to reevaluate in npm 11 or beyond.

**Comment by rotu** [comment]
> However, removing this could be a [breaking change to folks](https://xkcd.com/1172/). We're gonna have to leave it in. _However_ I also think we shouldn't worry about covering that in testing. Can you add `/* istanbul ignore next */` to the line before it, and put it back in?

I thought about that and it makes me feel icky. The ignored path is the one MOST COMMON in practice. This PR is already a breaking change, and insofar as the NODE environment variable does anything, it’s a bug as well.

If you still insist, I can move it to another PR.

File: workspaces/config/lib/set-envs.js (hunk 3 above)
Comment (rotu) [reply workspaces/config/lib/set-envs.js:105]: I saw that. And I think that was same misunderstanding that led to the situation with $INIT_CWD.

**Comment by wraithgar** [comment]
Ok lemme noodle on it.

Ultimately the NODE environment is in all likelihood trying to solve the problem of having everything in side the npm lifecycle use the same node version as the one that npm was ran with.  I do remember this being an issue in the past, we don't want to support running different versions of node or npm in subprocesses.  In the past this manifested as refusing to support a config that told npm what version of node to run, that's an OS concern.

I think removing it may be the right choice here but as you can imagine we are trying to be extremely cautious with things that could break other folks.

**Comment by rotu** [comment]
> Ok lemme noodle on it.

@wraithgar, what did your noodle say?

**Review by wraithgar — APPROVED** [review]
We can re-export NODE if an edge case we didn't know about comes to light.

**Comment by rotu** [comment]
Woohoo!

> We can re-export NODE if an edge case we didn't know about comes to light.

I didn’t stop exporting `$NODE` to subprocess - I stopped npm from *importing* it from the parent process.

**Comment by wraithgar** [comment]
Ok yeah that's what I get from typing from memory.
