### PR TITLE
fix: peer edge crash due to no parent or detached node

### LINKED ISSUE #8261: [BUG] Cannot read properties of null (reading 'edgesOut') - on `npm i`
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

After a simple `npm i` the CLI errors with:

```sh
npm error Cannot read properties of null (reading 'edgesOut')
```

The log shows the following:

```sh
289 silly fetch manifest happy-dom@*
290 silly packumentCache full:https://company-registry:8765/npm/hmrs-dev-internal-npm/happy-dom cache-miss
291 http cache https://company-registry:8765/npm/hmrs-dev-internal-npm/happy-dom 22ms (cache hit)
292 silly packumentCache full:https://company-registry:8765/npm/hmrs-dev-internal-npm/happy-dom set size:1135281 disposed:false
293 verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
293 verbose stack     at #loadPeerSet (C:\Users\username\AppData\Roaming\nvm\v22.14.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1304:38)
293 verbose stack     at async #buildDepStep (C:\Users\username\AppData\Roaming\nvm\v22.14.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:915:11)
293 verbose stack     at async Arborist.buildIdealTree (C:\Users\username\AppData\Roaming\nvm\v22.14.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:182:7)
293 verbose stack     at async Promise.all (index 1)
293 verbose stack     at async Arborist.reify (C:\Users\username\AppData\Roaming\nvm\v22.14.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:130:5)
293 verbose stack     at async Install.exec (C:\Users\username\AppData\Roaming\nvm\v22.14.0\node_modules\npm\lib\commands\install.js:149:5)
293 verbose stack     at async Npm.exec (C:\Users\username\AppData\Roaming\nvm\v22.14.0\node_modules\npm\lib\npm.js:208:9)
293 verbose stack     at async module.exports (C:\Users\username\AppData\Roaming\nvm\v22.14.0\node_modules\npm\lib\cli\entry.js:67:5)
294 error Cannot read properties of null (reading 'edgesOut')
295 silly unfinished npm timer reify 1745836838067
296 silly unfinished npm timer reify:loadTrees 1745836838069
297 silly unfinished npm timer idealTree:buildDeps 1745836838098
298 silly unfinished npm timer idealTree:#root 1745836838100
300 verbose os Windows_NT 10.0.26100
301 verbose node v22.14.0
302 verbose npm  v11.3.0
303 verbose exit 1
304 verbose code 1
```

### Expected Behavior

_No response_

### Steps To Reproduce

I'm trying to provide a reproduction package.json file.

### Environment

- npm: 11.3.0
- Node.js: 22.14.0
- OS Name: Windows 11
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

### PR DESCRIPTION
**Pull request by milaninfy**
`node.parent` is resulting in `null` value somewhere in recursive/looped calls to `#loadPeerSet` method in building ideal tree.

When circular peer ref of a top level dependency replaced/resolved with different compatible version, it makes top level dependency to be removed from it's parent ( node.parent = null ) since it's been replaced, so no longer need to proceed with further peer set exploration.

fixes: https://github.com/npm/cli/issues/8261

### CODE REVIEW

File: workspaces/arborist/lib/arborist/build-ideal-tree.js [hunk 1]
```diff
@@ -1306,6 +1306,11 @@ This is a one-time fix-up, please be patient...
       .sort(({ name: a }, { name: b }) => localeCompare(a, b))
 
     for (const edge of peerEdges) {
+      // if node is detached/removed from the tree, or has no parent,
+      // then we can't place the peer dep, so skip it.
+      if (!node.parent) {
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/build-ideal-tree.js:1312]: If the node has no parent we should skip the loop altogether.  This approach still loops through every edge and does nothing, instead of just skipping the entire for loop if there is no parent.  An if statement wrapping the for loop seems more effecient.

Comment (milaninfy) [reply workspaces/arborist/lib/arborist/build-ideal-tree.js:1312]: Going into the loop, node has parent, in the loop we have recursive call via `#nodeFromEdge` function, node.parent becoming null when it's getting replaced (or anther compatible peer is found) with another node. 
something like a@1.2.0 explores peers b@1.1.0 & c@1.1.0 which also explores it's peer a@1.1.0 and ultimately instead of a@1.2.0 it uses a@1.1.0.  
since loop started with a@1.2.0 which is no longer in the tree ( since a@1.1.0 was placed ) don't have parent. 

in general node.parent property is getting mutated in/through the loop somewhere, that's why the break is in the loop instead of covering entire loop.

Comment (wraithgar) [reply workspaces/arborist/lib/arborist/build-ideal-tree.js:1312]: Oof I didn't realize state was being manipulated like that.  Ok.  Let's add a comment at least explaining this.

Comment (milaninfy) [reply workspaces/arborist/lib/arborist/build-ideal-tree.js:1312]: Added Comments for this behaviour.

**Review by wraithgar — APPROVED** [review]

**Review by carlajarchuleta1-a11y — COMMENTED** [review]
milaninfy:mm/fix-peer-load
