### PR TITLE
fix(arborist): retry bin-links on Windows EPERM

### LINKED ISSUE #9021: [BUG] EPERM on Windows with `install-strategy=linked`: `fs.rename` fails in `write-file-atomic`
## Is there an existing issue for this?

- [x] I have searched the existing issues

See [Related Issues](#related-issues) below. This is a known class of problem on Windows, but `install-strategy=linked` makes it significantly more likely to trigger.

## This issue exists in the latest npm version

- [x] I am using the latest npm

Reproducible with both npm 10.9.x and npm 11.x.

## Current Behavior

We are testing `install-strategy=linked` on the [Gutenberg monorepo](https://github.com/WordPress/gutenberg/pull/75814) (~200 workspace packages). On Windows, `npm install` fails with `EPERM: operation not permitted` during the reify phase. The rename happens inside `write-file-atomic`, which writes to a temp file and then calls `fs.rename()` to move it into place. On Windows, transient file locks from antivirus (Windows Defender) or the search indexer cause this rename to fail.

```
npm error code EPERM
npm error syscall rename
npm error path D:\a\gutenberg\gutenberg\node_modules\.store\jscodeshift@0.14.0-6sY5dqfkSNugpVGmHmy3mQ\node_modules\jscodeshift\bin\jscodeshift.js.2477615846
npm error dest D:\a\gutenberg\gutenberg\node_modules\.store\jscodeshift@0.14.0-6sY5dqfkSNugpVGmHmy3mQ\node_modules\jscodeshift\bin\jscodeshift.js
npm error errno -4048
npm error [Error: EPERM: operation not permitted, rename '...\jscodeshift.js.2477615846' -> '...\jscodeshift.js'] {
npm error   errno: -4048,
npm error   code: 'EPERM',
npm error   syscall: 'rename',
npm error }
npm error The operation was rejected by your operating system.
```

Cleanup also fails with a similar EPERM:

```
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'D:\\a\\gutenberg\\gutenberg\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir '...\.store\@react-native\debugger-frontend@0.73.3-...\node_modules\@react-native\debugger-frontend'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup     }
npm warn cleanup   ]
```

## Expected Behavior

`npm install` should complete successfully on Windows with `install-strategy=linked`, handling transient file locks gracefully with retries.

## Steps To Reproduce

This needs a Windows environment with real-time antivirus enabled (the default on GitHub Actions `windows-2025` runners).

### Standalone (PowerShell)

```powershell
# Requires Node.js 20+ on Windows
mkdir test-linked
cd test-linked
npm init -y

# Enable linked strategy
"install-strategy=linked" | Out-File -Encoding utf8 .npmrc

# Install packages with many transitive deps and bin files with hashbangs
npm install jscodeshift@0.14.0 @react-native/debugger-frontend@0.73.3
```

This may not fail every time with a small project. The race condition is more likely with large monorepos that write many `.store` entries in parallel. In our case, it happens with the [Gutenberg](https://github.com/WordPress/gutenberg) monorepo (~200 workspace packages).

### GitHub Actions

```yaml
name: Reproduce EPERM
on: workflow_dispatch

jobs:
  test:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
```

With an `.npmrc` containing `install-strategy=linked` and a sufficiently large dependency tree.

**Failed CI run**: https://github.com/WordPress/gutenberg/actions/runs/22299881844/job/64504879968?pr=75814

## Environment

- npm: 10.9.x (also reproducible with npm 11.x)
- Node.js: v20.x
- OS Name: Windows Server 2025 (GitHub Actions `windows-2025`)
- npm config:
  ```ini
  install-strategy=linked
  ```

## Root Cause

The linked strategy stores packages in `node_modules/.store/<pkg>@<version>-<hash>/node_modules/<pkg>/` and hard-links files from the npm cache. During reify, `bin-links/fix-bin.js` rewrites hashbang lines in bin files using `write-file-atomic`, which does a temp-file write followed by `fs.rename()`.

On Windows, this rename fails because:

1. **Transient file locks from antivirus**: Windows Defender real-time scanning opens files as they're written. When the rename fires immediately after the write, the target may still be held open by the scanner. The linked strategy writes many files in parallel into `.store/`, making it more likely that the scanner is still processing a file when the rename happens.

2. **No retry in `write-file-atomic`**: The package uses bare `require('fs')` ([line 7](https://github.com/npm/write-file-atomic/blob/main/lib/index.js#L7)) and has no retry logic for `rename`. By contrast, `graceful-fs` already patches `fs.rename` on Windows with exponential backoff (up to 60s) for EACCES/EPERM/EBUSY errors ([`polyfills.js` lines 96-120](https://github.com/isaacs/node-graceful-fs/blob/master/polyfills.js#L96-L120)). Since `write-file-atomic` uses bare `fs`, it doesn't get this retry and fails immediately.

   <details>
   <summary><code>graceful-fs</code> Windows rename retry logic</summary>

   ```js
   if (platform === "win32") {
     fs.rename = (function (fs$rename) {
       function rename (from, to, cb) {
         var start = Date.now()
         var backoff = 0;
         fs$rename(from, to, function CB (er) {
           if (er
               && (er.code === "EACCES" || er.code === "EPERM" || er.code === "EBUSY")
               && Date.now() - start < 60000) {
             setTimeout(function() {
               fs.stat(to, function (stater, st) {
                 if (stater && stater.code === "ENOENT")
                   fs$rename(from, to, CB);
                 else
                   cb(er)
               })
             }, backoff)
             if (backoff < 100)
               backoff += 10;
             return;
           }
           if (cb) cb(er)
         })
       }
       // ...
     })(fs.rename)
   }
   ```

   </details>

3. **Hard link locking across entries**: Files in `.store` are hard-linked from the npm cache. On Windows, if any hard link to the same underlying inode is open (e.g., the cache copy being scanned), renaming the target fails with EPERM.

The hoisted layout writes packages directly into `node_modules/`, while the linked layout writes everything into `.store/` first and then creates symlinks, resulting in more parallel file operations in a single directory tree and a larger window for antivirus lock conflicts.

## Suggested Fixes

There are two places this could be addressed:

### 1. In npm (arborist): retry `binLinks` on Windows

The `rebuild.js` step in `@npmcli/arborist` could wrap the `binLinks()` call with retry logic for transient Windows errors. This handles the problem at the npm level without waiting on upstream changes to `write-file-atomic`.

```js
// workspaces/arborist/lib/arborist/rebuild.js
async #binLinksWithRetry (node, retries = 5) {
  try {
    return await binLinks({
      pkg: node.package,
      path: node.path,
      top: !!(node.isTop || node.globalTop),
      force: this.options.force,
      global: !!node.globalTop,
    })
  } catch (err) {
    if (process.platform === 'win32' &&
        retries > 0 &&
        (err.code === 'EPERM' || err.code === 'EACCES' || err.code === 'EBUSY')) {
      const delay = (6 - retries) * 500
      await new Promise(r => setTimeout(r, delay))
      return this.#binLinksWithRetry(node, retries - 1)
    }
    throw err
  }
}
```

We tested this approach in [our fork](https://github.com/manzoorwanijk/npm-cli/commit/e110c7aea508c18068c81d866670e93e68609a50) and it resolves the issue on Windows CI.

### 2. In `write-file-atomic`: use `graceful-fs`

The underlying issue is that `write-file-atomic` uses bare `require('fs')` and misses the Windows rename retry that `graceful-fs` provides. Swapping it in would fix this for all consumers:

```diff
- const fs = require('fs')
+ const fs = require('graceful-fs')
```

`graceful-fs` is already a transitive dependency across the npm ecosystem, so this wouldn't add new weight. This would be a separate issue/PR on the [`write-file-atomic`](https://github.com/npm/write-file-atomic) repo.

## Related Issues

This problem has been reported in various forms:

- [npm/write-file-atomic#28](https://github.com/npm/write-file-atomic/issues/28) -- EPERM on Windows when multiple processes write the same file. Open since 2017, documents the same `fs.rename` race condition in `write-file-atomic`. Originally surfaced via Jest parallel workers ([facebook/jest#4444](https://github.com/facebook/jest/issues/4444)).
- [npm/cli#8072](https://github.com/npm/cli/issues/8072) -- EPERM during `npm install` on Windows with npm 10.x. Users report it works on macOS and with older npm 9.x, suggesting a regression in how npm 10 handles file operations on Windows.
- [npm/cli#6412](https://github.com/npm/cli/issues/6412) -- EPERM when `npm install` tries to `mkdir` on a Windows drive root. A different trigger but the same underlying Windows file permission behavior.

The linked strategy amplifies the existing problem because it concentrates all file writes into `.store/` with heavy parallelism, increasing the chance that antivirus scanning overlaps with rename operations.

### PR DESCRIPTION
**Pull request by manzoorwanijk**
In continuation of our exploration of using `install-strategy=linked` in the [Gutenberg monorepo](https://github.com/WordPress/gutenberg/pull/75814), which powers the WordPress Block Editor, this is a follow up of the fixes from #8996.

On Windows, `npm install` with `install-strategy=linked` fails with `EPERM: operation not permitted` during the bin-linking phase. This is hitting us on Windows CI for the [Gutenberg monorepo](https://github.com/WordPress/gutenberg/pull/75814) (~200 workspace packages).

## Summary

During rebuild, `bin-links/fix-bin.js` rewrites hashbang lines in bin files using `write-file-atomic`, which does a temp-file write followed by `fs.rename()`. On Windows, antivirus (Windows Defender) and the search indexer can transiently lock files that were just written, causing the rename to fail with EPERM.

The linked strategy amplifies this because it writes all packages into `.store/` in parallel, increasing the window for antivirus lock conflicts compared to the hoisted layout.

## Root cause

npm already patches the global `fs` with `graceful-fs` at startup ([entry.js:8](https://github.com/npm/cli/blob/10d530242c7d893c562456013bb1c5104ca3e3b8/lib/cli/entry.js#L8)), which adds Windows rename retry logic. However, `graceful-fs`'s retry only kicks in when the destination file does **not** exist — it checks `fs.stat(to)` after EPERM, and if the target already exists (stat succeeds), it [gives up immediately](https://github.com/isaacs/node-graceful-fs/blob/master/polyfills.js#L107-L111). In `write-file-atomic`'s case, the destination file always exists (it's being overwritten), so the retry never fires.

## Changes

- ~~Wrapped the `binLinks()` call in `rebuild.js` `#createBinLinks` with a new `#binLinksWithRetry` method that retries up to 5 times with 500ms–2.5s backoff on Windows when the error code is EPERM, EACCES, or EBUSY.~~
- Wrapped the `binLinks()` call in `rebuild.js` `#createBinLinks` with `@gar/promise-retry`. On Windows, EPERM/EACCES/EBUSY errors trigger a retry with exponential backoff (5 retries, 500ms min timeout).
- Added `@gar/promise-retry` to arborist's dependencies.
- The retry only activates on `process.platform === 'win32'` — no behavior change on macOS/Linux.

## Testing

We tested this approach in [our fork](https://github.com/manzoorwanijk/npm-cli/commit/ea7a1774eb00143510fbcf5f97d684c8b8652204) and it resolves the issue on Windows CI for the Gutenberg monorepo.

## References

Fixes #9021

### CODE REVIEW

File: workspaces/arborist/lib/arborist/rebuild.js [hunk 1]
```diff
@@ -15,6 +15,30 @@ const { resolve } = require('node:path')
 const boolEnv = b => b ? '1' : ''
 const sortNodes = (a, b) => (a.depth - b.depth) || localeCompare(a.path, b.path)
 
+// On Windows, antivirus/indexer can transiently lock files, causing
+// EPERM/EACCES/EBUSY on the rename inside write-file-atomic (used by
+// bin-links/fix-bin.js).  Retry with backoff for up to ~7.5 seconds.
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/rebuild.js]:
```suggestion
// On Windows, antivirus/indexer can transiently lock files, causing EPERM/EACCES/EBUSY on the rename inside write-file-atomic (used by bin-links/fix-bin.js).
// Retry with backoff for up to ~7.5 seconds.
```

As part of our efforts to increase accessibility we try to keep comments all on one line, breaking only for sentences.

File: workspaces/arborist/lib/arborist/rebuild.js [hunk 2]
```diff
@@ -15,6 +15,30 @@ const { resolve } = require('node:path')
...
+/* istanbul ignore next */
+const retryBinLinks = async (binLinks, node, opts, retries = 4) => {
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/rebuild.js]: Elsewhere we have delegated retries to a library.  There is a LOT that goes into retrying and it's not something we want to hand roll.

https://github.com/npm/cli/blob/10d530242c7d893c562456013bb1c5104ca3e3b8/workspaces/libnpmexec/lib/with-lock.js#L70

File: workspaces/arborist/lib/arborist/rebuild.js [hunk 3]
```diff
@@ -15,6 +15,30 @@ const { resolve } = require('node:path')
...
+  try {
+    return await binLinks({
+      pkg: node.package,
+      path: node.path,
+      top: !!(node.isTop || node.globalTop),
+      force: opts.force,
+      global: !!node.globalTop,
+    })
+  } catch (err) {
+    if (retries > 0 &&
```
Comment (wraithgar) [inline workspaces/arborist/lib/arborist/rebuild.js]: This is a good example of why a retry library is the right option. We can wrap this whole thing in the retry library and then make the decision on whether or not to retry it at all (by checking codes) in our callback.

**Comment by wraithgar** [comment]
We may want to dig into the `write-file-atomic` PR first to see why this isn't already happening.

**Comment by manzoorwanijk** [comment]
> We may want to dig into the `write-file-atomic` PR first to see why this isn't already happening.

I dug into this. As you already [pointed out](https://github.com/npm/write-file-atomic/pull/228#issuecomment-3994137158), npm already calls `gracefulify(require('node:fs'))` at startup ([entry.js:8](https://github.com/npm/cli/blob/10d530242c7d893c562456013bb1c5104ca3e3b8/lib/cli/entry.js#L8)), which patches the global fs singleton - so `write-file-atomic`'s `require('fs')` already gets the patched `fs.rename`.

The reason it doesn't help is that `graceful-fs`'s rename retry has a condition that prevents it from retrying in this case. After getting `EPERM`, it does `fs.stat(to)` - if the destination file already exists (stat succeeds), it [gives up immediately](https://github.com/isaacs/node-graceful-fs/blob/f7a43701434b3e8f1c3c9fe9df972330de8b7ecb/polyfills.js#L107-L112) without retrying. In `write-file-atomic`'s case, the destination file always exists (it's being overwritten), so the retry never fires.

The fix needs to be here at the arborist level. I'll update to use `promiseRetry` per your review.

File: workspaces/arborist/lib/arborist/rebuild.js (hunk 2 above)
Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/rebuild.js]: Updated. Thanks.

File: workspaces/arborist/lib/arborist/rebuild.js (hunk 3 above)
Comment (manzoorwanijk) [reply workspaces/arborist/lib/arborist/rebuild.js]: Yes, better to hand it over to something robust. I have updated it. Thank you for the hint.

File: package-lock.json [hunk 4]
```diff
@@ -14440,6 +14440,7 @@
       "version": "9.4.0",
       "license": "ISC",
       "dependencies": {
+        "@gar/promise-retry": "^1.0.0",
```
Comment (wraithgar) [inline package-lock.json:14443]: We are making an exception for this PR on our [policy accepting dependency updates](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#dependencies).  This dependency is already in the npm tree, and adding it is only a matter of adding it to the package.json and lockfile.  The bundled assets are already present.

**Comment by wraithgar** [comment]
Oh yes so much cleaner w/ the retry library!

**Review by wraithgar — APPROVED** [review]

File: package-lock.json (hunk 4 above)
Comment (manzoorwanijk) [reply package-lock.json:14443]: Yes, I already saw it already used in the repo and used the exact same version for the same reason.
