### PR TITLE
fix(libnpmpublish): unpublish from custom reg

### LINKED ISSUE #4253: [BUG](libnpmpublish) Unpublish url not correctly defined
Hello,

When unpublishing a package into an internal repository (such as artifactory) where the registry contains a path, the tarballUrl bellow (unpublish.js:71) will be wrong as it will contain the full registry path

`const tarballUrl = url.parse(dist.tarball).pathname.substr(1)`

Example :

C:\>npm unpublish  my-app@1.0-SNAPSHOT --verbose --force --registry https://artifactory.example.com/api/npm/npm-snapshots/
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Tools\\node-v10.16.3-win-x64\\node.exe',
npm verb cli   'C:\\Tools\\node-v10.16.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'unpublish',
npm verb cli   'my-app@1.0-SNAPSHOT',
npm verb cli   '--verbose',
npm verb cli   '--force',
npm verb cli   '--registry',
npm verb cli   'https://artifactory.example.com/api/npm/npm-snapshots/' ]
npm info using npm@6.9.0
npm info using node@v10.16.3
npm WARN using --force I sure hope you know what you are doing.
npm verb npm-session 501f69ac7af05ab3
npm http fetch GET 200 https://artifactory.example.com/api/npm/npm-snapshots/my-app?write=true 372ms
npm http fetch PUT 200 https://artifactory.example.com/api/npm/npm-snapshots/my-app/-rev/1-0 44ms
npm http fetch GET 304 https://artifactory.example.com/api/npm/npm-snapshots/my-app?write=true 93ms
npm http fetch DELETE 200 https://artifactory.example.com/api/npm/npm-snapshots/api/npm/npm-snapshots/my-app/-/my-app-1.0-SNAPSHOT.tgz/-rev/1-0 79ms
-my-app@1.0-SNAPSHOT
npm verb exit [ 0, true ]
npm timing npm Completed in 5982ms
npm info ok

The last DELETE fetch is wrong the registry path has been duplicated

### PR DESCRIPTION
**Pull request by ruyadorno**
Fixes unpublishing a package from a registry url that has pathnames after its hostname.

## References
Fixes: https://github.com/npm/cli/issues/4253

### CODE REVIEW

File: workspaces/libnpmpublish/lib/get-pathname.js [hunk 1]
```diff
@@ -0,0 +1,22 @@
+'use strict'
```
Comment (wraithgar) [inline workspaces/libnpmpublish/lib/get-pathname.js]: Did this really need a separate file?  Given the kinds of bugs we've been finding the last few weeks consolidating these single-use functions out of the cli I would humbly ask if this could be inline and tested as part of unpublish.js itself.

Comment (ruyadorno) [reply workspaces/libnpmpublish/lib/get-pathname.js]: 💯

File: workspaces/libnpmpublish/lib/unpublish.js [hunk 2]
```diff
@@ -1,9 +1,26 @@
...
+// and handles the registry hostname via opts
+const getPathname = (tarball, registry) => {
+  const registryUrl = new URL(registry).pathname.substring(1)
+  let tarballUrl = new URL(tarball).pathname.substring(1)
+
+  // test the tarball url to see if it starts with a possible
+  // pathname from the registry url, in that case strips that portion
+  // of it so that we only return the post-registry-url pathname
+  if (registryUrl) {
+    tarballUrl = tarballUrl.substring(registryUrl.length)
```
Comment (ljharb) [inline workspaces/libnpmpublish/lib/unpublish.js]:
```suggestion
  const registryUrl = new URL(registry).pathname.slice(1)
  let tarballUrl = new URL(tarball).pathname.slice(1)

  // test the tarball url to see if it starts with a possible
  // pathname from the registry url, in that case strips that portion
  // of it so that we only return the post-registry-url pathname
  if (registryUrl) {
    tarballUrl = tarballUrl.slice(registryUrl.length)
```

Comment (ruyadorno) [reply workspaces/libnpmpublish/lib/unpublish.js]: hi @ljharb could you elaborate a bit more on your suggestion?

Comment (ljharb) [reply workspaces/libnpmpublish/lib/unpublish.js]: just to use slice instead of substring, because it's a much better API, and because it mirrors the one on Array

Comment (ruyadorno) [reply workspaces/libnpmpublish/lib/unpublish.js]: sounds good 😊

**Review by nlf — APPROVED** [review]
nice fix!
